### PR TITLE
Validate TreeTTL of received Revocations

### PR DESCRIPTION
**Pull request by shitz**
Also: Move `_validate_revocation` to `rev_info.py` #1279 

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1281)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
Looks good to me.
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1281#-:-Kw5W1KvcgL4oo65cLTs:b-gxg2vh)*

**Comment by klausman** [comment]
One nit, otherwise :lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[python/lib/crypto/hash_tree.py, line 225 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1281#-Kw5Xdb1908RZPYNIm88:-Kw5Xdb2t58pAPFgJPQI:b-rnuf4f) ([raw file](https://github.com/netsec-ethz/scion/blob/de64f62b52bc3fbb48acc5b6727884e60629cd1c/python/lib/crypto/hash_tree.py#L225)):*
> ```Python
>         proof = rev_info.p
>         hash_func = hash_func_for_type(proof.hashType)
>         assert proof.treeTTL > 0, "proof.TreeTTL == 0"
> ```

Make this either `==` or `>` on both the condition and the message, just for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1281#-:-Kw5XuJZ0hTCMH0qD8ON:bnl47ba)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/lib/crypto/hash_tree.py, line 225 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1281#-Kw5Xdb1908RZPYNIm88:-Kw5dndMIHWdbyxXCDZC:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/de64f62b52bc3fbb48acc5b6727884e60629cd1c/python/lib/crypto/hash_tree.py#L225)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Make this either `==` or `>` on both the condition and the message, just for consistency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1281)*

**Comment by klausman** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1281)*

**Pull request merged**
