### PR TITLE
TRC/CC request resend

### PR DESCRIPTION
**Pull request by sezergueler**
Tackles the problem https://github.com/netsec-ethz/scion/issues/1079

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1121)

### CODE REVIEW

**Comment by shitz** [comment]
[[3] Retry path segment verification](https://trello.com/c/GvIa2Yi6/9-3-retry-path-segment-verification)

**Comment by shitz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[python/scion_elem/scion_elem.py, line 122 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmB6eY7QwwY8QGdqAot:-KmB6eY7QwwY8QGdqAou:b-xtxipi) ([raw file](https://github.com/netsec-ethz/scion/blob/2027a0f23c6777f6cfc0479910636c6c425e3825/python/scion_elem/scion_elem.py#L122)):*
> ```Python
>     USE_TCP = False
>     # Timeout for TRC or Certificate requests.
>     REQUESTS_TIMEOUT = 10
> ```

10s seconds seems excessive. Reduce to 3s. Also rename this to `TRC_CC_REQ_TIMEOUT`

---

*[python/scion_elem/scion_elem.py, line 279 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmB61iGzZevUhfhACqJ:-KmB61iGzZevUhfhACqK:b6unl5v) ([raw file](https://github.com/netsec-ethz/scion/blob/2027a0f23c6777f6cfc0479910636c6c425e3825/python/scion_elem/scion_elem.py#L279)):*
> ```Python
>         with self.req_trcs_lock:
>             for (isd, ver), (req_time, meta) in self.requested_trcs.items():
>                 if time.time() - req_time >= self.REQUESTS_TIMEOUT:
> ```

Only call `time.time()` once before the loop and use that value. Same for `check_cert_reqs`.

---

*[python/scion_elem/scion_elem.py, line 280 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmB7eMq_7ckws-5hFa1:-KmB7eMq_7ckws-5hFa2:bffmq0h) ([raw file](https://github.com/netsec-ethz/scion/blob/2027a0f23c6777f6cfc0479910636c6c425e3825/python/scion_elem/scion_elem.py#L280)):*
> ```Python
>             for (isd, ver), (req_time, meta) in self.requested_trcs.items():
>                 if time.time() - req_time >= self.REQUESTS_TIMEOUT:
>                     logging.info("Re-Requesting %sv%s TRC from %s", isd, ver, meta)
> ```

Also log the request, i.e.,
`logging.info("Re-Requesting %sv%s TRC from %s: %s", isd, ver, meta, trc_req.short_desc())`

Same in `check_cert_reqs`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1121)*

**Comment by sezergueler** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[python/scion_elem/scion_elem.py, line 122 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmB6eY7QwwY8QGdqAot:-KmBCd0EpcbSeVrK3_JD:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2027a0f23c6777f6cfc0479910636c6c425e3825/python/scion_elem/scion_elem.py#L122)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

10s seconds seems excessive. Reduce to 3s. Also rename this to `TRC_CC_REQ_TIMEOUT`
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 279 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmB61iGzZevUhfhACqJ:-KmBCgMO6jW6MADhZFfd:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2027a0f23c6777f6cfc0479910636c6c425e3825/python/scion_elem/scion_elem.py#L279)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Only call `time.time()` once before the loop and use that value. Same for `check_cert_reqs`.
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 280 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmB7eMq_7ckws-5hFa1:-KmBCkhlsGBm3kWB00lf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2027a0f23c6777f6cfc0479910636c6c425e3825/python/scion_elem/scion_elem.py#L280)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Also log the request, i.e.,
`logging.info("Re-Requesting %sv%s TRC from %s: %s", isd, ver, meta, trc_req.short_desc())`

Same in `check_cert_reqs`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1121)*

**Comment by sezergueler** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[python/scion_elem/scion_elem.py, line 173 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBE8tqnncPjyysXrCQ:-KmBRxttfSIGL0QgC6WS:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ffe2c9e66ae506c5f62395f9b2ba1e9c6369bc1b/python/scion_elem/scion_elem.py#L173)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

They don't need to be defaultdicts. Just make them normal dicts.
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 273 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBEgbXI_BISVhYn6TK:-KmBRwxH_BpLAlJjdt8v:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ffe2c9e66ae506c5f62395f9b2ba1e9c6369bc1b/python/scion_elem/scion_elem.py#L273)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Prepend `_` for consistency. `_foo` is a protected method by convention so you can still call it in subclasses.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1121)*

**Comment by kormat** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[python/beacon_server/base.py, line 514 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBTA3mdfJWHYMK0j-8:-KmBTA3mdfJWHYMK0j-9:b-ebdnxk) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/beacon_server/base.py#L514)):*
> ```Python
>                     pass
>                 last_registration = now
>             self._check_cert_reqs()
> ```

This is a bad place for these calls. If the BS isn't master, or it can't connect to zookeeper, it will never get here. As these steps are independent of both those things, these should be before `self.zk.get_lock` above.

Actually, this is worse than that. See `self.zk.wait_connected()` above? That will hang indefinitely until it can reach zookeeper, which shouldn't be a prerequisite for getting certs/trcs.  `worker()` is effectively for parts of the service that depend on zookeeper. Anything which does not depend on zookeeper need to be taken care of elsewhere, probably in their own thread.

---

*[python/scion_elem/scion_elem.py, line 282 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBVyQ_Nd6U4S_rwhpV:-KmBVyQ_Nd6U4S_rwhpW:b2zbeag) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L282)):*
> ```Python
>                 if now - req_time >= self.TRC_CC_REQ_TIMEOUT:
>                     trc_req = TRCRequest.from_values(isd, ver, cache_only=True)
>                     logging.info("Re-Requesting %sv%s TRC from %s: %s",
> ```

If you're including the short desc of the request, do you still need to include the isd+ver?

---

*[python/scion_elem/scion_elem.py, line 376 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmB_Jx2lmj_-WNDp42-:-KmB_Jx2lmj_-WNDp420:b3r8z03) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L376)):*
> ```Python
>             meta = seg_meta.meta
>             if not meta:
>                 meta = self._get_cs()
> ```

This can be simplified to `meta = seg_meta.meta or self._get_cs()`

---

*[python/scion_elem/scion_elem.py, line 377 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBXYn6lXu8l2xkou9b:-KmBXYn6lXu8l2xkou9c:b6pu72f) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L377)):*
> ```Python
>             if not meta:
>                 meta = self._get_cs()
>             if meta:
> ```

It's cleaner to handle the failure case first:
```
if not meta:
   logging.error(...)
   continue
logging.info("Requesting...)
```

---

*[python/scion_elem/scion_elem.py, line 378 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBbMmD7MagemrSwi6y:-KmBbMmD7MagemrSwi6z:bi64dtw) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L378)):*
> ```Python
>                 meta = self._get_cs()
>             if meta:
>                 logging.info("Requesting %sv%s TRC for PCB %s", isd, ver, seg_meta.seg.short_id())
> ```

These should say where it's sending the request.

---

*[python/scion_elem/scion_elem.py, line 472 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBclx-HjlRlelvPa68:-KmBclx-HjlRlelvPa69:buinuvm) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L472)):*
> ```Python
>         with self.req_trcs_lock:
>             if (isd, ver) in self.requested_trcs:
>                 del self.requested_trcs[(isd, ver)]
> ```

`self.requested_trcs.pop((isd, ver), None)` is simpler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1121)*

**Comment by sezergueler** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[python/beacon_server/base.py, line 514 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBTA3mdfJWHYMK0j-8:-KmC54NTZAN0CYXWS8t8:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/beacon_server/base.py#L514)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is a bad place for these calls. If the BS isn't master, or it can't connect to zookeeper, it will never get here. As these steps are independent of both those things, these should be before `self.zk.get_lock` above.

Actually, this is worse than that. See `self.zk.wait_connected()` above? That will hang indefinitely until it can reach zookeeper, which shouldn't be a prerequisite for getting certs/trcs.  `worker()` is effectively for parts of the service that depend on zookeeper. Anything which does not depend on zookeeper need to be taken care of elsewhere, probably in their own thread.
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 282 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBVyQ_Nd6U4S_rwhpV:-KmC6uy7mNDg9dSghTFi:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L282)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

If you're including the short desc of the request, do you still need to include the isd+ver?
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 376 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmB_Jx2lmj_-WNDp42-:-KmC70SUB5zxm_iNOd_b:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L376)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be simplified to `meta = seg_meta.meta or self._get_cs()`
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 377 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBXYn6lXu8l2xkou9b:-KmC70zypWJeAEVDJIfH:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L377)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It's cleaner to handle the failure case first:
```
if not meta:
   logging.error(...)
   continue
logging.info("Requesting...)
```

</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 378 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBbMmD7MagemrSwi6y:-KmC74Cg9QaGQ8ewgwoe:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L378)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These should say where it's sending the request.
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 472 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmBclx-HjlRlelvPa68:-KmC76cLfwXNoV8Knmuv:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/bb126baac4ab7c7525a130e9da077432e3f31c7a/python/scion_elem/scion_elem.py#L472)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`self.requested_trcs.pop((isd, ver), None)` is simpler.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1121)*

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/scion_elem/scion_elem.py, line 276 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-KmRUguvUp8IdqrZdfvs:-KmRUguvUp8IdqrZdfvt:b-44yn91) ([raw file](https://github.com/netsec-ethz/scion/blob/07754c0dd954adeb750927978d4c0d543c87050c/python/scion_elem/scion_elem.py#L276)):*
> ```Python
>         check_cyle = 1.0
>         while self.run_flag.is_set():
>             sleep_interval(time.time(), check_cyle, "Elem.check_trc_cert_reqs cycle")
> ```

That is not how `sleep_interval` works :P The simplest thing is to have at the start of the loop `start = time.time()`, and at the end `sleep_interval(start, ...)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1121)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1121#-:-KmRYqqGGWVDijlqbFIn:bnfp4nl)*

**Pull request merged**
