### PR TITLE
scion-web submodule update

### PR DESCRIPTION
**Pull request by ercanucan**
Updates scion-web submodule to commit cdc8f9d5f199831593311083d156fd16170f9c47.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1149)

### CODE REVIEW

**Comment by ercanucan** [comment]
@shitz

**Comment by shitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sub/web, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1149#-KoGwh3wWBwK-SR_Zsqf:-KoGwh3wWBwK-SR_Zsqg:b-ei7xj0) ([raw file](https://github.com/netsec-ethz/scion/blob/1af492bb80de226cff765c7361a51c329ffed924/sub/web#L1)):*
> ```
> Subproject commit cdc8f9d5f199831593311083d156fd16170f9c47
> ```

Update to `b126ea21a0862ac7cb941daa7b58559124f1ed2d`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1149)*

**Comment by ercanucan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sub/web, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1149#-KoGwh3wWBwK-SR_Zsqf:-KoH3K0FpLiUTFTM01Mi:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/1af492bb80de226cff765c7361a51c329ffed924/sub/web#L1)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Update to `b126ea21a0862ac7cb941daa7b58559124f1ed2d`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1149)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1149#-:-KoHL7WEnCEI7OUzEMGP:bnfp4nl)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1149#-:-KoHUh9wBTOGzodgxF7C:bnfp4nl)*

**Pull request merged**
