### PR TITLE
Add some small tools for dev/debug/op purposes.

### PR DESCRIPTION
**Pull request by kormat**
pktgen: generates packets at a high rate.
pktprint: turns hex-encoded packets into pretty-printed output.
zkls: list the contents of zookeeper paths.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1030)

### CODE REVIEW

**Comment by klausman** [comment]
:lgtm: with three minor requests for clarification.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/pktgen.py, line 103 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTUxtVAY6HvRIdcUjc:-KgTUxtVAY6HvRIdcUjd:b-bz0cio) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L103)):*
> ```Python
>     try:
>         gen.run(args.count)
>     except KeyboardInterrupt:
> ```

Why is `^C` explicitly ignored?

---

*[tools/zkls.py, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTVFFJhuCnlfIezFNY:-KgTVFFK0hqrDS5-MjaI:b3a043y) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/zkls.py#L32)):*
> ```Python
>     print(dir_)
>     for entries in zk.get_children(dir_):
>         print_dir(zk, os.path.join(dir_, entries))
> ```

How difficult would it be to make this output sorted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-:-KgTVNF0HpBH8ctdgYxP:b5w1jj9)*

**Comment by ercanucan** [comment]
:lgtm: with a very minor comment

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/pktgen.py, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTVnrswrsUDIKzR1Zi:-KgTVnrtYh2IoV8OrqCC:bb6ht2h) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L2)):*
> ```Python
> #!/usr/bin/python3
> # Copyright 2016 ETH Zurich
> ```

2017

---

*[tools/pktprint.py, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTWog53r0B4RgK87TE:-KgTWog53r0B4RgK87TF:bb6ht2h) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktprint.py#L2)):*
> ```Python
> #!/usr/bin/python3
> # Copyright 2016 ETH Zurich
> ```

2017

---

*[tools/zkls.py, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTWtM2jYrExfhI_la_:-KgTWtM2jYrExfhI_laa:bb6ht2h) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/zkls.py#L2)):*
> ```Python
> #!/usr/bin/python3
> # Copyright 2016 ETH Zurich
> ```

2017

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-:-KgTXxzXqx9YE3aM5Z7v:b8yk6k4)*

**Comment by ercanucan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/pktgen.py, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTbKV3cfvmhByUuhux:-KgTbKV4_m05iL0wKSWe:beym1ow) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L48)):*
> ```Python
>         logging.debug("Sending (via %s:%s):\n%s", overlay_dest, overlay_port, spkt)
>         logging.debug("Interfaces: %s", ", ".join(
>             [str(ifentry) for ifentry in self.path_meta.iter_ifs()]))
> ```

`short_desc()` in `FwdPathMeta` does the same thing (+ MTU)

---

*[tools/pktgen.py, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgT_dKj66lt1RrND-VB:-KgT_dKj66lt1RrND-VC:btjxltd) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L99)):*
> ```Python
>     api_path_default = os.path.join(SCIOND_API_SOCKDIR, "sd%s.sock" % src.isd_as)
>     api_path = os.getenv(SCIOND_API_PATH_ENV_VAR) or api_path_default
>     gen = PktGen(api_path, b"data", "finished", src, dst, 3000, size=args.size)
> ```

Passing in "finished" instead of a `threading.Event` object could crash the pktgen. It probably won't, since `run` is reimplemented, but it just goes to show that `TestClientBase` is not a good "application library". I can live with it, since this is just an internal tool, but PktGen should probably have a FIXME stating that something about this and how to fix it in the future.

---

*[tools/pktgen.py, line 107 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTbrYlpv1Y_2h6ssGv:-KgTbrYlpv1Y_2h6ssGw:bahpfwt) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L107)):*
> ```Python
>     total = time.time() - start
>     logging.info("Sent %d %dB packets in %.3fs (%d pps, %d bps)",
>                  gen.sent, gen.size, total, gen.sent/total, (gen.sent * gen.size * 8)/total)
> ```

Whitespaces around `/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/pktgen.py, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTVnrswrsUDIKzR1Zi:-KgTgUyQUdda0yUlm-_-:bi8opy1) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L2)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

2017
</blockquote></details>

These were all written last year, hence the copyright.

---

*[tools/pktgen.py, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTbKV3cfvmhByUuhux:-KgThKLn-bbAI-Mprv_B:b-5zq6n4) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L48)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`short_desc()` in `FwdPathMeta` does the same thing (+ MTU)
</blockquote></details>

Changed, also in `base_cli_srv.py`.

---

*[tools/pktgen.py, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgT_dKj66lt1RrND-VB:-KgTh_4XOCiA4E8xtW8Q:bi1he7e) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L99)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Passing in "finished" instead of a `threading.Event` object could crash the pktgen. It probably won't, since `run` is reimplemented, but it just goes to show that `TestClientBase` is not a good "application library". I can live with it, since this is just an internal tool, but PktGen should probably have a FIXME stating that something about this and how to fix it in the future.
</blockquote></details>

Well, the fix is either to refactor `TestBase` substantially, or to provide more features in `lib.app`. Looking over it quickly, it looks like the only features pktgen uses from the test base classes are `_get_path`,  `_build_pkt` and `_create_l4_hdr`. I _could_ just copy them over, if you like, but it's not a great solution either.

I've added a FIXME for now in any case.

---

*[tools/pktgen.py, line 103 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTUxtVAY6HvRIdcUjc:-KgTipnfnvlh97h7wn6t:b83tzqi) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L103)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Why is `^C` explicitly ignored?
</blockquote></details>

It's not ignored. It's explicitly not an error. If you run pktgen with `-c 0`, it will run forever. When you hit ctrl-c, it will exit gracefully, and print out stats on the way.

---

*[tools/pktgen.py, line 107 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTbrYlpv1Y_2h6ssGv:-KgTjjhp_U_NvXtCp8Wf:b731k1o) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L107)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Whitespaces around `/`
</blockquote></details>

Done, though it looks harder to read to me now. Maybe i'm just too used to Go.

---

*[tools/zkls.py, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTVFFJhuCnlfIezFNY:-KgTjs-O3yvV3nQ4lwKx:b-rnz1ht) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/zkls.py#L32)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

How difficult would it be to make this output sorted?
</blockquote></details>

Oh yeah, thanks for the reminder. I'll have a quick look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030)*

**Comment by kormat** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/zkls.py, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTVFFJhuCnlfIezFNY:-KgTkueZPnOodOQkG5zf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/zkls.py#L32)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Oh yeah, thanks for the reminder. I'll have a quick look.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030)*

**Comment by ercanucan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[test/integration/base_cli_srv.py, line 188 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTlO1jGN4N2O6xYU2a:-KgTlO1koljEbKJAzY20:bh79dvi) ([raw file](https://github.com/netsec-ethz/scion/blob/1b2122c10efd5bba94450f4f88897de39b851e80/test/integration/base_cli_srv.py#L188)):*
> ```Python
>     def _send(self):
>         self._send_pkt(self._build_pkt(), self.first_hop)
>         logging.debug("Path meta: %s", self.path_meta)
> ```

This will produce `Path meta: FwdPathMeta: MTU: X Interfaces: [...]`. Either drop "Path meta:" or print the `short_desc()`

---

*[tools/pktgen.py, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTbKV3cfvmhByUuhux:-KgTlcGqwIRoQqyR95kt:b33bxm9) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L48)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Changed, also in `base_cli_srv.py`.
</blockquote></details>

see comment there

---

*[tools/pktgen.py, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgT_dKj66lt1RrND-VB:-KgTmZPRIw3z9eT-wh2M:bec9icv) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L99)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Well, the fix is either to refactor `TestBase` substantially, or to provide more features in `lib.app`. Looking over it quickly, it looks like the only features pktgen uses from the test base classes are `_get_path`,  `_build_pkt` and `_create_l4_hdr`. I _could_ just copy them over, if you like, but it's not a great solution either.

I've added a FIXME for now in any case.
</blockquote></details>

I don't like copying. I can live with the FIXME

---

*[tools/pktgen.py, line 52 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTmQGRJVad7rpGW5bh:-KgTmQGRJVad7rpGW5bi:b-vqyrjr) ([raw file](https://github.com/netsec-ethz/scion/blob/1b2122c10efd5bba94450f4f88897de39b851e80/tools/pktgen.py#L52)):*
> ```Python
>         logging.debug("Path meta: %s", self.path_meta)
>         while True:
>             if count > 0 and self.sent >= count:
> ```

Include this in the while loop: `while not count or self.sent < count`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[test/integration/base_cli_srv.py, line 188 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTlO1jGN4N2O6xYU2a:-KgTnumY9cZLQjA4eS5e:b8gj3mz) ([raw file](https://github.com/netsec-ethz/scion/blob/1b2122c10efd5bba94450f4f88897de39b851e80/test/integration/base_cli_srv.py#L188)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This will produce `Path meta: FwdPathMeta: MTU: X Interfaces: [...]`. Either drop "Path meta:" or print the `short_desc()`
</blockquote></details>

Good catch, fixed.

---

*[tools/pktgen.py, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTbKV3cfvmhByUuhux:-KgToLGsP3FraFZE4594:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L48)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

see comment there
</blockquote></details>

Done.

---

*[tools/pktgen.py, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgT_dKj66lt1RrND-VB:-KgToNz-ajcAvtoZinqA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L99)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I don't like copying. I can live with the FIXME
</blockquote></details>

Done.

---

*[tools/pktgen.py, line 52 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTmQGRJVad7rpGW5bh:-KgToMRYL1FF_g0iKMrp:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/1b2122c10efd5bba94450f4f88897de39b851e80/tools/pktgen.py#L52)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Include this in the while loop: `while not count or self.sent < count`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-:-KgTxTuB8uMVe3aBNtwL:bnfp4nl)*

**Comment by ercanucan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-:-KgU3L2QxwIc49DsHrp1:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/pktgen.py, line 103 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1030#-KgTUxtVAY6HvRIdcUjc:-KgU3JsB6LcEqIftmn60:b-py1kmm) ([raw file](https://github.com/netsec-ethz/scion/blob/7ebb640b9850cdb3f0b4d249b52c414308459945/tools/pktgen.py#L103)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It's not ignored. It's explicitly not an error. If you run pktgen with `-c 0`, it will run forever. When you hit ctrl-c, it will exit gracefully, and print out stats on the way.
</blockquote></details>

Ah, ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1030)*

**Pull request merged**
