### PR TITLE
Enhance generator.py to produce Prometheus config files

### PR DESCRIPTION
**Pull request by forstern**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1033)

### CODE REVIEW

**Comment by forstern** [comment]
@kormat @ercanucan

**Comment by ercanucan** [comment]
@forstern I made a pass. Looks good in general. @kormat Could you please also have a look? @kormat I wonder if it makes sense to add Prometheus and Grafana to required packages. By the way, Ubuntu comes with an ancient version of Prometheus. @forstern wrote his code for Prometheus version 1.5.2.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[topology/generator.py, line 66 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgnbvvJ6heKE0JHWgRZ:-KgnbvvKjnoD9lXhURHN:buaq2n) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L66)):*
> ```Python
>     SCIOND_API_SOCKDIR,
>     TOPO_FILE,
>     PROM_FILE
> ```

This should be `PROM_FILE,` (ending with a comma) according to our coding conventions. Also, please keep the imports sorted.

---

*[topology/generator.py, line 667 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgnsU6nLwYiIgsjKwHn:-KgnsU6o1dU5zG327Qbi:bsrehsv) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L667)):*
> ```Python
> 
>     def _write_target_file(self, base_path, router_addrs):
>         targets_path = os.path.join(base_path, "prometheus", "targets.yml")
> ```

It would make sense for ease of readability to define these strings as constants in the class.

---

*[topology/generator.py, line 698 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-Kgnu0pCky61z85taIQD:-Kgnu0pDyGuK5gI5ZLCw:b-1fdv3w) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L698)):*
> ```Python
>         self._write_config_file(os.path.join(self.out_dir, PROM_FILE), list_of_paths)
> 
>     def generate(self):
> ```

I wonder if we should specify in the function name or the class name that at the moment it's generating Prometheus config only for the border routers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-:-KgnuJgtMMwuNE4avOwc:bzd8nym)*

**Comment by kormat** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[topology/generator.py, line 664 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoS9EPmLT_zn9b7BlB:-KgoS9EPmLT_zn9b7BlC:b-rxzwll) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L664)):*
> ```Python
>         self.out_dir = out_dir
>         self.topo_dicts = topo_dicts
>         self.router_dict = {}
> ```

Most of the code in this class is also not router-specific. Also this dict is only written to by one method (`generate`) and read by one method (`_write_config_files`), so i would just make it a local var in `generate`, and pass it as a parameter to `_write_config_files`.

---

*[topology/generator.py, line 666 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoOcU7Z9hYgFvkQgdY:-KgoOcU7Z9hYgFvkQgdZ:b-difhzv) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L666)):*
> ```Python
>         self.router_dict = {}
> 
>     def _write_target_file(self, base_path, router_addrs):
> ```

In general, the order of methods should roughly follow the order of execution. In this case, it would be `generate`, `_write_config_files`, `_write_config_file`, `_write_target_file`.

---

*[topology/generator.py, line 667 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoRLWW-WltnCgWwRyS:-KgoRLWW-WltnCgWwRyT:bq8ehg4) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L667)):*
> ```Python
> 
>     def _write_target_file(self, base_path, router_addrs):
>         targets_path = os.path.join(base_path, "prometheus", "targets.yml")
> ```

It would be good to have the targets file be named after the service being monitored, so `br.yml` in this case.

---

*[topology/generator.py, line 674 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoQuVffKdn0U2S0MKq:-KgoQuVffKdn0U2S0MKr:bovbm4s) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L674)):*
> ```Python
>         config = {
>             'global': {
>                 'scrape_interval': '15s',
> ```

Mixing scrape intervals gets messy, apparently. I suggest setting the global scrape and evaluation intervals to 5s, and removing the custom scrape interval on the border job.

---

*[topology/generator.py, line 698 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-Kgnu0pCky61z85taIQD:-KgoT4C9RcqjNvET4kzw:bjsmrut) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L698)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

I wonder if we should specify in the function name or the class name that at the moment it's generating Prometheus config only for the border routers.
</blockquote></details>

I think it's ok as-is, it'll need to be refactored when we add other services to monitoring, but it's small and simple enough that that won't be too hard (and we'll have a better idea then of exactly what we want).

---

*[topology/generator.py, line 702 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoTGdjEH6rn5RGA8l0:-KgoTGdjEH6rn5RGA8l1:bmxnw32) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L702)):*
> ```Python
>             router_list = []
>             for br_id, br_ele in as_topo["BorderRouters"].items():
>                 router_list.append(str(br_ele['Addr'].ip) + ":" + str(br_ele['Port']))
> ```

`"[%s]:%s" % (br_ele['Addr'].ip, br_ele['Port'])`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033)*

**Comment by forstern** [comment]
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[topology/generator.py, line 66 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgnbvvJ6heKE0JHWgRZ:-KgsrBRlp2Ra7EvZIq9y:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L66)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

This should be `PROM_FILE,` (ending with a comma) according to our coding conventions. Also, please keep the imports sorted.
</blockquote></details>

Done.

---

*[topology/generator.py, line 664 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoS9EPmLT_zn9b7BlB:-Kgsr61Rv-zE5gMHww1q:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L664)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Most of the code in this class is also not router-specific. Also this dict is only written to by one method (`generate`) and read by one method (`_write_config_files`), so i would just make it a local var in `generate`, and pass it as a parameter to `_write_config_files`.
</blockquote></details>

Done.

---

*[topology/generator.py, line 666 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoOcU7Z9hYgFvkQgdY:-Kgsr993bmqYyZ51rsAf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L666)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

In general, the order of methods should roughly follow the order of execution. In this case, it would be `generate`, `_write_config_files`, `_write_config_file`, `_write_target_file`.
</blockquote></details>

Done.

---

*[topology/generator.py, line 667 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgnsU6nLwYiIgsjKwHn:-KgsrA2vAzzYSZ81dWe7:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L667)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

It would make sense for ease of readability to define these strings as constants in the class.
</blockquote></details>

Done.

---

*[topology/generator.py, line 667 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoRLWW-WltnCgWwRyS:-KgsrDWbSAEoRY413g_y:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L667)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It would be good to have the targets file be named after the service being monitored, so `br.yml` in this case.
</blockquote></details>

Done.

---

*[topology/generator.py, line 674 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoQuVffKdn0U2S0MKq:-KgsrELQGDAytYsMJ959:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L674)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Mixing scrape intervals gets messy, apparently. I suggest setting the global scrape and evaluation intervals to 5s, and removing the custom scrape interval on the border job.
</blockquote></details>

Done.

---

*[topology/generator.py, line 702 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoTGdjEH6rn5RGA8l0:-Kgsql0MiyKHFYFeeE0m:b-o0evel) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L702)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`"[%s]:%s" % (br_ele['Addr'].ip, br_ele['Port'])`
</blockquote></details>

why do you put [] around the ip addr?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033)*

**Comment by ercanucan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[topology/generator.py, line 705 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-Kgx_IlKkuI7f78a3xkD:-Kgx_IlLBzSg8LZRoipt:bspq1nv) ([raw file](https://github.com/netsec-ethz/scion/blob/3aaefd6e9e289b40da29de7641707497b2a461bb/topology/generator.py#L705)):*
> ```Python
>     def _write_target_file(self, base_path, router_addrs):
>         targets_path = os.path.join(base_path, self.PROM_DIR, self.BR_TARGET_FILE)
>         target_config = [{'targets': router_addrs}]
> ```

@kormat I think it may be good to add the AS identifier as a label to the target file. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[topology/generator.py, line 705 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-Kgx_IlKkuI7f78a3xkD:-KgxzlWUNu0FXOWgAhOI:b-uzx6yq) ([raw file](https://github.com/netsec-ethz/scion/blob/3aaefd6e9e289b40da29de7641707497b2a461bb/topology/generator.py#L705)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

@kormat I think it may be good to add the AS identifier as a label to the target file. What do you think?
</blockquote></details>

Nevermind about the above comment. As discussed, the labels for ASes will come from the services not the Prometheus config.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-:-Kgy-CB6wJAXbAbswkMq:bnfp4nl)*

**Comment by kormat** [comment]
One minor comment, LGTM otherwise :)

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[topology/generator.py, line 702 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgoTGdjEH6rn5RGA8l0:-KgydxeK4WV2yq3bUrxp:b-h5l581) ([raw file](https://github.com/netsec-ethz/scion/blob/a4153ff385f59f0da1490d80748e317a4420d7de/topology/generator.py#L702)):*
<details><summary><i>Previously, forstern (Nicolas Forster) wrote…</i></summary><blockquote>

why do you put [] around the ip addr?
</blockquote></details>

(For posterity, it's so that if we use ipv6 addresses (which contain :'s), they will still parse correctly)

---

*[topology/generator.py, line 681 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgyfO9jsQVgqLgboiW5:-KgyfO9jsQVgqLgboiW6:blqcgpt) ([raw file](https://github.com/netsec-ethz/scion/blob/3aaefd6e9e289b40da29de7641707497b2a461bb/topology/generator.py#L681)):*
> ```Python
>         for topo_id, router_list in router_dict.items():
>             base = os.path.join(self.out_dir, topo_id.ISD(), topo_id.AS())
>             targets_path = os.path.join(base, self.PROM_DIR, "*.yml")
> ```

This should be `br.yml`, instead of `*.yml`. Otherwise when we have other target files, they will all be included in the `border` job.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-:-Kgyh2X5M4LYm_-gL3kF:bqgt1z2)*

**Comment by forstern** [comment]
@kormat I made the last change suggested by you. As soon as you give your LGTM I am going to rebase it into a single commit

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[topology/generator.py, line 681 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-KgyfO9jsQVgqLgboiW5:-Kh2GCG4b8QNeYENv3eX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3aaefd6e9e289b40da29de7641707497b2a461bb/topology/generator.py#L681)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be `br.yml`, instead of `*.yml`. Otherwise when we have other target files, they will all be included in the `border` job.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-:-Kh2Fz0JQa-l8ZjFilUW:bhivmn0)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-:-Kh2Xe0XIEh_hImaIL6G:bnfp4nl)*

**Comment by forstern** [comment]
this PR should be ready to merge

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-:-Kh2bToiAGWtKK83Bc41:byvsn6p)*

**Comment by kormat** [comment]
Please rebase on master, and then we can merge.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-:-KiA2uyTsotkOkxDsjKc:b-mxzjjq)*

**Comment by forstern** [comment]
done

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1033#-:-KiAIND1d7-0XX9zAC-h:bb7f2mf)*

**Pull request merged**
