### PR TITLE
Expire revocations at BR

### LINKED ISSUE #1049: border router does not expire revocations
The br gets notified of revocations by the BS sending it IFState messages. If the BS stops doing that for any reason, the br will continue to send stale revocations in response to packets it gets. It needs to stop doing that.

### PR DESCRIPTION
**Pull request by shitz**
Outdated revocations are not sent anymore by BRs. Fixes #1049.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1055)

### CODE REVIEW

**Comment by klausman** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-:-KidLmY8SmvbGGH6RY28:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055)*

**Comment by ercanucan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[go/lib/crypto/htree.go, line 22 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KidMATAcjo8QFkb8_Fr:-KidMATB6X1t4eAZ6OW0:bbukyv3) ([raw file](https://github.com/netsec-ethz/scion/blob/a09afb39f545b841fb095aa7aff2c621daa0b0a9/go/lib/crypto/htree.go#L22)):*
> ```Go
> 
> // HashTreeTTL is the TTL of one hash tree (in seconds).
> // FIXME(shitz): This should really be matching spath.MaxTTL, but more importantely,
> ```

very minor: "importantly"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-:-KidMH62KJuRZDIqhLEw:bnfp4nl)*

**Comment by shitz** [comment]
@kormat implemented the changes we discussed offline.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/crypto/htree.go, line 22 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KidMATAcjo8QFkb8_Fr:-Kj8FJmyM_sM2b9nuPAi:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a09afb39f545b841fb095aa7aff2c621daa0b0a9/go/lib/crypto/htree.go#L22)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

very minor: "importantly"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-:-Kj8FLJ7Zt4D9jRrji6O:bqnxbdt)*

**Comment by kormat** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[go/border/ifstate.go, line 23 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjIeFgO2SD0DAFHfhBf:-KjIeFgO2SD0DAFHfhBg:bqlc9qq) ([raw file](https://github.com/netsec-ethz/scion/blob/84e388eb54e488ced14a08d825a88dddd674f814/go/border/ifstate.go#L23)):*
> ```Go
> // startup.
> 
> package main
> ```

Does this file still need to exist in the main package? What about moving the rest of it into `go/border/ifstate/`?

---

*[go/border/ifstate/ifstate.go, line 38 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjIem60tY6OYDjTpfDX:-KjIem61VcIhUjuG32C-:bb4r8ul) ([raw file](https://github.com/netsec-ethz/scion/blob/84e388eb54e488ced14a08d825a88dddd674f814/go/border/ifstate/ifstate.go#L38)):*
> ```Go
> 
> // ProcessIFStates processes Interface State updates from the beacon service.
> func ProcessIFStates(ifStates proto.IFStateInfos) {
> ```

This can be renamed to `Process`, now that it's namespaced by the package.

---

*[go/border/rpkt/path.go, line 101 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjIfPy5KbAPxTh1bbRI:-KjIfPy5KbAPxTh1bbRJ:bu9i1y7) ([raw file](https://github.com/netsec-ethz/scion/blob/84e388eb54e488ced14a08d825a88dddd674f814/go/border/rpkt/path.go#L101)):*
> ```Go
> 	var err error
> 	if revInfo, err = info.P.RevInfo(); err != nil {
> 		rp.Warn("Couldn't load revinfo.", "err", err.Error())
> ```

I think this would be clearer: `"Couldn't load RevInfo for revoked interface", "err", err, "ifid", *ifid`
You don't need to call `.Error()`, the logging library will manage that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055)*

**Comment by shitz** [comment]
Review status: 3 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[go/border/ifstate.go, line 23 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjIeFgO2SD0DAFHfhBf:-KjNuRT2Tc0NpUUCuFt4:b-lnnt8l) ([raw file](https://github.com/netsec-ethz/scion/blob/84e388eb54e488ced14a08d825a88dddd674f814/go/border/ifstate.go#L23)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Does this file still need to exist in the main package? What about moving the rest of it into `go/border/ifstate/`?
</blockquote></details>

Refactored code such that it's not needed anymore.

---

*[go/border/ifstate/ifstate.go, line 38 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjIem60tY6OYDjTpfDX:-KjNuaeCncQu8HmbvvkK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/84e388eb54e488ced14a08d825a88dddd674f814/go/border/ifstate/ifstate.go#L38)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be renamed to `Process`, now that it's namespaced by the package.
</blockquote></details>

Done.

---

*[go/border/rpkt/path.go, line 101 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjIfPy5KbAPxTh1bbRI:-KjNul3zvhiZmlWSAHWg:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/84e388eb54e488ced14a08d825a88dddd674f814/go/border/rpkt/path.go#L101)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I think this would be clearer: `"Couldn't load RevInfo for revoked interface", "err", err, "ifid", *ifid`
You don't need to call `.Error()`, the logging library will manage that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055)*

**Comment by kormat** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[go/border/gen.go, line 70 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjO3mNXTg53bnOtMcaJ:-KjO3mNXTg53bnOtMcaK:b192u9a) ([raw file](https://github.com/netsec-ethz/scion/blob/0a673bf3b4447751205266e383b3eb0252d5236b/go/border/gen.go#L70)):*
> ```Go
> }
> 
> func (r *Router) genPkt(dstIA *addr.ISD_AS, dstHost addr.HostAddr, dstPort int,
> ```

The ordering seems a bit random in this file. I would put `genPkt` at the top (as it's the fundamental part of this file), then `SyncInterface`, `genIFIDPkts`, `IFStateUpdate`, `getnIFStateReq`. That way the flow follows more naturally.

---

*[go/border/gen.go, line 104 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjO3btTokvpORccqU1M:-KjO3btTokvpORccqU1N:b-yw564t) ([raw file](https://github.com/netsec-ethz/scion/blob/0a673bf3b4447751205266e383b3eb0252d5236b/go/border/gen.go#L104)):*
> ```Go
> }
> 
> func (r *Router) genIFIDPkts() {
> ```

There's no need for this method, we can just move the for loop into `SyncInterface`.

---

*[go/border/gen.go, line 149 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjO6DO_VjUGFXkxBHtv:-KjO6DO_VjUGFXkxBHtw:b-ngwnp) ([raw file](https://github.com/netsec-ethz/scion/blob/0a673bf3b4447751205266e383b3eb0252d5236b/go/border/gen.go#L149)):*
> ```Go
> 
> // genRevInfo forwards RevInfo payloads to a designated local host.
> func (r *Router) genRevInfo(revInfo *proto.RevInfo, dstHost addr.HostAddr) {
> ```

I would keep this in `revinfo.go`, so that it's with the rest of the revocation handling code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[go/border/gen.go, line 70 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjO3mNXTg53bnOtMcaJ:-Kjb0mzqOzR7aqF5Z5hF:bafu8fr) ([raw file](https://github.com/netsec-ethz/scion/blob/0a673bf3b4447751205266e383b3eb0252d5236b/go/border/gen.go#L70)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The ordering seems a bit random in this file. I would put `genPkt` at the top (as it's the fundamental part of this file), then `SyncInterface`, `genIFIDPkts`, `IFStateUpdate`, `getnIFStateReq`. That way the flow follows more naturally.
</blockquote></details>

Ok. The current ordering had a system btw ;) The functions with the long docstrings at the top, since I was assuming that this would be the most interesting part for someone looking into that file, followed by `genPkt` and then the more specific `genX` methods. 

---

*[go/border/gen.go, line 104 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjO3btTokvpORccqU1M:-Kjb1hOJZ_tqDo-p0EC-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/0a673bf3b4447751205266e383b3eb0252d5236b/go/border/gen.go#L104)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There's no need for this method, we can just move the for loop into `SyncInterface`.
</blockquote></details>

Done.

---

*[go/border/gen.go, line 149 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjO6DO_VjUGFXkxBHtv:-Kjb1iFi5Hn6FZOFgbDT:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/0a673bf3b4447751205266e383b3eb0252d5236b/go/border/gen.go#L149)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I would keep this in `revinfo.go`, so that it's with the rest of the revocation handling code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055)*

**Comment by kormat** [comment]
Two minor comment, then LGTM.

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/border/revinfo.go, line 56 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-Kjbv91qc8rcPYLyLRk0:-Kjbv91qc8rcPYLyLRk1:b1174bi) ([raw file](https://github.com/netsec-ethz/scion/blob/8cae55ebf63b833815f11815fe6b93e061c26127/go/border/revinfo.go#L56)):*
> ```Go
> 		for _, svcAddr := range args.Addrs {
> 			log.Debug("Forwarding revocation.", "target", svcAddr, "revInfo", revInfo)
> 			r.genRevInfo(revInfo, &svcAddr)
> ```

revert to `fwdRevInfo`.

---

*[go/border/rpkt/route.go, line 74 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjbvJDFzPhWxr9j0BT5:-KjbvJDFzPhWxr9j0BT6:b1d5jg3) ([raw file](https://github.com/netsec-ethz/scion/blob/8cae55ebf63b833815f11815fe6b93e061c26127/go/border/rpkt/route.go#L74)):*
> ```Go
> 	}
> 
> 	f := callbacks.locOutFs[0]
> ```

Add a comment to explain why this case is needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-:-KjbvOwXMd4tIAycdvZ5:b-kc9dx6)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/border/revinfo.go, line 56 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-Kjbv91qc8rcPYLyLRk0:-KjbvmaSFrj2QYKslvWn:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/8cae55ebf63b833815f11815fe6b93e061c26127/go/border/revinfo.go#L56)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

revert to `fwdRevInfo`.
</blockquote></details>

Done.

---

*[go/border/rpkt/route.go, line 74 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-KjbvJDFzPhWxr9j0BT5:-Kjbw4cVYF_FNwZ66iPC:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/8cae55ebf63b833815f11815fe6b93e061c26127/go/border/rpkt/route.go#L74)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Add a comment to explain why this case is needed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055#-:-KjbwjWBnj65CbtILVk-:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 3 of 7 files at r2, 5 of 7 files at r3, 1 of 3 files at r4, 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1055)*

**Pull request merged**
