### PR TITLE
Move common definitions to go/lib/common

### PR DESCRIPTION
**Pull request by kormat**
This resolves some circular imports that were getting in the way.

Also:
- Move scmp from go/border/scmp to go/lib/scmp
- Add constants for InfoF and HopF lengths, and use those instead.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/921)

### CODE REVIEW

**Comment by kormat** [comment]
@klausman

**Comment by klausman** [comment]
One minor nit. Otherwise :lgtm:

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/common/extn.go, line 22 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/921#-KUbnApLnlU_UYpBMCDI:-KUbnApLnlU_UYpBMCDJ:bu5tx0u) ([raw file](https://github.com/netsec-ethz/scion/blob/ebcb282748619c813069c917d0216ae3e91bbb87/go/lib/common/extn.go#L22)):*
> ```Go
> 
> type ExtnType struct {
> 	Class L4ProtoType
> ```

How hard would it be to call this `L4ProtocolType` instead to dodge the very small amount ambiguity?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/921#-:-KUbnbWRO0AuFkFBFASi:byvyid5)*

**Comment by kormat** [comment]
Review status: 17 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/common/extn.go, line 22 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/921#-KUbnApLnlU_UYpBMCDI:-KUboN3NnNEPkt0OPKRF:b-6mz4j5) ([raw file](https://github.com/netsec-ethz/scion/blob/ebcb282748619c813069c917d0216ae3e91bbb87/go/lib/common/extn.go#L22)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> How hard would it be to call this `L4ProtocolType` instead to dodge the very small amount ambiguity?
</details>
Yeah alright, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/921)*

**Comment by klausman** [comment]
Reviewed 1 of 29 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/921)*

**Pull request merged**
