### PR TITLE
Support running the go router on the same IP as other services.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/970)

### CODE REVIEW

**Comment by kormat** [comment]
@ercanucan - this should fix the issue, but hasn't been tested much.

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/970#-:-KdQDFiGmukBPJduNYsC:bnfp4nl)*

**Comment by ercanucan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[go/border/rpkt/process.go, line 89 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/970#-KdQK9zgbw0MOAEwQMby:-KdQK9zhNQhegJeAYTrD:buowfjh) ([raw file](https://github.com/netsec-ethz/scion/blob/299b54e4e22b940208769c3f20add29c1d00d74d/go/border/rpkt/process.go#L89)):*
> ```Go
> 	rp.hooks.Route = append(rp.hooks.Route, rp.forward)
> 	return nil
> Self:
> ```

minor: would that make sensse to separate it out into a function rather than using `goto` statement?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/970)*

**Comment by ercanucan** [comment]
@kormat I can confirm that this enables running to go router in the same IP with other services.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/970#-:-KdQKJiMgLkrmamMIlER:bvukzpb)*

**Comment by ercanucan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/970#-:-KdQKYTqI39Idbo0OFwY:bnfp4nl)*

**Comment by ercanucan** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/970)*

**Pull request merged**
