### PR TITLE
Simplify handling of dependency changes

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1048)

### CODE REVIEW

**Comment by pszalach** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-:-KiArQl1SbZ3E1JWohy0:bnfp4nl)*

**Comment by klausman** [comment]
Just minor things/cleanups. Otherwise :lgtm:

---

Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docker/deps_check, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFvi99WQ5GrCYVzYjb:-KiFvi99WQ5GrCYVzYjc:b-odi9zm) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/docker/deps_check#L6)):*
> ```
> 
> check() {
>     echo "Check: $@"
> ```

Does this have the same semantics as `echo Check: "$@"`?

---

*[docker/Dockerfile.base, line 9 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFw-Hiyy8zPCCPW8RQ:-KiFw-HjOSOjy_KR405t:b-v4yort) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/docker/Dockerfile.base#L9)):*
> ```
> WORKDIR $BASE
> 
> RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y eatmydata sudo && apt-get clean
> ```

BTW, these could probably be changed to `apt update` etc. Entirely optional.

---

*[env/debian/check, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFwXKr_i_zA-YwKxni:-KiFwXKr_i_zA-YwKxnj:b-4wkw6c) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/env/debian/check#L6)):*
> ```
> 
> BASE=$(dirname "$0")
> . $(dirname "$BASE")/common.sh
> ```

Couldn't this be folded into the line above? `$BASE` is not elsewhere in the script.

---

*[env/debian/deps, line 13 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFwfDA-4pguG1Z9d4x:-KiFwfDA-4pguG1Z9d4y:b-mtp16w) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/env/debian/deps#L13)):*
> ```
> [ -z "$pkgs" ] && exit
> 
> sudo DEBIAN_FRONTEND=noninteractive apt-get install $APTARGS --no-remove --no-install-recommends $pkgs
> ```

Is `--no-remove` duplicated here on purpose?

---

*[env/pip3web/check, line 7 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFwwjaZKM_7DphHzSl:-KiFwwjaZKM_7DphHzSm:b13ce3a) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/env/pip3web/check#L7)):*
> ```
> BASE=$(dirname "$0")
> . $(dirname "$BASE")/common.sh
> . "$BASE/common.sh"
> ```

This looks odd. Why is `common.sh` sourced twice from two different locations? Is this just a difference between Py2 and Py3 deps?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-:-KiFxP_2dXWK0qvLKzbl:b-4tp4yf)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docker/deps_check, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFvi99WQ5GrCYVzYjb:-KiFxdhpHTODcXRHL44c:bb77ufg) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/docker/deps_check#L6)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Does this have the same semantics as `echo Check: "$@"`?
</blockquote></details>

Yes.

---

*[docker/Dockerfile.base, line 9 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFw-Hiyy8zPCCPW8RQ:-KiFxgUr0nMkPFzmRXmm:b-smyryd) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/docker/Dockerfile.base#L9)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

BTW, these could probably be changed to `apt update` etc. Entirely optional.
</blockquote></details>

Considered, but apparently `apt` is not supported for that:
`WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

---

*[env/debian/check, line 6 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFwXKr_i_zA-YwKxni:-KiFxvYIUN2jNJaxSjil:b9stgv0) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/env/debian/check#L6)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Couldn't this be folded into the line above? `$BASE` is not elsewhere in the script.
</blockquote></details>

It could in this specific case, but this was it's consistent with all the other env/*/* scripts. Also if  `env/common.sh` ever depended on `$BASE` being set, then this would be needed.

---

*[env/debian/deps, line 13 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFwfDA-4pguG1Z9d4x:-KiFyPQxYltZbAZS02Rx:byh79s8) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/env/debian/deps#L13)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Is `--no-remove` duplicated here on purpose?
</blockquote></details>

Nope, good catch :)

---

*[env/pip3web/check, line 7 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-KiFwwjaZKM_7DphHzSl:-KiFySJcLCONKzamiMsW:by4wz2v) ([raw file](https://github.com/netsec-ethz/scion/blob/b4179edf7bec2807d6b5c401a1dfefba3905c6ed/env/pip3web/check#L7)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This looks odd. Why is `common.sh` sourced twice from two different locations? Is this just a difference between Py2 and Py3 deps?
</blockquote></details>

They are different files. `env/common.sh` vs `env/pip3web/common.sh`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1048)*

**Comment by klausman** [comment]
Bonus :lgtm:!

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1048#-:-KiFzo3i2J_L-dQSFsy5:bqkav4f)*

**Pull request merged**
