### PR TITLE
Request missing tr cs certs

### PR DESCRIPTION
**Pull request by sezergueler**
On receicing a beacon: 

- A list of all TRCs and certificates contained in the beacon is created.

- Checks which TRCs and certificates are missing on this beacon server.

- For missing TRCs and certificates creates requests to receive them

- On receving a reply adds the TRC/certificate to trust store

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/959)

### CODE REVIEW

**Comment by sezergueler** [comment]
@pszalach you can review this

**Comment by pszalach** [comment]
as discussed, this should be part of `SCIONElement`

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[infrastructure/beacon_server/base.py, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-KboGxNSxN7hxDX7VvT6:-KboGxNSxN7hxDX7VvT7:b-995edz) ([raw file](https://github.com/netsec-ethz/scion/blob/e7b2982846e27089dfeb18a77301853d0b69df1b/infrastructure/beacon_server/base.py#L126)):*
> ```Python
>         self.cert_requests = {}
>         self.trcs = {}
>         self.missing_TRCs = deque()
> ```

I'm not sure does it make sense to have it. What would be needed it `pcb/path -> missing TRCs&cert` map. Let's discuss.

---

*[infrastructure/beacon_server/base.py, line 490 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-KboHVVo7O2_ufZJC00E:-KboHVVo7O2_ufZJC00F:b-9fbbmc) ([raw file](https://github.com/netsec-ethz/scion/blob/e7b2982846e27089dfeb18a77301853d0b69df1b/infrastructure/beacon_server/base.py#L490)):*
> ```Python
>             try:
>                 self.process_pcb_queue()
>                 self.process_missing_certs_TRCs_queue()
> ```

I don't believe it is a good place for that.

---

*[lib/packet/pcb.py, line 285 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-Kbo7OfZAIImbua8C2Hb:-Kbo7OfZAIImbua8C2Hc:br3c788) ([raw file](https://github.com/netsec-ethz/scion/blob/e7b2982846e27089dfeb18a77301853d0b69df1b/lib/packet/pcb.py#L285)):*
> ```Python
>         """
>         Returns a dict of all trcs and a dict of all certificates used
>         in this PCB, with their highest version number.
> ```

Description is incorrect. It does return the highest versions of used TRCs and certificates.
I think it is just easier to return everything needed and check what's missing. btw:
- you need all TRCs 
- you need all intermediate TRCs if your local TRC was updated (others TRCs are authenticated via cross-signing)
- you need all certificates used (you don't have to get older certificates. e.g., if you have version=1 and pcb is signed with version=23, only the 23rd cert matters)

---

*[lib/packet/pcb.py, line 294 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-Kbo7rWH0miq6uHIYnD1:-Kbo7rWH0miq6uHIYnD2:b-xbqatn) ([raw file](https://github.com/netsec-ethz/scion/blob/e7b2982846e27089dfeb18a77301853d0b69df1b/lib/packet/pcb.py#L294)):*
> ```Python
>             if isd_ not in trcs.keys() or asm.p.trcVer > trcs[isd_]:
>                 trcs[isd_as] = asm.p.trcVer
>             if isd_as not in certs.keys() or asm.p.certVer > certs[isd_as]:
> ```

as mentioned above, you care only about used certificates

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-:-Kbo8P6byfRCjgMnk7KE:b-df1p8g)*

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 236 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-Kby3jNapQv1_4lSF7Wu:-Kby3jNapQv1_4lSF7Wv:b9sxywy) ([raw file](https://github.com/netsec-ethz/scion/blob/bb1468fda74b61dcb6454e931668e7e4b7b35b74/infrastructure/scion_elem.py#L236)):*
> ```Python
>             log_exception("Error handling message:\n%s" % msg)
> 
>     def handle_pcb_path(self, msg, meta):
> ```

This isn't called by anything, so i can't tell when it's supposed to be used. Also, what is a `path` in this context?

---

*[infrastructure/scion_elem.py, line 240 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-Kby3sRkfhpiq7UHVXqG:-Kby3sRkfhpiq7UHVXqH:b7iec4g) ([raw file](https://github.com/netsec-ethz/scion/blob/bb1468fda74b61dcb6454e931668e7e4b7b35b74/infrastructure/scion_elem.py#L240)):*
> ```Python
>         When a pcb or path is received, this function is called to find missing
>         TRCs and certs and request them. TODO: Maybe call this handle_msg?
>         TODO: First, one needs to check that a msg is a pcb or path.
> ```

Any `TODO` (or `FIXME` or `XXX`) needs to be followed by the username of the person adding it.  E.g. `TODO(kormat)`.

---

*[infrastructure/scion_elem.py, line 250 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-KbyckKiFjEYbOSWsl3U:-KbyckKiFjEYbOSWsl3V:bmuxmnn) ([raw file](https://github.com/netsec-ethz/scion/blob/bb1468fda74b61dcb6454e931668e7e4b7b35b74/infrastructure/scion_elem.py#L250)):*
> ```Python
>             self._get_missing_trcs_certs(trcs, meta)
> 
>     def process_trc_rep(self, rep, meta):
> ```

When i search the codebase i see the following definitions:
```
infrastructure/beacon_server/base.py:    def process_trc_rep(self, rep, meta):
infrastructure/cert_server/main.py:    def process_trc_reply(self, trc_rep, meta, from_zk=False):
infrastructure/scion_elem.py:    def process_trc_rep(self, rep, meta):
```
What is the difference between them?

---

*[infrastructure/scion_elem.py, line 270 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-KbydkVhSzlQeagfiTgh:-KbydkVhSzlQeagfiTgi:b-lh7dh6) ([raw file](https://github.com/netsec-ethz/scion/blob/bb1468fda74b61dcb6454e931668e7e4b7b35b74/infrastructure/scion_elem.py#L270)):*
> ```Python
>         """
>         Check which intermediate trcs are missing and which cetificates are
>         missing and return them.
> ```

The name and description are misleading. It sounds like it actually retrieves the missing certs/TRCs, as opposed to identifying which ones are missing.

---

*[infrastructure/beacon_server/base.py, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-KboGxNSxN7hxDX7VvT6:-KbyfJdwdqZeFNpegeFN:b-k9rxxy) ([raw file](https://github.com/netsec-ethz/scion/blob/e7b2982846e27089dfeb18a77301853d0b69df1b/infrastructure/beacon_server/base.py#L126)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

I'm not sure does it make sense to have it. What would be needed it `pcb/path -> missing TRCs&cert` map. Let's discuss.
</blockquote></details>

It's also never added to.

---

*[infrastructure/beacon_server/base.py, line 588 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-KbyeGPAkDpk_HemVMy8:-KbyeGPBHVdTZHAqErS8:b9l0laq) ([raw file](https://github.com/netsec-ethz/scion/blob/bb1468fda74b61dcb6454e931668e7e4b7b35b74/infrastructure/beacon_server/base.py#L588)):*
> ```Python
> 
>     @abstractmethod
>     def process_cert_chain_rep(self, cert_chain_rep, meta):
> ```

This method is overridden by both the local and core BSes, so this won't ever get used:
```
infrastructure/beacon_server/base.py:    def process_cert_chain_rep(self, cert_chain_rep, meta):
infrastructure/beacon_server/core.py:    def process_cert_chain_rep(self, cert_chain_rep, meta):
infrastructure/beacon_server/local.py:    def process_cert_chain_rep(self, rep, meta):
```

---

*[lib/packet/pcb.py, line 292 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-KbyfumKWQoQ4-JLxXfk:-KbyfumKWQoQ4-JLxXfl:b2dnbba) ([raw file](https://github.com/netsec-ethz/scion/blob/bb1468fda74b61dcb6454e931668e7e4b7b35b74/lib/packet/pcb.py#L292)):*
> ```Python
>             isd_as = str(asm.isd_as())
>             isd_ = str(asm.isd_as()[0])
>             if isd_ not in trcs.keys():
> ```

`.keys()` is unnecessary here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/959)*

**Comment by pszalach** [comment]
Review status: 1 of 3 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 161 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-Kc1xiLnAuwBC35Jmt2C:-Kc1xiLnAuwBC35Jmt2D:b-leiy41) ([raw file](https://github.com/netsec-ethz/scion/blob/15a48f1195e3b2e68653f90209cf6aad4332ec97/infrastructure/scion_elem.py#L161)):*
> ```Python
>         else:
>             self.DefaultMeta = UDPMetadata
>         self.msg_missing_trcs_certs_map = {}
> ```

msg -> path?

---

*[infrastructure/scion_elem.py, line 162 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-Kc1xk0YzYcMBy6mOKzi:-Kc1xk0YzYcMBy6mOKzj:b-rqxvol) ([raw file](https://github.com/netsec-ethz/scion/blob/15a48f1195e3b2e68653f90209cf6aad4332ec97/infrastructure/scion_elem.py#L162)):*
> ```Python
>             self.DefaultMeta = UDPMetadata
>         self.msg_missing_trcs_certs_map = {}
>         self.msgs_to_verify = deque()
> ```

ditto 

---

*[infrastructure/scion_elem.py, line 243 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/959#-Kc1xoO0dmLTBjd297BD:-Kc1xoO0dmLTBjd297BE:b-rqrrsi) ([raw file](https://github.com/netsec-ethz/scion/blob/15a48f1195e3b2e68653f90209cf6aad4332ec97/infrastructure/scion_elem.py#L243)):*
> ```Python
>         When a pcb or path is received, this function is called to find missing
>         TRCs and certs and request them. TODO: First, one needs to check that
>         a msg is a pcb or path. What other kinds of messages can a SCION element
> ```

there are many messages a SCION elem can receive, however certificate and trc distribution is tied to paths (i.e., pcbs and path segments), so I would rename that to `verify_path()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/959)*

**Pull request closed without merging**
