### PR TITLE
cmac deps

### PR DESCRIPTION
**Pull request by pszalach**
Required to build #999

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1045)

### CODE REVIEW

**Comment by pszalach** [comment]
@kormat

**Comment by kormat** [comment]
Please update the `scion_base` hash in `.circle/config.yml` to `sha256:99e5771f2624fac797d008008a6ba186c19aac9d2680127df2fd113e2275e2ce` and repush.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1045#-:-Ki5vqMciAGsWRvHQ4u0:b-4hcmt0)*

**Comment by pszalach** [comment]
Done.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1045#-:-Ki9FztI2zhAbDso9MPm:b-896fix)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1045#-:-Ki9jvdIlfWiJcA2ryaS:bnfp4nl)*

**Pull request merged**
