### PR TITLE
Make PathSegmentTTL and RevocationTreeTTL configurable.

### LINKED ISSUE #1098: Don't assume global hashtree ttl window size
If ASes want to have a max segment ttl of greater than 24h, for example, the current code would not allow them to revoke PCBs that are older than 24h. From a discussion with @shitz, keeping the epoch window size to 10s is probably a good idea (for consistency and network overhead reasons), but that each AS should be able to decide on their hashtree ttl window size. This then needs to be communicated to other ASes, in revocation info messages, and maybe in PCBs(?).

### PR DESCRIPTION
**Pull request by shitz**
This PR adds the ability for each AS to configure the TTL of both their path segments and the revocation tree. The revocation tree TTL has to be at least as large as the path segment TTL.

Since each AS now can have a different revocation tree TTL, each revocation needs to include the TTL of the corresponding tree. Fixes #1098.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1164)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 10 of 12 files at r1.
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docker/Dockerfile, line 21 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1164#-KsO4bLmr-YZfoJrk6-1:-KsO4bLmr-YZfoJrk6-2:b-1snexp) ([raw file](https://github.com/netsec-ethz/scion/blob/7d594659ce803bc68497e1908a346d1d5a22efa3/docker/Dockerfile#L21)):*
> ```Dockerfile
> 
> # Build topology files
> RUN ./scion.sh topology --circleci
> ```

This isn't the right place. The topology is regenerated on circleci, in `tools/ci/build_prep`.

---

*[python/topology/generator.py, line 1312 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1164#-KsO4UEfWakLG25gx2t_:-KsO4UEgUmYwHyxMZhar:bp6brpi) ([raw file](https://github.com/netsec-ethz/scion/blob/7d594659ce803bc68497e1908a346d1d5a22efa3/python/topology/generator.py#L1312)):*
> ```Python
>     parser.add_argument('-b', '--bind-addr', default=GENERATE_BIND_ADDRESS,
>                         help='Generate bind addresses (E.g. "192.168.0.0/16"')
>     parser.add_argument('--circleci', action='store_true',
> ```

I would prefer instead to specify the segment ttl as the flag. `--pseg-ttl` or similar. That's much more generic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1164)*

**Comment by shitz** [comment]
Review status: 4 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[docker/Dockerfile, line 21 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1164#-KsO4bLmr-YZfoJrk6-1:-Kux9hr9mDFGc7qGU1fb:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/7d594659ce803bc68497e1908a346d1d5a22efa3/docker/Dockerfile#L21)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This isn't the right place. The topology is regenerated on circleci, in `tools/ci/build_prep`.
</blockquote></details>

Done.

---

*[python/topology/generator.py, line 1312 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1164#-KsO4UEfWakLG25gx2t_:-Kux9gCEhgC4q4QnW2RI:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/7d594659ce803bc68497e1908a346d1d5a22efa3/python/topology/generator.py#L1312)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I would prefer instead to specify the segment ttl as the flag. `--pseg-ttl` or similar. That's much more generic.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1164)*

**Comment by kormat** [comment]
Reviewed 8 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/lib/ctrl/path_mgmt/rev_info.go, line 56 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1164#-KuyVROgO0rTugFunXgU:-KuyVROhiOmCMX2n33pd:b46mwkq) ([raw file](https://github.com/netsec-ethz/scion/blob/a18b8c29720231ca2ead74f125262742aa958541/go/lib/ctrl/path_mgmt/rev_info.go#L56)):*
> ```Go
> 
> func (r *RevInfo) String() string {
> 	return fmt.Sprintf("IA: %v IfID: %v Epoch: %v TreeTTL: %v",
> ```

These should use the appropriate string formatting operators. %s, and 3x %d.

---

*[python/lib/crypto/hash_tree.py, line 51 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1164#-KsO7GdYGShi3DqG6HCP:-KsO7GdZMX1inK4HA864:b-y3txps) ([raw file](https://github.com/netsec-ethz/scion/blob/7d594659ce803bc68497e1908a346d1d5a22efa3/python/lib/crypto/hash_tree.py#L51)):*
> ```Python
>         self._hash_type = hash_type
>         self._hash_func = hash_func_for_type(hash_type)
>         self._n_epochs = ttl // HASHTREE_EPOCH_TIME
> ```

This assumes that `ttl` is a strict multiple of `HASHTREE_EPOCH_TIME`. That should probably be asserted somewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1164)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/lib/ctrl/path_mgmt/rev_info.go, line 56 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1164#-KuyVROgO0rTugFunXgU:-KuybW65a-wu7jImZBWP:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a18b8c29720231ca2ead74f125262742aa958541/go/lib/ctrl/path_mgmt/rev_info.go#L56)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These should use the appropriate string formatting operators. %s, and 3x %d.
</blockquote></details>

Done.

---

*[python/lib/crypto/hash_tree.py, line 51 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1164#-KsO7GdYGShi3DqG6HCP:-KuybhYMQ2swUMJieXQO:b-fwik1p) ([raw file](https://github.com/netsec-ethz/scion/blob/7d594659ce803bc68497e1908a346d1d5a22efa3/python/lib/crypto/hash_tree.py#L51)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This assumes that `ttl` is a strict multiple of `HASHTREE_EPOCH_TIME`. That should probably be asserted somewhere.
</blockquote></details>

Hmm not necessarily. It would just be rounded towards 0 otherwise (iirc) and I *think* it should still work. However, I agree that the `TTL` should be a multiple of the epoch anyway. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1164)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1164#-:-KuygnXTuisLuOhze_HE:bnfp4nl)*

**Comment by shitz** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1164)*

**Pull request merged**
