### PR TITLE
Ca certificate implementation

### PR DESCRIPTION
**Pull request by sezergueler**
Root CA generation for ISDs. Added CA certificates to TRC.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/966)

### CODE REVIEW

**Comment by pszalach** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[topology/generator.py, line 364 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXpv1SRygPChs6LTDm:-KcXpv1SRygPChs6LTDn:bpufy4) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L364)):*
> ```Python
>     def __init__(self, topo_config):
>         self.topo_config = topo_config
>         self.ca_keys = {}
> ```

these are private or public keys? (reflect that in the name)

---

*[topology/generator.py, line 394 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXqCQVuAMiIcaf1qSP:-KcXqCQVuAMiIcaf1qSQ:b7cq5gi) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L394)):*
> ```Python
>         ca.get_subject().OU = ca_config["organizationalUnitName"]
>         ca.gmtime_adj_notBefore(0)
>         ca.gmtime_adj_notAfter(24 * 60 * 60)
> ```

seems like it will be valid one day. Make them valid ~5 years.

---

*[topology/generator.py, line 398 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXqOZWXArltYwJ9Ve5:-KcXqOZWXArltYwJ9Ve6:b-39ivn3) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L398)):*
> ```Python
>         ca.set_pubkey(self.ca_keys[ca_name])
>         ca.add_extensions([
>             crypto.X509Extension(
> ```

please comment implications of this config. Especially `basicConstraints` and `pathlen` are important

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by sezergueler** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[topology/generator.py, line 364 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXpv1SRygPChs6LTDm:-KcYCiGBuxS8jgGUwBQN:b-pqlvue) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L364)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

these are private or public keys? (reflect that in the name)
</blockquote></details>

This is a OpenSSL PKey Object, it represents the RSA key pair. Call it better ca_key_pairs ?

---

*[topology/generator.py, line 394 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXqCQVuAMiIcaf1qSP:-KcYD1zmB3v3G-wGEQdz:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L394)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

seems like it will be valid one day. Make them valid ~5 years.
</blockquote></details>

Done.

---

*[topology/generator.py, line 398 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXqOZWXArltYwJ9Ve5:-KcYU47m-J6xfl0k4pSJ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L398)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

please comment implications of this config. Especially `basicConstraints` and `pathlen` are important
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by sezergueler** [comment]
@pszalach you can review

**Comment by pszalach** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[topology/generator.py, line 364 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXpv1SRygPChs6LTDm:-KcYbPOo4wkJqTXW9cb2:b-er5873) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L364)):*
<details><summary><i>Previously, sezergueler wrote…</i></summary><blockquote>

This is a OpenSSL PKey Object, it represents the RSA key pair. Call it better ca_key_pairs ?
</blockquote></details>

yes, that makes more sense

---

*[topology/generator.py, line 398 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXqOZWXArltYwJ9Ve5:-KcYbb_Uh21Q6sPaLys1:b-w4esth) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L398)):*
<details><summary><i>Previously, sezergueler wrote…</i></summary><blockquote>

Done.
</blockquote></details>

pathlen=0 isn't the best idea for root CAs. Please set to 1.

---

*[topology/generator.py, line 413 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcYc06roYVIWBvuGOIX:-KcYc06roYVIWBvuGOIY:b3d5lsz) ([raw file](https://github.com/netsec-ethz/scion/blob/d1291b1934e4c5eeaa5d1b5cdb00f3f59cb4bb9e/topology/generator.py#L413)):*
> ```Python
>             # used for verifying signatures on public key certificates.
>             crypto.X509Extension(b"keyUsage", True, b"keyCertSign, cRLSign"),
>             # The keyIdentifier is composed of the 160-bit SHA-1 hash of the
> ```

can we use sha2?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by sezergueler** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[topology/generator.py, line 364 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXpv1SRygPChs6LTDm:-KcZxKRTcwYdlk1woTGi:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L364)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

yes, that makes more sense
</blockquote></details>

Done.

---

*[topology/generator.py, line 413 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcYc06roYVIWBvuGOIX:-KcZxmuxNRSU8PRoiL-x:b80v397) ([raw file](https://github.com/netsec-ethz/scion/blob/d1291b1934e4c5eeaa5d1b5cdb00f3f59cb4bb9e/topology/generator.py#L413)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

can we use sha2?
</blockquote></details>

I did not find out if really SHA-1 is used if one puts "hash" there. According to the RFC it would compute the SHA-1 hash, but the documentation does not say what is implemented there. 

To be sure, we would need to compute the sha2 hash ourselves. I implemented a basic approach, which is not correct yet. I take the public key file and hash it with sha2, but what we need is just the public key itself without the other information. We would need to parse the file ourselves to get the public key. It seems that openssl does not support this. http://certificateerror.blogspot.ch/2011/02/how-to-validate-subject-key-identifier.html 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by sezergueler** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[topology/generator.py, line 398 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXqOZWXArltYwJ9Ve5:-KccAhYVfxTSPscFARqV:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L398)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

pathlen=0 isn't the best idea for root CAs. Please set to 1.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by pszalach** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[topology/generator.py, line 413 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcYc06roYVIWBvuGOIX:-KccHu76e5jL6Jc3AMH4:b6e3uyz) ([raw file](https://github.com/netsec-ethz/scion/blob/d1291b1934e4c5eeaa5d1b5cdb00f3f59cb4bb9e/topology/generator.py#L413)):*
<details><summary><i>Previously, sezergueler wrote…</i></summary><blockquote>

I did not find out if really SHA-1 is used if one puts "hash" there. According to the RFC it would compute the SHA-1 hash, but the documentation does not say what is implemented there. 

To be sure, we would need to compute the sha2 hash ourselves. I implemented a basic approach, which is not correct yet. I take the public key file and hash it with sha2, but what we need is just the public key itself without the other information. We would need to parse the file ourselves to get the public key. It seems that openssl does not support this. http://certificateerror.blogspot.ch/2011/02/how-to-validate-subject-key-identifier.html 
</blockquote></details>

The link is quite old, now sha1 is sunsetting (https://cabforum.org/2014/10/16/ballot-118-sha-1-sunset/), but maybe that lib does not support it. So leave it as it is for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by pszalach** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[topology/generator.py, line 398 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXqOZWXArltYwJ9Ve5:-KccIeevVCTma0wtC39H:b-b84h7x) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L398)):*
<details><summary><i>Previously, sezergueler wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sync comment with the value or make it generic (now comment says about pathlen 0)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by sezergueler** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[topology/generator.py, line 398 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcXqOZWXArltYwJ9Ve5:-KccP9hGQeivfZS7CmkP:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca3f1265e58dceb87a9a6ca1d077125e973293e4/topology/generator.py#L398)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

sync comment with the value or make it generic (now comment says about pathlen 0)
</blockquote></details>

Done.

---

*[topology/generator.py, line 413 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcYc06roYVIWBvuGOIX:-KccPAOeLUbXYayJbk6V:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d1291b1934e4c5eeaa5d1b5cdb00f3f59cb4bb9e/topology/generator.py#L413)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

The link is quite old, now sha1 is sunsetting (https://cabforum.org/2014/10/16/ballot-118-sha-1-sunset/), but maybe that lib does not support it. So leave it as it is for now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by pszalach** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-:-KccPlQRntNaoN9UOyaC:bnfp4nl)*

**Comment by sezergueler** [comment]
@kormat Can you review, please?

**Comment by kormat** [comment]
Reviewed 3 of 5 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[lib/util.py, line 93 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kcclls2WlLZLqKARKzz:-Kcclls2WlLZLqKARL--:b-jgiq3p) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/lib/util.py#L93)):*
> ```Python
>     Return the ca private key file path
>     """
>     return os.path.join(conf_dir, CAS_DIR, "%s.key" % name)
> ```

I'm a bit concerned about the location of this. It seems to be under `gen/ISDX/cas/`. Until now every directory under `gen/ISDX` was an AS dir. Adding a non-AS dir could break assumptions, and makes scripting/automation harder. Perhaps create `gen/CAs/` and use that instead?

---

*[lib/util.py, line 98 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcckCLztbNnmyOpS202:-KcckCM-RAqiCt5Ua5L3:b-4nh4gw) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/lib/util.py#L98)):*
> ```Python
> def get_ca_cert_file_path(conf_dir, name):
>     """
>     Return the ca private key file path
> ```

Needs updating.

---

*[topology/Default.topo, line 70 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kccl-7H9Pcnp5hhvKOf:-Kccl-7H9Pcnp5hhvKOg:b-n65q1t) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/topology/Default.topo#L70)):*
> ```
>   2-26:
>     cert_issuer: 2-24
> CAs:
> ```

If this section is now mandatory, it needs to be added to the other `.topo` files.

---

*[topology/generator.py, line 413 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcYc06roYVIWBvuGOIX:-KccqfaQOJ8TrYO_Qqkt:bjtejtl) ([raw file](https://github.com/netsec-ethz/scion/blob/d1291b1934e4c5eeaa5d1b5cdb00f3f59cb4bb9e/topology/generator.py#L413)):*
<details><summary><i>Previously, sezergueler wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sha2 would definitely be important, so i'm glad to see it's in there now.

---

*[topology/generator.py, line 206 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KccmLgfgenUtpO2LbNZ:-KccmLgfgenUtpO2LbN_:b-45fywz) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/topology/generator.py#L206)):*
> ```Python
>         isds = set()
>         for topo_id, as_topo in topo_dicts.items():
>             isds.add(str(topo_id).split("-", 1)[0])
> ```

`topo_id[0]`

---

*[topology/generator.py, line 207 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KccmRCgHLifjzLRYnoF:-KccmRCgHLifjzLRYnoG:b-hwcyom) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/topology/generator.py#L207)):*
> ```Python
>         for topo_id, as_topo in topo_dicts.items():
>             isds.add(str(topo_id).split("-", 1)[0])
>         for isd_ in isds:
> ```

Why the `_`?

---

*[topology/generator.py, line 210 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kcco2E8t6vzbhbNYb7n:-Kcco2E9eGBg7WiWm6ed:b-265c53) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/topology/generator.py#L210)):*
> ```Python
>             base = os.path.join(self.out_dir, "ISD%s" % isd_)
>             for path, value in ca_files[int(isd_)].items():
>                 write_file(os.path.join(base, path), str(value))
> ```

This ends up writing a quoted python string to the file. Change to `value.decode()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by sezergueler** [comment]
Review status: 3 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[lib/util.py, line 93 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kcclls2WlLZLqKARKzz:-KcdCREpn_dy5SZkx_0J:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/lib/util.py#L93)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'm a bit concerned about the location of this. It seems to be under `gen/ISDX/cas/`. Until now every directory under `gen/ISDX` was an AS dir. Adding a non-AS dir could break assumptions, and makes scripting/automation harder. Perhaps create `gen/CAs/` and use that instead?
</blockquote></details>

Done.

---

*[lib/util.py, line 98 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcckCLztbNnmyOpS202:-KcdCS2KPvaKq4tv6BuT:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/lib/util.py#L98)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Needs updating.
</blockquote></details>

Done.

---

*[topology/Default.topo, line 70 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kccl-7H9Pcnp5hhvKOf:-KcdCTjqnffqvbaRPiCE:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/topology/Default.topo#L70)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

If this section is now mandatory, it needs to be added to the other `.topo` files.
</blockquote></details>

Done.

---

*[topology/generator.py, line 413 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcYc06roYVIWBvuGOIX:-KcdCqn1OSO0Kfn49Roo:bccen92) ([raw file](https://github.com/netsec-ethz/scion/blob/d1291b1934e4c5eeaa5d1b5cdb00f3f59cb4bb9e/topology/generator.py#L413)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

sha2 would definitely be important, so i'm glad to see it's in there now.
</blockquote></details>

I am not sure, which hash function is used here(for subjectKeyIdentifier constraint). I did not find this information in the openssl documentation. Later(3 lines below) we use sha2 to sign the certificate, there it is possible to choose a particular hash function. But for the constraint it seems like you can not choose.

---

*[topology/generator.py, line 206 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KccmLgfgenUtpO2LbNZ:-KcdCVI7IcP3xfynGdHW:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/topology/generator.py#L206)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`topo_id[0]`
</blockquote></details>

Done.

---

*[topology/generator.py, line 207 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KccmRCgHLifjzLRYnoF:-KcdCWCYffVNg9qO_AKu:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/topology/generator.py#L207)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Why the `_`?
</blockquote></details>

Done.

---

*[topology/generator.py, line 210 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kcco2E8t6vzbhbNYb7n:-KcdCYJntRR9BtGRY-d6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/topology/generator.py#L210)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This ends up writing a quoted python string to the file. Change to `value.decode()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by pszalach** [comment]
Review status: 3 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[lib/util.py, line 93 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kcclls2WlLZLqKARKzz:-KcdOGO4Q17VxnP81Sey:b-62hokm) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/lib/util.py#L93)):*
<details><summary><i>Previously, sezergueler wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is something I suggested, as CAs are "local" for TRC files, which are per ISD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by sezergueler** [comment]
@kormat This is done. Can you review?

**Comment by kormat** [comment]
Reviewed 2 of 4 files at r4, 1 of 3 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[lib/crypto/trc.py, line 254 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kd5o4Y18L4JG-Mjw51-:-Kd5o4Y18L4JG-Mjw510:bgug08s) ([raw file](https://github.com/netsec-ethz/scion/blob/6a5423f4aa9597b9387cc0171f18dc50dc773777/lib/crypto/trc.py#L254)):*
> ```Python
>         root_cas = {}
>         for subject in trc_dict[ROOT_CAS_STRING]:
>             cert_str = trc_dict[ROOT_CAS_STRING][subject]
> ```

This can be simplified to:
```
for subject, cert_str in trc_dict[ROOT_CAS_STRING].items():
  root_cas[subject] = base64.b64encode(cert_str).decode()
```

---

*[topology/Default.topo, line 72 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kd5oPv11Msw3VEf8efz:-Kd5oPv22Uda1qyWgswN:b1q1u74) ([raw file](https://github.com/netsec-ethz/scion/blob/6a5423f4aa9597b9387cc0171f18dc50dc773777/topology/Default.topo#L72)):*
> ```
> CAs:
>   CA1-1:
>     ISD: 1
> ```

Isn't it already included in the `CA1-x` name? Looking at the changes to `Wide.topo`, the two values disagree a lot.

---

*[topology/generator.py, line 413 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcYc06roYVIWBvuGOIX:-Kd5pRbBUflpye2NTq9E:bj7fayj) ([raw file](https://github.com/netsec-ethz/scion/blob/d1291b1934e4c5eeaa5d1b5cdb00f3f59cb4bb9e/topology/generator.py#L413)):*
Ahh, ok. I hadn't looked at the context. From RFC6818:

> | One-way hash functions are commonly used to generate key identifier
| values (AKI and SKI), e.g., as described in Sections 4.1.1 and 4.1.2.
| However, none of the security properties of such functions are
| required for this context.

And
> collision resistance is not a required property of one-way hash functions when used to generate key identifiers.

So yeah, SHA-1 is totally fine.

---

*[topology/Wide.topo, line 127 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kd5qADxyP9XSeDZEBDI:-Kd5qADxyP9XSeDZEBDJ:bmlx2qj) ([raw file](https://github.com/netsec-ethz/scion/blob/6a5423f4aa9597b9387cc0171f18dc50dc773777/topology/Wide.topo#L127)):*
> ```
>     organizationalUnitName: my organization
>   CA5-3:
>     ISD: 2
> ```

Most of the ISD values here don't match the names given.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by sezergueler** [comment]
Review status: 5 of 7 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[lib/util.py, line 93 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kcclls2WlLZLqKARKzz:-Kd76G3q0ZAWx96F2xxY:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2062e1eba0eba19804b762b5830eaa1e26e7b3ab/lib/util.py#L93)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

This is something I suggested, as CAs are "local" for TRC files, which are per ISD
</blockquote></details>

Done.

---

*[lib/crypto/trc.py, line 254 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kd5o4Y18L4JG-Mjw51-:-Kd76z7vYIoAu0XWlP-v:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6a5423f4aa9597b9387cc0171f18dc50dc773777/lib/crypto/trc.py#L254)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be simplified to:
```
for subject, cert_str in trc_dict[ROOT_CAS_STRING].items():
  root_cas[subject] = base64.b64encode(cert_str).decode()
```
</blockquote></details>

Done.

---

*[topology/Default.topo, line 72 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kd5oPv11Msw3VEf8efz:-Kd77-K_jIiYVdEntt8b:bquw7d2) ([raw file](https://github.com/netsec-ethz/scion/blob/6a5423f4aa9597b9387cc0171f18dc50dc773777/topology/Default.topo#L72)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Isn't it already included in the `CA1-x` name? Looking at the changes to `Wide.topo`, the two values disagree a lot.
</blockquote></details>

In this case it is included, yes. But we do not have any restrictions for CA names yet. They could have any name, and the name may not include the isdid. 

---

*[topology/generator.py, line 413 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-KcYc06roYVIWBvuGOIX:-Kd77ZR8eCcodmdj5C5n:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d1291b1934e4c5eeaa5d1b5cdb00f3f59cb4bb9e/topology/generator.py#L413)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Ahh, ok. I hadn't looked at the context. From RFC6818:

> | One-way hash functions are commonly used to generate key identifier
| values (AKI and SKI), e.g., as described in Sections 4.1.1 and 4.1.2.
| However, none of the security properties of such functions are
| required for this context.

And
> collision resistance is not a required property of one-way hash functions when used to generate key identifiers.

So yeah, SHA-1 is totally fine.
</blockquote></details>

Done.

---

*[topology/Wide.topo, line 127 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-Kd5qADxyP9XSeDZEBDI:-Kd77aPwtNRgsoobdktx:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6a5423f4aa9597b9387cc0171f18dc50dc773777/topology/Wide.topo#L127)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Most of the ISD values here don't match the names given.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966#-:-KdBQFJJ3yKKjp7QcwXw:bnfp4nl)*

**Comment by pszalach** [comment]
Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 1 of 4 files at r4, 1 of 2 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/966)*

**Pull request merged**
