### PR TITLE
Increase go checksum performance 2x

### PR DESCRIPTION
**Pull request by kormat**
Before: 948 ns/op
After: 455 ns/op

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1209)

### CODE REVIEW

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1209#-:-KrV-aY_ZF7VDwr8oC8F:bnfp4nl)*

**Comment by scrye** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[go/lib/util/checksum.go, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1209#-KrV0VcHEzACVwjTsrgR:-KrV0VcHEzACVwjTsrgS:batlgd) ([raw file](https://github.com/netsec-ethz/scion/blob/f8a6819a7dd3c32837e48b71c3f7da0346c3d319/go/lib/util/checksum.go#L56)):*
> ```Go
> 		sum = (sum >> 16) + (sum & 0xffff)
> 	}
> 	sum = (sum&0xFF)<<8 + (sum >> 8)
> ```

I think this inversion breaks stuff for big-endian architectures, in that case you wouldn't want to swap the bytes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1209)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1209#-:-KrV1PBuQTr7nIr9yTgl:bnfp4nl)*

**Comment by scrye** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/common/defs.go, line 31 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1209#-KrV1zpc36hEMIkRa7mW:-KrV1zpc36hEMIkRa7mX:b-bsphd2) ([raw file](https://github.com/netsec-ethz/scion/blob/6d95ccd9c93bec6d1289aa66355cfe98ceede86e/go/lib/common/defs.go#L31)):*
> ```Go
> var Order = binary.BigEndian
> var NativeOrder binary.ByteOrder
> var BigEndian bool
> ```

I suggest renaming this (maybe `IsBigEndian`?) to prevent confusion as it has the same name as `encoding/binary.BigEndian`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1209)*

**Comment by scrye** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/util/checksum.go, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1209#-KrV0VcHEzACVwjTsrgR:-KrV2fc3DeA13USeu-m-:b9u3dbn) ([raw file](https://github.com/netsec-ethz/scion/blob/f8a6819a7dd3c32837e48b71c3f7da0346c3d319/go/lib/util/checksum.go#L56)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

I think this inversion breaks stuff for big-endian architectures, in that case you wouldn't want to swap the bytes.
</blockquote></details>

Aaand, now it's fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1209)*

**Comment by klausman** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1209)*

**Pull request merged**
