### PR TITLE
Revocation epoch tolerance window

### LINKED ISSUE #854: include hash type in revocation message
Currently the revocation system uses sha256. This should be specified in the revocation message, so that any node that receives it can use the appropriate hash function to verify.

### LINKED ISSUE #1077: Race-condition in revocation renewals
As seen in https://circleci.com/gh/netsec-ethz/scion/4834, there's a race-condition when a BS renews a revocation. If a packet arrives just after a revocation epoch has ended, but just before the BS issues a renewed revocation, the packet will be forwarded by the BRs. We can fix this by adding a small tolerance to the end time of a revocation in the BR. E.g. if a packet arrives within 1s of a revocation expiring, still send the revocation in response. This gives the BS time to issue a new revocation if needed.

Relatedly, this seems a bit too lax: `lib/defines.py:HASHTREE_EPOCH_TOLERANCE = 5`
If the window for the BR is 1s, then the above constant should probably be 2s, so that clients will still accept revocations send in the above renewal window.

### PR DESCRIPTION
**Pull request by shitz**
BR uses now a tolerance window when verifying a revocation epoch. Reduce tolerance window to 2s (from 5s). Fixes #1077.

Additionally, the `RevInfo` now contains the hash function type needed to verify the revocation (fixes #854) and the `epoch` in `RevInfo` is now relative to 0 UNIX time (instead of the current TTL window). This fixes a bug when verifying the epoch from a different TTL window.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1083)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/crypto/htree.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-KkVweqiHmP6JttHxkn4:-KkVweqiHmP6JttHxkn5:bqv3tzp) ([raw file](https://github.com/netsec-ethz/scion/blob/642a4b4d4caa0f1550bfee8af5a4e38e55cc069b/go/lib/crypto/htree.go#L31)):*
> ```Go
> // HashTreeEpochTolerance is the duration after a revocation expired within which a
> // revocation is still accepted by a verifier.
> const HashTreeEpochTolerance float64 = 2.0
> ```

`const HashTreeEpochTolerance time.Duration = 2 * time.Second`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Comment by kormat** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Comment by shitz** [comment]
As discussed offline I made `epoch` in `RevInfo` relative to zero-UNIX time (instead of current TTL window) and the `RevInfo` now also contains the hash function type needed to verify the revocation.

---

Review status: 1 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/crypto/htree.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-KkVweqiHmP6JttHxkn4:-KkkxuDlIAcZJj6Foj30:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/642a4b4d4caa0f1550bfee8af5a4e38e55cc069b/go/lib/crypto/htree.go#L31)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`const HashTreeEpochTolerance time.Duration = 2 * time.Second`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-:-KkkxekyU1P9ssDKylXN:b-jiamec)*

**Comment by kormat** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/lib/crypto/htree.go, line 41 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-KkobztHJvxX0R2FVKKd:-KkobztHJvxX0R2FVKKe:b-okl1ki) ([raw file](https://github.com/netsec-ethz/scion/blob/7b523ba12d1e7172c6ba8a8877fe33dc6b44fcf2/go/lib/crypto/htree.go#L41)):*
> ```Go
> 
> // GetTimeSinceHashTreeEpoch returns the time since the start of the current epoch.
> func GetTimeSinceHashTreeEpoch() time.Duration {
> ```

If this takes an epoch as a parameter:
```
epochStart := epoch * HashTreeEpochTime.Seconds() * time.Second
return time.Since(epochStart)
```
then `VerifyHashTree` gets simpler:
```
return GetTimeSinceHashTreeEpoch(epoch) < HashTreeEpochTolerance
```

---

*[go/lib/crypto/htree.go, line 43 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-KkoXcuoJ360uBCakv1Z:-KkoXcupAzZRfyOSMT8k:brjyhvc) ([raw file](https://github.com/netsec-ethz/scion/blob/7b523ba12d1e7172c6ba8a8877fe33dc6b44fcf2/go/lib/crypto/htree.go#L43)):*
> ```Go
> func GetTimeSinceHashTreeEpoch() time.Duration {
> 	nanoSecs := time.Now().UnixNano() % HashTreeEpochTime.Nanoseconds()
> 	return time.Unix(0, nanoSecs).Sub(time.Unix(0, 0))
> ```

(If not replacing this with my suggestion above) 
This looks a bit complex. How about `return time.Duration(nanoSecs)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Comment by shitz** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/crypto/htree.go, line 41 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-KkobztHJvxX0R2FVKKd:-Kkps056M5VcrnltpVJy:bn4kfjo) ([raw file](https://github.com/netsec-ethz/scion/blob/7b523ba12d1e7172c6ba8a8877fe33dc6b44fcf2/go/lib/crypto/htree.go#L41)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

If this takes an epoch as a parameter:
```
epochStart := epoch * HashTreeEpochTime.Seconds() * time.Second
return time.Since(epochStart)
```
then `VerifyHashTree` gets simpler:
```
return GetTimeSinceHashTreeEpoch(epoch) < HashTreeEpochTolerance
```


</blockquote></details>

Done (with a slight correction).

---

*[go/lib/crypto/htree.go, line 43 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-KkoXcuoJ360uBCakv1Z:-Kkps6-mf5IUctjzEp7a:bdv89gc) ([raw file](https://github.com/netsec-ethz/scion/blob/7b523ba12d1e7172c6ba8a8877fe33dc6b44fcf2/go/lib/crypto/htree.go#L43)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

(If not replacing this with my suggestion above) 
This looks a bit complex. How about `return time.Duration(nanoSecs)`?
</blockquote></details>

Not applicable anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-:-KkpvAMjVCmndBsV1dNt:bnfp4nl)*

**Comment by shitz** [comment]
`cacheOnly` is now always set for TRC/Cert requests from `SCIONElement`

---

Review status: 10 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-:-KkuA1jBm-pbAhcx5en2:biv5o4v)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[infrastructure/cert_server/main.py, line 215 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-KkuI51Kp9IZwStKbRCf:-KkuI51Kp9IZwStKbRCg:bp0noxu) ([raw file](https://github.com/netsec-ethz/scion/blob/2ec3d1f83e062adefea64dd92de259d8aa63dc78/infrastructure/cert_server/main.py#L215)):*
> ```Python
>         meta = self._build_meta(isd_as, host=SVCType.CS_A, path=path)
>         if path and self.send_meta(req, meta):
>             logging.info("Cert chain request sent to %s: %s", meta, req.short_desc())
> ```

Might as well include the path here too ("sent to X via P").

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Comment by kormat** [comment]
Reviewed 1 of 5 files at r5.
Review status: 9 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Comment by kormat** [comment]
Reviewed 3 of 5 files at r5.
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Comment by shitz** [comment]
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[infrastructure/cert_server/main.py, line 215 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-KkuI51Kp9IZwStKbRCf:-KkueNdzCZDNvyulpHFR:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2ec3d1f83e062adefea64dd92de259d8aa63dc78/infrastructure/cert_server/main.py#L215)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Might as well include the path here too ("sent to X via P").
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r6.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083#-:-KkvAlPaK0TVos-iZKY5:bnfp4nl)*

**Comment by shitz** [comment]
Reviewed 1 of 2 files at r6.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Comment by kormat** [comment]
Reviewed 1 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1083)*

**Pull request merged**
