### PR TITLE
Wrap CtrlPld in a signable outer proto.

### PR DESCRIPTION
**Pull request by kormat**
This PR is the start of a series to overhaul how signing of protos is
handled in SCION.

- The signature is outside the CtrlPld proto, as we otherwise can't
  exclude it from the verification input.
- This approach marshals the CtrlPld to a []byte and signs that
  representation, as we can't depend on language/platform support for
  canonicalisation of capnp protos, especially with unknown fields (for
  forwards/backwards compatibility).

This will allow us to verify ctrl payload messages and senders in
transit. The signature code is in place, but not used/tested.

Note that this approach implies that if later verification of the
CtrlPld is desired, then the original raw representation must be
retained, as it is not possible for a receiver to reconstruct it
identically.

Also:
- Output cerr.Desc in border/gen.go error logs.
- Copy payloads in ScnPkt.Copy()

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1310)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 2 of 11 files at r1.
Review status: 2 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/border/rpkt/payload_ctrl.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxLvyatyuZfGXpL9o2:-KxxLvyatyuZfGXpL9o3:byuzqpd) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/go/border/rpkt/payload_ctrl.go#L31)):*
> ```Go
> 		return HookContinue, nil, nil
> 	}
> 	cpldout, err := ctrl.NewPldOuterFromRaw(rp.Raw[rp.idxs.pld:])
> ```

Hmm I was more thinking that clients of the library could call `ctrl.NewPldFromSignedRaw` and get a `ctrl.Pld` object. `ctrl.NewPldFromRaw` would take as an input a byte string representing `ctrl.PldOuter` and a bool that controls whether the signature should be verified.

---

*[go/lib/ctrl/ctrl.go, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxKA4OlZ_j00LnnA5t:-KxxKA4OlZ_j00LnnA5u:b-sb9nps) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/go/lib/ctrl/ctrl.go#L38)):*
> ```Go
> var _ proto.Cerealizable = (*PldOuter)(nil)
> 
> type PldOuter struct {
> ```

`SignedPld` or `PldSigned`

---

*[go/proto/sign.go, line 49 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxJ80oiJRKCzhXXKfB:-KxxJ80oiJRKCzhXXKfC:bd12ure) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/go/proto/sign.go#L49)):*
> ```Go
> 	case SignType_none:
> 		return nil, nil
> 	case SignType_ed25519:
> ```

`crypto.Sign` (in `asymcrypto.go` will do this for you. Same for verifying. 

---

*[proto/blobsign.capnp, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxDOH7AvVw0hUAz1OR:-KxxDOH7AvVw0hUAz1OS:b-8ysanc) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/proto/blobsign.capnp#L1)):*
> ```
> @0x99440334ec0946a0;
> ```

Change filename to `signedblob.capnp`

---

*[proto/ctrl_pld.capnp, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxDkRo6rk9fT7v4B1S:-KxxDkRo6rk9fT7v4B1T:ba8yviz) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/proto/ctrl_pld.capnp#L15)):*
> ```
> using SIG = import "sig.capnp";
> 
> struct CtrlPldOuter {
> ```

I like any of `SignedCtrlPld`, `CtrlPldSigned`, or `CtrlPldSignedBlob` better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1310)*

**Comment by kormat** [comment]
Review status: 2 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

*[go/border/rpkt/payload_ctrl.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxLvyatyuZfGXpL9o2:-KyH3UT4OhU3eiYDBv_7:b-izmv91) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/go/border/rpkt/payload_ctrl.go#L31)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Hmm I was more thinking that clients of the library could call `ctrl.NewPldFromSignedRaw` and get a `ctrl.Pld` object. `ctrl.NewPldFromRaw` would take as an input a byte string representing `ctrl.PldOuter` and a bool that controls whether the signature should be verified.
</blockquote></details>

As discussed offline, it can't work like this.

---

*[go/lib/ctrl/ctrl.go, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxKA4OlZ_j00LnnA5t:-KyH4iwcSQH8CRlctGI4:b-o19bmu) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/go/lib/ctrl/ctrl.go#L38)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`SignedPld` or `PldSigned`
</blockquote></details>

See response on proto.

---

*[go/lib/ctrl/ctrl.go, line 203 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KyH4xMQ39gX66IgHZ1q:-KyH4xMQ39gX66IgHZ1r:ba5n7zp) ([raw file](https://github.com/netsec-ethz/scion/blob/e0fe5837d3474b526516068f9b2af9b7d7369561/go/lib/ctrl/ctrl.go#L203)):*
> ```Go
> 	PathSegment *seg.PathSegment `capnp:"pcb"`
> 	IfID        *ifid.IFID       `capnp:"ifid"`
> 	CertMgmt    *cert_mgmt.Pld
> ```

Base changes.

---

*[go/lib/ctrl/ctrl.go, line 226 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KyH55v8-i1gXtsgEdpv:-KyH55v8-i1gXtsgEdpw:ba5n7zp) ([raw file](https://github.com/netsec-ethz/scion/blob/e0fe5837d3474b526516068f9b2af9b7d7369561/go/lib/ctrl/ctrl.go#L226)):*
> ```Go
> 	case *cert_mgmt.Pld:
> 		u.Which = proto.CtrlPld_Which_certMgmt
> 		u.CertMgmt = p
> ```

Base changes.

---

*[go/lib/ctrl/ctrl.go, line 244 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KyH56OSoKXyRCbExXPT:-KyH56OSoKXyRCbExXPU:ba5n7zp) ([raw file](https://github.com/netsec-ethz/scion/blob/e0fe5837d3474b526516068f9b2af9b7d7369561/go/lib/ctrl/ctrl.go#L244)):*
> ```Go
> 		return u.Sig, nil
> 	case proto.CtrlPld_Which_certMgmt:
> 		return u.CertMgmt, nil
> ```

Base changes.

---

*[go/proto/sign.go, line 49 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxJ80oiJRKCzhXXKfB:-KyH6JJtrA8JqMkpONSI:b-4b7fbz) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/go/proto/sign.go#L49)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`crypto.Sign` (in `asymcrypto.go` will do this for you. Same for verifying. 
</blockquote></details>

Excellent, thanks :)

---

*[proto/blobsign.capnp, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxDOH7AvVw0hUAz1OR:-KyH6kh_Khi3C3Z1DOv0:bhdi14g) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/proto/blobsign.capnp#L1)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Change filename to `signedblob.capnp`
</blockquote></details>

Went with `sign.capnp`

---

*[proto/ctrl_pld.capnp, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxDkRo6rk9fT7v4B1S:-KyH6o3ueLHVss0qePFO:bxy609j) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/proto/ctrl_pld.capnp#L15)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I like any of `SignedCtrlPld`, `CtrlPldSigned`, or `CtrlPldSignedBlob` better.
</blockquote></details>

I went for a more generic name, because it's possible we may want to add other items at this level. I _can_ rename it if you wish, but at the expense of it becoming inaccurate in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1310)*

**Comment by shitz** [comment]
Review status: 2 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[proto/ctrl_pld.capnp, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxDkRo6rk9fT7v4B1S:-KyH7zwMM2l_UQYcLgNn:bctmfnu) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/proto/ctrl_pld.capnp#L15)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I went for a more generic name, because it's possible we may want to add other items at this level. I _can_ rename it if you wish, but at the expense of it becoming inaccurate in the future.
</blockquote></details>

Even if you want to add unsigned content it would still fit the `SignedCtrlPld` name (because this is ultimately what it is). I image it would then look something like this:
```
struct SignedCtrlPld {
    blob @0 :Data;
    sign @1 :Sign.Sign;
    group unsigned {
        foo @3 :Uint32;
        ...
    }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1310)*

**Comment by kormat** [comment]
Review status: 2 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/lib/ctrl/ctrl.go, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxKA4OlZ_j00LnnA5t:-KyHCxnAG9CCnGzhy1w1:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/go/lib/ctrl/ctrl.go#L38)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

See response on proto.
</blockquote></details>

Done.

---

*[proto/ctrl_pld.capnp, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-KxxDkRo6rk9fT7v4B1S:-KyHCqrUnd7B2LscuLdx:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6ed419a9fb8716ba13303dea31f7c9bd635ab0a8/proto/ctrl_pld.capnp#L15)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Even if you want to add unsigned content it would still fit the `SignedCtrlPld` name (because this is ultimately what it is). I image it would then look something like this:
```
struct SignedCtrlPld {
    blob @0 :Data;
    sign @1 :Sign.Sign;
    group unsigned {
        foo @3 :Uint32;
        ...
    }
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1310)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r3.
Review status: 13 of 14 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1310#-:-KyHERXBY59e4BrIK5vO:bnfp4nl)*

**Comment by shitz** [comment]
Reviewed 1 of 13 files at r3.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1310)*

**Comment by shitz** [comment]
Reviewed 1 of 13 files at r3.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1310)*

**Comment by shitz** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1310)*

**Pull request merged**
