### PR TITLE
Add cffi tarball hash for i686 (fit-PC2)

### PR DESCRIPTION
**Pull request by ercanucan**
Similar to https://github.com/netsec-ethz/scion/commit/13c1d9b0f1ab5b8ef61fc81e3cc130f6e29c5874, this PR adds tarball hash for fit-PC2 devices (i686), for the cffi package.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1109)

### CODE REVIEW

**Comment by ercanucan** [comment]
@kormat @klausman

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[env/pip3/requirements.txt, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1109#-KlO-EhbCSU3Fvmvdt6n:-KlO-EhbCSU3Fvmvdt6o:b-unm4sc) ([raw file](https://github.com/netsec-ethz/scion/blob/c4860ded39ee58f080392ab3e0b0c988922abac0/env/pip3/requirements.txt#L14)):*
> ```
> packaging==16.8 --hash=sha256:99276dc6e3a7851f32027a68f1095cd3f77c148091b092ea867a351811cfe388
> setuptools==35.0.2 --hash=sha256:19d753940f8cdbee7548da318f8b56159aead279ef811a6efc8b8a33d89c86a4
> cffi==1.10.0 --hash=sha256:4fc9c2ff7924b3a1fa326e1799e5dd58cac585d7fb25fe53ccaa1333b0453d65 # x86_64 --hash=sha256:b3b02911eb1f6ada203b0763ba924234629b51586f72a21faacc638269f4ced5 # armv7l --hash=sha256:afa7d8b8d38ad40db8713ee053d41b36d87d6ae5ec5ad36f9210b548a18dc214 # i686
> ```

This is not valid. The first `#` turns the rest of the line into a comment, so only the first hash is seen/used. Put the comments at the end of the line. Also, the comment names are wrong. Suggestion, reorder the hashes, and put this comment: `# tarball, x86_64 wheel, i686 wheel`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1109)*

**Comment by ercanucan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[env/pip3/requirements.txt, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1109#-KlO-EhbCSU3Fvmvdt6n:-KlO3LGIZfISYTO0EcZ9:b-hwnjw5) ([raw file](https://github.com/netsec-ethz/scion/blob/758cbcfb25940041dd625a1399efe8d3d8931d0d/env/pip3/requirements.txt#L14)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is not valid. The first `#` turns the rest of the line into a comment, so only the first hash is seen/used. Put the comments at the end of the line. Also, the comment names are wrong. Suggestion, reorder the hashes, and put this comment: `# tarball, x86_64 wheel, i686 wheel`.
</blockquote></details>

brainfart.. had tried it on fit-PC2 but it had not complained about the syntax as the cffi it was already installed/cached. fixed as you suggested

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1109)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1109#-:-KlOAPYbbw7VJk0dJipa:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1109)*

**Comment by ercanucan** [comment]
thx! merging.

**Pull request merged**
