### PR TITLE
Renamed SCION proto to CtrlPld

### PR DESCRIPTION
**Pull request by shitz**
Also:
Rename `contents` to `union` since there can only be one unnamed union in a capnp struct.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1257)

### CODE REVIEW

**Comment by kormat** [comment]
This fails to build due to go/proto/*capnp.go not getting rebuilt properly. `make clean` in the top-level isn't enough, as it turns out there's a bug in the Makefile. Can you please change 

`if type -P go >/dev/null; then cd go && $(MAKE) clean; fi`

to just

`cd go && $(MAKE) clean` in `Makefile`, thanks.

---

Reviewed 8 of 9 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/lib/ctrl/ctrl.go, line 33 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv6q5GUvDotYn969xly:-Kv6q5GUvDotYn969xlz:bp6b7mu) ([raw file](https://github.com/netsec-ethz/scion/blob/b4117d4564b1dca4f111d6967da473e4db11c2b2/go/lib/ctrl/ctrl.go#L33)):*
> ```Go
> 
> // contents represents the contents of the unnamed capnp union.
> type contents struct {
> ```

I'm not 100% convinced by this name, as it implies the entire, well, contents, are inside this union. `union` would be better.

---

*[go/proto/doc.go, line 23 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv6ppf52PvgDupxVqZb:-Kv6ppf52PvgDupxVqZc:b-hb4dm8) ([raw file](https://github.com/netsec-ethz/scion/blob/b4117d4564b1dca4f111d6967da473e4db11c2b2/go/proto/doc.go#L23)):*
> ```Go
> 	// Parse new ctrl message from bytes.
> 	cpld2, _ := ParseFromRaw(b)
> 	// Access the first union.
> ```

This comment needs to be updated, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-:-Kv6pPu797mZEDzlRWmJ:bxyfa3p)*

**Comment by shitz** [comment]
Done.

---

Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/lib/ctrl/ctrl.go, line 33 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv6q5GUvDotYn969xly:-Kv7MXB20xTjc_quh-VP:b-k9ix1i) ([raw file](https://github.com/netsec-ethz/scion/blob/b4117d4564b1dca4f111d6967da473e4db11c2b2/go/lib/ctrl/ctrl.go#L33)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'm not 100% convinced by this name, as it implies the entire, well, contents, are inside this union. `union` would be better.
</blockquote></details>

Hmm this is consistent with Python where you named it `contents` as well. I'm ok with `union`, but shouldn't we be consistent between the two versions?

---

*[go/proto/doc.go, line 23 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv6ppf52PvgDupxVqZb:-Kv7MoxXhuVRieiwAtYS:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/b4117d4564b1dca4f111d6967da473e4db11c2b2/go/proto/doc.go#L23)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This comment needs to be updated, too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-:-Kv7N4jc8W_q29Wvc7ht:b-896fix)*

**Comment by kormat** [comment]
Reviewed 1 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/ctrl/ctrl.go, line 33 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv6q5GUvDotYn969xly:-Kv7NUuIYJU6oZaKoYuI:b8qdlbk) ([raw file](https://github.com/netsec-ethz/scion/blob/b4117d4564b1dca4f111d6967da473e4db11c2b2/go/lib/ctrl/ctrl.go#L33)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Hmm this is consistent with Python where you named it `contents` as well. I'm ok with `union`, but shouldn't we be consistent between the two versions?
</blockquote></details>

In my mind the `contents` name in python was deliberately more generic as the types are much more.. fluid. But thinking about it, it actually ends up with the same semantics/type hierarchy. So, yeah, `union` in both languages would be great.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1257)*

**Comment by shitz** [comment]
Review status: 5 of 21 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/ctrl/ctrl.go, line 33 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv6q5GUvDotYn969xly:-Kv7SePkVRMMg_fCyiu5:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/b4117d4564b1dca4f111d6967da473e4db11c2b2/go/lib/ctrl/ctrl.go#L33)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

In my mind the `contents` name in python was deliberately more generic as the types are much more.. fluid. But thinking about it, it actually ends up with the same semantics/type hierarchy. So, yeah, `union` in both languages would be great.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1257)*

**Comment by kormat** [comment]
Reviewed 16 of 16 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/border/rpkt/process.go, line 143 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv7UGfPIzFTdoAcaGk6:-Kv7UGfPIzFTdoAcaGk7:b-yg5qj6) ([raw file](https://github.com/netsec-ethz/scion/blob/d3a98370877b1b943c85e246e063aa4231025de1/go/border/rpkt/process.go#L143)):*
> ```Go
> 	}
> 	// Determine the type of SCION control payload.
> 	cts, err := cpld.Union()
> ```

`cts` should probably be renamed, too.

---

*[go/lib/ctrl/ctrl.go, line 44 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv7U0T_-cinGYFXifjd:-Kv7U0T_-cinGYFXifje:brzw4oo) ([raw file](https://github.com/netsec-ethz/scion/blob/d3a98370877b1b943c85e246e063aa4231025de1/go/lib/ctrl/ctrl.go#L44)):*
> ```Go
> }
> 
> func (cts *union) set(c proto.Cerealizable) error {
> ```

The variable naming is a bit confusing now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1257)*

**Comment by shitz** [comment]
Review status: 18 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/border/rpkt/process.go, line 143 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv7UGfPIzFTdoAcaGk6:-Kv7WbO4NY0srg_zKsNP:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d3a98370877b1b943c85e246e063aa4231025de1/go/border/rpkt/process.go#L143)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`cts` should probably be renamed, too.
</blockquote></details>

Done.

---

*[go/lib/ctrl/ctrl.go, line 44 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-Kv7U0T_-cinGYFXifjd:-Kv7VHJ-lFs_btluvQhy:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d3a98370877b1b943c85e246e063aa4231025de1/go/lib/ctrl/ctrl.go#L44)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The variable naming is a bit confusing now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1257)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1257#-:-Kv7cc7AmIkHVdhB237v:bnfp4nl)*

**Pull request merged**
