### PR TITLE
Add randomized option to pktgen

### PR DESCRIPTION
**Pull request by forstern**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1070)

### CODE REVIEW

**Comment by forstern** [comment]
@kormat @ercanucan

**Comment by kormat** [comment]
Looks generally good, i have left some feedback. The only downside is that it's very slow. (If i remove the `time.sleep`, it can do 7285 pps on my machine, compared with 226672 pps for the non-random version).

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tools/pktgen.py, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkB6V5yuSJDoBapenq7:-KkB6V5zrPh0z1xEpMTr:bzcbxus) ([raw file](https://github.com/netsec-ethz/scion/blob/a7ba86f1b49bfc21d3d320952b4eb0a224b4a7fd/tools/pktgen.py#L56)):*
> ```Python
>         self._shutdown()
> 
>     def random_run(self, count, lambd):
> ```

The first half of this is a duplicate of `run()`. You could combine them:

```
def _run_prep():
      self.sent = 0
        spkt = self._build_pkt()
        overlay_dest, overlay_port = str(self.first_hop[0]), self.first_hop[1]
        logging.debug("Sending (via %s:%s):\n%s", overlay_dest, overlay_port, spkt)
        logging.debug(self.path_meta)
```

---

*[tools/pktgen.py, line 87 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkB8EaQOLiH09UWQM69:-KkB8EaQOLiH09UWQM6A:bwjrl1e) ([raw file](https://github.com/netsec-ethz/scion/blob/a7ba86f1b49bfc21d3d320952b4eb0a224b4a7fd/tools/pktgen.py#L87)):*
> ```Python
>         return self._gen_padded_pld(data, pld_len)
> 
>     def _create_payload_random(self, spkt):
> ```

This also contains a fair bit of overlap with `_create_payload`, assuming the size checks are still needed for the random length version.

```
def _create_payload(self, spkt, randlen=False):
        data = b"ping " + self.data
        hdr_len = spkt.cmn_hdr.hdr_len + len(spkt.l4_hdr)
        min_size = hdr_len + len(data)
        if randlen:
            mean = (self.path_meta.p.mtu - min_size)/2
            mu = mean + min_size
            sigma = mean / 3
            self.size = int(rand.gauss(mu, sigma))
        if not self.size or self.size > self.path_meta.p.mtu:
            self.size = self.path_meta.p.mtu
        if self.size < min_size:
            self.size = min_size
        pld_len = self.size - hdr_len
        return self._gen_padded_pld(data, pld_len)
  ```

---

*[tools/pktgen.py, line 139 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkBAAUZHsKpTl904A3l:-KkBAAUZHsKpTl904A3m:bwlhoro) ([raw file](https://github.com/netsec-ethz/scion/blob/a7ba86f1b49bfc21d3d320952b4eb0a224b4a7fd/tools/pktgen.py#L139)):*
> ```Python
>     try:
>         if args.random:
>             print('Flags -w and -s are not used in this mode.')
> ```

This should be a log warning, it should be before the `try` statement, and it should only be printed if either of those flags have been specified.

---

*[tools/pktgen.py, line 148 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkBAQIn-cCqszdxKl0g:-KkBAQIn-cCqszdxKl0h:bs73b9v) ([raw file](https://github.com/netsec-ethz/scion/blob/a7ba86f1b49bfc21d3d320952b4eb0a224b4a7fd/tools/pktgen.py#L148)):*
> ```Python
> 
>     if args.random:
>         logging.info("Sent %d packets in %.3fs (%d pps)", gen.sent, total, gen.sent / total)
> ```

It would be useful to have the total number of bytes sent, and the effective bps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-:-KkBAWb8Esa0mjetz5BF:b-rpubqc)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1070)*

**Comment by forstern** [comment]
I reworked the code a little. Now without waiting time I get ~250000pps compared to ~370000pps (non-random version) on  my machine. This results in around 1.3 Gbps (should be enough for testing purposes?).

If I use a exponentially distributed waiting time the pps drops to ~7500pps. I guess, that time.sleep() does not handle sleep times in order of 10e-7 seconds very efficient. I assume that the overhead of going to sleep and waking up gets to big. 

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/pktgen.py, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkB6V5yuSJDoBapenq7:-KkFVBKMnBwT0-dAwIbA:b-li3l2z) ([raw file](https://github.com/netsec-ethz/scion/blob/27d282196b150577f3a2bcb539ca16f1b35426fb/tools/pktgen.py#L56)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The first half of this is a duplicate of `run()`. You could combine them:

```
def _run_prep():
      self.sent = 0
        spkt = self._build_pkt()
        overlay_dest, overlay_port = str(self.first_hop[0]), self.first_hop[1]
        logging.debug("Sending (via %s:%s):\n%s", overlay_dest, overlay_port, spkt)
        logging.debug(self.path_meta)
```
</blockquote></details>

After addressing the performance issues the do not have that much in common.

---

*[tools/pktgen.py, line 87 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkB8EaQOLiH09UWQM69:-KkGT4cmp2ProiMUkn3r:bb7f2mf) ([raw file](https://github.com/netsec-ethz/scion/blob/27d282196b150577f3a2bcb539ca16f1b35426fb/tools/pktgen.py#L87)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This also contains a fair bit of overlap with `_create_payload`, assuming the size checks are still needed for the random length version.

```
def _create_payload(self, spkt, randlen=False):
        data = b"ping " + self.data
        hdr_len = spkt.cmn_hdr.hdr_len + len(spkt.l4_hdr)
        min_size = hdr_len + len(data)
        if randlen:
            mean = (self.path_meta.p.mtu - min_size)/2
            mu = mean + min_size
            sigma = mean / 3
            self.size = int(rand.gauss(mu, sigma))
        if not self.size or self.size > self.path_meta.p.mtu:
            self.size = self.path_meta.p.mtu
        if self.size < min_size:
            self.size = min_size
        pld_len = self.size - hdr_len
        return self._gen_padded_pld(data, pld_len)
  ```
</blockquote></details>

done

---

*[tools/pktgen.py, line 139 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkBAAUZHsKpTl904A3l:-KkGT39KE8rUlPjtPkt1:bb7f2mf) ([raw file](https://github.com/netsec-ethz/scion/blob/27d282196b150577f3a2bcb539ca16f1b35426fb/tools/pktgen.py#L139)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be a log warning, it should be before the `try` statement, and it should only be printed if either of those flags have been specified.
</blockquote></details>

done

---

*[tools/pktgen.py, line 148 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkBAQIn-cCqszdxKl0g:-KkGT1D2WOw6DSqvHlJc:bb7f2mf) ([raw file](https://github.com/netsec-ethz/scion/blob/27d282196b150577f3a2bcb539ca16f1b35426fb/tools/pktgen.py#L148)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It would be useful to have the total number of bytes sent, and the effective bps.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-:-KkGT6vLTxHQwS_eyZkK:b-qf75v9)*

**Comment by kormat** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/pktgen.py, line 90 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkoFSnZzk3wvm7H15a8:-KkoFSnZzk3wvm7H15a9:bjr9dl2) ([raw file](https://github.com/netsec-ethz/scion/blob/186aa61b92086b17470b9a2b064278c06bcfddd2/tools/pktgen.py#L90)):*
> ```Python
>             self.bytes_sent += len(packet)
> 
>     def _slow_random_loop(self, count, packets, number, overlay_dest, overlay_port, lambd):
> ```

These two are so similar they could just be merged into `random_run`:

```
while not count or self.sent < count:
    packet = ...
    ...
    if lambd:
       time.sleep(rand.expovariate(lambd))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1070)*

**Comment by forstern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/pktgen.py, line 90 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-KkoFSnZzk3wvm7H15a8:-KkpEju-HRPIuGFwOX5-:bwtf02k) ([raw file](https://github.com/netsec-ethz/scion/blob/186aa61b92086b17470b9a2b064278c06bcfddd2/tools/pktgen.py#L90)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These two are so similar they could just be merged into `random_run`:

```
while not count or self.sent < count:
    packet = ...
    ...
    if lambd:
       time.sleep(rand.expovariate(lambd))
```
</blockquote></details>

Yeah first i thought it would impact the performance for the "fast" run. but after doing some tests, I saw that this is not the case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1070)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1070#-:-Kkpi9-QAiVwKumSmu3q:bnfp4nl)*

**Pull request merged**
