### PR TITLE
Modifications to dispatcher to support bind addresses.

### PR DESCRIPTION
**Pull request by jonghoonkwon**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1123)

### CODE REVIEW

**Comment by jonghoonkwon** [comment]
@kormat @shitz @ercanucan

**Comment by klausman** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[c/dispatcher/dispatcher.c, line 587 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmRV5sTXxTPHpzMSLiu:-KmRV5sTXxTPHpzMSLiv:b-yahzxp) ([raw file](https://github.com/netsec-ethz/scion/blob/e70fc60c143837765be3e3eb9b4318dbbc698cb2/c/dispatcher/dispatcher.c#L587)):*
> ```C
>             /* command (1B) | proto (1B) | isd_as (4B) | port (2B) | addr type (1B) | addr (?B) |
>                bind_port (2B) | bind_addr type (1B) | bind_addr (?B) | SVC (2B, optional) */
>             L4AddrPair *ap = (L4AddrPair *)malloc(sizeof(L4AddrPair));
> ```

check for `NULL` return value and afterwards `memset(ap, 0, sizeof(L4AddrPair))`

---

*[c/dispatcher/dispatcher.c, line 634 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmRVgmOrqK1njFt5oy8:-KmRVgmOrqK1njFt5oy9:b-jn1h8m) ([raw file](https://github.com/netsec-ethz/scion/blob/e70fc60c143837765be3e3eb9b4318dbbc698cb2/c/dispatcher/dispatcher.c#L634)):*
> ```C
> 
>         if (IS_BIND_SOCKET(*buf)) {
>             SVCAddrPair *sp = (SVCAddrPair *)malloc(sizeof(SVCAddrPair));
> ```

Same deal as above for `ap`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by jonghoonkwon** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[c/dispatcher/dispatcher.c, line 587 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmRV5sTXxTPHpzMSLiu:-KmWlwzKfxme8FDYkmbv:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e70fc60c143837765be3e3eb9b4318dbbc698cb2/c/dispatcher/dispatcher.c#L587)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

check for `NULL` return value and afterwards `memset(ap, 0, sizeof(L4AddrPair))`
</blockquote></details>

Done.

---

*[c/dispatcher/dispatcher.c, line 634 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmRVgmOrqK1njFt5oy8:-KmWlxHHev93N9bdmX2a:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e70fc60c143837765be3e3eb9b4318dbbc698cb2/c/dispatcher/dispatcher.c#L634)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Same deal as above for `ap`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by klausman** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[c/dispatcher/dispatcher.c, line 587 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmRV5sTXxTPHpzMSLiu:-KmWn-rktS5FkvngJOK9:b-tfupwu) ([raw file](https://github.com/netsec-ethz/scion/blob/e70fc60c143837765be3e3eb9b4318dbbc698cb2/c/dispatcher/dispatcher.c#L587)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The `memset()` is still missing

---

*[c/dispatcher/dispatcher.c, line 634 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmRVgmOrqK1njFt5oy8:-KmWn4EiDajdaH8L8kzy:b13w35q) ([raw file](https://github.com/netsec-ethz/scion/blob/e70fc60c143837765be3e3eb9b4318dbbc698cb2/c/dispatcher/dispatcher.c#L634)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same for `memset()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by jonghoonkwon** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[c/dispatcher/dispatcher.c, line 587 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmRV5sTXxTPHpzMSLiu:-KmWpBsUep62U8XhKk2Z:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e70fc60c143837765be3e3eb9b4318dbbc698cb2/c/dispatcher/dispatcher.c#L587)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

The `memset()` is still missing
</blockquote></details>

Done.

---

*[c/dispatcher/dispatcher.c, line 634 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmRVgmOrqK1njFt5oy8:-KmWpCJyAI8ngeqGiSqz:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e70fc60c143837765be3e3eb9b4318dbbc698cb2/c/dispatcher/dispatcher.c#L634)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Same for `memset()`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-:-KmWpmq9zAP42RspRB84:bnfp4nl)*

**Comment by ercanucan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[c/dispatcher/dispatcher.c, line 598 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmWpQYoV3Qk4-sLgYB5:-KmWpQYpKLfa-C8EJy2B:bltk7yz) ([raw file](https://github.com/netsec-ethz/scion/blob/fc28c1bd4a51fb64cb1d959fe2710bb9889fa471/c/dispatcher/dispatcher.c#L598)):*
> ```C
> 
>             uint16_t b_port = ntohs(*(uint16_t *)(buf + end));
>             uint8_t b_type = *(uint8_t *)(buf + end + 2);
> ```

minor: would it make sense to declare the offset values as more meaningful/informative constants?

---

*[python/scion_elem/scion_elem.py, line 196 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmWq3k8GuLJhjTu697j:-KmWq3k8GuLJhjTu697k:b-4wk5s9) ([raw file](https://github.com/netsec-ethz/scion/blob/fc28c1bd4a51fb64cb1d959fe2710bb9889fa471/python/scion_elem/scion_elem.py#L196)):*
> ```Python
>         # Setup UDP socket
>         if self.bind:
>             host_addr, b_port = self.bind[0]
> ```

Maybe a comment here would be useful saying that for the moment we are considering only the first element of bind addresses list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by ercanucan** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by jonghoonkwon** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[c/dispatcher/dispatcher.c, line 598 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmWpQYoV3Qk4-sLgYB5:-KmWuXaU79X8DyBrjIDF:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fc28c1bd4a51fb64cb1d959fe2710bb9889fa471/c/dispatcher/dispatcher.c#L598)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

minor: would it make sense to declare the offset values as more meaningful/informative constants?
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 196 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmWq3k8GuLJhjTu697j:-KmWuY3-rrTXJ_oUUfyH:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fc28c1bd4a51fb64cb1d959fe2710bb9889fa471/python/scion_elem/scion_elem.py#L196)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Maybe a comment here would be useful saying that for the moment we are considering only the first element of bind addresses list.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by shitz** [comment]
Could you add a description of how your change works exactly and why you implemented it like this? For example, it is not immediately clear to me why you wouldn't just add the bind address to the `Entry` struct.

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[c/dispatcher/dispatcher.c, line 612 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmX9Jkdfo4lW2UxCPF1:-KmX9Jkdfo4lW2UxCPF2:b-qefri7) ([raw file](https://github.com/netsec-ethz/scion/blob/56d7c5eb686c1d65e99efbd669b98ddcd24629c6/c/dispatcher/dispatcher.c#L612)):*
> ```C
>             HASH_ADD(hh, l4_addr_list, bind_key, sizeof(L4Key), ap);
>             unsigned int cnt;
>             cnt = HASH_COUNT(l4_addr_list);
> ```

It seems that `cnt` is not used after this.

---

*[c/dispatcher/dispatcher.c, line 657 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmX9hTOP4Baagl8Ml7V:-KmX9hTOP4Baagl8Ml7W:brhumzt) ([raw file](https://github.com/netsec-ethz/scion/blob/56d7c5eb686c1d65e99efbd669b98ddcd24629c6/c/dispatcher/dispatcher.c#L657)):*
> ```C
>             HASH_ADD(hh, svc_addr_list, bind_key, sizeof(SVCKey), sp);
>             unsigned int cnt;
>             cnt = HASH_COUNT(svc_addr_list);
> ```

Same here.

---

*[python/lib/dispatcher.py, line 68 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmXAuJJ79lba5ei74Tr:-KmXAuJJ79lba5ei74Ts:b-ott86k) ([raw file](https://github.com/netsec-ethz/scion/blob/56d7c5eb686c1d65e99efbd669b98ddcd24629c6/python/lib/dispatcher.py#L68)):*
> ```Python
> 
> 
> def _pack_dispatcher_msg(addr, port, b_addr, b_port, svc, scmp):
> ```

Name these `bind_addr` and `bind_port`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-:-KmXE5tTc2qeuxILBTq1:bgw2fla)*

**Comment by jonghoonkwon** [comment]
The initial idea of changes on dispatcher is to create a hash table that stores public and bind address pairs. The main role of the hash table is to translate bind addresses to corresponding public addresses, so that the hash table performs as a kind of NAT in dispatcher. I thought that making the hash table separated from the Entry struct would be helpful for further implementation such as supporting a new packet forwarding mechanism that mights need another struct. If you feel it doesn't make sense, please give me a comment with a brief direction. Thank you for your comment :)

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[c/dispatcher/dispatcher.c, line 612 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmX9Jkdfo4lW2UxCPF1:-Kmkp561j8SSCLG7zRVS:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/56d7c5eb686c1d65e99efbd669b98ddcd24629c6/c/dispatcher/dispatcher.c#L612)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

It seems that `cnt` is not used after this.
</blockquote></details>

Done.

---

*[c/dispatcher/dispatcher.c, line 657 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmX9hTOP4Baagl8Ml7V:-Kmkp5Ttjq0L-Qonl6kO:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/56d7c5eb686c1d65e99efbd669b98ddcd24629c6/c/dispatcher/dispatcher.c#L657)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-:-Kmkp6_pNKC4xN6d3IB9:b-cc7y4c)*

**Comment by jonghoonkwon** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[python/lib/dispatcher.py, line 68 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmXAuJJ79lba5ei74Tr:-Kmkr34YDlnIcPAr_UuP:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/56d7c5eb686c1d65e99efbd669b98ddcd24629c6/python/lib/dispatcher.py#L68)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Name these `bind_addr` and `bind_port`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by pszalach** [comment]
So, if I understand it correctly: an app knows its private and public addresses and binds both, and the dispatcher does NAT between them. But then, why doesn't the app just use the public address?

---

Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-:-Kml5vo5eaYrT26cvL88:byyz1gf)*

**Comment by shitz** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[c/dispatcher/dispatcher.c, line 877 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-Kml5vibXzt1Bgk3sh8Z:-Kml5vibXzt1Bgk3sh8_:bwgu3z2) ([raw file](https://github.com/netsec-ethz/scion/blob/748c18323a9f5b9481e02ac097ab3fdcd63fd173/c/dispatcher/dispatcher.c#L877)):*
> ```C
> 
>     L4AddrPair *ap;
>     HASH_FIND(hh, l4_addr_list, &key, sizeof(L4Key), ap);
> ```

Switch the order of the hash table lookups, ie. first try the lookup in `udp_port_list` using the public `key` if that fails look up the entry in the other hash table. For this to work `L4AddrPair` needs to have a pointer to the original `Entry` instead of just another key. The advantage of this approach is that in most cases you only need one hash table lookup, since most deployments won't have a bind address that is different from the public address. Obviously, this should also be done for the SVC list.

---

*[c/dispatcher/dispatcher.c, line 1094 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-Kml7Jk1XaB5BCIL2dum:-Kml7Jk1XaB5BCIL2dun:bqxiful) ([raw file](https://github.com/netsec-ethz/scion/blob/748c18323a9f5b9481e02ac097ab3fdcd63fd173/c/dispatcher/dispatcher.c#L1094)):*
> ```C
> }
> 
> void cleanup_socket(int sock, int index, int err)
> ```

Here you need to delete the entries in `l4_addr_list` and `svc_addr_list` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by jonghoonkwon** [comment]
Sorry for late response. I think you got a response from Steven about your questions. :) 

---

Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[c/dispatcher/dispatcher.c, line 877 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-Kml5vibXzt1Bgk3sh8Z:-KmmVm4JbDIN4i5uyMum:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/748c18323a9f5b9481e02ac097ab3fdcd63fd173/c/dispatcher/dispatcher.c#L877)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Switch the order of the hash table lookups, ie. first try the lookup in `udp_port_list` using the public `key` if that fails look up the entry in the other hash table. For this to work `L4AddrPair` needs to have a pointer to the original `Entry` instead of just another key. The advantage of this approach is that in most cases you only need one hash table lookup, since most deployments won't have a bind address that is different from the public address. Obviously, this should also be done for the SVC list.
</blockquote></details>

Done.

---

*[c/dispatcher/dispatcher.c, line 1094 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-Kml7Jk1XaB5BCIL2dum:-KmmVmQZuUMW7-3Y-qIp:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/748c18323a9f5b9481e02ac097ab3fdcd63fd173/c/dispatcher/dispatcher.c#L1094)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Here you need to delete the entries in `l4_addr_list` and `svc_addr_list` 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-:-KmmVqMgFwAXMKMmBqhn:b7ppb7p)*

**Comment by kormat** [comment]
Reviewed 1 of 4 files at r1, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[c/dispatcher/dispatcher.c, line 102 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmzcEV2jkczxJfjwhGe:-KmzcEV2jkczxJfjwhGf:bt0gi0x) ([raw file](https://github.com/netsec-ethz/scion/blob/99bd120444d70a924e7bc006f11901a0832c68bd/c/dispatcher/dispatcher.c#L102)):*
> ```C
> Entry *bind_ssp_flow_list = NULL;
> Entry *bind_ssp_wildcard_list = NULL;
> Entry *bind_udp_port_ist = NULL;
> ```

Missing `l` from `list`.

---

*[c/dispatcher/dispatcher.c, line 545 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-Kmzcto1-Uf9dN_7UNe6:-Kmzcto1-Uf9dN_7UNe7:b-bodqsm) ([raw file](https://github.com/netsec-ethz/scion/blob/99bd120444d70a924e7bc006f11901a0832c68bd/c/dispatcher/dispatcher.c#L545)):*
> ```C
> 
>     /* Register bind address info if the app has a bind address */
>     if (IS_BIND_SOCKET(*buf)) {
> ```

It looks like this is missing a `find_available_port()` call for the bind port.

---

*[c/dispatcher/dispatcher.c, line 617 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmzeIWjEHqD3mRmKM5R:-KmzeIWjEHqD3mRmKM5S:b-rvles3) ([raw file](https://github.com/netsec-ethz/scion/blob/99bd120444d70a924e7bc006f11901a0832c68bd/c/dispatcher/dispatcher.c#L617)):*
> ```C
>                bind_port (2B) | bind_addr type (1B) | bind_addr (?B) | SVC (2B, optional) */
>             int b_port_len = port_len;
>             int b_type_len = type_len;
> ```

Both of these variables look redundant.

---

*[c/dispatcher/dispatcher.c, line 619 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-Kmzei01HMUSLwgLc4os:-Kmzei01HMUSLwgLc4ot:bje8vf0) ([raw file](https://github.com/netsec-ethz/scion/blob/99bd120444d70a924e7bc006f11901a0832c68bd/c/dispatcher/dispatcher.c#L619)):*
> ```C
>             int b_type_len = type_len;
> 
>             uint16_t b_port = ntohs(*(uint16_t *)(buf + end));
> ```

This could assign to `e->bind_key.port` directly.

---

*[c/dispatcher/dispatcher.c, line 621 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-Kmzf-mJVO459TJ3IS5w:-Kmzf-mJVO459TJ3IS5x:bcu046u) ([raw file](https://github.com/netsec-ethz/scion/blob/99bd120444d70a924e7bc006f11901a0832c68bd/c/dispatcher/dispatcher.c#L621)):*
> ```C
>             uint16_t b_port = ntohs(*(uint16_t *)(buf + end));
>             uint8_t b_type = *(uint8_t *)(buf + end + b_port_len);
>             b_addr_len = get_addr_len(b_type);
> ```

I think these 2 lines can just become: `b_addr_len = buf[end + port_len]`

---

*[python/lib/dispatcher.py, line 37 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmzgsH7b_tXgXFk1LRE:-KmzgsH7b_tXgXFk1LRF:b9ehlo5) ([raw file](https://github.com/netsec-ethz/scion/blob/99bd120444d70a924e7bc006f11901a0832c68bd/python/lib/dispatcher.py#L37)):*
> ```Python
> 
> 
> def reg_dispatcher(sock, addr, port, bind_addr, bind_port, init=True, svc=None, scmp=True):
> ```

Bind address and port should be optional arguments. I would represent it as a tuple, `bind=()`.

---

*[python/lib/dispatcher.py, line 77 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/1123#-KmzhMgTUEkTbzdHKDhM:-KmzhMgTUEkTbzdHKDhN:b9ye4z7) ([raw file](https://github.com/netsec-ethz/scion/blob/99bd120444d70a924e7bc006f11901a0832c68bd/python/lib/dispatcher.py#L77)):*
> ```Python
>             struct.pack("!BBIHB", cmd, L4Proto.UDP, addr.isd_as.int(), port,
>                         addr.host.TYPE),
>             addr.host.pack(),
> ```

These first two terms are identical between these two cases. How about:
```
data = []
if bind_addr:
  cmd |= 1 <<2
data.append(struct.pack("!BBIHB", cmd, L4Proto.UDP, addr.isd_as.int(), port, addr.host.TYPE)
data.append(addr.host.pack())
if bind_addr:
  data.append(struct.pack("!HB", bind_port, bind_addr.host.TYPE))
  data.append(bind_addr.host.pack())
if svc is not None:
   ...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1123)*

**Comment by shitz** [comment]
Superseded by #1134.

**Pull request closed without merging**
