### PR TITLE
Add comments to Go code.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/935)

### CODE REVIEW

**Comment by kormat** [comment]
@klausman

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-:-KX5Ilv9ITTiGwTh_SJu:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 16 of 17 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[go/border/io-hsr.go, line 34 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXFXIOGq8iOqgycK_tY:-KXFXIOGq8iOqgycK_tZ:b-227bfn) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/io-hsr.go#L34)):*
> ```Go
> )
> 
> // readHSRInput reads batches of packets from libhsr, and dispatch them for
> ```

dispatches*

---

*[go/border/io.go, line 69 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXFXgcvVIbOEx-vYQkk:-KXFXgcwi5BYikoM8rtF:b-ddjhef) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/io.go#L69)):*
> ```Go
> type posixOutputFunc func(common.RawBytes, *net.UDPAddr) (int, error)
> 
> // writePosixOutput writes packets to a POSIX(/BSD) socket using the provided function.
> ```

Is the supplied function something from the libc API? Or something generated ad-hoc for that packet object?

If the former, maybe add information along the lines "... which is typically frobniz(1)"

---

*[go/border/main.go, line 15 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXFY37tXzj2n4cx2fUp:-KXFY37tXzj2n4cx2fUq:bmt9qzb) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/main.go#L15)):*
> ```Go
> // limitations under the License.
> 
> // This file takes care of parsing flags, setting up logging and signal
> ```

s/flags/command line &/

---

*[go/border/router.go, line 129 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXF_33zzkNgW5hoLPzK:-KXF_33zzkNgW5hoLPzL:bg25ww3) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/router.go#L129)):*
> ```Go
> 		return
> 	}
> 	// Process the packet, if a previous step has regsitered a relevant hook
> ```

registered*

---

*[go/border/router.go, line 135 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXF_6wOJNILIvCuWLuX:-KXF_6wOJNILIvCuWLuY:b-45cjep) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/router.go#L135)):*
> ```Go
> 		return
> 	}
> 	// If the packet is to this router, there's no need to forward it.
> ```

Reformulate: "If this packet's destination is this router, ..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[go/border/io-hsr.go, line 34 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXFXIOGq8iOqgycK_tY:-KXFdCDjWrx1LJaeIc12:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/io-hsr.go#L34)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> dispatches*
</details>
Done.

---

*[go/border/io.go, line 69 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXFXgcvVIbOEx-vYQkk:-KXFdX7bWAHXiaJlYJdQ:by2fehw) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/io.go#L69)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> Is the supplied function something from the libc API? Or something generated ad-hoc for that packet object?
> 
> If the former, maybe add information along the lines "... which is typically frobniz(1)"
</details>
It's actually generated for the socket, at startup, though that doesn't really matter to `writePosixOutput`. I've added a bit more detail.

---

*[go/border/main.go, line 15 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXFY37tXzj2n4cx2fUp:-KXFdngjgxOVoJsLXgHc:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/main.go#L15)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> s/flags/command line &/
</details>
Done.

---

*[go/border/router.go, line 129 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXF_33zzkNgW5hoLPzK:-KXFduUorg77scakKJPf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/router.go#L129)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> registered*
</details>
Done.

---

*[go/border/router.go, line 135 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXF_6wOJNILIvCuWLuX:-KXFe4kWhRKCkKEFcpF7:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/51ae9b0ca4f2a99e34e3b2cc13987668503cc8ef/go/border/router.go#L135)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> Reformulate: "If this packet's destination is this router, ..."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/border/hsr/hsr.go, line 88 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXGwXX_CJaOf59DCGgu:-KXGwXX_CJaOf59DCGgv:bsav1p1) ([raw file](https://github.com/netsec-ethz/scion/blob/8583016199fab668db39cdb7009fa7ab59d2471f/go/border/hsr/hsr.go#L88)):*
> ```Go
> 		argv = append(argv, C.CString(arg))
> 	}
> 	// Initialise libhsr. Its logging is controlled by the zlog config and
> ```

Initialize*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-:-KXGxIvVdrqd18jQ6tvu:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 13 of 13 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[go/border/rpkt/addr.go, line 43 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXPLZL9U24szqVUpnqH:-KXPLZL9U24szqVUpnqI:bsa7amq) ([raw file](https://github.com/netsec-ethz/scion/blob/2b1420433ec3b22100243d811c5ca6e22e74812e/go/border/rpkt/addr.go#L43)):*
> ```Go
> }
> 
> // SrcIA retrieves the destination ISD-AS if it isn't already known.
> ```

DstIA*

---

*[go/border/rpkt/addr.go, line 84 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXPLd3KfE6Z-jAW1WPa:-KXPLd3KfE6Z-jAW1WPb:b-oh328u) ([raw file](https://github.com/netsec-ethz/scion/blob/2b1420433ec3b22100243d811c5ca6e22e74812e/go/border/rpkt/addr.go#L84)):*
> ```Go
> }
> 
> // SrcHost retrieves the destination host address if it isn't already known.
> ```

DstHost*

---

*[go/border/rpkt/l4.go, line 50 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXPMbeGVM56B0RvPfaa:-KXPMbeGVM56B0RvPfab:b-q8clcc) ([raw file](https://github.com/netsec-ethz/scion/blob/2b1420433ec3b22100243d811c5ca6e22e74812e/go/border/rpkt/l4.go#L50)):*
> ```Go
> 				return nil, err
> 			}
> 			// Update metadata.
> ```

This comment and the one above are identical. Maybe also add the actual protocol names?

---

*[go/border/rpkt/rpkt.go, line 248 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXPNQ0fEWxsF_13POjm:-KXPNQ0gyIFHLf84nm4e:b-rlqc8u) ([raw file](https://github.com/netsec-ethz/scion/blob/2b1420433ec3b22100243d811c5ca6e22e74812e/go/border/rpkt/rpkt.go#L248)):*
> ```Go
> // ToScnPkt converts this RtrPkt into an spkt.ScnPkt. The verify argument
> // defines whether verification errors should cause this conversion to fail or
> // not. Setting this to false is useful when trying to convert a packet that it
> ```

s/it/is/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[go/border/rpkt/addr.go, line 43 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXPLZL9U24szqVUpnqH:-KXPjxz6TAXFSBFBt_t6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2b1420433ec3b22100243d811c5ca6e22e74812e/go/border/rpkt/addr.go#L43)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> DstIA*
</details>
Done.

---

*[go/border/rpkt/addr.go, line 84 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXPLd3KfE6Z-jAW1WPa:-KXPjyHaZcu_B19pX5QV:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2b1420433ec3b22100243d811c5ca6e22e74812e/go/border/rpkt/addr.go#L84)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> DstHost*
</details>
Done.

---

*[go/border/rpkt/l4.go, line 50 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXPMbeGVM56B0RvPfaa:-KXPjzCSUuJoCgZg-bf_:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2b1420433ec3b22100243d811c5ca6e22e74812e/go/border/rpkt/l4.go#L50)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> This comment and the one above are identical. Maybe also add the actual protocol names?
</details>
Done.

---

*[go/border/rpkt/rpkt.go, line 248 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXPNQ0fEWxsF_13POjm:-KXPjt8ZBn6fSCRDoSzs:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2b1420433ec3b22100243d811c5ca6e22e74812e/go/border/rpkt/rpkt.go#L248)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> s/it/is/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935)*

**Comment by klausman** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935)*

**Comment by klausman** [comment]
Reviewed 16 of 16 files at r7, 10 of 10 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[go/border/rpkt/l4.go, line 116 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfOuap8LhQdsUKYDNX:-KXfOuaq4d56S7ct8VDW:bsgvl5a) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/l4.go#L116)):*
> ```Go
> 
> // verifyL4Chksum calculates the appropriate checksum for the layer 4 header,
> // and verifys that it matches the one supplied in the l4 header.
> ```

verifies*

---

*[go/border/rpkt/parse.go, line 154 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfPtV6zrbPLd_dg8Qp:-KXfPtV6zrbPLd_dg8Qq:brzu67n) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/parse.go#L154)):*
> ```Go
> }
> 
> // setDirTo figures out which Dir a packet is going to.
> ```

"... and sets the [fieldname] field accordingly"?

---

*[go/border/rpkt/path.go, line 172 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfQzWANQBwSRYfCl8X:-KXfQzWANQBwSRYfCl8Y:bc3ldan) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/path.go#L172)):*
> ```Go
> 			}
> 		}
> 		// Check the common header path metadata validity, and if so extract
> ```

"if so" only works if the first clause is "Check whether the common header path metadata is valid,"

---

*[go/border/rpkt/path.go, line 392 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfRsalRF8iqWpVzaEB:-KXfRsalRF8iqWpVzaEC:b-bqe098) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/path.go#L392)):*
> ```Go
> 
> // IFNext retrieves the next interface ID if not already known. As this may be
> // an interface is an external ISD-AS, this is not sanity-checked.
> ```

s/is an/in an/

---

*[go/border/rpkt/route.go, line 177 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfSgrdzlrqgaGYg86G:-KXfSgrdzlrqgaGYg86H:b-di12ut) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/route.go#L177)):*
> ```Go
> 
> // forwardFromLocal handles packet received from the local ISD-AS, to be
> // forwareded to neighbouring ISD-ASes.
> ```

forwarded*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935)*

**Comment by kormat** [comment]
Review status: 37 of 42 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[go/border/rpkt/l4.go, line 116 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfOuap8LhQdsUKYDNX:-KXfU-Wd-rLqcpcVfER_:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/l4.go#L116)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

verifies*
</blockquote></details>

Done.

---

*[go/border/rpkt/parse.go, line 154 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfPtV6zrbPLd_dg8Qp:-KXfU6szhptWZSt7RUG7:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/parse.go#L154)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

"... and sets the [fieldname] field accordingly"?
</blockquote></details>

Done.

---

*[go/border/rpkt/path.go, line 172 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfQzWANQBwSRYfCl8X:-KXfUD-Z2pgj6AwnIRlj:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/path.go#L172)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

"if so" only works if the first clause is "Check whether the common header path metadata is valid,"
</blockquote></details>

Done.

---

*[go/border/rpkt/path.go, line 392 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfRsalRF8iqWpVzaEB:-KXfUHkYSjuOvx_TH2FV:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/path.go#L392)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

s/is an/in an/
</blockquote></details>

Done.

---

*[go/border/rpkt/route.go, line 177 at r7](https://reviewable.io:443/reviews/netsec-ethz/scion/935#-KXfSgrdzlrqgaGYg86G:-KXfUM9lv1V8q78ICjvd:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/56030e4cbb68fb9634fb3028ffcf006d01ce9c93/go/border/rpkt/route.go#L177)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

forwarded*
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935)*

**Comment by klausman** [comment]
Reviewed 5 of 5 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/935)*

**Pull request merged**
