### PR TITLE
New repo layout

### PR DESCRIPTION
**Pull request by shitz**
Changed repo layout according to #1007.

The code is now grouped into language specific top-level directories, i.e., `c/`, `go/`, and `python/`. Removed the following top-level directories: `endhost/`, `infrastructure/`, `lib/`, and `test`. The contents of these directories have been moved to the appropriate language directories.

All the changes to the content of files were needed to make everything work again. This PR also depends on https://github.com/netsec-ethz/scion-lwip-contrib/pull/12 and https://github.com/netsec-ethz/scion-lwip/pull/14. Furthermore, a new `scion_base` docker image is needed.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1118)

### CODE REVIEW

**Comment by shitz** [comment]
[Change layout of github repository](https://trello.com/c/jAC7cpXA/10-change-layout-of-github-repository)

**Comment by kormat** [comment]
Reviewed 168 of 682 files at r1.
Review status: 89 of 409 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[c/lib/hsr/README.md, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxYJd7wDc1cYmv1iAK:-KlxYJd7wDc1cYmv1iAL:b6x1yxt) ([raw file](https://github.com/netsec-ethz/scion/blob/c593396ba5c33ef8ba2b386b9d49e06cdcb18d25/c/lib/hsr/README.md#L73)):*
> ```Markdown
> make libhsr
> ```
> This builds the library at lib/hsr/build/lib
> ```

This should probably have `c/` at the start of the path. Same below.

---

*[docker/Dockerfile, line 17 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxaX5f5RYsFXaC20Oe:-KlxaX5f5RYsFXaC20Of:bdb9yea) ([raw file](https://github.com/netsec-ethz/scion/blob/c593396ba5c33ef8ba2b386b9d49e06cdcb18d25/docker/Dockerfile#L17)):*
> ```Dockerfile
> 
> # Setup scion-web
> ENV PYTHONPATH=python/:.
> ```

This shouldn't be required - it looks like `scion-web` just needs to be updated to the new path too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118)*

**Comment by kormat** [comment]
Some failures:
```
$ make clean
...
make[1]: Entering directory '/home/kormat/go/src/github.com/netsec-ethz/scion/c'
make[1]: *** No rule to make target 'clean'.  Stop.
```

```
$ make
...
GOBIN=/home/kormat/go/src/github.com/netsec-ethz/scion/bin govendor install --tags "assert" -v +local,program
github.com/netsec-ethz/scion/go/lib/libscion
# github.com/netsec-ethz/scion/go/lib/libscion
lib/libscion/checksum.go:21:29: fatal error: libscion/scion.h: No such file or directory
compilation terminated.
```

---

Review status: 89 of 409 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-:-Klxc7Pypbn8bn1SbaCV:b-pw3xsn)*

**Comment by kormat** [comment]
Reviewed 28 of 682 files at r1, 2 of 44 files at r2.
Review status: 114 of 409 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118)*

**Comment by kormat** [comment]
Reviewed 82 of 682 files at r1.
Review status: 158 of 409 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118)*

**Comment by kormat** [comment]
Reviewed 245 of 682 files at r1, 20 of 44 files at r2.
Review status: 300 of 409 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[python/mininet/README.md, line 16 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxgFjO3Y5y1ucmxJ6K:-KlxgFjO3Y5y1ucmxJ6L:be9rbbc) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/mininet/README.md#L16)):*
> ```Markdown
> Now run the network:
> ```
> user@ubuntu:~/scion$ topology/mininet/run.sh
> ```

This needs updating.

---

*[python/mininet/run.sh, line 21 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxgSj0bGeYqUP5OcoT:-KlxgSj1rRMms0qhIKWZ:be9rbbc) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/mininet/run.sh#L21)):*
> ```Shell
> fi
> 
> PYTHONPATH=topology/mininet pox \
> ```

This needs updating.

---

*[python/scion_proxy/scion_proxy.py, line 83 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxgsrTNjNtUg5cgSoF:-KlxgsrTNjNtUg5cgSoG:b-1r0fzr) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/scion_proxy/scion_proxy.py#L83)):*
> ```Python
> as follows:
> 
> scion_proxy/scion_proxy.py -f
> ```

Add `python/` to the start.

---

*[python/test/README.md, line 5 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-Klxh6xEBn9VKdhK7rke:-Klxh6xFnyVpJXHXD9ys:b-leapp6) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/test/README.md#L5)):*
> ```Markdown
> 
> ## Usage
> All commands must be run within `tests/` directory.
> ```

Hum. This section needs updating.

`./scion.sh test py`
`./scion.sh test py test/lib/packet/opaque_field_test.py`
`./scion.sh test py test/lib/packet/opaque_field_test.py:TestHopOpaqueFieldCalcMac` or
`./scion.sh test py test.lib.packet.opaque_field_test:TestHopOpaqueFieldCalcMac` or
`./scion.sh test py test/lib/packet/opaque_field_test.py:TestHopOpaqueFieldCalcMac.test_prev`
`./scion.sh test py -v`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118)*

**Comment by kormat** [comment]
Reviewed 152 of 682 files at r1, 22 of 44 files at r2.
Review status: 406 of 409 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[python/topology/generator.py, line 91 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-Klxihszu83nvCwxv8Yq:-Klxihszu83nvCwxv8Yr:b5nnscz) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/topology/generator.py#L91)):*
> ```Python
> )
> 
> DEFAULT_TOPOLOGY_FILE = "python/topology/Default.topo"
> ```

I'm wondering if the data/conf files should be left in `topology/`, as they aren't language-specific. (E.g. a Go generator would also use them).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118)*

**Comment by kormat** [comment]
General comments:
- I dislike the python path containing both `python/` and `.`, only the former should be needed.
- Any human-readable paths (e.g. specified in documentation or docstrings) should be rooted at the top-level directory, for consistency.

---

Review status: 406 of 409 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-:-KlxmO-Vuk6vEhcBbdLE:bha4naz)*

**Comment by shitz** [comment]
Fixed the compilation failures. Unfortunately, `.` is still need in the PYTHONPATH due to the protos. Checked all the READMEs for strings not relative to the top-level dir.

---

Review status: 406 of 409 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[c/lib/hsr/README.md, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxYJd7wDc1cYmv1iAK:-KlxoyVvkA5E-irOgHgS:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/c593396ba5c33ef8ba2b386b9d49e06cdcb18d25/c/lib/hsr/README.md#L73)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should probably have `c/` at the start of the path. Same below.
</blockquote></details>

Done.

---

*[docker/Dockerfile, line 17 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxaX5f5RYsFXaC20Oe:-KlyALkcn3Vi8wGhKDXE:b-7bvikm) ([raw file](https://github.com/netsec-ethz/scion/blob/c593396ba5c33ef8ba2b386b9d49e06cdcb18d25/docker/Dockerfile#L17)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This shouldn't be required - it looks like `scion-web` just needs to be updated to the new path too.
</blockquote></details>

What do you mean by that? The scion-web code contains imports of the form `from lib.X.Y import Z` and I don't think we want to change them to `from python.lib.X.Y import Z`, or do we?

---

*[python/mininet/README.md, line 16 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxgFjO3Y5y1ucmxJ6K:-KlxpCPFT7UY52ZaB5FN:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/mininet/README.md#L16)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This needs updating.
</blockquote></details>

Done.

---

*[python/mininet/run.sh, line 21 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxgSj0bGeYqUP5OcoT:-KlxpzSOXuq-Plt_pmiT:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/mininet/run.sh#L21)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This needs updating.
</blockquote></details>

Done.

---

*[python/scion_proxy/scion_proxy.py, line 83 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxgsrTNjNtUg5cgSoF:-Klxq8-6USHaOp53cBZg:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/scion_proxy/scion_proxy.py#L83)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Add `python/` to the start.
</blockquote></details>

Done.

---

*[python/test/README.md, line 5 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-Klxh6xEBn9VKdhK7rke:-Klxwy33aL9WnzPZBD9O:b-2mtphr) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/test/README.md#L5)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Hum. This section needs updating.

`./scion.sh test py`
`./scion.sh test py test/lib/packet/opaque_field_test.py`
`./scion.sh test py test/lib/packet/opaque_field_test.py:TestHopOpaqueFieldCalcMac` or
`./scion.sh test py test.lib.packet.opaque_field_test:TestHopOpaqueFieldCalcMac` or
`./scion.sh test py test/lib/packet/opaque_field_test.py:TestHopOpaqueFieldCalcMac.test_prev`
`./scion.sh test py -v`
</blockquote></details>

Removed this README and added a toplevel `TESTING.md` file.

---

*[python/topology/generator.py, line 91 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-Klxihszu83nvCwxv8Yq:-Klxx2dGkRlGFdwuFlya:bd93mbc) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/topology/generator.py#L91)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'm wondering if the data/conf files should be left in `topology/`, as they aren't language-specific. (E.g. a Go generator would also use them).
</blockquote></details>

Yep, I agree. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-:-KlxxckeugTEOCbUCooY:b7qw0v5)*

**Comment by kormat** [comment]
Reviewed 19 of 697 files at r1, 2 of 44 files at r2, 45 of 62 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docker/Dockerfile, line 17 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxaX5f5RYsFXaC20Oe:-Km5s8E7ZxjaMKSYnHZC:b1qh5es) ([raw file](https://github.com/netsec-ethz/scion/blob/c593396ba5c33ef8ba2b386b9d49e06cdcb18d25/docker/Dockerfile#L17)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

What do you mean by that? The scion-web code contains imports of the form `from lib.X.Y import Z` and I don't think we want to change them to `from python.lib.X.Y import Z`, or do we?
</blockquote></details>

`scion-web` does some special hacks to automatically include the scion root dir in its `sys.path`. E.g. https://github.com/netsec-ethz/scion-web/blob/master/web_scion/settings/base.py#L33 
Those should be updated to include the `python/` subdir, and remove the need to set a custom `PYTHONPATH` for scion-web.

---

*[python/mininet/run.sh, line 21 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxgSj0bGeYqUP5OcoT:-Km5tku0irh6nTMhXnm8:br6rrsr) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/mininet/run.sh#L21)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118)*

**Comment by shitz** [comment]
Review status: 397 of 406 files reviewed at latest revision, 2 unresolved discussions.

---

*[python/mininet/run.sh, line 21 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxgSj0bGeYqUP5OcoT:-Km6TsHQqqhoc05aa_0X:bb7113i) ([raw file](https://github.com/netsec-ethz/scion/blob/6510aecd7ca98087f26851106a456fbbf1c13dfd/python/mininet/run.sh#L21)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Nope :P
</blockquote></details>

Now?

---

*[docker/Dockerfile, line 17 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-KlxaX5f5RYsFXaC20Oe:-Km6PUhCbhRkBTGM4iTz:by1nco1) ([raw file](https://github.com/netsec-ethz/scion/blob/c593396ba5c33ef8ba2b386b9d49e06cdcb18d25/docker/Dockerfile#L17)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`scion-web` does some special hacks to automatically include the scion root dir in its `sys.path`. E.g. https://github.com/netsec-ethz/scion-web/blob/master/web_scion/settings/base.py#L33 
Those should be updated to include the `python/` subdir, and remove the need to set a custom `PYTHONPATH` for scion-web.
</blockquote></details>

Done. See https://github.com/netsec-ethz/scion-web/pull/88

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 4 of 697 files at r1, 1 of 44 files at r2, 14 of 14 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118#-:-Km6WGt6xZeu3w8WoAmJ:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1118)*

**Comment by pszalach** [comment]
@shitz I just realized that you forgot to update the README ;-)

**Pull request merged**
