### PR TITLE
Path server now expires path requests.

### PR DESCRIPTION
**Pull request by shitz**
Also: SCIOND retries cert/trc requests

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1194)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[python/path_server/base.py, line 101 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1194#-KqXu0yOKIfROkueqIS1:-KqXu0yOKIfROkueqIS2:b4tcvhu) ([raw file](https://github.com/netsec-ethz/scion/blob/496f3ac46cdd136b3f07768055b58e043ab023a4/python/path_server/base.py#L101)):*
> ```Python
>         self.down_segments = PathSegmentDB(max_res_no=self.MAX_SEG_NO, labels=down_labels)
>         self.core_segments = PathSegmentDB(max_res_no=self.MAX_SEG_NO, labels=core_labels)
>         self.pending_req = defaultdict(lambda: ExpiringDict(100, 2))  # Dict of pending requests.
> ```

`100` is probably too small, and should be a class constant. `2` should definitely be a named constant. It looks like `SCIONDaemon.PATH_REQ_TOUT` is the source, so that should probably move to `defines.py`.

---

*[python/path_server/base.py, line 336 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1194#-KqXv2uRPHCmwaG_D2Vk:-KqXv2uRPHCmwaG_D2Vl:bnu4pg9) ([raw file](https://github.com/netsec-ethz/scion/blob/496f3ac46cdd136b3f07768055b58e043ab023a4/python/path_server/base.py#L336)):*
> ```Python
>                 # Clean state.
>                 for req_id in to_remove:
>                     self.pending_req[key].pop(req_id)
> ```

With `ExpiringDict`, it's safe to remove items while traversing `items()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1194)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[python/path_server/base.py, line 101 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1194#-KqXu0yOKIfROkueqIS1:-KqXxBtHLofBBDikZGhG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/496f3ac46cdd136b3f07768055b58e043ab023a4/python/path_server/base.py#L101)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`100` is probably too small, and should be a class constant. `2` should definitely be a named constant. It looks like `SCIONDaemon.PATH_REQ_TOUT` is the source, so that should probably move to `defines.py`.
</blockquote></details>

Done.

---

*[python/path_server/base.py, line 336 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1194#-KqXv2uRPHCmwaG_D2Vk:-KqXxSI0mNSTv5oymbLc:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/496f3ac46cdd136b3f07768055b58e043ab023a4/python/path_server/base.py#L336)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

With `ExpiringDict`, it's safe to remove items while traversing `items()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1194)*

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/path_server/base.py, line 334 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1194#-KqYTTmw0oAMXm8eA5v1:-KqYTTmw0oAMXm8eA5v2:bhf5tzl) ([raw file](https://github.com/netsec-ethz/scion/blob/c5ab1e4f812c2542ea10b975a07789fb2ea17bc3/python/path_server/base.py#L334)):*
> ```Python
>                             req, meta, new_request=False, logger=logger, req_id=req_id):
>                         meta.close()
>                         self.pending_req[key].pop(req_id)
> ```

This should be `del self.pending_req[key][req_id]`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1194)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/path_server/base.py, line 334 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1194#-KqYTTmw0oAMXm8eA5v1:-KqYU-DbLY_wv_f8FfYE:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/c5ab1e4f812c2542ea10b975a07789fb2ea17bc3/python/path_server/base.py#L334)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be `del self.pending_req[key][req_id]`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1194)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1194#-:-KqYWJl7b6tS9Gq0ELuS:bnfp4nl)*

**Pull request merged**
