### PR TITLE
Added full SCION packet parsing to main go libs

### PR DESCRIPTION
**Pull request by scrye**
First step for end to end Go tests.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1213)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/common/pld.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KrWLoc2m0AGv4vUQlpw:-KrWLoc2m0AGv4vUQlpx:b-3t6v51) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/common/pld.go#L26)):*
> ```Go
> 	Copy() (Payload, *Error)
> 	// If there is insufficient space in b to fit the Payload, return an
> 	// error
> ```

This is only one scenario. E.g. if there is something invalid in the payload's metadata, that should also return an error. I'm not sure that it makes sense to try and list all possible errors in the interface.

---

*[go/lib/common/raw.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KrWM6VZiylWjratXGK_:-KrWM6VZiylWjratXGKa:bbmzbme) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/common/raw.go#L26)):*
> ```Go
> 	return fmt.Sprintf("%x", []byte(r))
> }
> ```

As the intention is to implement the `Payload` interface, it's a good idea to make that implicit (and checked at compile time). This is done by having:
```
var _ Payload = (*RawBytes)(nil)
```
above the type declaration.

---

*[go/lib/common/raw.go, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KrWMt_evQMBnCu-dWSn:-KrWMt_evQMBnCu-dWSo:b-xma4ef) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/common/raw.go#L32)):*
> ```Go
> 
> func (r RawBytes) Copy() (Payload, *Error) {
> 	return RawBytes(append([]byte{}, r...)), nil
> ```

This can just be `append(RawBytes{}, r...))`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1213)*

**Comment by kormat** [comment]
Reviewed 1 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1213)*

**Comment by scrye** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/lib/common/pld.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KrWLoc2m0AGv4vUQlpw:-KrWU2adgpQltzwIVCn_:b-gy535v) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/common/pld.go#L26)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is only one scenario. E.g. if there is something invalid in the payload's metadata, that should also return an error. I'm not sure that it makes sense to try and list all possible errors in the interface.
</blockquote></details>

Yes, but it's something that's very different from Go's classical `Read`/`Write` calls which generally silently stop at the end of the slice. I'll rephrase the comment to not make it sound like it's the only error scenario.

Also, including the direction of data in the comment would really help, as it's in reverse from common Go convention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1213)*

**Comment by kormat** [comment]
Reviewed 2 of 6 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[go/lib/spkt/spkt.go, line 40 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_HJMFERNduOgxI6r4:-Kr_HJMFERNduOgxI6r5:b-21k63a) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L40)):*
> ```Go
> 
> func ScnPktFromRaw(b common.RawBytes) (*ScnPkt, error) {
> 	s := &ScnPkt{}
> ```

This presumably should call `NewScnPkt`, as fields aren't initialised.

---

*[go/lib/spkt/spkt.go, line 67 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_HVQOUXu4DimPeR-P:-Kr_HVQOUXu4DimPeR-Q:b-j2xr2h) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L67)):*
> ```Go
> 	offset += CmnHdrLen
> 
> 	// Parse address header
> ```

This is very very simplified. The code doesn't handle extensions at all, and extensions can override address parsing (as well as many other things). This is why extensions must be parsed directly after common header parsing, and before parsing anything else. See `go/border/rpkt/hooks.go:hooks` for a list of things that extensions can override.

---

*[go/lib/spkt/spkt.go, line 85 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_HszA3NByuJ_b8q-c:-Kr_HszA3NByuJ_b8q-d:b25df5q) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L85)):*
> ```Go
> 	// Validate address padding bytes
> 	addrHdrLen := 2*addr.IABytes + s.DstHost.Size() + s.SrcHost.Size()
> 	padBytes := util.CalcPadding(addrHdrLen, common.LineLen)
> ```

You could just use `offset` instead of `addrHdrLen`.

---

*[go/lib/spkt/spkt.go, line 94 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_I1Z6tWf9wb3LFsNj:-Kr_I1Z6tWf9wb3LFsNk:bq7vm6j) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L94)):*
> ```Go
> 
> 	// Parse path header
> 	pathLen := s.CmnHdr.HdrLenBytes() - CmnHdrLen - addrHdrLen
> ```

`pathLen :=  s.CmnHdr.HdrLenBytes() - offset`?

---

*[go/lib/spkt/spkt.go, line 117 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_IY8bxrWaclLXBS3X:-Kr_IY8bxrWaclLXBS3Y:b82n1hk) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L117)):*
> ```Go
> 		return common.NewError("Incomplete packet, bad payload length",
> 			"expected", pldLen, "actual", len(b)-offset)
> 	}
> ```

The checksum needs to be validated as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1213)*

**Comment by scrye** [comment]
Regarding our discussion from yesterday:
  - currently the new package only does very basic parsing; in the future, as we clarify how end-hosts interact with extensions (via `setsockopt`-like calls on `SCIONConn`, for example) , it will be modified to handle them
  - the package will be mostly used by `SCIONConn`

---

Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[go/lib/common/pld.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KrWLoc2m0AGv4vUQlpw:-Kr_UFLnH3dYkf1Pngxm:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/common/pld.go#L26)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Yes, but it's something that's very different from Go's classical `Read`/`Write` calls which generally silently stop at the end of the slice. I'll rephrase the comment to not make it sound like it's the only error scenario.

Also, including the direction of data in the comment would really help, as it's in reverse from common Go convention.
</blockquote></details>

Done.

---

*[go/lib/common/raw.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KrWM6VZiylWjratXGK_:-Kr_UNGMDP22RYei6hSe:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/common/raw.go#L26)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As the intention is to implement the `Payload` interface, it's a good idea to make that implicit (and checked at compile time). This is done by having:
```
var _ Payload = (*RawBytes)(nil)
```
above the type declaration.
</blockquote></details>

Done.

---

*[go/lib/common/raw.go, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KrWMt_evQMBnCu-dWSn:-Kr_UXPqdewUqiwS4Jqv:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/common/raw.go#L32)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can just be `append(RawBytes{}, r...))`. 
</blockquote></details>

Done.

---

*[go/lib/spkt/spkt.go, line 40 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_HJMFERNduOgxI6r4:-Kr_Uvah5lw-nOneyOB3:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L40)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This presumably should call `NewScnPkt`, as fields aren't initialised.
</blockquote></details>

Done.

---

*[go/lib/spkt/spkt.go, line 67 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_HVQOUXu4DimPeR-P:-KreEfW0DjPLb7fIpg0A:b156fm4) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L67)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is very very simplified. The code doesn't handle extensions at all, and extensions can override address parsing (as well as many other things). This is why extensions must be parsed directly after common header parsing, and before parsing anything else. See `go/border/rpkt/hooks.go:hooks` for a list of things that extensions can override.
</blockquote></details>

The code now fails with an error whenever an unknown next proto is found. As we define end-host behavior for various extensions we can include them.

---

*[go/lib/spkt/spkt.go, line 85 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_HszA3NByuJ_b8q-c:-Kr_V7UooHqedxq6whZK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L85)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

You could just use `offset` instead of `addrHdrLen`.
</blockquote></details>

Done.

---

*[go/lib/spkt/spkt.go, line 94 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_I1Z6tWf9wb3LFsNj:-Kr_VB2ZDw4TZoOpHhkr:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L94)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`pathLen :=  s.CmnHdr.HdrLenBytes() - offset`?
</blockquote></details>

Done.

---

*[go/lib/spkt/spkt.go, line 117 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kr_IY8bxrWaclLXBS3X:-Kr_ilzaSpS138RrFp-Z:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d69a7e3f4a0bb21396e16bfb270dc5cda8556fcc/go/lib/spkt/spkt.go#L117)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The checksum needs to be validated as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-:-KreCaV4llbKdWZggGZM:bttjl7g)*

**Comment by kormat** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/hpkt/hpkt.go, line 1 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KreaHzemOafpVryQy7h:-KreaHzemOafpVryQy7i:bm3jz2w) ([raw file](https://github.com/netsec-ethz/scion/blob/7dccfc25672b28f63af4a679a68745d4c145da61/go/lib/hpkt/hpkt.go#L1)):*
> ```Go
> package hpkt
> ```

Missing the copyright notice, and also a description of what this package is. The name alone doesn't mean anything to me.

---

*[go/lib/hpkt/hpkt.go, line 14 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kreb_-75iaYyTsKpPMV:-Kreb_-8r0In5XFHMutd:b-6kq9y9) ([raw file](https://github.com/netsec-ethz/scion/blob/7dccfc25672b28f63af4a679a68745d4c145da61/go/lib/hpkt/hpkt.go#L14)):*
> ```Go
> )
> 
> func NewScnPkt() *spkt.ScnPkt {
> ```

It feels a bit odd to have a constructor for a type in a different module. Maybe this can stay in `spkt.go`.

---

*[go/lib/hpkt/hpkt.go, line 98 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KreciM6wqdllLvOjlS2:-KreciM6wqdllLvOjlS3:bbhdfu) ([raw file](https://github.com/netsec-ethz/scion/blob/7dccfc25672b28f63af4a679a68745d4c145da61/go/lib/hpkt/hpkt.go#L98)):*
> ```Go
> 
> 	// Verify checksum
> 	actual := util.Checksum(b[addrHdrStart:addrHdrEnd],
> ```

This can be replaced by a call to `go/lib/l4:CheckCSum()`, i believe.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1213)*

**Comment by scrye** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/hpkt/hpkt.go, line 1 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KreaHzemOafpVryQy7h:-KregrD6iFRTFiClfEKd:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/7dccfc25672b28f63af4a679a68745d4c145da61/go/lib/hpkt/hpkt.go#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Missing the copyright notice, and also a description of what this package is. The name alone doesn't mean anything to me.
</blockquote></details>

Done.

---

*[go/lib/hpkt/hpkt.go, line 14 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-Kreb_-75iaYyTsKpPMV:-KreeCFeEcpnYzwTKoSX:bti9tyo) ([raw file](https://github.com/netsec-ethz/scion/blob/7dccfc25672b28f63af4a679a68745d4c145da61/go/lib/hpkt/hpkt.go#L14)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It feels a bit odd to have a constructor for a type in a different module. Maybe this can stay in `spkt.go`.
</blockquote></details>

It's not a true constructor though, it's more like an external allocator that knows exactly what it's doing (the contents are also atypical of a standard constructor, since the structure is only partially initialized). Maybe change the name to differentiate it from Go conventions?

I think putting it in `spkt.go` would be confusing, because it's tightly tied to how `hpkt` uses it. It will probably be moved to `SCIONConn` in the future, since that's the code that is actually allocating.

---

*[go/lib/hpkt/hpkt.go, line 98 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KreciM6wqdllLvOjlS2:-KregHyJhWFeep7s64CB:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/7dccfc25672b28f63af4a679a68745d4c145da61/go/lib/hpkt/hpkt.go#L98)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be replaced by a call to `go/lib/l4:CheckCSum()`, i believe.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1213)*

**Comment by kormat** [comment]
Reviewed 1 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/hpkt/hpkt.go, line 113 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-KremDK_Zd1FlsfcrvPC:-KremDK_Zd1FlsfcrvPD:b-9y7zcs) ([raw file](https://github.com/netsec-ethz/scion/blob/e2f5720609bd83ce498a2932746beb7859ea60d2/go/lib/hpkt/hpkt.go#L113)):*
> ```Go
> 		b[offset:offset+pldLen])
> 	if err != nil {
> 		return common.NewError("Bad checksum", "err", err)
> ```

As `CheckCSum` already returns a useful `*common.Error`, you can just return that directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1213)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1213#-:-KrenT99_1R3h6J_-Giz:bnfp4nl)*

**Pull request merged**
