### PR TITLE
Add vagrant configs for SCION-IP Gateway test environment.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/969)

### CODE REVIEW

**Comment by kormat** [comment]
@klausman

**Comment by klausman** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[vagrant/sig/a1/Vagrantfile, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/969#-Kd0Z6TtYlav9PHr5-NK:-Kd0Z6TtYlav9PHr5-NL:b-i0s3k2) ([raw file](https://github.com/netsec-ethz/scion/blob/ffa9291c830b98b4e688d65dcc5cdde8e7e8d319/vagrant/sig/a1/Vagrantfile#L2)):*
> ```Ruby
> # -*- mode: ruby -*-
> # vi: set ft=ruby :
> ```

drop trailing ` :`

---

*[vagrant/sig/a2/Vagrantfile, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/969#-Kd0ZC4FjKL6k-OpmBmN:-Kd0ZC4FjKL6k-OpmBmO:b35y0sm) ([raw file](https://github.com/netsec-ethz/scion/blob/ffa9291c830b98b4e688d65dcc5cdde8e7e8d319/vagrant/sig/a2/Vagrantfile#L2)):*
> ```Ruby
> # -*- mode: ruby -*-
> # vi: set ft=ruby :
> ```

same: drop ` :`

---

*[vagrant/sig/b1/Vagrantfile, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/969#-Kd0ZEKAey-lgwZuKqxG:-Kd0ZEKAey-lgwZuKqxH:bio604c) ([raw file](https://github.com/netsec-ethz/scion/blob/ffa9291c830b98b4e688d65dcc5cdde8e7e8d319/vagrant/sig/b1/Vagrantfile#L2)):*
> ```Ruby
> # -*- mode: ruby -*-
> # vi: set ft=ruby :
> ```

And again.

---

*[vagrant/sig/b2/Vagrantfile, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/969#-Kd0ZLiVBJCtkJVxJwTm:-Kd0ZLiVBJCtkJVxJwTn:b-vtcvv) ([raw file](https://github.com/netsec-ethz/scion/blob/ffa9291c830b98b4e688d65dcc5cdde8e7e8d319/vagrant/sig/b2/Vagrantfile#L2)):*
> ```Ruby
> # -*- mode: ruby -*-
> # vi: set ft=ruby :
> ```

same, same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/969#-:-Kd0ZP__XMyFFwKu7n0o:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/969)*

**Comment by kormat** [comment]
Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[vagrant/sig/a1/Vagrantfile, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/969#-Kd0Z6TtYlav9PHr5-NK:-Kd0dp__Hqx_u6euehCS:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ffa9291c830b98b4e688d65dcc5cdde8e7e8d319/vagrant/sig/a1/Vagrantfile#L2)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

drop trailing ` :`
</blockquote></details>

Done.

---

*[vagrant/sig/a2/Vagrantfile, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/969#-Kd0ZC4FjKL6k-OpmBmN:-Kd0dpuxWwo-tPUAG7Is:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ffa9291c830b98b4e688d65dcc5cdde8e7e8d319/vagrant/sig/a2/Vagrantfile#L2)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

same: drop ` :`
</blockquote></details>

Done.

---

*[vagrant/sig/b1/Vagrantfile, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/969#-Kd0ZEKAey-lgwZuKqxG:-Kd0dqLfQwZUbivJZc2Y:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ffa9291c830b98b4e688d65dcc5cdde8e7e8d319/vagrant/sig/b1/Vagrantfile#L2)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

And again.
</blockquote></details>

Done.

---

*[vagrant/sig/b2/Vagrantfile, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/969#-Kd0ZLiVBJCtkJVxJwTm:-Kd0dngdNCK121s6LPR2:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ffa9291c830b98b4e688d65dcc5cdde8e7e8d319/vagrant/sig/b2/Vagrantfile#L2)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

same, same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/969)*

**Pull request merged**
