### PR TITLE
Add extension support to CtrlPld

### PR DESCRIPTION
**Pull request by scrye**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1331)

### CODE REVIEW

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1331#-:-KzA_FI2an2hcG_O-LxB:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[proto/ctrl_pld.capnp, line 34 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1331#-KzT5Ufh7lSEVDOfuFcc:-KzT5UfiRzG9lczReM5M:b-1b4jwo) ([raw file](https://github.com/netsec-ethz/scion/blob/11db58c01f4ffe7d3592df663339314d754e6031/proto/ctrl_pld.capnp#L34)):*
> ```
> }
> 
> struct ExtnData {
> ```

This name is too generic. E.g. in the go code, this would be `proto.ExtnData`, which is ~meaningless. `CtrlExtnData` would be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1331)*

**Comment by scrye** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[proto/ctrl_pld.capnp, line 34 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1331#-KzT5Ufh7lSEVDOfuFcc:-KzUQtThfseampc7FXf4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/11db58c01f4ffe7d3592df663339314d754e6031/proto/ctrl_pld.capnp#L34)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This name is too generic. E.g. in the go code, this would be `proto.ExtnData`, which is ~meaningless. `CtrlExtnData` would be better.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1331)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[proto/ctrl_extn.capnp, line 11 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1331#-KzURv4bzXAGMphqsejZ:-KzURv4bzXAGMphqsej_:bij7ac9) ([raw file](https://github.com/netsec-ethz/scion/blob/fe36b0a3e75d015247e700abb2babd46823f6180/proto/ctrl_extn.capnp#L11)):*
> ```
> 
> struct CtrlExtnData {
>     type @0 :UInt64;
> ```

This should be `:Data;`. We want a _sparse_ namespace. The intention here is to specifically avoid any sort of central coordination. My proposal was that we would use things like byte[]{`com.company.extnname`} as the `type`, hence `:Data;`.

---

*[proto/ctrl_pld.capnp, line 31 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1331#-KzURnu0o_br89yREvFy:-KzURnu0o_br89yREvFz:bn4tgrn) ([raw file](https://github.com/netsec-ethz/scion/blob/fe36b0a3e75d015247e700abb2babd46823f6180/proto/ctrl_pld.capnp#L31)):*
> ```
>         drkeyMgmt @6 :DRKeyMgmt.DRKeyMgmt;
>         sig @7 :SIG.SIGCtrl;
>         extn @8 :CtrlExtn.CtrlExtnDataList;
> ```

Why not `:List(CtrlExtn.CtrlExtnData);`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1331)*

**Comment by scrye** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[proto/ctrl_extn.capnp, line 11 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1331#-KzURv4bzXAGMphqsejZ:-KzUXIhjowIqxC0wP9MK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fe36b0a3e75d015247e700abb2babd46823f6180/proto/ctrl_extn.capnp#L11)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be `:Data;`. We want a _sparse_ namespace. The intention here is to specifically avoid any sort of central coordination. My proposal was that we would use things like byte[]{`com.company.extnname`} as the `type`, hence `:Data;`.
</blockquote></details>

Done.

---

*[proto/ctrl_pld.capnp, line 31 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1331#-KzURnu0o_br89yREvFy:-KzUWtNHJL8it-qYipH0:b8yaaoq) ([raw file](https://github.com/netsec-ethz/scion/blob/fe36b0a3e75d015247e700abb2babd46823f6180/proto/ctrl_pld.capnp#L31)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Why not `:List(CtrlExtn.CtrlExtnData);`?
</blockquote></details>

Union members in the Go code have to implement `interface Cerealizable`, so they need to be their own type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1331)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[proto/ctrl_pld.capnp, line 31 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1331#-KzURnu0o_br89yREvFy:-KzYWfkdJK2twGEy5E3_:bh72gy5) ([raw file](https://github.com/netsec-ethz/scion/blob/fe36b0a3e75d015247e700abb2babd46823f6180/proto/ctrl_pld.capnp#L31)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Union members in the Go code have to implement `interface Cerealizable`, so they need to be their own type.
</blockquote></details>

Damn, that is unfortunate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1331#-:-KzYXHZw59DxpCH5jb2N:bnfp4nl)*

**Pull request merged**
