### PR TITLE
go 1.8 WIP

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1120)

### CODE REVIEW

**Comment by klausman** [comment]
:lgtm: with one nit.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[env/go/deps, line 58 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1120#-Km6TQo_CKy-1SPYhzRW:-Km6TQo_CKy-1SPYhzRX:b7g1e0x) ([raw file](https://github.com/netsec-ethz/scion/blob/48f35ca212ad1bb27803d5fda8e2d850c5456ca4/env/go/deps#L58)):*
> ```
>     echo "Downloading $src to $file"
>     curl -# "$src" -o "$file"
>     sha256sum -c "$tmpdir/SHA256SUM"
> ```

You can actually use `echo $sum $filename |sh256sum -c -` and avoid the tmpfile. I suspect `basename $src` should work to make `$filename`.

Or leave it as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1120#-:-Km6TpsLiRdEmxwCEjUp:b2dc52y)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1120#-:-Km6x8pas5Pxw0z12kfg:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1120)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[env/go/deps, line 58 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1120#-Km6TQo_CKy-1SPYhzRW:-Km6wbWkUVx9pqLtV4Kp:b4xbpm) ([raw file](https://github.com/netsec-ethz/scion/blob/48f35ca212ad1bb27803d5fda8e2d850c5456ca4/env/go/deps#L58)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

You can actually use `echo $sum $filename |sh256sum -c -` and avoid the tmpfile. I suspect `basename $src` should work to make `$filename`.

Or leave it as-is.
</blockquote></details>

That works, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1120)*

**Pull request merged**
