### PR TITLE
Sync CurrINF, CurrHF, HdrLen, ExtHdrLen with Book

### PR DESCRIPTION
**Pull request by Oncilla**
Refactor Lengths/offsets: (addresses issue #981)
CurrINF, CurrHF, HdrLen, ExtHdrLen are all computed as value * 8.
set CurrINF,CurrHF = 0 if no path.
fix TotalLength computation for spkt

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1136)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 18 of 24 files at r1.
Review status: 18 of 24 files reviewed at latest revision, 7 unresolved discussions.

---

*[c/lib/scion/udp.c, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4ylg2tsfxOstPMbrs:-Kn4ylg3QvfhljPVSMOH:bsikwcr) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/c/lib/scion/udp.c#L32)):*
> ```C
>  * return value: Payload class
>  */
> uint8_t get_payload_class(uint8_t *buf)
> ```

These two functions aren't used any more - we no longer have payload class/type fields.

---

*[go/border/rpkt/create.go, line 67 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4m1UL0gTm8odAU03K:-Kn4m1UMB-GJjUn0W_AM:bnkconv) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/border/rpkt/create.go#L67)):*
> ```Go
> 	if sp.Path != nil {
> 		copy(rp.Raw[rp.idxs.path:], sp.Path.Raw)
> 		rp.CmnHdr.CurrInfoF = uint8((rp.idxs.path + int(sp.Path.InfOff)) / common.LineLen)
> ```

Ah. I've just realised that `spath.Path.IntOff` and `HopOff` should be `int`'s, not `uint8`, as they are raw byte offsets, and otherwise cannot handle a path longer than 255B.  Can you fix that as well, please?

---

*[go/border/rpkt/extn_onehoppath.go, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4naWJ4osXIIFyZVHH:-Kn4naWKdqQthBNBRgA0:b-c4i2z0) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/border/rpkt/extn_onehoppath.go#L59)):*
> ```Go
> 		return HookContinue, nil, nil
> 	}
> 	currHopF, err := spath.HopFFromRaw(o.rp.Raw[int(o.rp.CmnHdr.CurrHopF)*common.LineLen:])
> ```

Given how common this is, it's probably worth adding some methods to CmnHdr to calculate offsets. Maybe `HdrLenBytes`, `InfoFOffBytes`, `HopFOffBytes`?

Also, calculating the current hopF offset 4 times in one method seems a bit excessive ;)

---

*[go/lib/spkt/spkt.go, line 93 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4kpBFDuihGd6oN8wE:-Kn4kpBFDuihGd6oN8wF:bwe2ygm) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/lib/spkt/spkt.go#L93)):*
> ```Go
> 		l += len(s.Path.Raw)
> 	}
> 	return l / common.LineLen
> ```

This should still be the length of the header in bytes. `AddrLen()` is in bytes, as is `TotalLen()`.

---

*[python/lib/packet/scion.py, line 112 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4tfH9g7rHRg9aadnE:-Kn4tfH9g7rHRg9aadnF:b-3c8o6i) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/lib/packet/scion.py#L112)):*
> ```Python
>                 "hdr_len (%sB) < common header len (%sB) + addrs len (%sB) " %
>                 (self.hdr_len_bytes(), self.LEN, self.addrs_len))
>         if iof_off == hof_off:
> ```

As an extra check:
`if iof_off == hof_off == 0:`

---

*[python/lib/packet/scion.py, line 197 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4vw-5lyjNUDGV8v-S:-Kn4vw-5lyjNUDGV8v-T:bi075t0) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/lib/packet/scion.py#L197)):*
> ```Python
>         for i in ("version", "total_len", "_iof_idx", "_hof_idx", "next_hdr"):
>             values[i] = getattr(self, i)
>         values["hdr_len"] = self.hdr_len_bytes()
> ```

Move this into the declaration of `values`.

---

*[python/test/lib/packet/scion_test.py, line 70 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4xVWFbf19_xknSzW9:-Kn4xVWFbf19_xknSzWA:b4vxtce) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/test/lib/packet/scion_test.py#L70)):*
> ```Python
>         data = create_mock(["pop"])
>         data.pop.return_value = bytes([first_b, 0b00111111]) + \
>             bytes.fromhex('0304 04 07 08 07')
> ```

Change the next_hdr field to be distinct from the new infoF offset, it makes the tests easier to follow. Same for the pack() tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1136)*

**Comment by kormat** [comment]
Reviewed 4 of 24 files at r1.
Review status: 22 of 24 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1136)*

**Comment by Oncilla** [comment]
Review status: 14 of 27 files reviewed at latest revision, 7 unresolved discussions.

---

*[c/lib/scion/udp.c, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4ylg2tsfxOstPMbrs:-Kn50NmVNCcs4DrtmpVH:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/c/lib/scion/udp.c#L32)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These two functions aren't used any more - we no longer have payload class/type fields.
</blockquote></details>

Done.

---

*[go/border/rpkt/create.go, line 67 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4m1UL0gTm8odAU03K:-Kn50lt82MkkJuDucFfl:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/border/rpkt/create.go#L67)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Ah. I've just realised that `spath.Path.IntOff` and `HopOff` should be `int`'s, not `uint8`, as they are raw byte offsets, and otherwise cannot handle a path longer than 255B.  Can you fix that as well, please?
</blockquote></details>

Done.

---

*[go/border/rpkt/extn_onehoppath.go, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4naWJ4osXIIFyZVHH:-Kn51c8fhecuDJxwZZsk:b-dvj46d) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/border/rpkt/extn_onehoppath.go#L59)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Given how common this is, it's probably worth adding some methods to CmnHdr to calculate offsets. Maybe `HdrLenBytes`, `InfoFOffBytes`, `HopFOffBytes`?

Also, calculating the current hopF offset 4 times in one method seems a bit excessive ;)
</blockquote></details>

I was counting on the compiler ;)
Done.

---

*[go/lib/spkt/spkt.go, line 93 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4kpBFDuihGd6oN8wE:-Kn56jXmCkhvBYDjboj9:b-l2be0a) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/lib/spkt/spkt.go#L93)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should still be the length of the header in bytes. `AddrLen()` is in bytes, as is `TotalLen()`.
</blockquote></details>

Okay. It might be confusing, since the field is also called hdrLen.
Done.

---

*[python/lib/packet/scion.py, line 112 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4tfH9g7rHRg9aadnE:-Kn57gTK-nA9iKqWgXYv:b45i8t8) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/lib/packet/scion.py#L112)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As an extra check:
`if iof_off == hof_off == 0:`
</blockquote></details>

Should a parse error be thrown if ioff == hoff != 0?

---

*[python/lib/packet/scion.py, line 197 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4vw-5lyjNUDGV8v-S:-Kn580Q3kWaERm0sbWct:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/lib/packet/scion.py#L197)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Move this into the declaration of `values`.
</blockquote></details>

Done.

---

*[python/test/lib/packet/scion_test.py, line 70 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4xVWFbf19_xknSzW9:-Kn5CET5zWutyRJZ2oUp:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/test/lib/packet/scion_test.py#L70)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Change the next_hdr field to be distinct from the new infoF offset, it makes the tests easier to follow. Same for the pack() tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1136)*

**Comment by kormat** [comment]
Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[go/border/rpkt/extn_onehoppath.go, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4naWJ4osXIIFyZVHH:-KnYkdKMvMSiAjbwsNqN:b-dd2bc) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/border/rpkt/extn_onehoppath.go#L59)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

I was counting on the compiler ;)
Done.
</blockquote></details>

You're still calling it twice :)

---

*[go/border/rpkt/path.go, line 149 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-KnYhs3iO6FH3H0j2Ktm:-KnYhs3j02_QtIXPFIoY:b663ozn) ([raw file](https://github.com/netsec-ethz/scion/blob/1906b95168a932a6de015b183758114ab68e82c8/go/border/rpkt/path.go#L149)):*
> ```Go
> 		case rp.CmnHdr.CurrHopF == rp.CmnHdr.CurrInfoF:
> 			// There is no path, so do nothing.
> 		case rp.CmnHdr.CurrInfoF < uint8(rp.idxs.path/common.LineLen): // Error
> ```

This can be simplified to `case rp.CmnHdr.InfoOffBytes() < rp.idxs.path`

---

*[go/border/rpkt/path.go, line 151 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-KnYhwWiTQMsrTkoG8Ui:-KnYhwWiTQMsrTkoG8Uj:b7frp84) ([raw file](https://github.com/netsec-ethz/scion/blob/1906b95168a932a6de015b183758114ab68e82c8/go/border/rpkt/path.go#L151)):*
> Info field index too small

would be much clearer. Same for the info field too large, and the corresponding hop field errors below.

---

*[go/lib/spkt/spkt.go, line 93 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4kpBFDuihGd6oN8wE:-KnYglRQk-AnXt3vLI2F:bf72ap6) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/lib/spkt/spkt.go#L93)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Okay. It might be confusing, since the field is also called hdrLen.
Done.
</blockquote></details>

Adding a docstring would help a lot there. `// HdrLen returns the length of the header, in bytes.`

---

*[python/lib/packet/scion.py, line 112 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4tfH9g7rHRg9aadnE:-KnYeyctMYPdtDvVM1fl:bc5j7bo) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/lib/packet/scion.py#L112)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Should a parse error be thrown if ioff == hoff != 0?
</blockquote></details>

Good question. There should probably be a check like `if (ioff == 0 or hoff == 0)  and ioff != hoff:` that then throws a parse error.

---

*[python/test/lib/packet/scion_test.py, line 70 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4xVWFbf19_xknSzW9:-KnYgFTjxUXRWSoi2m-W:b-43b0z4) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/test/lib/packet/scion_test.py#L70)):*
> Same for the pack() tests.

:P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1136)*

**Comment by Oncilla** [comment]
Review status: 22 of 28 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/border/rpkt/extn_onehoppath.go, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4naWJ4osXIIFyZVHH:-KnYvXwpmgV6o-PsKYcI:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/border/rpkt/extn_onehoppath.go#L59)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

You're still calling it twice :)
</blockquote></details>

Done.

---

*[go/border/rpkt/path.go, line 149 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-KnYhs3iO6FH3H0j2Ktm:-KnYw3-alLhkknRujeQw:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/1906b95168a932a6de015b183758114ab68e82c8/go/border/rpkt/path.go#L149)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be simplified to `case rp.CmnHdr.InfoOffBytes() < rp.idxs.path`
</blockquote></details>

Done.

---

*[go/border/rpkt/path.go, line 151 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-KnYhwWiTQMsrTkoG8Ui:-KnYwHN-mcrmQnbkdRoq:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/1906b95168a932a6de015b183758114ab68e82c8/go/border/rpkt/path.go#L151)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

> Info field index too small

would be much clearer. Same for the info field too large, and the corresponding hop field errors below.
</blockquote></details>

Done.

---

*[go/lib/spkt/spkt.go, line 93 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4kpBFDuihGd6oN8wE:-KnYwk47bdpLlxLnW3dX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/go/lib/spkt/spkt.go#L93)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Adding a docstring would help a lot there. `// HdrLen returns the length of the header, in bytes.`
</blockquote></details>

Done.

---

*[python/lib/packet/scion.py, line 112 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4tfH9g7rHRg9aadnE:-KnZTKslA0ac2vecqtmU:b-9xuirz) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/lib/packet/scion.py#L112)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Good question. There should probably be a check like `if (ioff == 0 or hoff == 0)  and ioff != hoff:` that then throws a parse error.
</blockquote></details>

This is certainly an invalid case to. But does not cover ioff == hoff and ioff != 0.

---

*[python/test/lib/packet/scion_test.py, line 70 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-Kn4xVWFbf19_xknSzW9:-KnZ_8lBq3eFOwYMqPFW:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f0366383f506dd7cabbd2f64adc0bab6d286fcb4/python/test/lib/packet/scion_test.py#L70)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

> Same for the pack() tests.

:P
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1136)*

**Comment by kormat** [comment]
Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[python/lib/packet/scion.py, line 115 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-KnZe5CLmkKys5rniCBk:-KnZe5CLmkKys5rniCBl:b-ysieh7) ([raw file](https://github.com/netsec-ethz/scion/blob/e7db520a450634046b915c7d9114768d602e1f97/python/lib/packet/scion.py#L115)):*
> ```Python
>             self._iof_idx = self._hof_idx = 0
>             return
>         if iof_off == hof_off or (iof_off == 0 or hof_off == 0) and iof_off != hof_off:
> ```

This is a bit hard to read, and i'm not sure it will do the right thing without looking up precedence. However, i think it can be simplified:
```
if iof_off == 0 or hof_off <= iof_off:
```

---

*[python/lib/packet/scion.py, line 154 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-KnZefCXD9aJP80PisGz:-KnZefCXD9aJP80PisH-:b8jbbh1) ([raw file](https://github.com/netsec-ethz/scion/blob/e7db520a450634046b915c7d9114768d602e1f97/python/lib/packet/scion.py#L154)):*
> ```Python
>             curr_hof_p += self._hof_idx * OpaqueField.LEN
>         if curr_hof_p == offset and curr_iof_p == offset:
>             curr_hof_p = curr_iof_p = 0
> ```

I think it's probably simpler to just initialise them to `0`,  and then do:
```
if self._iof_idx:
   curr_iof_p = self.LEN + self.addrs_len + self._iof_idx * OpaqueField.LEN
...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1136)*

**Comment by Oncilla** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[python/lib/packet/scion.py, line 115 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-KnZe5CLmkKys5rniCBk:-KnZg_wxM_jEzDWIugZl:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e7db520a450634046b915c7d9114768d602e1f97/python/lib/packet/scion.py#L115)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is a bit hard to read, and i'm not sure it will do the right thing without looking up precedence. However, i think it can be simplified:
```
if iof_off == 0 or hof_off <= iof_off:
```
</blockquote></details>

Done.

---

*[python/lib/packet/scion.py, line 154 at r4](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-KnZefCXD9aJP80PisGz:-KnZgaF5Wm-pFX5odH_w:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e7db520a450634046b915c7d9114768d602e1f97/python/lib/packet/scion.py#L154)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I think it's probably simpler to just initialise them to `0`,  and then do:
```
if self._iof_idx:
   curr_iof_p = self.LEN + self.addrs_len + self._iof_idx * OpaqueField.LEN
...
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1136)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-:-KnZpzIgQvrlRkbt7gmq:bnfp4nl)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1136#-:-Kncq0Ar3VIoFoB-rPAS:bnfp4nl)*

**Pull request merged**
