### PR TITLE
Added checksum computation in native Go

### PR DESCRIPTION
**Pull request by scrye**
Also:
  * Checksum function is now commutative
  * Byte order is correct on wire

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1187)

### CODE REVIEW

**Comment by shitz** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/lib/util/checksum.go, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-KpzanmpKPV-7A76T48h:-KpzanmpKPV-7A76T48i:bb6ht2h) ([raw file](https://github.com/netsec-ethz/scion/blob/d01540f6c8c0c80e3bd402b032a3f38a2dedc31c/go/lib/util/checksum.go#L1)):*
> ```Go
> // Copyright 2016 ETH Zurich
> ```

2017

---

*[go/lib/util/checksum.go, line 47 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kpzat3LIe18lL2eb81N:-Kpzat3LIe18lL2eb81O:b9ls9ii) ([raw file](https://github.com/netsec-ethz/scion/blob/d01540f6c8c0c80e3bd402b032a3f38a2dedc31c/go/lib/util/checksum.go#L47)):*
> ```Go
> }
> 
> func toUint16(x uint8, y uint8) uint32 {
> ```

I would call this `toUint32` because that's what it's doing.

---

*[go/sig/lib/scion/scion.go, line 248 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-KpzbM_qhfzsTqTQULbO:-KpzbM_rZ6ntjI0FnA5A:bxfejq7) ([raw file](https://github.com/netsec-ethz/scion/blob/d01540f6c8c0c80e3bd402b032a3f38a2dedc31c/go/sig/lib/scion/scion.go#L248)):*
> ```Go
> 
> 	checksum := util.Checksum(addrHeader[0:16], commonHeader[7:8], udpHeader, b)
> 	udpHeader[6] = uint8(checksum >> 8)
> ```

Can't you use `binary.BigEndian.PutUint16(udpHeader[6:8], checksum)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1187)*

**Comment by scrye** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/util/checksum.go, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-KpzanmpKPV-7A76T48h:-Kq2-buHMFFisOUVxOoa:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d01540f6c8c0c80e3bd402b032a3f38a2dedc31c/go/lib/util/checksum.go#L1)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

2017
</blockquote></details>

Done.

---

*[go/lib/util/checksum.go, line 47 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kpzat3LIe18lL2eb81N:-Kq2-ZyQ-RdLledLda1M:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d01540f6c8c0c80e3bd402b032a3f38a2dedc31c/go/lib/util/checksum.go#L47)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I would call this `toUint32` because that's what it's doing.
</blockquote></details>

Done.

---

*[go/sig/lib/scion/scion.go, line 248 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-KpzbM_qhfzsTqTQULbO:-Kq20Ma4GA-g0OhbsZzl:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/d01540f6c8c0c80e3bd402b032a3f38a2dedc31c/go/sig/lib/scion/scion.go#L248)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Can't you use `binary.BigEndian.PutUint16(udpHeader[6:8], checksum)`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1187)*

**Comment by scrye** [comment]
RFC768 (for IPv4) and RFC2460 (for IPv6) state that in case of a 0x0000 checksum, all bits should be flipped to 0xFFFF. The scapy code doesn't do this, so I deleted the flip in the Go `Checksum` from the previous commit.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-:-Kq21y6SkUggewDIoif8:bde9vn6)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-:-Kq3vTg9pkwBT2zDu1sf:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 2 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[go/lib/l4/common.go, line 49 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8XbrVSCJUGDjt-q1N:-Kq8XbrVSCJUGDjt-q1O:b1qcnc9) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/lib/l4/common.go#L49)):*
> ```Go
> 		return nil, err
> 	}
> 	sum := util.Checksum(addr, []uint8{uint8(h.L4Type())}, rawh, pld)
> ```

This doesn't pad _before_ the proto type, like in IP.

---

*[go/lib/l4/common.go, line 51 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8XthT3i1uZ05-0nqs:-Kq8XthT3i1uZ05-0nqt:b-52nh84) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/lib/l4/common.go#L51)):*
> ```Go
> 	sum := util.Checksum(addr, []uint8{uint8(h.L4Type())}, rawh, pld)
> 	out := make(common.RawBytes, 2)
> 	binary.BigEndian.PutUint16(out, sum)
> ```

As `common.Order` is defined to by `BigEndian`, why not use it?

---

*[go/lib/util/checksum.go, line 17 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8aY4863RA8KwWnGHg:-Kq8aY4863RA8KwWnGHh:b-l231jg) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/lib/util/checksum.go#L17)):*
> ```Go
> package util
> 
> import "github.com/netsec-ethz/scion/go/lib/common"
> ```

Put all imports inside `()`, reduces diff noise when imports are changed later.

---

*[go/lib/util/checksum.go, line 21 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8afmkd1rACTL2xDwb:-Kq8afmkd1rACTL2xDwc:b-cs3mtf) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/lib/util/checksum.go#L21)):*
> ```Go
> // Calculate RFC1071 checksum of supplied data chunks. If a chunk has
> // an odd length, it is padded with a 0 during checksum computation.
> func Checksum(srcs ...common.RawBytes) uint16 {
> ```

This needs some unit tests.

---

*[go/sig/lib/scion/scion.go, line 247 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8b8iCJQY4Ydoqf8Mz:-Kq8b8iCJQY4Ydoqf8N-:bs89zgg) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/sig/lib/scion/scion.go#L247)):*
> ```Go
> 	binary.BigEndian.PutUint16(udpHeader[4:6], uint16(len(b))+l4.UDPLen)
> 
> 	checksum := util.Checksum(addrHeader[0:16], commonHeader[7:8], udpHeader, b)
> ```

Same here re: not padding _before_ proto type.

Also, please don't hard code the address header size. You already have the exact size above.

---

*[go/sig/lib/scion/scion.go, line 248 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8b3e70M6ir_4Ds7kD:-Kq8b3e70M6ir_4Ds7kE:b6zkf39) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/sig/lib/scion/scion.go#L248)):*
> ```Go
> 
> 	checksum := util.Checksum(addrHeader[0:16], commonHeader[7:8], udpHeader, b)
> 	binary.BigEndian.PutUint16(udpHeader[6:8], checksum)
> ```

Same here re: `common.Order`.

---

*[python/lib/packet/scion_udp.py, line 117 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8cJOg-qTAZs_3tcVh:-Kq8cJOg-qTAZs_3tcVi:b-87y31z) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/python/lib/packet/scion_udp.py#L117)):*
> ```Python
>             self._dst.isd_as.pack(), self._src.isd_as.pack(),
>             self._dst.host.pack(), self._src.host.pack(),
>             struct.pack("!B", L4Proto.UDP), b"\x00",
> ```

Ditto re: proto padding.

---

*[python/lib/packet/scion_udp.py, line 121 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8cFUhL7J3hijo_mi2:-Kq8cFUhL7J3hijo_mi3:b-oyn5vt) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/python/lib/packet/scion_udp.py#L121)):*
> ```Python
>         ])
>         chk_int = scapy.utils.checksum(pseudo_header)
>         return struct.pack(">H", chk_int)
> ```

Please use `!` instead of `>`, we use `!` everywhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1187)*

**Comment by scrye** [comment]
Review status: 1 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[go/lib/l4/common.go, line 49 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8XbrVSCJUGDjt-q1N:-Kq8fyydIafS9_VPXXto:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/lib/l4/common.go#L49)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This doesn't pad _before_ the proto type, like in IP.
</blockquote></details>

Done.

---

*[go/lib/l4/common.go, line 51 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8XthT3i1uZ05-0nqs:-Kq8g0QVl-2acRiqJz50:b-dw5urt) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/lib/l4/common.go#L51)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As `common.Order` is defined to by `BigEndian`, why not use it?
</blockquote></details>

This should always be BigEndian since it's network order, but as `common.Order` will never change to LittleEndian I guess either is fine.

---

*[go/lib/util/checksum.go, line 17 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8aY4863RA8KwWnGHg:-Kq8gTKRi_MbtCyLzDg6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/lib/util/checksum.go#L17)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Put all imports inside `()`, reduces diff noise when imports are changed later.
</blockquote></details>

Done.

---

*[go/lib/util/checksum.go, line 21 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8afmkd1rACTL2xDwb:-Kq8uPZiGptzrPga0Juh:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/lib/util/checksum.go#L21)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This needs some unit tests.
</blockquote></details>

Done.

---

*[go/sig/lib/scion/scion.go, line 247 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8b8iCJQY4Ydoqf8Mz:-Kq8gg_yK0vRF2I9qvbl:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/sig/lib/scion/scion.go#L247)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Same here re: not padding _before_ proto type.

Also, please don't hard code the address header size. You already have the exact size above.
</blockquote></details>

Done.

---

*[go/sig/lib/scion/scion.go, line 248 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8b3e70M6ir_4Ds7kD:-Kq8ghLlxjLDMVW0qC0n:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/go/sig/lib/scion/scion.go#L248)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Same here re: `common.Order`.
</blockquote></details>

Done.

---

*[python/lib/packet/scion_udp.py, line 117 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8cJOg-qTAZs_3tcVh:-Kq8uNHPHcrlxZqEChUy:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/python/lib/packet/scion_udp.py#L117)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Ditto re: proto padding.
</blockquote></details>

Done.

---

*[python/lib/packet/scion_udp.py, line 121 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq8cFUhL7J3hijo_mi2:-Kq8uMyXcVjQolxlcPlR:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/284cc24c8003b21550d0456a9fe2e646650d0e1c/python/lib/packet/scion_udp.py#L121)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Please use `!` instead of `>`, we use `!` everywhere else.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1187)*

**Comment by kormat** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/util/checksum_test.go, line 18 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq9-53dXDFKxPBOP5ZH:-Kq9-53dXDFKxPBOP5ZI:b-jk4dao) ([raw file](https://github.com/netsec-ethz/scion/blob/3d98b71148a380282c8b7c7258e6c29770ca9de8/go/lib/util/checksum_test.go#L18)):*
> ```Go
> 		Output [2]byte
> 	}{
> 		{common.RawBytes{0x00, 0x01}, [2]byte{0xff, 0xfe}},
> ```

It would be better to pass in a slice of `common.RawBytes`, as that will test intermediate padding etc.

---

*[go/sig/lib/scion/scion.go, line 247 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq9-onmoHFpZiwVdfEs:-Kq9-onmoHFpZiwVdfEt:b-b02m9k) ([raw file](https://github.com/netsec-ethz/scion/blob/3d98b71148a380282c8b7c7258e6c29770ca9de8/go/sig/lib/scion/scion.go#L247)):*
> ```Go
> 	binary.BigEndian.PutUint16(udpHeader[4:6], uint16(len(b))+l4.UDPLen)
> 
> 	checksum := util.Checksum(addrHeader, []byte{0, commonHeader[7]}, udpHeader[0:6], b)
> ```

The `0` in `0:6` is superfluous.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1187)*

**Comment by scrye** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/util/checksum_test.go, line 18 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq9-53dXDFKxPBOP5ZH:-Kq95325ZUXxsBgu5fh1:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3d98b71148a380282c8b7c7258e6c29770ca9de8/go/lib/util/checksum_test.go#L18)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It would be better to pass in a slice of `common.RawBytes`, as that will test intermediate padding etc.
</blockquote></details>

Done.

---

*[go/sig/lib/scion/scion.go, line 247 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-Kq9-onmoHFpZiwVdfEs:-Kq953hd9g7PAJOnFHdZ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3d98b71148a380282c8b7c7258e6c29770ca9de8/go/sig/lib/scion/scion.go#L247)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The `0` in `0:6` is superfluous.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1187)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1187#-:-Kq96JBYyC4CVfdQuT6S:bnfp4nl)*

**Pull request closed without merging**
