### PR TITLE
Rework BR/Ringbug metrics, and some other fixes.

### PR DESCRIPTION
**Pull request by kormat**
- Re-design most of the BR metrics to fit better with our needs.
- Use RtrPkt free time to determine processing latency.
- Don't treat "ECONNREFUSED" on read as an error.
- Shrink sock ringbufs to 64, to prevent freePkts from being depeleted
  too easily.
- Shrink input/process/output buffers to 32, to reduce ringbuf read/write
  latency.
- Change ringbuf interface to return a bool indicating if a read/write
  blocked.
- Change assert.Mustf to take a function and an argument, to remove the
  memory overhead of creating a closure multiple times per packet.
- Rewrite a lot of overlay.conn.connUDPIPv4.Read logic, to reduce
  allocations, and to expose metadata to the caller.
- Change ringbuf condition signalling to use Broadcast() instead of
  Signal(), to allow multiple readers/writers to work (albiet somewhat
  inefficiently).

Also:
- Fix pktgen to produce packets with the correct size.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1229)

### CODE REVIEW

**Comment by klausman** [comment]
Reviewed 15 of 15 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/border/io.go, line 90 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1229#-KsIaD6EmZubhP-hFBKH:-KsIaD6EmZubhP-hFBKI:bynrhlu) ([raw file](https://github.com/netsec-ethz/scion/blob/1399235010950652d05c59eee3a4b3f3281b1e74/go/border/io.go#L90)):*
> ```Go
> 					// the socket. As these do not indicate a problem with this BR,
> 					// these errors should not be counted, and should not
> 					// increment the read counter.
> ```

It _may_ be useful to count such errors here since the other BR may not be under our control/not scraped by us. Thus, having a metric like `br_remote_read_err{remote_endpoint="1.2.3.4:54321"}` or the like could be useful. Not necessary now but maybe a TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1229)*

**Comment by scrye** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1229#-:-KsIwgSLa9Zi2hmyXSGg:bnfp4nl)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/border/io.go, line 90 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1229#-KsIaD6EmZubhP-hFBKH:-KsIwxkOJfIw9Hj5ddVK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/1399235010950652d05c59eee3a4b3f3281b1e74/go/border/io.go#L90)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

It _may_ be useful to count such errors here since the other BR may not be under our control/not scraped by us. Thus, having a metric like `br_remote_read_err{remote_endpoint="1.2.3.4:54321"}` or the like could be useful. Not necessary now but maybe a TODO.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1229)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: 14 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1229#-:-KsIyUCIx72JJF_VC3ai:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1229)*

**Pull request merged**
