### PR TITLE
Add a simple checksum benchmark utility.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1199)

### CODE REVIEW

**Comment by klausman** [comment]
Cosmetic stuff, otherwise :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[c/lib/scion/checksum_bench.c, line 8 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1199#-Kr0geKXKhNV9jq7Id8z:-Kr0geKXKhNV9jq7Id9-:b-ks0cx9) ([raw file](https://github.com/netsec-ethz/scion/blob/8d17d3e034794ba3778eab12b1bb3212067321b0/c/lib/scion/checksum_bench.c#L8)):*
> ```C
> 
> #define SIMPLE_COUNT 500000000
> #define COMPLEX_COUNT 50000000
> ```

I think these two defines can be dropped now?

---

*[c/lib/scion/checksum_bench.c, line 45 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1199#-Kr0gzOa3oqXjJNuoesN:-Kr0gzOa3oqXjJNuoesO:b-syyxgn) ([raw file](https://github.com/netsec-ethz/scion/blob/8d17d3e034794ba3778eab12b1bb3212067321b0/c/lib/scion/checksum_bench.c#L45)):*
> ```C
>         checksum(input);
>     }
>     printf("simple_test(%ld = %ldB): %ld in %ds (%.2lfM call/s)\n",
> ```

`calls`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1199#-:-Kr0hN5Hwx_oP5fXd0Dy:b6cykl0)*

**Comment by kormat** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[c/lib/scion/checksum_bench.c, line 8 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1199#-Kr0geKXKhNV9jq7Id8z:-Kr0iFIUAoF3rOf5AflX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/8d17d3e034794ba3778eab12b1bb3212067321b0/c/lib/scion/checksum_bench.c#L8)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

I think these two defines can be dropped now?
</blockquote></details>

Done.

---

*[c/lib/scion/checksum_bench.c, line 45 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1199#-Kr0gzOa3oqXjJNuoesN:-Kr0iFcfh26_zxju3SMB:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/8d17d3e034794ba3778eab12b1bb3212067321b0/c/lib/scion/checksum_bench.c#L45)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

`calls`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1199)*

**Comment by klausman** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1199)*

**Comment by scrye** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1199#-:-Kr0jm2cBdkoDkCUjuem:bnfp4nl)*

**Pull request merged**
