### PR TITLE
DO NOT MERGE - Initial work on new topology format generation.

### PR DESCRIPTION
**Pull request by jonghoonkwon**
@kormat @ercanucan 
This is the initial work on the new topology format generation. I'm glad to get some feedback for the direction of this work
-not to be merged

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/977)

### CODE REVIEW

**Comment by kormat** [comment]
One thing that might not have been clear in the sample topology is that i would like to support both of these formats:
```
"Public": [{"Addr": ... "L4Port": ...}]
```
and
```
"Public": {"Addr": ..., "L4Port":...}
```
I.e. `Public`/`Bind` entries don't need to be inside a list if there's only a single entry.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-:-Kdeyv4W11ekzSCgvcRP:b-8yrzg0)*

**Comment by kormat** [comment]
Ok, first pass done. There's lots of little comments, but in general it looks really good :)

Run `./scion.sh lint` to run the linter. There's a number of minor formatting issues that need fixing.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[lib/topology.py, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KderQNzCTm1ka7H_pQe:-KderQNzCTm1ka7H_pQf:bt7x00k) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L35)):*
> ```Python
> from lib.util import (
>     load_yaml_file,
>     load_json_file,
> ```

Sort imports (also this is short enough that it can easily be on one line).

---

*[lib/topology.py, line 55 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf-n-pnNl5jNIswmp8:-Kdf-n-pnNl5jNIswmp9:bmnm9ov) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L55)):*
> ```Python
>         self.bind = []
>         if public:
>             for attr in public:
> ```

It would be better to have a method dedicated to handling this.
```
def _parse_addrs(self, value):
   if not value:
     return []
   addrs = []
   if not isinstance(value, (list, tuple)):
      value = [value]
   for val in value:
       addrs.append((haddr_parse_interface(attr['Addr']), attr['L4Port']))
    return addrs
```
 This can then be called in `__init__`:
```
self.public = self._parse_addrs(public)
self.bind = self._parse_addrs(bind)
```

---

*[lib/topology.py, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KdervZvhpQueZ0ZfvID:-KdervZvhpQueZ0ZfvIE:b63icd7) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L56)):*
> ```Python
>         if public:
>             for attr in public:
>                 self.public.append({haddr_parse_interface(attr['Addr']), attr['L4Port']})
> ```

This should be `()`, not `{}` - the latter declares a set.

---

*[lib/topology.py, line 74 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KdesLnucHAVOXaSntyf:-KdesLnucHAVOXaSntyg:b-nv6xs0) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L74)):*
> ```Python
>         :param dict server_dict: contains information about a particular server.
>         :param str name: server element name or id
>         """
> ```

This can be simplified to:
```
super().__init__(server_dict['Public'], server_dict.get('Bind'), name)
```

---

*[lib/topology.py, line 115 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdevk6yMg5JMGl1nBev:-Kdevk6yMg5JMGl1nBew:b6jg3cb) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L115)):*
> ```Python
>         self.mtu = interface_dict['MTU']
>         to_addr = interface_dict['Remote']['Addr']
>         if to_addr:
> ```

This is a very old check, which should just be removed at this point. We can also update the naming:
```
self.remote = self._parse_addrs(interface_dict['Remote'])
```

---

*[lib/topology.py, line 117 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf250IO2IZYXDmoqQu:-Kdf250IO2IZYXDmoqQv:b-6srupm) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L117)):*
> ```Python
>         if to_addr:
>             self.to_addr = haddr_parse_interface(to_addr)
>         self.to_if_id =0 # Filled in later by IFID packets
> ```

There's a space missing before the `0`.

---

*[lib/topology.py, line 118 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf1Tk4hWwePuNn5o3_:-Kdf1Tk5r6mIshTqaJqp:b-ck3exk) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L118)):*
> ```Python
>             self.to_addr = haddr_parse_interface(to_addr)
>         self.to_if_id =0 # Filled in later by IFID packets
>         super().__init__(public, bind, name)
> ```

`super().__init__(interface_dict['Public'], server_dict.get('Bind'), name)`

---

*[lib/topology.py, line 121 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf2G0ir9SiIgazUnoR:-Kdf2G0ir9SiIgazUnoS:b-cre5vl) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L121)):*
> ```Python
> 
> 
> class InternalAddrElement(Element):
> ```

I don't think this is needed, `Element` can just be used directly instead.

---

*[lib/topology.py, line 153 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf2QruhXo7jY2XD7pw:-Kdf2QruhXo7jY2XD7px:bj11v8u) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L153)):*
> ```Python
>         self.internaladdrs = []
>         for attr in router_dict['InternalAddrs']:
>             self.internaladdrs.append(InternalAddrElement(attr))
> ```

self.internaladdrs.append(Element(addr['Public'], addr.get('Bind'))

---

*[lib/topology.py, line 155 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf2wK_yRAXRL6nQNu6:-Kdf2wK_yRAXRL6nQNu7:b-7029do) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L155)):*
> ```Python
>             self.internaladdrs.append(InternalAddrElement(attr))
>         self.interface = []
>         for attr in router_dict['Interfaces']:
> ```

```
self.interfaces = {}
for if_id, intf in router_dict['Interfaces'].values():
    if_id = int(if_id)
    self.interfaces[if_id] = InterfaceElement(if_id, intf)
```

---

*[lib/topology.py, line 158 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf3_uBiuMPsu8N0y_R:-Kdf3_uBiuMPsu8N0y_S:b-aivxk5) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L158)):*
> ```Python
>             self.interface.append(InterfaceElement(attr, router_dict['Interfaces'][attr]))
> 
>     def __lt__(self, other):  # pragma: no cover
> ```

This isn't valid any more, as routers aren't sortable, only interfaces are. For now, please change this function to `raise NotImplementedError`, so that it's obvious where it's called from.

---

*[lib/topology.py, line 205 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf3qD2HL5ujbrmSeQt:-Kdf3qD2HL5ujbrmSeQu:bxkyfy0) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L205)):*
> ```Python
>             return cls.from_dict(load_yaml_file(topology_file))
>         elif topology_file.endswith('.json'):
>             return cls.from_dict(load_json_file(topology_file))
> ```

I think it's easier to just drop yaml support.

---

*[topology/generator.py, line 654 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf5NE7kDv8rmfO8oJR:-Kdf5NE8hWCfyb34_CR1:bhgxip) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/topology/generator.py#L654)):*
> ```Python
>             path = os.path.join(base, TOPO_FILE)
>             contents = yaml.dump(self.topo_dicts[topo_id],
>                                  default_flow_style=False)
> ```

You can remove this, and just call `json.dumps` on `self.topo_dicts[topo_id]` directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-:-Kdf4p9Z0e_Rjx_9zrXl:b-zejm8z)*

**Comment by jonghoonkwon** [comment]
@kormat Addressed your initial feedback and also added parsing of the new topology format. Tests are still not adapted yet.

---

Review status: 1 of 8 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[lib/topology.py, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KderQNzCTm1ka7H_pQe:-Kei4tE1dJODqxxuYjXN:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L35)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Sort imports (also this is short enough that it can easily be on one line).
</blockquote></details>

Done.

---

*[lib/topology.py, line 55 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf-n-pnNl5jNIswmp8:-Kei4viZAB4NaOnedLRA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L55)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It would be better to have a method dedicated to handling this.
```
def _parse_addrs(self, value):
   if not value:
     return []
   addrs = []
   if not isinstance(value, (list, tuple)):
      value = [value]
   for val in value:
       addrs.append((haddr_parse_interface(attr['Addr']), attr['L4Port']))
    return addrs
```
 This can then be called in `__init__`:
```
self.public = self._parse_addrs(public)
self.bind = self._parse_addrs(bind)
```
</blockquote></details>

Done.

---

*[lib/topology.py, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KdervZvhpQueZ0ZfvID:-Kei4tbN61zzlU2fF00q:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L56)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be `()`, not `{}` - the latter declares a set.
</blockquote></details>

Done.

---

*[lib/topology.py, line 74 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KdesLnucHAVOXaSntyf:-Kei4uHfOXEASG7jbOu0:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L74)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be simplified to:
```
super().__init__(server_dict['Public'], server_dict.get('Bind'), name)
```
</blockquote></details>

Done.

---

*[lib/topology.py, line 115 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdevk6yMg5JMGl1nBev:-Kei4urZFDVL9iHdpySP:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L115)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is a very old check, which should just be removed at this point. We can also update the naming:
```
self.remote = self._parse_addrs(interface_dict['Remote'])
```
</blockquote></details>

Done.

---

*[lib/topology.py, line 117 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf250IO2IZYXDmoqQu:-Kei4wjaeGip-Or8Z1Sg:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L117)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There's a space missing before the `0`.
</blockquote></details>

Done.

---

*[lib/topology.py, line 118 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf1Tk4hWwePuNn5o3_:-Kei4wPko3nqA-2-UHLr:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L118)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`super().__init__(interface_dict['Public'], server_dict.get('Bind'), name)`
</blockquote></details>

Done.

---

*[lib/topology.py, line 121 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf2G0ir9SiIgazUnoR:-Kei4xY68-V6cCsOTcEF:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L121)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I don't think this is needed, `Element` can just be used directly instead.
</blockquote></details>

Done.

---

*[lib/topology.py, line 153 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf2QruhXo7jY2XD7pw:-Kei4yS-kpLJ7svLKdMr:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L153)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

self.internaladdrs.append(Element(addr['Public'], addr.get('Bind'))
</blockquote></details>

Done.

---

*[lib/topology.py, line 155 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf2wK_yRAXRL6nQNu6:-Kei4zJDiYXLGrxANO6f:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L155)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

```
self.interfaces = {}
for if_id, intf in router_dict['Interfaces'].values():
    if_id = int(if_id)
    self.interfaces[if_id] = InterfaceElement(if_id, intf)
```
</blockquote></details>

Done.

---

*[lib/topology.py, line 158 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf3_uBiuMPsu8N0y_R:-Kei4zwJ6FkI2AcYACDq:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L158)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This isn't valid any more, as routers aren't sortable, only interfaces are. For now, please change this function to `raise NotImplementedError`, so that it's obvious where it's called from.
</blockquote></details>

Done.

---

*[lib/topology.py, line 205 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf3qD2HL5ujbrmSeQt:-Kei5-HnUl1M19RXhxQw:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/lib/topology.py#L205)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I think it's easier to just drop yaml support.
</blockquote></details>

Done.

---

*[topology/generator.py, line 654 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-Kdf5NE7kDv8rmfO8oJR:-Kei506vAaFCZwZr8UTH:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/topology/generator.py#L654)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

You can remove this, and just call `json.dumps` on `self.topo_dicts[topo_id]` directly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-:-Kei54rwPSSxgOotGccr:bg8t31h)*

**Comment by kormat** [comment]
Reviewed 6 of 7 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 138 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KfHnqfIfv3ykxlhrbCG:-KfHnqfJ8IwlH6oq_yhQ:bs6fikn) ([raw file](https://github.com/netsec-ethz/scion/blob/a4a706177c6fca567e1b958fde5d908df2909209/infrastructure/scion_elem.py#L138)):*
> ```Python
>         self.public = []
>         self.bind = []
>         if public is None:
> ```

This line doesn't look right - why change it?

---

*[infrastructure/scion_elem.py, line 177 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KfHsm8mHo1bWt9m0Sru:-KfHsm8mHo1bWt9m0Srv:bb7lwj0) ([raw file](https://github.com/netsec-ethz/scion/blob/a4a706177c6fca567e1b958fde5d908df2909209/infrastructure/scion_elem.py#L177)):*
> ```Python
>             return []
>         addrs = []
>         if not isinstance(value, (list, tuple)):
> ```

You don't need to handle this case, just require that the `public` and `bind` arguments to `SCIONElement.__init__` are always lists.

---

*[infrastructure/scion_elem.py, line 195 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KfHt5_1K0o46NRmJsld:-KfHt5_1K0o46NRmJsle:bxxfupq) ([raw file](https://github.com/netsec-ethz/scion/blob/a4a706177c6fca567e1b958fde5d908df2909209/infrastructure/scion_elem.py#L195)):*
> ```Python
>         svc = SERVICE_TO_SVC_A.get(self.SERVICE_TYPE)
>         # Setup TCP "accept" socket.
>         self._setup_tcp_accept_socket(svc)
> ```

Note to self - reviewed until here.

---

*[infrastructure/beacon_server/base.py, line 374 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KfHqir9ZAUrQOw6n2So:-KfHqirAUp7UoVoPcUJ5:b-gwq63k) ([raw file](https://github.com/netsec-ethz/scion/blob/a4a706177c6fca567e1b958fde5d908df2909209/infrastructure/beacon_server/base.py#L374)):*
> ```Python
>                     pld = IFStatePayload.from_values([state_info])
>                     for br in self.topology.get_all_border_routers():
>                         for attr in br.internaladdrs:
> ```

This doesn't need to be sent to all internal addresses, one is fine, same as you do in `_issue_revocation`.

---

*[infrastructure/router/main.py, line 113 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KfHrM8-DRjjGTR6_Xyl:-KfHrM80E5Z1OeZyCMb1:b-eo9avc) ([raw file](https://github.com/netsec-ethz/scion/blob/a4a706177c6fca567e1b958fde5d908df2909209/infrastructure/router/main.py#L113)):*
> ```Python
>         for br in self.topology.get_all_border_routers():
>             if br.name == self.id:
>                 (self.if_id, ) = br.interfaces
> ```

This.. is not something i've seen before :)
A clearer way to do this would be: `self.if_id = list(d.keys())[0]`

---

*[lib/topology.py, line 120 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KfHnUojtObSJfZlcMa5:-KfHnUojtObSJfZlcMa6:b5oejcc) ([raw file](https://github.com/netsec-ethz/scion/blob/a4a706177c6fca567e1b958fde5d908df2909209/lib/topology.py#L120)):*
> ```Python
>             self.internaladdrs.append(Element(attr['Public'], attr.get('Bind')))
>         self.interfaces = {}
>         self._order_id = maxsize
> ```

I'm still not convinced it makes sense to support sorting `RouterElements`.

---

*[topology/generator.py, line 578 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KeiADx2vFPOkuNLOGbh:-KeiADx2vFPOkuNLOGbi:bg912kb) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/topology/generator.py#L578)):*
> ```Python
>                 'Public': [{
>                     'Addr': self._reg_addr(topo_id, elem_id), 
>                     'L4Port': random.randint(30050, 30100),
> ```

There's no need to remove trailing `,`'s.

---

*[topology/generator.py, line 639 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KeiAi73rHYusnTas3H7:-KeiAi73rHYusnTas3H8:b-pqqn4) ([raw file](https://github.com/netsec-ethz/scion/blob/59c1dc73873b12b56709260ed419d4340a5faaac/topology/generator.py#L639)):*
> ```Python
>         self.topo_dicts[topo_id]["ZookeeperService"][zk_id] = {
>             'Addr': addr,
>             'L4Port': zk.clientPort,
> ```

Same here re: `,`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/977)*

**Comment by kormat** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 227 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KfM7u-dES6TSR-iNp6C:-KfM7u-dES6TSR-iNp6D:b-6n71kh) ([raw file](https://github.com/netsec-ethz/scion/blob/a4a706177c6fca567e1b958fde5d908df2909209/infrastructure/scion_elem.py#L227)):*
> ```Python
>             udp_sock = ReliableSocket(
>                 reg=(addr, port, init, svc))
>             sock_id = self.ip2int(addr)
> ```

Why not just use `addr` as the key?

---

*[infrastructure/scion_elem.py, line 640 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/977#-KfM8DjEEoV-9j_ux5cc:-KfM8DjEEoV-9j_ux5cd:b-ro5f7) ([raw file](https://github.com/netsec-ethz/scion/blob/a4a706177c6fca567e1b958fde5d908df2909209/infrastructure/scion_elem.py#L640)):*
> ```Python
>             for sock_id, udp_sock in self._udp_sock.items():
>                 if sock == udp_sock:
>                     self._udp_sock[sock_id] = None
> ```

`del self._udp_sock[sock_id]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/977)*

**Comment by jonghoonkwon** [comment]
Closing in favor of #1057

**Pull request closed without merging**
