### PR TITLE
SIG ingress rework

### PR DESCRIPTION
**Pull request by shitz**
This PR adds an `IngressDispatcher` that takes a SIG frame, classifies it based on remote IA -> remote host -> session id and hands it off the the corresponding `IngressWorker` for processing.

Also:
* Moved ingress logic out of `base` and created a new `ingress` package
* Replaced `sync.Pool` and channels with `ringbuf`

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1264)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[go/sig/ingress/dispatcher.go, line 64 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRebSduiAn8A26XJUr:-KvRebSe0IVurVvt5zZa:b-wfixe2) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/dispatcher.go#L64)):*
> ```Go
> 			prometheus.Labels{"ringId": "freeFrames"}),
> 	}
> 	// Fill ringbuf
> ```

This is what the `NewEntryF` parameter to `ringbuf.New` is for. See `go/border/setup.go:setup()` for an example.

---

*[go/sig/ingress/dispatcher.go, line 120 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRhObJhM2WXptE-qom:-KvRhObNAMtOVANF1Dwq:bf9bb6q) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/dispatcher.go#L120)):*
> ```Go
> 	dispatchStr := fmt.Sprintf("%s/%s/%d", src.IA, src.Host, session)
> 	// Check if we already have a worker running and start one if not.
> 	d.workersMutex.Lock()
> ```

~Go 1.9 has https://golang.org/pkg/sync/#Map, which is probably a good fit for this. Add a TODO to look at that once we move to 1.9, pls.~

From discussion: `Read()` could do a periodic check for stale workers and do the cleanup directly. It avoids the need for another goroutine, and locking.

---

*[go/sig/ingress/rlist.go, line 43 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvSLmL-ZVK2C5zXE1GL:-KvSLmL-ZVK2C5zXE1GM:bm670zf) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/rlist.go#L43)):*
> ```Go
> 
> // NewReassemblyList returns a ReassemblyList object for the given epoch, with given
> // maximum capacity and using bufPool to release processed frame buffers into.
> ```

Outdated comment (mentions `bufPool`)

---

*[go/sig/ingress/worker.go, line 53 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRjnrwpShsO-h8skJI:-KvRjnrwpShsO-h8skJJ:bxk1014) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/worker.go#L53)):*
> ```Go
> 		Remote:          remote,
> 		Session:         session,
> 		Ring:            ringbuf.New(64, nil, "", ringLabels),
> ```

`""` should be `"ingress"`.

---

*[go/sig/ingress/worker.go, line 68 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRp4N2ZRDGHOrstVK-:-KvRp4N2ZRDGHOrstVK0:bkf8ai4) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/worker.go#L68)):*
> ```Go
> }
> 
> func (w *Worker) Stop() {
> ```

I'm not sure this is necessary. Instead of calling `.Stop()`, the management code can just close the ringbuf. The `stopped` channel is probably still useful, but the `stop` channel can be dropped.

---

*[go/sig/ingress/worker.go, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRtlnIwZq8JoABCzk9:-KvRtlnJSxS0XAJP9UaL:bw1o7dv) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/worker.go#L99)):*
> ```Go
> 		for i := 0; i < n; i++ {
> 			frame := frames[i].(*FrameBuf)
> 			w.processFrame(frame)
> ```

`frames[[i] = nil` will prevent stray references hanging around.

---

*[go/sig/util/util.go, line 19 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRdCGxjzbFeLnUvT1M:-KvRdCGyTyupTdiJuiMo:b-j89wuz) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/util/util.go#L19)):*
> ```Go
> 
> // PadOffset returns the next integer larger than x that is aligned to align.
> func PadOffset(x, align int) int {
> ```

`go/lib/util:CalcPadding` already exists, and does almost the same thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1264)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[go/sig/ingress/dispatcher.go, line 64 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRebSduiAn8A26XJUr:-KvSSzf7O0a1c8fizDRO:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/dispatcher.go#L64)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is what the `NewEntryF` parameter to `ringbuf.New` is for. See `go/border/setup.go:setup()` for an example.
</blockquote></details>

Done.

---

*[go/sig/ingress/dispatcher.go, line 120 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRhObJhM2WXptE-qom:-KvSVSaXCdJAxqHWinyC:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/dispatcher.go#L120)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

~Go 1.9 has https://golang.org/pkg/sync/#Map, which is probably a good fit for this. Add a TODO to look at that once we move to 1.9, pls.~

From discussion: `Read()` could do a periodic check for stale workers and do the cleanup directly. It avoids the need for another goroutine, and locking.
</blockquote></details>

Done.

---

*[go/sig/ingress/rlist.go, line 43 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvSLmL-ZVK2C5zXE1GL:-KvSVbGmOxmicrrNto_B:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/rlist.go#L43)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Outdated comment (mentions `bufPool`)
</blockquote></details>

Done.

---

*[go/sig/ingress/worker.go, line 53 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRjnrwpShsO-h8skJI:-KvSVeZWbZDTMEzS3VYm:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/worker.go#L53)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`""` should be `"ingress"`.
</blockquote></details>

Done.

---

*[go/sig/ingress/worker.go, line 68 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRp4N2ZRDGHOrstVK-:-KvSVwBAbgj5dHBKgrxq:b2smz59) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/worker.go#L68)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'm not sure this is necessary. Instead of calling `.Stop()`, the management code can just close the ringbuf. The `stopped` channel is probably still useful, but the `stop` channel can be dropped.
</blockquote></details>

Left the method but removed the `stop` channel since it is indeed not needed.

---

*[go/sig/ingress/worker.go, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRtlnIwZq8JoABCzk9:-KvSW4_RZuSh1sksa7Rq:bd30ifx) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/worker.go#L99)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`frames[[i] = nil` will prevent stray references hanging around.
</blockquote></details>

good catch

---

*[go/sig/util/util.go, line 19 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRdCGxjzbFeLnUvT1M:-KvSXBrUnvivVwnWpg5a:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/util/util.go#L19)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`go/lib/util:CalcPadding` already exists, and does almost the same thing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1264)*

**Comment by kormat** [comment]
Reviewed 2 of 10 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/sig/ingress/dispatcher.go, line 44 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvWF_CFDWe9_36anMYg:-KvWF_CFDWe9_36anMYh:b6z9b9z) ([raw file](https://github.com/netsec-ethz/scion/blob/378e5c5b614c52952c5c47666fd072f5b28809bd/go/sig/ingress/dispatcher.go#L44)):*
> ```Go
> 	ExternalIngress *snet.Conn
> 	InternalIngress io.ReadWriteCloser
> 	FreeFrames      *ringbuf.Ring
> ```

These 3 can probably all be unexported, they should only be needed inside this module.

---

*[go/sig/ingress/worker.go, line 68 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRp4N2ZRDGHOrstVK-:-KvWGiYelanjjuUGhU84:b-n7frqz) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/worker.go#L68)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Left the method but removed the `stop` channel since it is indeed not needed.
</blockquote></details>

Looking at where this is called from (`cleanup()`), waiting for worker to stop seems unnecessary, in which case this can be reduced to just `w.Ring.Close()`. It means that cleanup doesn't need to spawn a goroutine for each stopping worker, either.

---

*[go/sig/ingress/worker.go, line 78 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvWHDKoXiMfAJ_zI4wl:-KvWHDKoXiMfAJ_zI4wm:b-55pbuz) ([raw file](https://github.com/netsec-ethz/scion/blob/378e5c5b614c52952c5c47666fd072f5b28809bd/go/sig/ingress/worker.go#L78)):*
https://golang.org/pkg/time/#Tick:
> While Tick is useful for clients that have no need to shut down the Ticker, be aware that without a way to shut it down the underlying Ticker cannot be recovered by the garbage collector; it "leaks".

This becomes a problem when you have a large number of workers starting/stopping.

As there is no other channel to select on, this can simply use the same cleanup-timeout logic as the Dispatcher.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1264)*

**Comment by shitz** [comment]
Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/sig/ingress/dispatcher.go, line 44 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvWF_CFDWe9_36anMYg:-KvWUgOwQCLDQ1rLJWPl:b-1jeiq5) ([raw file](https://github.com/netsec-ethz/scion/blob/378e5c5b614c52952c5c47666fd072f5b28809bd/go/sig/ingress/dispatcher.go#L44)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These 3 can probably all be unexported, they should only be needed inside this module.
</blockquote></details>

Done. Also unexported a couple of other vars/methods.

---

*[go/sig/ingress/worker.go, line 68 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvRp4N2ZRDGHOrstVK-:-KvWWkzEWE6f8Qu9ZSmn:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/63b47c931326c1991ae29b542178df45dd788b8e/go/sig/ingress/worker.go#L68)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Looking at where this is called from (`cleanup()`), waiting for worker to stop seems unnecessary, in which case this can be reduced to just `w.Ring.Close()`. It means that cleanup doesn't need to spawn a goroutine for each stopping worker, either.
</blockquote></details>

Done.

---

*[go/sig/ingress/worker.go, line 78 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-KvWHDKoXiMfAJ_zI4wl:-KvWWnKyZsVh7C_pM9gE:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/378e5c5b614c52952c5c47666fd072f5b28809bd/go/sig/ingress/worker.go#L78)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

https://golang.org/pkg/time/#Tick:
> While Tick is useful for clients that have no need to shut down the Ticker, be aware that without a way to shut it down the underlying Ticker cannot be recovered by the garbage collector; it "leaks".

This becomes a problem when you have a large number of workers starting/stopping.

As there is no other channel to select on, this can simply use the same cleanup-timeout logic as the Dispatcher.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1264)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 10 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1264#-:-KvWXqhwJB4e9VvP4sPI:bnfp4nl)*

**Pull request merged**
