### PR TITLE
Add a dedicated int type for ISD-AS, and use it everywhere.

### PR DESCRIPTION
**Pull request by kormat**
Also:
- Add some range-checking for parsing ISD-AS from a string.
- Re-flow a lot of go/lib/pathmgr/apppath_test.go

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1269)

### CODE REVIEW

**Comment by scrye** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/lib/addr/isdas.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgaN3yl0UonEglzWHz:-KvgaN3yl0UonEglzWI-:b-v2c6dt) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L31)):*
> ```Go
> )
> 
> type ISD_AS struct {
> ```

Since we're here, this name doesn't follow normal Go naming conventions. Is this the right time to change this to just `IA`?

---

*[go/lib/addr/isdas.go, line 40 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgbCH4FgPYxqPg8UAk:-KvgbCH4FgPYxqPg8UAl:bu3x3n8) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L40)):*
> ```Go
> )
> 
> func IAFromRaw(b common.RawBytes) *ISD_AS {
> ```

This probably needs to account for errors during parsing.

---

*[go/lib/addr/isdas.go, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgapIH--dxLSyJNICZ:-KvgapIH--dxLSyJNIC_:by6g23t) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L73)):*
> ```Go
> 
> func (ia *ISD_AS) Parse(b common.RawBytes) {
> 	newIA := IAInt(common.Order.Uint32(b)).IA()
> ```

Parsing can silently fail here, see https://golang.org/pkg/encoding/binary/#Uvarint

---

*[go/lib/addr/isdas.go, line 103 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgaAYO5BNCL4IDOSDH:-KvgaAYPSrOHTep16Guc:b-yd0z7u) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L103)):*
> ```Go
> type IAInt uint32
> 
> func (iaI IAInt) IA() *ISD_AS {
> ```

Receiver name can probably be just `i` here, the method is so small that it shouldn't cause any confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1269)*

**Comment by kormat** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/lib/addr/isdas.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgaN3yl0UonEglzWHz:-KvggklC4tnVj3QXWwx6:b-6g4i65) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L31)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Since we're here, this name doesn't follow normal Go naming conventions. Is this the right time to change this to just `IA`?
</blockquote></details>

I _definitely_ don't want to do that in this PR ;) `IA` is also a bit opaque, for probably the most used type in SCION. We _could_ consider `IsdAs`.

---

*[go/lib/addr/isdas.go, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgapIH--dxLSyJNICZ:-KvggVpMThxBiEfbXkev:b-2me0sk) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L73)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Parsing can silently fail here, see https://golang.org/pkg/encoding/binary/#Uvarint
</blockquote></details>

We're not using varint. See https://developers.google.com/protocol-buffers/docs/encoding for what a varint is.

---

*[go/lib/addr/isdas.go, line 103 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgaAYO5BNCL4IDOSDH:-Kvgg_3YAQ4ixysDXmwt:bvlmg7z) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L103)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Receiver name can probably be just `i` here, the method is so small that it shouldn't cause any confusion.
</blockquote></details>

I dislike using `i`/`j` etc for receiver names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1269)*

**Comment by scrye** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/lib/addr/isdas.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgaN3yl0UonEglzWHz:-KvghxNMUBdj48JKaBRM:b-n6w4aj) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L31)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I _definitely_ don't want to do that in this PR ;) `IA` is also a bit opaque, for probably the most used type in SCION. We _could_ consider `IsdAs`.
</blockquote></details>

Well, we're already involuntarily using it that way in a lot of places (e.g., `ErrorIAUnpack` and `IAInt.IA()`). For something that has become so universally used during discussions and coding, I feel like `common.IA` is straightforward enough.

---

*[go/lib/addr/isdas.go, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgapIH--dxLSyJNICZ:-Kvgit6o-m-yoUuTGHkB:bkh0ltf) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L73)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

We're not using varint. See https://developers.google.com/protocol-buffers/docs/encoding for what a varint is.
</blockquote></details>

Ah, you're right. I somehow thought that it's doing the same thing behind the scenes, but by looking at the code it's just some bitwise arithmetic that can panic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1269)*

**Comment by scrye** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/addr/isdas.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1269#-KvgaN3yl0UonEglzWHz:-KvgkCvQ4bmhO4Stbufl:bxxxkkw) ([raw file](https://github.com/netsec-ethz/scion/blob/5f0b8b5d2a2fba518bf0705b87ce292e463e8b1e/go/lib/addr/isdas.go#L31)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Well, we're already involuntarily using it that way in a lot of places (e.g., `ErrorIAUnpack` and `IAInt.IA()`). For something that has become so universally used during discussions and coding, I feel like `common.IA` is straightforward enough.
</blockquote></details>

Also, re: not doing this now, I agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1269)*

**Pull request merged**
