### PR TITLE
SCMP echo capability

### PR DESCRIPTION
**Pull request by Oncilla**
-Fix dispatcher crashing on SCMP echo request
-Add mapping SCMP echo request -> socket

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1128)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[c/dispatcher/dispatcher.c, line 925 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1128#-KmzYX2Bcpa9dM30MmvR:-KmzYX2Bcpa9dM30MmvS:b-53s48b) ([raw file](https://github.com/netsec-ethz/scion/blob/b67269625f36c8b3ce54db1df04a1e35630e9bb8/c/dispatcher/dispatcher.c#L925)):*
> ```C
>         send_dp_header(e->sock, from, len);
>         send_all(e->sock, buf, len);
>         zlog_debug(zc, "SCMP echo reply (%d-%d) entry found", info[0], info[1]);
> ```

The id/seq numbers are in network order, and should be converted to local byte order for logging.

---

*[c/dispatcher/dispatcher.c, line 1004 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1128#-KmzZeFRMLwcpH2o7rLR:-KmzZeFRMLwcpH2o7rLS:bymekmu) ([raw file](https://github.com/netsec-ethz/scion/blob/b67269625f36c8b3ce54db1df04a1e35630e9bb8/c/dispatcher/dispatcher.c#L1004)):*
> ```C
>         }else {
>             e = ping_list;
>             HASH_DELETE(hh, ping_list, e);
> ```

Rather than this, add a loop to `cleanup_socket` to find any ping entries with the same sock fd. That makes this particular case an error, as there are `MAX_NUMBER_PINGS` programs sending SCMP echos.

---

*[c/dispatcher/dispatcher.c, line 1010 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1128#-KmzZJrdEF6wYph2DWSo:-KmzZJrdEF6wYph2DWSp:b8w4krx) ([raw file](https://github.com/netsec-ethz/scion/blob/b67269625f36c8b3ce54db1df04a1e35630e9bb8/c/dispatcher/dispatcher.c#L1010)):*
> ```C
>         e->sock = sock;
>         HASH_ADD(hh, ping_list, id, sizeof(uint16_t), e);
>     }
> ```

Log an error if the entry already exists, but has a different sock fd.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1128)*

**Comment by Oncilla** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[c/dispatcher/dispatcher.c, line 925 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1128#-KmzYX2Bcpa9dM30MmvR:-Kn0E8uwwFeAxm0rO1ZH:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/b67269625f36c8b3ce54db1df04a1e35630e9bb8/c/dispatcher/dispatcher.c#L925)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The id/seq numbers are in network order, and should be converted to local byte order for logging.
</blockquote></details>

Done.

---

*[c/dispatcher/dispatcher.c, line 1004 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1128#-KmzZeFRMLwcpH2o7rLR:-Kn0IEJQJRCfT_zFqnV9:b9n3oow) ([raw file](https://github.com/netsec-ethz/scion/blob/b67269625f36c8b3ce54db1df04a1e35630e9bb8/c/dispatcher/dispatcher.c#L1004)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Rather than this, add a loop to `cleanup_socket` to find any ping entries with the same sock fd. That makes this particular case an error, as there are `MAX_NUMBER_PINGS` programs sending SCMP echos.
</blockquote></details>

That will potentially limit the number of SCMP echo requests to 1 per socket. Can a socket really only have one SCMP echo id ?

---

*[c/dispatcher/dispatcher.c, line 1010 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1128#-KmzZJrdEF6wYph2DWSo:-Kn0If6JpFgpDX4VVagL:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/b67269625f36c8b3ce54db1df04a1e35630e9bb8/c/dispatcher/dispatcher.c#L1010)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Log an error if the entry already exists, but has a different sock fd.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1128)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[c/dispatcher/dispatcher.c, line 1004 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1128#-KmzZeFRMLwcpH2o7rLR:-Kn3V46gA7yQwbGfMGlU:b-vij3gs) ([raw file](https://github.com/netsec-ethz/scion/blob/b67269625f36c8b3ce54db1df04a1e35630e9bb8/c/dispatcher/dispatcher.c#L1004)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

That will potentially limit the number of SCMP echo requests to 1 per socket. Can a socket really only have one SCMP echo id ?
</blockquote></details>

Looking at the source of both the standard `ping` and `fping` utilities, they both use `getpid() & 0xFFFF` as the ICMP echo ID. ping starts at sequence 0 and increments from there, fping uses a different sequence number for each ping sent, all using the same id. A SCION application can do the same - it doesn't need multiple SCMP echo id's, just one is sufficient as it controls the sequence numbers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1128)*

**Comment by Oncilla** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[c/dispatcher/dispatcher.c, line 1004 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1128#-KmzZeFRMLwcpH2o7rLR:-Kn3cLz1a0QgDg1vtaRb:buha151) ([raw file](https://github.com/netsec-ethz/scion/blob/b67269625f36c8b3ce54db1df04a1e35630e9bb8/c/dispatcher/dispatcher.c#L1004)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Looking at the source of both the standard `ping` and `fping` utilities, they both use `getpid() & 0xFFFF` as the ICMP echo ID. ping starts at sequence 0 and increments from there, fping uses a different sequence number for each ping sent, all using the same id. A SCION application can do the same - it doesn't need multiple SCMP echo id's, just one is sufficient as it controls the sequence numbers.
</blockquote></details>

Okay. Thanks for looking into it.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1128)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1128#-:-Kn3cggTbv_pbcseiha8:bnfp4nl)*

**Pull request merged**
