### PR TITLE
Replace deques in path servers with expiring dicts

### LINKED ISSUE #1126: Change CPS propagation queues to expiring dicts
Currently when a non-master CPS gets a down-segment registration (https://github.com/netsec-ethz/scion/blob/8773e206f4529168145edb273f56c90498ad3007/python/path_server/core.py#L110) it adds it to a deque for propagation to other core ASes. But as it is not master, that queue is never serviced, and grows continuously. If we replace this deque with an expiring dict instead, using the pcb ID as the key, this would both remove the unbounded queuing behaviour, as well as remove duplicate propagations.

The deque for propagating core PCBs to the master CPS probably also needs the same treatment, as if the connection to zookeeper breaks, that queue doesn't get cleared either.

### PR DESCRIPTION
**Pull request by shitz**
Replace deques in path servers with expiring dicts to prevent them from growing forever. Fixes #1126.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1133)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[python/path_server/base.py, line 426 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-KmzJsKsG_NhygdYQ-sC:-KmzJsKtLAmR1KvmkpmD:bq67b52) ([raw file](https://github.com/netsec-ethz/scion/blob/19d66db66a8b5d893a22754fac2e3b7cb51c79d0/python/path_server/base.py#L426)):*
> ```Python
>         while container:
>             count += 1
>             _, (type_, pcb) = container.popitem(last=False)
> ```

This isn't thread-safe, add a `try`/`except` to catch `KeyError`.

---

*[python/path_server/base.py, line 479 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-KmzKSkb9l5KtzAI9rDi:-KmzKSkb9l5KtzAI9rDj:b474d6a) ([raw file](https://github.com/netsec-ethz/scion/blob/19d66db66a8b5d893a22754fac2e3b7cb51c79d0/python/path_server/base.py#L479)):*
> ```Python
>         logging.info("Sharing %d revocation(s) via ZK", len(self._revs_to_zk))
>         while self._revs_to_zk:
>             self._zk_write_rev(self._revs_to_zk.popitem(last=False)[1])
> ```

Same here re: thread-safe.

---

*[python/path_server/core.py, line 49 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-KmzKrtqG-zF64GPs8MP:-KmzKrtqG-zF64GPs8MQ:b-h20kfj) ([raw file](https://github.com/netsec-ethz/scion/blob/19d66db66a8b5d893a22754fac2e3b7cb51c79d0/python/path_server/core.py#L49)):*
> ```Python
>         assert self.topology.is_core_as, "This shouldn't be a local PS!"
>         self._master_id = None  # Address of master core Path Server.
>         self._segs_to_master = ExpiringDict(1000, 10)
> ```

What's the reasoning for this ttl value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1133)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[python/path_server/base.py, line 426 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-KmzJsKsG_NhygdYQ-sC:-KmzVVi0xGSBHXlTc-H6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/19d66db66a8b5d893a22754fac2e3b7cb51c79d0/python/path_server/base.py#L426)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This isn't thread-safe, add a `try`/`except` to catch `KeyError`.
</blockquote></details>

Done.

---

*[python/path_server/base.py, line 479 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-KmzKSkb9l5KtzAI9rDi:-KmzVu6ZuUXt8qH3ZHYc:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/19d66db66a8b5d893a22754fac2e3b7cb51c79d0/python/path_server/base.py#L479)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Same here re: thread-safe.
</blockquote></details>

Done.

---

*[python/path_server/core.py, line 49 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-KmzKrtqG-zF64GPs8MP:-KmzW070w6J_iBDgU4Ys:b-tyzizm) ([raw file](https://github.com/netsec-ethz/scion/blob/19d66db66a8b5d893a22754fac2e3b7cb51c79d0/python/path_server/core.py#L49)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

What's the reasoning for this ttl value?
</blockquote></details>

`_segs_to_master` only has to keep around segments as long as it takes to detect a disconnect to ZK and reelect a new master. We discussed offline that this should be in the order of 10s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1133)*

**Comment by shitz** [comment]
[[1] Change CPS propagation queues to expiring dicts](https://trello.com/c/7jGuTIah/24-1-change-cps-propagation-queues-to-expiring-dicts)

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[python/path_server/base.py, line 425 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-Kmz_Ir7UdG0SRVu1Jxq:-Kmz_Ir7UdG0SRVu1Jxr:b-2wxsft) ([raw file](https://github.com/netsec-ethz/scion/blob/be39269ebe3bca640f9dca17104cbba4f644f3e8/python/path_server/base.py#L425)):*
> ```Python
>         pcbs = defaultdict(list)
>         while container:
>             count += 1
> ```

`count` should be moved after the try/except block, just so that it doesn't get out of sync. (It doesn't matter right now, but if this got refactored it could cause problems).

---

*[python/path_server/core.py, line 49 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-KmzKrtqG-zF64GPs8MP:-KmzaG-gTgqucpeCwmRN:b-836gv8) ([raw file](https://github.com/netsec-ethz/scion/blob/19d66db66a8b5d893a22754fac2e3b7cb51c79d0/python/path_server/core.py#L49)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`_segs_to_master` only has to keep around segments as long as it takes to detect a disconnect to ZK and reelect a new master. We discussed offline that this should be in the order of 10s.
</blockquote></details>

Ahh, because `_sync_master` will cover longer outages. Ok :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1133)*

**Comment by shitz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[python/path_server/base.py, line 425 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-Kmz_Ir7UdG0SRVu1Jxq:-KmzdNHE3Qrl8E1eAY4k:boj1qgt) ([raw file](https://github.com/netsec-ethz/scion/blob/be39269ebe3bca640f9dca17104cbba4f644f3e8/python/path_server/base.py#L425)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`count` should be moved after the try/except block, just so that it doesn't get out of sync. (It doesn't matter right now, but if this got refactored it could cause problems).
</blockquote></details>

Good catch. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1133)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1133#-:-Kmziiv_kT0o_dC951xE:bnfp4nl)*

**Pull request merged**
