### PR TITLE
Switch to circleci 2.0

### PR DESCRIPTION
**Pull request by kormat**
Switch to circleci 2.0

This is a major overhaul of how we build and test the code in a CI environment.
The biggest change is that we now supply a docker image (`scion_base`) that is
run directly by circleci. This image contains all the dependencies of the code,
but not the code itself.

One of the big advantages of circle 2.0 is that there is now a way to run
locally using the ~same environment as circleci.com uses; `tools/ci/local`
automates this, using the "local" build target in `.circleci/config.yml` and
the `scion` docker image.

Notes:
- ci 2.0 stops processing as soon as any step exits with a non-zero status. As
  we have multiple independent tests to run, `tools/ci/run` is used to record
  failures for non-critical steps, and `tools/ci/post_check` is run at the end
  to report any failures.
- `deps.sh` has been split up into `env/*`. This allows go/python/etc
  dependencies to be handled completely seperately from each other. The old
  `./deps.sh all` is now `./env/deps`; the old `./deps.sh golang` is now
  `./env/go/deps`, and so on.
- `./docker.sh base` builds `scion_base`, which is used directly by
  circleci.com. It contains all the dependencies, but no code.
- `./docker.sh build` builds `scion`, which is based on `scion_base`, and
  includes the code and some basic setup steps like topology generation. This
  is the image that `./docker.sh run` and local circleci use.
- `docker.sh` no longer uses `--privileged` to run docker. This no longer works
  on circleci.com, and the need for it has been removed by a symlink created in
  `scion_base`. This does however mean that mininet won't run in docker
  directly. See `topology/mininet/README.md` for the workaround.
- `docker/deps_check` is run as part of circleci and the `scion` docker image
  build; it ensures that no dependency changes have happened since `scion_base`
  was built.                                                                                                                                                                                                      

<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1005)
<!-- Reviewable:end -->

### CODE REVIEW

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 30 of 30 files at r1, 3 of 5 files at r2, 2 of 5 files at r3.
Review status: 28 of 34 files reviewed at latest revision, 2 unresolved discussions.

---

*[.circleci/config.yml, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki04e_S22ARwVlJBbe4:-Ki04e_TkmNiNgQOnpxb:b-55pxgz) ([raw file](https://github.com/netsec-ethz/scion/blob/1c8e50fe6929bd6e7aca27588d8a6e96d04190d2/.circleci/config.yml#L2)):*
> ```YAML
> version: 2
> defaults:
> ```

Is `defaults` a namespace CircleCI might collide with in the future? If so, is there a way to make that less likely?

---

*[docker/Dockerfile.base, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki0629wqi1ROe4Z9yaV:-Ki0629xA7yJnZfsrjNd:b-y07i01) ([raw file](https://github.com/netsec-ethz/scion/blob/1c8e50fe6929bd6e7aca27588d8a6e96d04190d2/docker/Dockerfile.base#L59)):*
> ```
> RUN chown -R scion: .
> RUN cd go && govendor sync -v && govendor install ./vendor/...
> RUN tar czf /tmp/build/go_vendor.tar.gz -C go/vendor .
> ```

You can use `caf` instead of `czf`, that way, `tar` will autmagically guess the right compression algorithm from the tarfile extension.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-:-Ki0FeVKXtFJwxhRSWlJ:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 1 of 5 files at r2, 3 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005)*

**Comment by kormat** [comment]
Review status: 29 of 35 files reviewed at latest revision, 2 unresolved discussions.

---

*[.circleci/config.yml, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki04e_S22ARwVlJBbe4:-Ki0K52Fsu4gR0fgxTjg:b1uk1js) ([raw file](https://github.com/netsec-ethz/scion/blob/1c8e50fe6929bd6e7aca27588d8a6e96d04190d2/.circleci/config.yml#L2)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Is `defaults` a namespace CircleCI might collide with in the future? If so, is there a way to make that less likely?
</blockquote></details>

Good point, renamed it to `scion_defaults`. The name isn't referenced anywhere.
I've also moved it to the end, as i think it reads better that way.

---

*[docker/Dockerfile.base, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki0629wqi1ROe4Z9yaV:-Ki0KKkiksXEFeRL3gqO:b-5e0wtc) ([raw file](https://github.com/netsec-ethz/scion/blob/1c8e50fe6929bd6e7aca27588d8a6e96d04190d2/docker/Dockerfile.base#L59)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

You can use `caf` instead of `czf`, that way, `tar` will autmagically guess the right compression algorithm from the tarfile extension.
</blockquote></details>

Done. Here and elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005)*

**Comment by klausman** [comment]
Reviewed 15 of 17 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/ci/build_prep, line 3 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki4yObxXO974Wyn4GbX:-Ki4yOby5u9TTnYR88AZ:bhprmwc) ([raw file](https://github.com/netsec-ethz/scion/blob/d426e11ddf8eb205d6214d04481ecaf20872140c/tools/ci/build_prep#L3)):*
> ```
> #!/bin/bash
> 
> set -x
> ```

Should this maybe also use -e? Or selective `||exit -`? Same for the other driver scripts.

---

*[tools/ci/env_setup, line 3 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki4zn_Twit62FeYq6YQ:-Ki4zn_Twit62FeYq6YR:b-q0a7fz) ([raw file](https://github.com/netsec-ethz/scion/blob/d426e11ddf8eb205d6214d04481ecaf20872140c/tools/ci/env_setup#L3)):*
> ```
> #!/bin/bash
> 
> echo '
> ```

Where is the closing `'` for this?

---

*[tools/ci/local, line 3 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki5-2YXBqWUrmvV6FaP:-Ki5-2YXBqWUrmvV6FaQ:b-gb93x5) ([raw file](https://github.com/netsec-ethz/scion/blob/d426e11ddf8eb205d6214d04481ecaf20872140c/tools/ci/local#L3)):*
> ```
> #!/bin/bash
> 
> TOOL=circleci
> ```

I'm not quite sure making this a variable is all that useful, especially since lines 11 and 16 below do not use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005)*

**Comment by klausman** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/ci/build_prep, line 3 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki4yObxXO974Wyn4GbX:-Ki53_odFaZaf7GhPsJ2:b-erm39d) ([raw file](https://github.com/netsec-ethz/scion/blob/d426e11ddf8eb205d6214d04481ecaf20872140c/tools/ci/build_prep#L3)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Should this maybe also use -e? Or selective `||exit -`? Same for the other driver scripts.
</blockquote></details>

* `exit -1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005)*

**Comment by kormat** [comment]
Review status: 37 of 39 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/ci/build_prep, line 3 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki4yObxXO974Wyn4GbX:-Ki5LV-znO_fwBDKHRiA:b-m67hft) ([raw file](https://github.com/netsec-ethz/scion/blob/d426e11ddf8eb205d6214d04481ecaf20872140c/tools/ci/build_prep#L3)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

* `exit -1`
</blockquote></details>

These are all run by circleci using `bash -eo pipeline`. This is why, eg, `tools/ci/run` has `set +e` at the top.

---

*[tools/ci/env_setup, line 3 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki4zn_Twit62FeYq6YQ:-Ki5LbuxhmIuJzoDoswq:bhbr7ue) ([raw file](https://github.com/netsec-ethz/scion/blob/d426e11ddf8eb205d6214d04481ecaf20872140c/tools/ci/env_setup#L3)):*
4 lines below:

> export PATH="$GOBIN:$HOME/.local/bin:$PATH"' >> ~/.profile

I'll add a newline after that line to make it a bit more obvious.

---

*[tools/ci/local, line 3 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki5-2YXBqWUrmvV6FaP:-Ki5MIaZsDjZq5XI93NX:b-k3gddc) ([raw file](https://github.com/netsec-ethz/scion/blob/d426e11ddf8eb205d6214d04481ecaf20872140c/tools/ci/local#L3)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

I'm not quite sure making this a variable is all that useful, especially since lines 11 and 16 below do not use it.
</blockquote></details>

The only real reason i added it is to that the string we look for in the path is the same we report in the error. I've updated to use it consistently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005)*

**Comment by shitz** [comment]
Good stuff @kormat. I'm not really knowledgeable enough about bash, circle-ci, and docker to add meaningful comments to the review.

---

Review status: 36 of 39 files reviewed at latest revision, 4 unresolved discussions.

---

*[docker/Dockerfile, line 1 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki5N5Bn4qyVVrxkkhsJ:-Ki5N5Bn4qyVVrxkkhsK:b-7y2frz) ([raw file](https://github.com/netsec-ethz/scion/blob/d426e11ddf8eb205d6214d04481ecaf20872140c/docker/Dockerfile#L1)):*
> ```Dockerfile
> FROM scion_base:latest
> ```

Out of curiosity, why do you split the docker images into `scion_base` and `scion`? Is it because circle-ci always rebuilds the docker image without using caches?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-:-Ki5NhlsRUDZILAZQ5GG:b-u6yqqc)*

**Comment by klausman** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/ci/env_setup, line 8 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki5dDXdKhljeDh-l07Q:-Ki5dDXdKhljeDh-l07R:b2hhm1o) ([raw file](https://github.com/netsec-ethz/scion/blob/da4ccf1f59e90c8b824de65f92c8d0734fa2efab/tools/ci/env_setup#L8)):*
> ```
> export GOBIN="$GOPATH/bin"
> export PATH="$GOBIN:$HOME/.local/bin:$PATH"' >> ~/.profile
> ```

Entirely optional: you have a comment at the top ("Added by circleci"), would it be useful to have an ending marker, too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-:-Ki5dY_ubJuUhXDP6KAv:bnfp4nl)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docker/Dockerfile, line 1 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki5N5Bn4qyVVrxkkhsJ:-Ki5eTHoyDHU1ar85A2u:bna6jgc) ([raw file](https://github.com/netsec-ethz/scion/blob/d426e11ddf8eb205d6214d04481ecaf20872140c/docker/Dockerfile#L1)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Out of curiosity, why do you split the docker images into `scion_base` and `scion`? Is it because circle-ci always rebuilds the docker image without using caches?
</blockquote></details>

Circleci no longer builds any docker images. It downloads `kormat/scion_base`, and runs everything inside that. `scion_base` changes (relatively) very rarely, and contains no code. This means that it caches very well. circleci then checks out our code into it, and runs the tests using that. The `scion` image is now only used for local testing.

---

*[tools/ci/env_setup, line 8 at r6](https://reviewable.io:443/reviews/netsec-ethz/scion/1005#-Ki5dDXdKhljeDh-l07Q:-Ki5eOnh7EYKZ_35pvgk:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/da4ccf1f59e90c8b824de65f92c8d0734fa2efab/tools/ci/env_setup#L8)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Entirely optional: you have a comment at the top ("Added by circleci"), would it be useful to have an ending marker, too?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1005)*

**Pull request merged**
