### PR TITLE
Added SCION packet creation function for Go end-hosts

### PR DESCRIPTION
**Pull request by scrye**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1220)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/lib/hpkt/hpkt.go, line 144 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfJXrYOl3GZk634TKd:-KrfJXrYOl3GZk634TKe:bptxep3) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L144)):*
> ```Go
> 	}
> 
> 	// Create the packet using initial IF/HF pointers
> ```

The supplied `Path` struct should already have those initialized. Also, the Path can be `nil` (e.g. for intra-AS packets, and beacons, etc).

---

*[go/lib/hpkt/hpkt.go, line 150 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfJ8rfqtDHiSj5payq:-KrfJ8rfqtDHiSj5payr:b7k9r4t) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L150)):*
> ```Go
> 	}
> 
> 	// Common Header
> ```

(As discussed) ScnPkt shouldn't have a CmnHdr field.

---

*[go/lib/hpkt/hpkt.go, line 151 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfGwfOkhU2ig7vkMBC:-KrfGwfPnqnw1c8vQH3H:b13nqqb) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L151)):*
> ```Go
> 
> 	// Common Header
> 	s.CmnHdr.Ver = 0
> ```

`spkt.SCIONVersion`

---

*[go/lib/hpkt/hpkt.go, line 180 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfKyCwPOaLIsIJ40eB:-KrfKyCwPOaLIsIJ40eC:b-x96ps2) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L180)):*
> ```Go
> 	// SCION/UDP Header
> 	l4Slice := b[offset : offset+s.L4.L4Len()]
> 	if s.L4.L4Type() != common.L4UDP {
> ```

Duplicate check, it's done at the top of the function too. But, why does this matter? So long as s.L4 implements `Payload`, this code shouldn't have to care.

---

*[go/lib/hpkt/hpkt.go, line 193 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfLJtMuTIzHDbsDXd1:-KrfLJtMuTIzHDbsDXd2:bbwoas2) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L193)):*
> ```Go
> 
> 	// L4 checksum
> 	checksum, cerr := l4.CalcCSum(s.L4, addrSlice, pldSlice)
> ```

`l4.SetCSum` exists for setting the checksum. It would be simpler to do something like:
```
// don't write L4 just yet
offset += s.L4.L4Len()

// Payload
pldSlice := b[offset : offset+s.Pld.Len()]
s.Pld.Write(b[offset:])
offset += s.Pld.Len()

s.L4.SetCSum(s.L4, addrSlice, pldSlice)
s.L4.Write(l4Slice)
```
This also avoids hard-coding the checksum offset into the l4 header (or checksum size, for that matter).

---

*[go/lib/hpkt/hpkt.go, line 217 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfWdW0-nmFMH4ovzmf:-KrfWdW0-nmFMH4ovzmg:b-zhp7jz) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L217)):*
> ```Go
> }
> 
> func resetHopIdx(path *spath.Path) (uint8, error) {
> ```

Note to self: not reviewed below here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1220)*

**Comment by scrye** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/lib/hpkt/hpkt.go, line 144 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfJXrYOl3GZk634TKd:-KrjCDDrmDOVb42HaYfb:bdddze5) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L144)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The supplied `Path` struct should already have those initialized. Also, the Path can be `nil` (e.g. for intra-AS packets, and beacons, etc).
</blockquote></details>

Moved path code out of the current PR, it will be included in the upcoming `SCIONConn` PR.

Also Done Re:nil path.

---

*[go/lib/hpkt/hpkt.go, line 150 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfJ8rfqtDHiSj5payq:-KrjDHQglbi2a1O7kks_:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L150)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

(As discussed) ScnPkt shouldn't have a CmnHdr field.
</blockquote></details>

Done.

---

*[go/lib/hpkt/hpkt.go, line 151 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfGwfOkhU2ig7vkMBC:-KrjDykYzQ_nKkUCo_Y3:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L151)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`spkt.SCIONVersion`
</blockquote></details>

Done.

---

*[go/lib/hpkt/hpkt.go, line 193 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfLJtMuTIzHDbsDXd1:-KrjF4rvEw_ww7RlJEwE:b60bcn8) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L193)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`l4.SetCSum` exists for setting the checksum. It would be simpler to do something like:
```
// don't write L4 just yet
offset += s.L4.L4Len()

// Payload
pldSlice := b[offset : offset+s.Pld.Len()]
s.Pld.Write(b[offset:])
offset += s.Pld.Len()

s.L4.SetCSum(s.L4, addrSlice, pldSlice)
s.L4.Write(l4Slice)
```
This also avoids hard-coding the checksum offset into the l4 header (or checksum size, for that matter).
</blockquote></details>

Good point, refactored the code using your suggestion.

---

*[go/lib/hpkt/hpkt.go, line 217 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfWdW0-nmFMH4ovzmf:-KrjF7QFFwWXQ6psuOjl:b-g4s739) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L217)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Note to self: not reviewed below here.
</blockquote></details>

Code removed altogether.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1220)*

**Comment by scrye** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/lib/hpkt/hpkt.go, line 180 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfKyCwPOaLIsIJ40eB:-KrjHdW4OIqQx7D3GiyE:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L180)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Duplicate check, it's done at the top of the function too. But, why does this matter? So long as s.L4 implements `Payload`, this code shouldn't have to care.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1220)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[go/lib/hpkt/hpkt.go, line 150 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfJ8rfqtDHiSj5payq:-KrjySvcAWhlrmszQdBY:b8rmfaa) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L150)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well, i note that `ScnPkt` struct still has a `CmnHdr` field. I see that the current sig code relies on that heavily, so i assume you will remove it in a later PR. Could you add a fixme to that field saying it should be removed? Just so we don't forget it (too easily).

---

*[go/lib/hpkt/hpkt.go, line 217 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfWdW0-nmFMH4ovzmf:-Krjzp9NPl8KPzuF0Hao:b34xcct) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L217)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Code removed altogether.
</blockquote></details>

Reviewing efficiency win! ;)

---

*[go/lib/hpkt/hpkt.go, line 150 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrjyodbZHijM4_dKyZ0:-KrjyodbZHijM4_dKyZ1:b-qd4qfo) ([raw file](https://github.com/netsec-ethz/scion/blob/658303e0e287c6089b564d7e7d5e635a799b99bd/go/lib/hpkt/hpkt.go#L150)):*
> ```Go
> 	cmnHdr.HdrLen = uint8(scionHdrLen / common.LineLen)
> 	baseIdx := (spkt.CmnHdrLen + addrHdrLen) / common.LineLen
> 	cmnHdr.CurrInfoF = uint8(baseIdx + s.Path.InfOff)
> ```

If there is no path header, both `CurrInfoF` and `CurrHopF` should be 0. If you look at `rpkt/create.go:RtrPktFromScnPkt`, you'll see that these fields aren't touched if there is no path.

---

*[go/lib/hpkt/hpkt.go, line 152 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrjzIG625EpyK1Fo6gc:-KrjzIG625EpyK1Fo6gd:bkq3g0j) ([raw file](https://github.com/netsec-ethz/scion/blob/658303e0e287c6089b564d7e7d5e635a799b99bd/go/lib/hpkt/hpkt.go#L152)):*
> ```Go
> 	cmnHdr.CurrInfoF = uint8(baseIdx + s.Path.InfOff)
> 	cmnHdr.CurrHopF = uint8(baseIdx + s.Path.HopOff)
> 	cmnHdr.NextHdr = common.L4UDP
> ```

`cmnHdr.NextHDr = s.L4.L4Type()`

---

*[go/lib/hpkt/hpkt.go, line 170 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrjzViFeCEm7FsTa-RP:-KrjzViGchFckOHkSYNF:b-evz10o) ([raw file](https://github.com/netsec-ethz/scion/blob/658303e0e287c6089b564d7e7d5e635a799b99bd/go/lib/hpkt/hpkt.go#L170)):*
> ```Go
> 
> 	// Forwarding Path
> 	if s.Path.Raw != nil {
> ```

If there is no path, then `s.Path` would be `nil`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1220)*

**Comment by scrye** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/lib/hpkt/hpkt.go, line 150 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrfJ8rfqtDHiSj5payq:-Krk091cbUSaFLNDwbtZ:bx04m8p) ([raw file](https://github.com/netsec-ethz/scion/blob/15d0c53c0e229562204ac0a25e899b99db60764c/go/lib/hpkt/hpkt.go#L150)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Well, i note that `ScnPkt` struct still has a `CmnHdr` field. I see that the current sig code relies on that heavily, so i assume you will remove it in a later PR. Could you add a fixme to that field saying it should be removed? Just so we don't forget it (too easily).
</blockquote></details>

Correct, I noticed the exact same issue hence the previous commit. Added the FIXME.

---

*[go/lib/hpkt/hpkt.go, line 150 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrjyodbZHijM4_dKyZ0:-Krk1dFzPMF3gvrQrOHQ:b-5c3kxn) ([raw file](https://github.com/netsec-ethz/scion/blob/658303e0e287c6089b564d7e7d5e635a799b99bd/go/lib/hpkt/hpkt.go#L150)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

If there is no path header, both `CurrInfoF` and `CurrHopF` should be 0. If you look at `rpkt/create.go:RtrPktFromScnPkt`, you'll see that these fields aren't touched if there is no path.
</blockquote></details>

Done. Also fixed values in `spath.Path` to be treated as multiples of 8.

---

*[go/lib/hpkt/hpkt.go, line 152 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrjzIG625EpyK1Fo6gc:-Krk2-UPVR7HSgJMODk6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/658303e0e287c6089b564d7e7d5e635a799b99bd/go/lib/hpkt/hpkt.go#L152)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`cmnHdr.NextHDr = s.L4.L4Type()`
</blockquote></details>

Done.

---

*[go/lib/hpkt/hpkt.go, line 170 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-KrjzViFeCEm7FsTa-RP:-Krk20dG5S7RA1iwmJAZ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/658303e0e287c6089b564d7e7d5e635a799b99bd/go/lib/hpkt/hpkt.go#L170)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

If there is no path, then `s.Path` would be `nil`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1220)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1220#-:-KrkCzyDLyoct4AJQXx5:bnfp4nl)*

**Pull request merged**
