### PR TITLE
Basic SCMP support for go router.

### PR DESCRIPTION
**Pull request by kormat**
- Parse SCMP header, payload, calculate checksum.
- Handle SCMP revocation messages (i.e. extract rev token, and send to
  local BS/PS services).

Also:
- Change how extension handlers are initialized - some of them now get
  the packet object passed into them.
- In packet.Payload(), don't get the l4 header unless payload hooks are
  registered.
- Use zerod udp checksum field when calculating udp checksum.
- Allow any SVC address to be used multicast.
- Some work on scmp_echo_test.py / dispatcher.c. Sending the ping works,
  but currently can't route the reply back to the sending application.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/904)

### CODE REVIEW

**Comment by kormat** [comment]
@pszalach @klausman

**Comment by klausman** [comment]
Mostly nits but one possible breakage (method/function name typo).

---

Reviewed 20 of 22 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[endhost/dispatcher.c, line 879 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5lCinDOIz05Rsh1c6:-KS5lCioFi-LDF3GFkb8:baof5mh) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/endhost/dispatcher.c#L879)):*
> ```C
>             send_scmp_echo_reply(buf, scmp, from);
>             return;
>         } /*else if (ntohs(scmp->type) == SCMP_ECHO_REPLY) {
> ```

If this is not implemented yet, annotate it as such.

---

*[go/border/revinfo.go, line 80 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5ltEzetqTm6MzayCi:-KS5ltEzetqTm6MzayCj:b75t8fl) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/go/border/revinfo.go#L80)):*
> ```Go
> 		addr.HostFromIP(srcAddr.IP), conf.C.IA, dstHost)
> 	if err != nil {
> 		log.Error("Error creating RevInfo packet", err.Ctx...)
> ```

Should we really just carry on here? Or is this missing a `return`?

---

*[go/border/revinfo.go, line 92 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5m3xOsvwhEaEIRl7c:-KS5m3xOsvwhEaEIRl7d:b-gmp1bu) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/go/border/revinfo.go#L92)):*
> ```Go
> 	_, err = pkt.RouteResolveSVCMulti(*dstHost.(*addr.HostSVC), r.locOutFs[0])
> 	if err != nil {
> 		log.Error("Unable to route RevInfo packet", err.Ctx...)
> ```

Again, missing `return`?

---

*[go/border/scmp/info.go, line 20 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5o290CT4kETvgEAwA:-KS5o290CT4kETvgEAwB:b-n8mdyl) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/go/border/scmp/info.go#L20)):*
> ```Go
> 	"fmt"
> 
> 	//log "github.com/inconshreveable/log15"
> ```

Consider dropping this.

---

*[go/border/scmp/pld.go, line 90 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5pF_gSEQiA58ZgeBo:-KS5pF_gSEQiA58ZgeBp:b-1vu470) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/go/border/scmp/pld.go#L90)):*
> ```Go
> 			return err
> 		}
> 		/*
> ```

Add "not implemented" comment.

---

*[go/border/scmp/scmp.go, line 20 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5pUUmzC8mOkhaph_s:-KS5pUUmzC8mOkhaph_t:b-894hjp) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/go/border/scmp/scmp.go#L20)):*
> ```Go
> 	"encoding/binary"
> 	"fmt"
> 	//log "github.com/inconshreveable/log15"
> ```

Drop?

---

*[lib/packet/host_addr.py, line 179 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5prgK-nYbU8Wz51Xa:-KS5prgK-nYbU8Wz51Xb:bwzg88b) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/lib/packet/host_addr.py#L179)):*
> ```Python
>         return self.addr & self.MCAST
> 
>     def muilticast(self):
> ```

Typo: s/muilticast/multicast/g

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-:-KS5qEhp8rhv3sRa5k5V:bo2yl29)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[endhost/dispatcher.c, line 879 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5lCinDOIz05Rsh1c6:-KS5rn2kcHr63b2wnOYs:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/endhost/dispatcher.c#L879)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> If this is not implemented yet, annotate it as such.
</details>
Done.

---

*[go/border/revinfo.go, line 80 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5ltEzetqTm6MzayCi:-KS5ru_rj-2rtPKt6V8o:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/go/border/revinfo.go#L80)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> Should we really just carry on here? Or is this missing a `return`?
</details>
Done.

---

*[go/border/revinfo.go, line 92 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5m3xOsvwhEaEIRl7c:-KS5rusuA6nffnGiatN4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/go/border/revinfo.go#L92)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> Again, missing `return`?
</details>
Done.

---

*[go/border/scmp/info.go, line 20 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5o290CT4kETvgEAwA:-KS5rwiFD3RR0IGYdswq:b-z8sict) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/go/border/scmp/info.go#L20)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> Consider dropping this.
</details>
It gets commented in/out constantly during development, as Go doesn't allow unused imports.

---

*[go/border/scmp/pld.go, line 90 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5pF_gSEQiA58ZgeBo:-KS5sGAEZCJAcsXztC0a:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/go/border/scmp/pld.go#L90)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> Add "not implemented" comment.
</details>
Done.

---

*[lib/packet/host_addr.py, line 179 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-KS5prgK-nYbU8Wz51Xa:-KS5sMyjw_4eXQ5Vxzz0:bxudj1x) ([raw file](https://github.com/netsec-ethz/scion/blob/79efd971e593fa39d19c0a80b251649170091755/lib/packet/host_addr.py#L179)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary>
> Typo: s/muilticast/multicast/g
</details>
Oops. Fixed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/904)*

**Comment by klausman** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/904)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-:-KS5u0eAUBV2a3qK1mqM:bnfp4nl)*

**Comment by pszalach** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/904#-:-KS67acFgTBTKqbDiRNi:bnfp4nl)*

**Pull request merged**
