### PR TITLE
TCP pipe mode

### PR DESCRIPTION
**Pull request by pszalach**
- WiP PR for TCP pipe mode. With optimal polling timeout it is ~30% faster than RPC-based send()/recv()
- It is not integrated with the infrastructure yet.
- Improved a bit TCP integration test.

`tcpmw_pipe_loop()` is entered after a successful a) `connect()` , or b) `accept()`. Otherwise socket is in the RPC mode.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/909)

### CODE REVIEW

**Comment by pszalach** [comment]
@klausman

**Comment by klausman** [comment]
One cosmetic nit.  Also, I'd very much like to have Stephen give this a once-over when he is back, since he is much mire familiar with the two different modes (and the existing code).

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/tcp/socket.py, line 146 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/909#-KSqKxG2rwzIW3CRMgRb:-KSqKxG2rwzIW3CRMgRc:b1opxj9) ([raw file](https://github.com/netsec-ethz/scion/blob/95d7b373f56451812179c91a6738da8463f7b1fa/lib/tcp/socket.py#L146)):*
> ```Python
>         self._lwip_accept = None
>         self._lock = threading.Lock()
>         self._cmd_mode = True  # False denotes "pipe mode"
> ```

"cmd" is not a very specific term. Is this meant to mean RPC mode?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/909#-:-KSqLiLWbDxKKzr5N6sG:bx2ijxj)*

**Comment by klausman** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/909)*

**Comment by pszalach** [comment]
Right, rpc mode sounds much better.
I'm sure that @kormat will review that carefully when he is back

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/909#-:-KSqNABAHmdHqy4cKa34:b4b3dup)*

**Comment by klausman** [comment]
Tentative :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/909#-:-KSqNQJzylI4Npxrbkci:b-2kgpr7)*

**Comment by pszalach** [comment]
@kormat FYI: it is waiting for an absolute lgtm ;-)

**Comment by kormat** [comment]
This change looks mostly ok, but misses a few important design points:

- Has one thread per connection on both sides of the local unix socket, instead of (mostly) using select.
- Uses polling for everything.
- Doesn't do any buffering, which hurts efficiency. (E.g. incoming data is written synchronously to the unix socket).

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/909#-:-KTiXsz-2rMwM0-VDYsQ:b-1p2qw3)*

**Comment by pszalach** [comment]
> Reply...
Thanks Stephen. I'll give it another try with select and callbacks as we discussed. Not sure about the buffering comment. Are you worried about callback-based synchronous writing to unix sockets?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/909#-:-KTi_aosfyfUANkKeT4h:bb9sg4i)*

**Comment by kormat** [comment]
Yes, callbacks must not block.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/909#-:-KTisa0pfKIwG6qOZb3X:b19kcql)*

**Pull request merged**
