### PR TITLE
CircleCI + TCP: another test

### PR DESCRIPTION
**Pull request by pszalach**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/912)

### CODE REVIEW

**Comment by pszalach** [comment]
Ready for review.
`SCIONElem` integrated with TCP (pipe mode).
(Although, locally it works well, TCP is still disabled by default as pipe mode doesn't help too much with CircleCI.)

@klausman, ...but it can also wait for Stephen.

**Comment by kormat** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 610 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTiuSfK4I2K5910TSYB:-KTiuSfLRSullcRhTbl7:b-v9bqis) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/infrastructure/scion_elem.py#L610)):*
> ```Python
>                 callback(sock)
>                 self._tcp_socks_update()
>             self._tcp_socks_update()
> ```

Why is this called inside the inner loop as well?

---

*[infrastructure/scion_elem.py, line 665 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTn59-T4LPZ0v97t6uI:-KTn59-UlVlJtxVuWPKc:b-xvjgm2) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/infrastructure/scion_elem.py#L665)):*
> ```Python
>                                 self._tcp_handle_recv)
>             except queue.Empty:
>                 pass
> ```

Why `pass` and not `break`? Changing it to `break` would also simplify the while condition to just `while true`.

---

*[lib/msg_meta.py, line 76 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTnY972dtkxK3C6oEK7:-KTnY973w4WHTuRm59_-:b1sc2pv) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/lib/msg_meta.py#L76)):*
> ```Python
> 
>     def close(self):
>         self.sock.active = False
> ```

Why this change? When does `close()` actually get called?

---

*[lib/socket.py, line 391 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTnZ7px6LkOUDvK2U7U:-KTnZ7px6LkOUDvK2U7V:b-xh8o3c) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/lib/socket.py#L391)):*
> ```Python
>         self._buf = bytearray()
>         self._sock = sock
>         self.sock = None  # Used by the selector.
> ```

This naming is pretty confusing (`_sock` vs `sock`).

---

*[lib/socket.py, line 398 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTnZ_yPKTlLYnZQENAV:-KTnZ_yPKTlLYnZQENAW:b-8bypg3) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/lib/socket.py#L398)):*
> ```Python
>         self._path = path
>         self._lock = threading.RLock()
>         self._last_read = time.time()
> ```

Why does the timeout only consider reads?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/912)*

**Comment by pszalach** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 610 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTiuSfK4I2K5910TSYB:-KVPYXjE9ytuNWUUeOQS:bue3qhq) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/infrastructure/scion_elem.py#L610)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> Why is this called inside the inner loop as well?
</details>
Good catch. Now it is unnecessary. Done.

---

*[infrastructure/scion_elem.py, line 665 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTn59-T4LPZ0v97t6uI:-KVPYwJeTJxzsEwRl6NG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/infrastructure/scion_elem.py#L665)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> Why `pass` and not `break`? Changing it to `break` would also simplify the while condition to just `while true`.
</details>
Done.

---

*[lib/msg_meta.py, line 76 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTnY972dtkxK3C6oEK7:-KVPYxGvXIWU5wnQshrE:b-jizxay) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/lib/msg_meta.py#L76)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> Why this change? When does `close()` actually get called?
</details>
`_tcp_socks_update()` -> `remove_inactive()`

---

*[lib/socket.py, line 391 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTnZ7px6LkOUDvK2U7U:-KVPZWbtp68gxy-aCoR4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/lib/socket.py#L391)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> This naming is pretty confusing (`_sock` vs `sock`).
</details>
Done.

---

*[lib/socket.py, line 398 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-KTnZ_yPKTlLYnZQENAV:-KVP_9aJZfKdwDVw2eCT:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a634f5dd9a3dc4bb45b763902a9e569f21cd3b0f/lib/socket.py#L398)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> Why does the timeout only consider reads?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/912)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/912#-:-KVQU8TeTWFBc-2T3Lbl:bnfp4nl)*

**Pull request merged**
