### PR TITLE
Changed encoding of ISD_AS for various payloads.

### PR DESCRIPTION
**Pull request by shitz**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/919)

### CODE REVIEW

**Comment by kormat** [comment]
Have you actually run this? The only thing that doesn't die on startup for me is the routers. Looks like it's the same on circleci.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[lib/packet/packet_base.py, line 62 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUQx6_joTpaJYCZLNKp:-KUQx6_joTpaJYCZLNKq:b-132oll) ([raw file](https://github.com/netsec-ethz/scion/blob/b2ddad56b5da3c53942bd81c7b576548af9c1cd7/lib/packet/packet_base.py#L62)):*
> ```Python
> class Cerealizable(object, metaclass=ABCMeta):
>     # P = capnp.load("proto/foo.capnp")
>     # P_CLS = P.Foo
> ```

Those were there as examples, demonstrating the expected/required class attributes.

---

*[lib/packet/pcb.py, line 78 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR1EMKXAKSZ-VpUuMO:-KUR1EMLWfddh0EcM-FQ:b-j7f0f9) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L78)):*
> ```Python
> 
>     def short_desc(self):
>         return "%s(%s)->%s(%s)[%s]:\n%s" % (self.inIA(), self.p.inIF,
> ```

This is a bit _too_ terse. I'd suggest renaming the existing `__str__()` method to `short_desc()` (and removing the `self.NAME` from the beginning of it) instead.

---

*[lib/packet/pcb.py, line 159 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR1tOsWOiarCexOMqO:-KUR1tOtxQ5iVCZuQ00h:b-grifq2) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L159)):*
> ```Python
>     def short_desc(self):
>         desc = []
>         desc.append("%s (trc=v%s, cert=v%s) [%s]" %
> ```

Why the different formattings? `%s TRC: v%s Cert: v%s AS MTU: %s`? At least that way it's consistent with the normal style.

---

*[lib/packet/pcb.py, line 161 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR30590r7MyZg7cDi2:-KUR30590r7MyZg7cDi3:b48swp3) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L161)):*
> ```Python
>         desc.append("%s (trc=v%s, cert=v%s) [%s]" %
>                     (self.isd_as(), self.p.trcVer, self.p.certVer, self.p.mtu))
>         for pcb in self.iter_pcbms():
> ```

`pcb` is a terrible name.

---

*[lib/packet/pcb.py, line 162 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR2Iy3rhfqTHUPagtG:-KUR2Iy3rhfqTHUPagtH:b-fk1rh7) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L162)):*
> ```Python
>                     (self.isd_as(), self.p.trcVer, self.p.certVer, self.p.mtu))
>         for pcb in self.iter_pcbms():
>             desc.append(str(pcb))
> ```

This screws up indentation. You need do something like what `PathSegment.__str__()` does:
```
for pcbm in self.iter_pcbms():
  for line in pcbm.short_desc().splitlines():
    desc.append("  %s" % line)
```

---

*[lib/packet/pcb.py, line 163 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR39V0FTF4FFu8Xo92:-KUR39V1sat19t_F1X9e:b-v548ck) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L163)):*
> ```Python
>         for pcb in self.iter_pcbms():
>             desc.append(str(pcb))
>         desc.append("hashTreeRoot=%s" % self.p.hashTreeRoot)
> ```

These 3 all need to be indented. Add two spaces after the opening quote.

---

*[proto/pcb.capnp, line 13 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR5v4wCpvCABSHoZDx:-KUR5v4wCpvCABSHoZDy:b-j5f70e) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/proto/pcb.capnp#L13)):*
> ```
>     inIF @1 :UInt64; # Interface ID on far end of ingress link
>     inMTU @2 :UInt16;  # Ingress Link MTU
>     outIA @3 :UInt64;  # Downstream ISD-AS
> ```

`UInt32`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-:-KUQzSwLsYwo8VoJNKk4:b-t3ak3)*

**Comment by kormat** [comment]
Also please rebase on master.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-:-KUR82cTGRSVhLgwpn02:b-6o0wr)*

**Comment by shitz** [comment]
Review status: 3 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[lib/packet/packet_base.py, line 62 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUQx6_joTpaJYCZLNKp:-KURW9xQ7ivxF6EJKHzl:b-435ngq) ([raw file](https://github.com/netsec-ethz/scion/blob/b2ddad56b5da3c53942bd81c7b576548af9c1cd7/lib/packet/packet_base.py#L62)):*
> # P = capnp.load("proto/foo.capnp")
>     # P_CLS = P.Foo
Not a fan of just putting some example there without context. Added it to the class docstring.

---

*[lib/packet/pcb.py, line 78 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR1EMKXAKSZ-VpUuMO:-KURWictZcHAT30AGrau:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L78)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> This is a bit _too_ terse. I'd suggest renaming the existing `__str__()` method to `short_desc()` (and removing the `self.NAME` from the beginning of it) instead.
</details>
Done.

---

*[lib/packet/pcb.py, line 159 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR1tOsWOiarCexOMqO:-KURWxq1xj0YqAgbeAgA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L159)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> Why the different formattings? `%s TRC: v%s Cert: v%s AS MTU: %s`? At least that way it's consistent with the normal style.
</details>
Done.

---

*[lib/packet/pcb.py, line 162 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR2Iy3rhfqTHUPagtG:-KURXD-bCMfQ7bkldNDS:b-4iwp56) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L162)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> This screws up indentation. You need do something like what `PathSegment.__str__()` does:
> ```
> for pcbm in self.iter_pcbms():
>   for line in pcbm.short_desc().splitlines():
>     desc.append("  %s" % line)
> ```
</details>
changed to `pcbm`

---

*[lib/packet/pcb.py, line 163 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR39V0FTF4FFu8Xo92:-KURXJasy46iZkEFKPXB:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L163)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> These 3 all need to be indented. Add two spaces after the opening quote.
</details>
Done.

---

*[proto/pcb.capnp, line 13 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR5v4wCpvCABSHoZDx:-KURdxcYcS6lFCpPSZLu:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/proto/pcb.capnp#L13)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> `UInt32`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/919)*

**Comment by shitz** [comment]
Review status: 3 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[lib/packet/pcb.py, line 161 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR30590r7MyZg7cDi2:-KURo60UpVM86FtsJ_Mv:b-xqx6wz) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L161)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> `pcb` is a terrible name.
</details>
I'm stupid at this. Changed to `pcbm`.

---

*[lib/packet/pcb.py, line 162 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR2Iy3rhfqTHUPagtG:-KURoAg8viCGAtYX6Hx2:b-ea36ni) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L162)):*
<details><summary><i>Previously, shitz wrote…</i></summary>
> changed to `pcbm`
</details>
Disregard. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/919)*

**Comment by kormat** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lib/packet/pcb.py, line 159 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR1tOsWOiarCexOMqO:-KURwBH0dvWsGQeJw2Zg:b-sqy1j5) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L159)):*
<details><summary><i>Previously, shitz wrote…</i></summary>
> Done.
</details>
I suggested "AS MTU" to make it more distinct from the "Incoming MTU"s in the PCBMs.

---

*[lib/packet/pcb.py, line 162 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR2Iy3rhfqTHUPagtG:-KURxepJYopbM5-t9dyR:b-rxuspq) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L162)):*
<details><summary><i>Previously, shitz wrote…</i></summary>
> Disregard. Done.
</details>
Not done :P

---

*[lib/packet/pcb.py, line 86 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KURvpXQCBwUQ6UiYlJQ:-KURvpXQCBwUQ6UiYlJR:b-6vypt) ([raw file](https://github.com/netsec-ethz/scion/blob/2239eaa63e7c4d33ca4cd50d8194063d9b64da5a/lib/packet/pcb.py#L86)):*
> ```Python
> 
>     def __str__(self):
>         return self.short_desc()
> ```

This is already covered by the base class, `Cerealizable`

---

*[test/lib/packet/scion_addr_test.py, line 78 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KURzY-kS61NgquzoQ8n:-KURzY-kS61NgquzoQ8o:boc468k) ([raw file](https://github.com/netsec-ethz/scion/blob/2239eaa63e7c4d33ca4cd50d8194063d9b64da5a/test/lib/packet/scion_addr_test.py#L78)):*
> ```Python
>         inst = ISD_AS()
>         # Call
>         inst._parse_int(111 << 20 | 22222)
> ```

Testing this with values that prove the bit boundary is correctly handled would be more useful. Something like `0xAAAFFFFF`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/919)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lib/packet/pcb.py, line 159 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR1tOsWOiarCexOMqO:-KUS-ffLXtt6k3t5ojuv:b-6dllkx) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L159)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> I suggested "AS MTU" to make it more distinct from the "Incoming MTU"s in the PCBMs.
</details>
Ah sorry missed that one. Done.

---

*[lib/packet/pcb.py, line 162 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KUR2Iy3rhfqTHUPagtG:-KUS03jlZQ73aU2MBmS2:b-43gj7y) ([raw file](https://github.com/netsec-ethz/scion/blob/3bc4ff7976102be2b83639f747c8a06e98eabb1f/lib/packet/pcb.py#L162)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> Not done :P
</details>
Damn, I'm struggling with Reviewable. Too much eye-candy. Should be done now.

---

*[lib/packet/pcb.py, line 86 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KURvpXQCBwUQ6UiYlJQ:-KUS-V_f3aPNdNatGR0D:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2239eaa63e7c4d33ca4cd50d8194063d9b64da5a/lib/packet/pcb.py#L86)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> This is already covered by the base class, `Cerealizable`
</details>
Done.

---

*[test/lib/packet/scion_addr_test.py, line 78 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-KURzY-kS61NgquzoQ8n:-KUS0PuY-a_w2kCEthr7:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/2239eaa63e7c4d33ca4cd50d8194063d9b64da5a/test/lib/packet/scion_addr_test.py#L78)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> Testing this with values that prove the bit boundary is correctly handled would be more useful. Something like `0xAAAFFFFF`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/919)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/919#-:-KUSHmxXt-RrYhEDJOvD:bnfp4nl)*

**Pull request merged**
