### PR TITLE
Log entries in TRC

### PR DESCRIPTION
**Pull request by sezergueler**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1130)

### CODE REVIEW

**Comment by pszalach** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[python/topology/generator.py, line 53 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-KmfybdPKeE7_b2s4dAJ:-KmfybdPKeE7_b2s4dAK:b-qd5x5e) ([raw file](https://github.com/netsec-ethz/scion/blob/ab3eec56a585e5562bb450260c9ab75016b65e42/python/topology/generator.py#L53)):*
> ```Python
> from lib.crypto.trc import (
>     ADDR_STRING,
>     get_trc_file_path,
> ```

I think this one should be moved at the end

---

*[python/topology/generator.py, line 443 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-Kmfz4kOxZlZUi9TNDQg:-Kmfz4kOxZlZUi9TNDQh:b8f4nkq) ([raw file](https://github.com/netsec-ethz/scion/blob/ab3eec56a585e5562bb450260c9ab75016b65e42/python/topology/generator.py#L443)):*
> ```Python
> 
> 
> class Log_Server_Generator(object):
> ```

don't use underscores in class names

---

*[topology/Default.topo, line 90 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-KmfzJIZDQhnG6Z8qM0U:-KmfzJIZDQhnG6Z8qM0V:b-t37yru) ([raw file](https://github.com/netsec-ethz/scion/blob/ab3eec56a585e5562bb450260c9ab75016b65e42/topology/Default.topo#L90)):*
> ```
>     commonName: CA2-3
> LogServers:
>   Log 1:
> ```

maybe don't use space in log labels

---

*[topology/Default.topo, line 92 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-KmfzWuA98oLm-LGXdO5:-KmfzWuA98oLm-LGXdO6:byjhmvo) ([raw file](https://github.com/netsec-ethz/scion/blob/ab3eec56a585e5562bb450260c9ab75016b65e42/topology/Default.topo#L92)):*
> ```
>   Log 1:
>     ISD: 1
>     addr: 127.0.1.0
> ```

for loopback it is ok, but somehow I don't like when IPs to bind start with `0`s. I'd use just subsequent 127.0.0.1 .2 .3 ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1130)*

**Comment by sezergueler** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[python/topology/generator.py, line 53 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-KmfybdPKeE7_b2s4dAJ:-Kmg2muJadAIz9x30iWk:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ab3eec56a585e5562bb450260c9ab75016b65e42/python/topology/generator.py#L53)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

I think this one should be moved at the end
</blockquote></details>

Done.

---

*[python/topology/generator.py, line 443 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-Kmfz4kOxZlZUi9TNDQg:-Kmg2oMDOm7LhVce17hM:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ab3eec56a585e5562bb450260c9ab75016b65e42/python/topology/generator.py#L443)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

don't use underscores in class names
</blockquote></details>

Done.

---

*[topology/Default.topo, line 90 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-KmfzJIZDQhnG6Z8qM0U:-Kmg2qS1BZs6IU0SrLfb:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ab3eec56a585e5562bb450260c9ab75016b65e42/topology/Default.topo#L90)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

maybe don't use space in log labels
</blockquote></details>

Done.

---

*[topology/Default.topo, line 92 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-KmfzWuA98oLm-LGXdO5:-Kmg2qmWQ3xfR5hgf0E7:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ab3eec56a585e5562bb450260c9ab75016b65e42/topology/Default.topo#L92)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

for loopback it is ok, but somehow I don't like when IPs to bind start with `0`s. I'd use just subsequent 127.0.0.1 .2 .3 ...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1130)*

**Comment by pszalach** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-:-Kmg4bs6Qk3ApYP_MJrw:bnfp4nl)*

**Comment by sezergueler** [comment]
@kormat As discussed I use SubnetGenerator to generate addresses instead of having them hard coded in the topology file. However I am not sure if I am using SubnetGenerator correctly. Can you have a look, please?

**Comment by kormat** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[python/topology/generator.py, line 456 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-Kne9jB7y_ug5nL9xCBs:-Kne9jB8baqaO5i39kPQ:b-m8a48u) ([raw file](https://github.com/netsec-ethz/scion/blob/d1b3efe68c05c62979bd7d791a5b06d444633703/python/topology/generator.py#L456)):*
> ```Python
>         self.log_entries = defaultdict(dict)
>         self.log_private_key_files = defaultdict(dict)
>         self.sng = SubnetGenerator(DEFAULT_NETWORK)
> ```

Given that log servers seem to belong to specific ASes, it's probably best to pass in `subnet_gen` from `ConfigGenerator`, and register the log servers inside that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1130)*

**Comment by kormat** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[python/topology/generator.py, line 456 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1130#-Kne9jB7y_ug5nL9xCBs:-KneB-GKr1A8GodW_9id:bhfaku1) ([raw file](https://github.com/netsec-ethz/scion/blob/d1b3efe68c05c62979bd7d791a5b06d444633703/python/topology/generator.py#L456)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Given that log servers seem to belong to specific ASes, it's probably best to pass in `subnet_gen` from `ConfigGenerator`, and register the log servers inside that.
</blockquote></details>

You'd have something like
```
subnet = self.subnet_gen.register("%s-%s" % (log_config["ISD"], log_config["AS"]))
return subnet.register("log%s-%s-%s" % (log_config["ISD"], log_config["AS"], log_name)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1130)*

**Comment by Oncilla** [comment]
Work continues in PR #1144.

**Pull request closed without merging**
