### PR TITLE
Disallow invalid segment switches.

### PR DESCRIPTION
**Pull request by shitz**
Implemented the checks when switching segments as discussed during the meeting:

1) Never switch from a down-segment to an up-segment (valley-freeness)
2) Never switch from an up(down)-segment to an up(down)-segment, unless we are a core router.
3) Never switch from a core-segment to a core-segment.

Also introduced a dedicated type for link types.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/964)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/main.py, line 542 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXSJD1Zr7SaXX0c6vH:-KcXSJD1Zr7SaXX0c6vI:b-72870z) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L542)):*
> ```Python
>             self.deliver(spkt)
>             return
>         if ingress:
> ```

This is a large block of code in the middle of `_process_data`. Move to a dedicated method?

---

*[infrastructure/router/main.py, line 550 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXf-8pVvDIZSmEdBgv:-KcXf-8pVvDIZSmEdBgw:b-ck4e6f) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L550)):*
> ```Python
>             cur_iof = path.get_iof()
>             if prev_iof != cur_iof:
>                 # If the router switches segment, perform the following checks:
> ```

These rules aren't quite complete (and could be simplified a bit). Here's my current list of rules:

- Cannot fwd from ROUTING to ROUTING, ever.
- Can only switch from up to up if exit is ROUTING.
- Can only switch from down to down if entrance is ROUTING.
- If a VERIFY_ONLY field was skipped, the segment must have changed.
- If a packet is received over a peering link, check that the egress IF is the
  same for both the current and next hop fields.                                                                                                                                                                  

The last one prevents a peer HopF from being spliced into a down-segment.

---

*[infrastructure/router/main.py, line 608 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXR-4nqUs1DlFjcODg:-KcXR-4oH7oLxiVZaUDk:bpazze1) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L608)):*
> ```Python
>         return path.get_fwd_if(), incd
> 
>     def _incoming_if_id(self, path, ingress):
> ```

The name here is unclear. At first read, the assumption would be that it is the ingress if id, but that's not true. We already have `SCIONPath.get_fwd_if`, so how about adding a `get_curr_if` there instead?

---

*[infrastructure/router/main.py, line 620 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXReuEgxfVZdHxGqre:-KcXReuEgxfVZdHxGqrf:b-mevmkz) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L620)):*
> ```Python
> 
>     def _link_type(self, if_id):
>         """Returns to link type of the link corresponding to 'if_id' or None."""
> ```

`s/ to / the /`

---

*[lib/packet/opaque_field.py, line 214 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXfbwvIstlJb-S98jk:-KcXfbwwgbeo1N0FdHia:b2hbc1i) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/lib/packet/opaque_field.py#L214)):*
> ```Python
>         return flags
> 
>     def __eq__(self, other):  # pragma: no cover
> ```

I'm not sure about this. The ISD and timestamp are intrinsic to the identify of an InfoF, but the flags and hops fields aren't, so context matters. You seem to be using it as a proxy to see if the segment has changed - that can be done by comparing the InfoF index before/after (via `SCIONPath.get_of_idxs()`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/main.py, line 550 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXf-8pVvDIZSmEdBgv:-KcXj9oj0riU0BMGwXJV:btinwny) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L550)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These rules aren't quite complete (and could be simplified a bit). Here's my current list of rules:

- Cannot fwd from ROUTING to ROUTING, ever.
- Can only switch from up to up if exit is ROUTING.
- Can only switch from down to down if entrance is ROUTING.
- If a VERIFY_ONLY field was skipped, the segment must have changed.
- If a packet is received over a peering link, check that the egress IF is the
  same for both the current and next hop fields.                                                                                                                                                                  

The last one prevents a peer HopF from being spliced into a down-segment.
</blockquote></details>

One extra missed from that list:
- - If a packet is to be forwarded over a peering link, check on ingress that
  the ingress IF is the same for both current and next hop fields.                                                                                                                                                

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Comment by pszalach** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/main.py, line 550 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXf-8pVvDIZSmEdBgv:-KcXjmENIwrFHHkyMueB:b-cn5y03) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L550)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

One extra missed from that list:
- - If a packet is to be forwarded over a peering link, check on ingress that
  the ingress IF is the same for both current and next hop fields.                                                                                                                                                

</blockquote></details>

can only switch from PEER to DOWN?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/main.py, line 550 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXf-8pVvDIZSmEdBgv:-KcXlLG172KGVmF8Xkbn:b-97pj9f) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L550)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

can only switch from PEER to DOWN?
</blockquote></details>

@pszalach - that restriction doesn't seem to add anything. Anything crossing a peering link has 2 segments, UP and DOWN. Anything else is disallowed by the previous rules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/main.py, line 542 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXSJD1Zr7SaXX0c6vH:-KcY2e_gJ3u3P8b_HxFj:b-ae0j1v) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L542)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is a large block of code in the middle of `_process_data`. Move to a dedicated method?
</blockquote></details>

Moved validating the segment switch to a dedicated method.

---

*[infrastructure/router/main.py, line 550 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXf-8pVvDIZSmEdBgv:-KcYTr05_6pdZHnwrC6U:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L550)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

@pszalach - that restriction doesn't seem to add anything. Anything crossing a peering link has 2 segments, UP and DOWN. Anything else is disallowed by the previous rules.
</blockquote></details>

Done.

---

*[infrastructure/router/main.py, line 608 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXR-4nqUs1DlFjcODg:-KcYFtbLm_LNZIAWeicz:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L608)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The name here is unclear. At first read, the assumption would be that it is the ingress if id, but that's not true. We already have `SCIONPath.get_fwd_if`, so how about adding a `get_curr_if` there instead?
</blockquote></details>

Done.

---

*[infrastructure/router/main.py, line 620 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXReuEgxfVZdHxGqre:-KcYG0TQSqeVe_oikVdF:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/infrastructure/router/main.py#L620)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`s/ to / the /`
</blockquote></details>

Done.

---

*[lib/packet/opaque_field.py, line 214 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcXfbwvIstlJb-S98jk:-KcYK94CUs9wHo8WWR7x:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/226d651c0b17835269cc6de62567be59829c7435/lib/packet/opaque_field.py#L214)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'm not sure about this. The ISD and timestamp are intrinsic to the identify of an InfoF, but the flags and hops fields aren't, so context matters. You seem to be using it as a proxy to see if the segment has changed - that can be done by comparing the InfoF index before/after (via `SCIONPath.get_of_idxs()`).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/main.py, line 589 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcbvplhEHBeogGofmz9:-KcbvplhEHBeogGofmzA:b-slqj2k) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/infrastructure/router/main.py#L589)):*
> ```Python
>            (valley-freeness)
>         2) Never switch from an up(down)-segment to an
>            up(down)-segment, unless we are a core router.
> ```

This isn't formulated correctly. The issue isn't being a core router (as being a core router is insufficient). The issue is the fwding link type. Same issues applies to the error messages used.

---

*[infrastructure/router/main.py, line 591 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcbwI3Yu69-BeS8RuXQ:-KcbwI3Yu69-BeS8RuXR:b-9d80v8) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/infrastructure/router/main.py#L591)):*
> "check on ingress that..."
as the egress hop doesn't inspect the previous HopF.

---

*[infrastructure/router/main.py, line 623 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcbxR6HHWbu4aMWMAiS:-KcbxR6IPaQKR9XtBeqn:bo1letg) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/infrastructure/router/main.py#L623)):*
> ```Python
>                 "HOF.")
>         if (fwd_on_link_type == LinkType.PEER and
>                 prev_hof.ingress_if != cur_hof.ingress_if):
> ```

These are the wrong interfaces.

---

*[lib/packet/path.py, line 263 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KccEwGq5ImUOrIpi7IO:-KccEwGrS9KtXOgwrmTv:bfv6lqh) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/lib/packet/path.py#L263)):*
> ```Python
>             if not hof.verify_only:
>                 break
>             else:
> ```

The `else` is unnecessary.

---

*[lib/packet/path.py, line 288 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KccF0eiURcUjVGggDF1:-KccF0eiURcUjVGggDF2:bfez2fh) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/lib/packet/path.py#L288)):*
> ```Python
>             (False, True): hof.ingress_if,
>             (True, False): hof.ingress_if,
>             (True, True): hof.egress_if
> ```

This can be simplified to:
```
if ingress == iof.up_flag:
  return hof.egress_if
return hof.ingress_if
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/main.py, line 589 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcbvplhEHBeogGofmz9:-KccJ_les_ocDCirwTE1:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/infrastructure/router/main.py#L589)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This isn't formulated correctly. The issue isn't being a core router (as being a core router is insufficient). The issue is the fwding link type. Same issues applies to the error messages used.
</blockquote></details>

Done.

---

*[infrastructure/router/main.py, line 591 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcbwI3Yu69-BeS8RuXQ:-KccIsLggGtLjYdBZfdQ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/infrastructure/router/main.py#L591)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

> "check on ingress that..."
as the egress hop doesn't inspect the previous HopF.
</blockquote></details>

Done.

---

*[infrastructure/router/main.py, line 623 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KcbxR6HHWbu4aMWMAiS:-KccImuT2xDstTnwblz5:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/infrastructure/router/main.py#L623)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These are the wrong interfaces.
</blockquote></details>

Done.

---

*[lib/packet/path.py, line 263 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KccEwGq5ImUOrIpi7IO:-KccGtJl0pYdP0BeT6Da:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/lib/packet/path.py#L263)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The `else` is unnecessary.
</blockquote></details>

Done.

---

*[lib/packet/path.py, line 288 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KccF0eiURcUjVGggDF1:-KccGp3uUyPnu-LAJFO6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/ca49cde76a12cfeeaada610b1db10d1267985621/lib/packet/path.py#L288)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be simplified to:
```
if ingress == iof.up_flag:
  return hof.egress_if
return hof.ingress_if
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/main.py, line 625 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KccKNt5yTYjCXSxcRmS:-KccKNt5yTYjCXSxcRmT:b-6oyvhh) ([raw file](https://github.com/netsec-ethz/scion/blob/70ed2ec107268d6c6fa24c30c6473b916b84ba76/infrastructure/router/main.py#L625)):*
> ```Python
>                 prev_hof.egress_if != cur_hof.egress_if):
>             raise SCIONSegmentSwitchError(
>                 "Ingress IF of peering HOF does not match ingress IF of "
> ```

This text is still wrong. Also, the two peering cases can be collapsed.

`if (rcvd_on_link_type == LinkType.PEER or fwd_on_link_type == LinkType.PEER) and prev_hof.egress_if != cur_hof.egress_if:`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/main.py, line 625 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-KccKNt5yTYjCXSxcRmS:-KdPZPx7q20mK17cVxR-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/70ed2ec107268d6c6fa24c30c6473b916b84ba76/infrastructure/router/main.py#L625)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This text is still wrong. Also, the two peering cases can be collapsed.

`if (rcvd_on_link_type == LinkType.PEER or fwd_on_link_type == LinkType.PEER) and prev_hof.egress_if != cur_hof.egress_if:`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964#-:-KdPooXKDZLchzwONBI-:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/964)*

**Pull request merged**
