### PR TITLE
Add proper support for scion ctrl payloads in Go

### PR DESCRIPTION
**Pull request by kormat**
Based on work by @shitz

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1235)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 13 of 33 files at r1, 15 of 23 files at r2, 1 of 4 files at r3.
Review status: 27 of 38 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[go/border/rpkt/process.go, line 151 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswcZN4EnIg1aMXPe9e:-KswcZN4EnIg1aMXPe9f:bivi7n6) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/border/rpkt/process.go#L151)):*
> ```Go
> 		return rp.processPathMgmtSelf(u0)
> 	default:
> 		rp.Error("Unsupported destination payload", "type", cpld.ProtoType())
> ```

I think you want `u0.ProtoType()` here, otherwise this always prints "scion".

---

*[go/lib/ctrl/path_mgmt/rev_info.go, line 55 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-Kswh5VL9O18OrJiVI4n:-Kswh5VL9O18OrJiVI4o:b-cac3lq) ([raw file](https://github.com/netsec-ethz/scion/blob/57add760cfdf9d7115acd479915ce14497372f2e/go/lib/ctrl/path_mgmt/rev_info.go#L55)):*
> ```Go
> 
> func (r *RevInfo) ProtoType() string {
> 	return proto.PathMgmt_Which_revInfo.String()
> ```

This won't really work well in cases where the `RevInfo` is not part of a `PathMgmt` packet. I suggest you change `ProtoType` to return the name of a proto schema everywhere, since that is meaningful in any context.

---

*[go/lib/ctrl/seg/as.go, line 26 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswhUQTVzOje0xq5nCp:-KswhUQTVzOje0xq5nCq:b-cmij3d) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/lib/ctrl/seg/as.go#L26)):*
> ```Go
> 	CertVer      uint32
> 	IfIDSize     uint8
> 	HopEntries   []*HopEntry
> ```

this needs `capnp:"pcbms"`

---

*[go/lib/sciond/types.go, line 77 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-Kswiw1l-By1l-NyPZLT:-Kswiw1l-By1l-NyPZLU:b39imti) ([raw file](https://github.com/netsec-ethz/scion/blob/57add760cfdf9d7115acd479915ce14497372f2e/go/lib/sciond/types.go#L77)):*
> ```Go
> 
> func (p *Pld) ProtoType() string {
> 	return "sciond"
> ```

`SCIONDMsg`

---

*[go/proto/cereal.go, line 87 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswjsCcc57l08gIOF1F:-KswjsCcc57l08gIOF1G:b-zhx0iw) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/proto/cereal.go#L87)):*
> ```Go
> }
> 
> func ReadRootFromRaw(b common.RawBytes) (capnp.Struct, *common.Error) {
> ```

This can just be
```
func ReadRootFromRaw(b common.RawBytes) (capnp.Struct, *common.Error) {
    return ReadRootFromReader(bytes.NewBuffer(b))
}
```

---

*[go/proto/cereal.go, line 120 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswkDSAhfhTXpYkWo_O:-KswkDSAhfhTXpYkWo_P:b-yabbg6) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/proto/cereal.go#L120)):*
> ```Go
> }
> 
> func ParseFromRaw(v interface{}, pType ProtoIdType, b common.RawBytes) *common.Error {
> ```

same here `ParseFromReader(v, pType, bytes.NewBuffer(b))`

---

*[go/proto/gen.go, line 8 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswkVpRohtPKD42-KK3:-KswkVpRohtPKD42-KK4:b-hfpv2h) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/proto/gen.go#L8)):*
> ```Go
> 
> import (
> 	//"fmt"
> ```

remove 

---

*[go/proto/gen.go, line 15 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswkWz92I857DihLh1P:-KswkWz92I857DihLh1Q:b-l6mwxj) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/proto/gen.go#L15)):*
> ```Go
> 	"text/template"
> 	"time"
> 	//"github.com/netsec-ethz/scion/go/proto"
> ```

remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1235)*

**Comment by kormat** [comment]
Review status: 21 of 40 files reviewed at latest revision, 8 unresolved discussions.

---

*[go/border/rpkt/process.go, line 151 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswcZN4EnIg1aMXPe9e:-KsxLQAHEF15fuuy2cWn:b-1l4un3) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/border/rpkt/process.go#L151)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I think you want `u0.ProtoType()` here, otherwise this always prints "scion".
</blockquote></details>

Ah, good point.

---

*[go/lib/ctrl/path_mgmt/rev_info.go, line 55 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-Kswh5VL9O18OrJiVI4n:-KsxLetD6RuAOOgmgybJ:bggjxq0) ([raw file](https://github.com/netsec-ethz/scion/blob/57add760cfdf9d7115acd479915ce14497372f2e/go/lib/ctrl/path_mgmt/rev_info.go#L55)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This won't really work well in cases where the `RevInfo` is not part of a `PathMgmt` packet. I suggest you change `ProtoType` to return the name of a proto schema everywhere, since that is meaningful in any context.
</blockquote></details>

Upon further inspection, `ProtoType()` is unnecessary, so i've removed it.

---

*[go/lib/ctrl/seg/as.go, line 26 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswhUQTVzOje0xq5nCp:-KsxM9wh9c8CKqmZUUIN:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/lib/ctrl/seg/as.go#L26)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

this needs `capnp:"pcbms"`
</blockquote></details>

Done.

---

*[go/lib/sciond/types.go, line 77 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-Kswiw1l-By1l-NyPZLT:-KsxMOHNi0e0Ub-I9CGt:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/57add760cfdf9d7115acd479915ce14497372f2e/go/lib/sciond/types.go#L77)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`SCIONDMsg`
</blockquote></details>

Done.

---

*[go/proto/cereal.go, line 87 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswjsCcc57l08gIOF1F:-KsxMep-wxChwTyUfw4F:b-jefjci) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/proto/cereal.go#L87)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This can just be
```
func ReadRootFromRaw(b common.RawBytes) (capnp.Struct, *common.Error) {
    return ReadRootFromReader(bytes.NewBuffer(b))
}
```
</blockquote></details>

Excellent point :)

---

*[go/proto/cereal.go, line 120 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswkDSAhfhTXpYkWo_O:-KsxMqqaMxaaIcNbUELO:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/proto/cereal.go#L120)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

same here `ParseFromReader(v, pType, bytes.NewBuffer(b))`
</blockquote></details>

Done.

---

*[go/proto/gen.go, line 8 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswkVpRohtPKD42-KK3:-KsxMvhptXNkRKWkgV7R:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/proto/gen.go#L8)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

remove 
</blockquote></details>

Done.

---

*[go/proto/gen.go, line 15 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KswkWz92I857DihLh1P:-KsxMvzNaN6IWMrFacxK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/proto/gen.go#L15)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1235)*

**Comment by shitz** [comment]
Reviewed 1 of 33 files at r1, 1 of 4 files at r3, 17 of 18 files at r4.
Review status: 40 of 41 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/border/revinfo.go, line 46 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KsxWFR_ye_Y4GUK-_ut:-KsxWFR_ye_Y4GUK-_uu:b-pl9u4o) ([raw file](https://github.com/netsec-ethz/scion/blob/a20eccd3cfffeafb5250d80924f2d1b449dcd78b/go/border/revinfo.go#L46)):*
> ```Go
> 	// Run forever.
> 	for args := range r.revInfoQ {
> 		if args.RevInfo == nil {
> ```

Hmm why remove this check? It doesn't make sense to forward a revocation if there is no `RevInfo` object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1235)*

**Comment by shitz** [comment]
:lgtm: minus docstrings and a useful PR description. Please also close #1228 when you merge this one.

---

Reviewed 1 of 18 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-:-KsxbwNwmwLO-mtxnonM:b-wcxmh5)*

**Comment by shitz** [comment]
Reviewed 9 of 13 files at r5.
Review status: 41 of 44 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/ctrl/ctrl.go, line 86 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KsxwRhXeMFROHJDfTQQ:-KsxwRhY7HEeon5JEr6Q:b-yreyah) ([raw file](https://github.com/netsec-ethz/scion/blob/fd61ad227867522ab148d260df9f102ea5f39894/go/lib/ctrl/ctrl.go#L86)):*
> ```Go
> }
> 
> // NewPld creates a new control payload, containing a new path_mgmt payload,
> ```

s/NewPld/NewPathMgmtPld/

---

*[go/proto/cereal.go, line 60 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-Ksxwwfb8ELrtLqZEciO:-Ksxwwfb8ELrtLqZEciP:b-lcvx34) ([raw file](https://github.com/netsec-ethz/scion/blob/fd61ad227867522ab148d260df9f102ea5f39894/go/proto/cereal.go#L60)):*
> ```Go
> }
> 
> // WriteRoot creates a complete capnp message for c, and returns it encoded as bytes.
> ```

PackRoot

---

*[go/proto/cereal.go, line 124 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KsxwsVB-pNuVruEg06G:-KsxwsVB-pNuVruEg06H:bsjzmmz) ([raw file](https://github.com/netsec-ethz/scion/blob/fd61ad227867522ab148d260df9f102ea5f39894/go/proto/cereal.go#L124)):*
> ```Go
> }
> 
> // ParseFromRaw is a utility function, which reads a capnp message from r and parses it into c.
> ```

ParseFromReader

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1235)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-:-Ksxy5y3GEqh_8B-qkkK:bnfp4nl)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[go/lib/ctrl/ctrl.go, line 86 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KsxwRhXeMFROHJDfTQQ:-KsxxROPXGBSktf0FvQE:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fd61ad227867522ab148d260df9f102ea5f39894/go/lib/ctrl/ctrl.go#L86)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

s/NewPld/NewPathMgmtPld/
</blockquote></details>

Done.

---

*[go/proto/cereal.go, line 60 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-Ksxwwfb8ELrtLqZEciO:-KsxxVun3J23B2Twqsh_:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fd61ad227867522ab148d260df9f102ea5f39894/go/proto/cereal.go#L60)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

PackRoot
</blockquote></details>

Done.

---

*[go/proto/cereal.go, line 124 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/1235#-KsxwsVB-pNuVruEg06G:-Ksxx_lgK-6TZJtNZ2aM:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fd61ad227867522ab148d260df9f102ea5f39894/go/proto/cereal.go#L124)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

ParseFromReader
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1235)*

**Pull request merged**
