### PR TITLE
Add asymmetric encryption/decryption

### PR DESCRIPTION
**Pull request by Oncilla**
add asymmetric encryption/decryption based on nacl PublicKey/PrivateKey.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1052)

### CODE REVIEW

**Comment by shitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/crypto/asymcrypto.py, line 85 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KidpuFJbQlGdyh4WH3K:-KidpuFJbQlGdyh4WH3L:bi0nfzt) ([raw file](https://github.com/netsec-ethz/scion/blob/3e5a507332e994b6df0b05a299f7f007d4261b21/lib/crypto/asymcrypto.py#L85)):*
> ```Python
>     :rtype: bytes
>     """
>     return bytes(
> ```

You don't need to convert this to bytes, since `nacl.utils.EncryptedMessage` is a subclass of `bytes`.

---

*[lib/crypto/asymcrypto.py, line 86 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KidqJ_38Znt5D3GYFLk:-KidqJ_38Znt5D3GYFLl:b1i9wsl) ([raw file](https://github.com/netsec-ethz/scion/blob/3e5a507332e994b6df0b05a299f7f007d4261b21/lib/crypto/asymcrypto.py#L86)):*
> ```Python
>     """
>     return bytes(
>         Box(private_key, public_key).encrypt(msg, random(Box.NONCE_SIZE)))
> ```

You don't need to pass in a nonce, since `encrypt` will generate a nonce for you.

---

*[lib/crypto/asymcrypto.py, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-Kidq5_kVAEXUvRMgbM4:-Kidq5_kVAEXUvRMgbM5:b-7dcf4y) ([raw file](https://github.com/netsec-ethz/scion/blob/3e5a507332e994b6df0b05a299f7f007d4261b21/lib/crypto/asymcrypto.py#L99)):*
> ```Python
>     :rtype: bytes
>     """
>     return bytes(Box(private_key, public_key).decrypt(msg))
> ```

`decrypt` already returns `bytes`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1052)*

**Comment by shitz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lib/crypto/asymcrypto.py, line 82 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KieIh0DrnWFohLtaU9R:-KieIh0EXmgEODNSrg85:bacre5c) ([raw file](https://github.com/netsec-ethz/scion/blob/f8173bd98dbf712fb030e2815b8eb2ae5e2b044a/lib/crypto/asymcrypto.py#L82)):*
> ```Python
>     :param PublicKey public_key: Public Key of decrypter.
>     :returns: The encrypted message.
>     :rtype: bytes
> ```

Change this to `nacl.utils.EncryptedMessage`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-:-KieIlDMG3omMtUuzize:bnfp4nl)*

**Comment by Oncilla** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lib/crypto/asymcrypto.py, line 85 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KidpuFJbQlGdyh4WH3K:-KieLRwxn0ad0AaZBT04:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3e5a507332e994b6df0b05a299f7f007d4261b21/lib/crypto/asymcrypto.py#L85)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You don't need to convert this to bytes, since `nacl.utils.EncryptedMessage` is a subclass of `bytes`.
</blockquote></details>

Done.

---

*[lib/crypto/asymcrypto.py, line 86 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KidqJ_38Znt5D3GYFLk:-KieLSIAZfIFuEGczKyO:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3e5a507332e994b6df0b05a299f7f007d4261b21/lib/crypto/asymcrypto.py#L86)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You don't need to pass in a nonce, since `encrypt` will generate a nonce for you.
</blockquote></details>

Done.

---

*[lib/crypto/asymcrypto.py, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-Kidq5_kVAEXUvRMgbM4:-KieLT6s2EUog5zm1pZZ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3e5a507332e994b6df0b05a299f7f007d4261b21/lib/crypto/asymcrypto.py#L99)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`decrypt` already returns `bytes`
</blockquote></details>

Done.

---

*[lib/crypto/asymcrypto.py, line 82 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KieIh0DrnWFohLtaU9R:-KieLPtkZllAxXNqn9lY:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f8173bd98dbf712fb030e2815b8eb2ae5e2b044a/lib/crypto/asymcrypto.py#L82)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Change this to `nacl.utils.EncryptedMessage`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1052)*

**Comment by shitz** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1052)*

**Comment by pszalach** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[lib/crypto/asymcrypto.py, line 20 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KieNL8D9t-NbWlA7Yv1:-KieNL8D9t-NbWlA7Yv2:b-wle1ue) ([raw file](https://github.com/netsec-ethz/scion/blob/9fc16e613f7d05a9be20151f964f9afd5449bf83/lib/crypto/asymcrypto.py#L20)):*
> ```Python
> # External
> from nacl.exceptions import BadSignatureError
> from nacl.public import Box, PrivateKey
> ```

where `PrivateKey` is used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1052)*

**Comment by pszalach** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/crypto/asymcrypto.py, line 74 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KieNSiocT7ByBn7mg8v:-KieNSiocT7ByBn7mg8w:bbve22t) ([raw file](https://github.com/netsec-ethz/scion/blob/9fc16e613f7d05a9be20151f964f9afd5449bf83/lib/crypto/asymcrypto.py#L74)):*
> ```Python
> 
> 
> def encrypt(msg, private_key, public_key):
> ```

why we pass private_key for public-key encryption?

---

*[lib/crypto/asymcrypto.py, line 87 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KieNYfIeSbLh9qQsey2:-KieNYfIeSbLh9qQsey3:b-1ftil) ([raw file](https://github.com/netsec-ethz/scion/blob/9fc16e613f7d05a9be20151f964f9afd5449bf83/lib/crypto/asymcrypto.py#L87)):*
> ```Python
> 
> 
> def decrypt(msg, private_key, public_key):
> ```

why we pass public_key for public-key decryption?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1052)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/crypto/asymcrypto.py, line 74 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KieNSiocT7ByBn7mg8v:-KieahgNbwXWBTy42gkr:b-pwe56t) ([raw file](https://github.com/netsec-ethz/scion/blob/9fc16e613f7d05a9be20151f964f9afd5449bf83/lib/crypto/asymcrypto.py#L74)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

why we pass private_key for public-key encryption?
</blockquote></details>

see https://pynacl.readthedocs.io/en/latest/public/

---

*[lib/crypto/asymcrypto.py, line 87 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KieNYfIeSbLh9qQsey2:-KieaigFFY7Wr_Sbed7n:b-pwe56t) ([raw file](https://github.com/netsec-ethz/scion/blob/9fc16e613f7d05a9be20151f964f9afd5449bf83/lib/crypto/asymcrypto.py#L87)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

why we pass public_key for public-key decryption?
</blockquote></details>

see https://pynacl.readthedocs.io/en/latest/public/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1052)*

**Comment by Oncilla** [comment]
*[lib/crypto/asymcrypto.py, line 20 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-KieNL8D9t-NbWlA7Yv1:-Kiegv56VHWa5ADPLn6P:bfgtmc) ([raw file](https://github.com/netsec-ethz/scion/blob/9fc16e613f7d05a9be20151f964f9afd5449bf83/lib/crypto/asymcrypto.py#L20)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

where `PrivateKey` is used?
</blockquote></details>

in  generate_enc_keypair

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1052)*

**Comment by pszalach** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1052#-:-KieiP5AraSt9pI5gnow:bnfp4nl)*

**Pull request merged**
