### PR TITLE
Refactor capnp handling in SCION to be more flexible.

### PR DESCRIPTION
**Pull request by kormat**
Packing/parsing of an inner capnp struct (e.g.
proto/rev_info.capnp:RevInfo) is now dependent on the container it is
in.

All protos which contain unions are now represented via the
packet_base.py:CerealBox class. CerealBoxes can be nested (e.g.
CtrlPayload(PathMgmt(RevInfo.from_values(...)))). All other protos are
represented via packet_base.py:Cerealizable.

As static PAYLOAD_CLASS-type class attributes should actually be
context-sensitive, these have been replaced with `proto_class()` and
`proto_type()` methods on CerealBox.

Also:
- Update to the latest pycapnp version.
- Add a Lot of type assertions, and make existing ones emit the
  incorrect type on failure.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1249)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 4 of 50 files at r1.
Review status: 4 of 50 files reviewed at latest revision, 6 unresolved discussions.

---

*[python/lib/packet/ctrl_pld.py, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuuVvBDt3xr0cLi5iro:-KuuVvBDt3xr0cLi5irp:bnust11) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/ctrl_pld.py#L38)):*
> ```Python
> 
> 
> class CtrlPayload(CerealBox):
> ```

Now that we also touch the Python control payload implementation, we can rename the proto to `CtrlPayload` (from `SCION`). Not in this PR though, just adding it here for reference.

---

*[python/lib/packet/ctrl_pld.py, line 67 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuuiZASqyrvVIxZ9jb1:-KuuiZASqyrvVIxZ9jb2:bwn29q4) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/ctrl_pld.py#L67)):*
> ```Python
>         return self._class(class_field_map)
> 
>     def proto_type(self):
> ```

Here the name is even more confusing. The old names `payload_class` and `payload_type` where clearer, however, I understand that `CerealBox` shouldn't refer to payloads. I am not sure what's a good solution for this.

---

*[python/lib/packet/packet_base.py, line 182 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuubcxZOBpfq6eaGeKo:-Kuubcx_K8D4V7MRZ8fG:b-ogwer4) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/packet_base.py#L182)):*
> ```Python
> 
> 
> class CerealBox(object, metaclass=ABCMeta):
> ```

This class could really use some docstring explaining it's structure. The various `from_X` methods are rather puzzling otherwise.

---

*[python/lib/packet/packet_base.py, line 190 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuua2-UI8PVm2mf1OpW:-Kuua2-UI8PVm2mf1OpX:bxfzuut) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/packet_base.py#L190)):*
> ```Python
> 
>     @classmethod
>     def _from_proto(cls, p, class_field_map):  # pragma: no cover
> ```

If you made `class_field_map` a class variable (or a method) that subclasses of `CerealBox` need to set, then you could get rid of the `proto_class` and `from_proto` boilerplate in all the subclasses of `CerealBox`. Imho, it would also be more intuitive if it's a member of the `CerealBox` class rather than some external map that you have to pass in to various methods.

Also, will this approach work if you have ever more than one union in a proto? In Go, you introduced the `union0` for this. Maybe we should do this as well in the Python implementation?

---

*[python/lib/packet/packet_base.py, line 201 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuuf0m2OufKUVZD1_-4:-Kuuf0m2OufKUVZD1_-5:bcybil3) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/packet_base.py#L201)):*
> ```Python
>         return cls(contents)
> 
>     def proto(self):
> ```

It's very confusing that this is called `proto()` and `proto_type()` etc., since this is really the (type of) the boxed proto. Also, `proto()` in `CerealBox` is semantically something different than `proto()` in `Cerealizable`, which isn't optimal. I suggest you rename this to something that makes it clear this isn't the toplevel proto object.

---

*[python/lib/packet/packet_base.py, line 203 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuuc_WHXMLAfxzMsDZl:-Kuuc_WHXMLAfxzMsDZm:bx2w33d) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/packet_base.py#L203)):*
> ```Python
>     def proto(self):
>         field = self.proto_class()
>         return self.P_CLS.new_message(**{field: self.contents.proto()})
> ```

Cache the result of this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1249)*

**Comment by kormat** [comment]
Review status: 3 of 52 files reviewed at latest revision, 6 unresolved discussions.

---

*[python/lib/packet/ctrl_pld.py, line 38 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuuVvBDt3xr0cLi5iro:-KuxRZYkchGQUD_Ptqji:b-81nlyc) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/ctrl_pld.py#L38)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Now that we also touch the Python control payload implementation, we can rename the proto to `CtrlPayload` (from `SCION`). Not in this PR though, just adding it here for reference.
</blockquote></details>

SGTM.

---

*[python/lib/packet/ctrl_pld.py, line 67 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuuiZASqyrvVIxZ9jb1:-KuySbtHP4eTYpNDgRe-:bbw21jx) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/ctrl_pld.py#L67)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Here the name is even more confusing. The old names `payload_class` and `payload_type` where clearer, however, I understand that `CerealBox` shouldn't refer to payloads. I am not sure what's a good solution for this.
</blockquote></details>

Refactored a bit and renamed.

---

*[python/lib/packet/packet_base.py, line 182 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuubcxZOBpfq6eaGeKo:-KuySgBrhGm_9boH6AK_:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/packet_base.py#L182)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This class could really use some docstring explaining it's structure. The various `from_X` methods are rather puzzling otherwise.
</blockquote></details>

Done.

---

*[python/lib/packet/packet_base.py, line 190 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuua2-UI8PVm2mf1OpW:-KuxxyngW0NweQsBZX-l:bmdpn3n) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/packet_base.py#L190)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

If you made `class_field_map` a class variable (or a method) that subclasses of `CerealBox` need to set, then you could get rid of the `proto_class` and `from_proto` boilerplate in all the subclasses of `CerealBox`. Imho, it would also be more intuitive if it's a member of the `CerealBox` class rather than some external map that you have to pass in to various methods.

Also, will this approach work if you have ever more than one union in a proto? In Go, you introduced the `union0` for this. Maybe we should do this as well in the Python implementation?
</blockquote></details>

Made subclasses of `CerealBox` have a `CLASS_FIELD_MAP` class attribute.

As discussed, lets leave the union0 issue for now, and revisit if it becomes relevant.

---

*[python/lib/packet/packet_base.py, line 201 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuuf0m2OufKUVZD1_-4:-KuySilOfeKzBmYhly47:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/packet_base.py#L201)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

It's very confusing that this is called `proto()` and `proto_type()` etc., since this is really the (type of) the boxed proto. Also, `proto()` in `CerealBox` is semantically something different than `proto()` in `Cerealizable`, which isn't optimal. I suggest you rename this to something that makes it clear this isn't the toplevel proto object.
</blockquote></details>

Done.

---

*[python/lib/packet/packet_base.py, line 203 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuuc_WHXMLAfxzMsDZl:-KuxyAy4J4E1MIWrrY2I:b92lqxi) ([raw file](https://github.com/netsec-ethz/scion/blob/6e5fb7345915cf09e0e2c7dac9cdec73e53bde8e/python/lib/packet/packet_base.py#L203)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Cache the result of this?
</blockquote></details>

As discussed, madness lies that way (cache-invalidation is a nightmare).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1249)*

**Comment by shitz** [comment]
Reviewed 32 of 50 files at r1, 10 of 14 files at r2.
Review status: 45 of 52 files reviewed at latest revision, 5 unresolved discussions.

---

*[python/lib/drkey/drkey_mgmt.py, line 104 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuy_GeAQ_beF0kCc9aZ:-Kuy_GeAQ_beF0kCc9a_:b-v5yhp4) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/lib/drkey/drkey_mgmt.py#L104)):*
> ```Python
>                    self.p.certVerDst, self.p.trcVer, self.p.timestamp))
> 
> DRKeyMgmt.CLASS_FIELD_MAP = {
> ```

Move to `DRKeyMgmt` class definition like in other places.

---

*[python/lib/packet/cert_mgmt.py, line 106 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuy_SfJLU3_IEZ9myfr:-Kuy_SfJLU3_IEZ9myfs:b-7ropln) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/lib/packet/cert_mgmt.py#L106)):*
> ```Python
> 
> 
> CertMgmt.CLASS_FIELD_MAP = {
> ```

ditto

---

*[python/path_server/base.py, line 234 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuyXp1_W4PJqu9vQ4-q:-KuyXp1_W4PJqu9vQ4-r:b-dhhp65) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/path_server/base.py#L234)):*
> ```Python
>         for info in infos.iter_infos():
>             if not info.p.active and info.p.revInfo:
>                 self._handle_revocation(CtrlPayload(PathMgmt(info.rev_info())), meta)
> ```

Seems unnecessary to wrap the `rev_info` inside a `PathMgmt` and then inside `CtrlPayload`. I suggest you  something like:
```
def _handle_revocation(self, cpld, meta):
    pgmt = cpld.contents
    rev_info = pgmt.contents
    self._process_rev_info(rev_info, meta)

def _process_rev_info(self, rev_info, meta):
    assert instance(rev_info, RevocationInfo), type(rev_info)
    if not self_.validate_revocation(rev_info):
    ...
```
and call `self_process_rev_info(rev_info, meta)` here.

---

*[python/path_server/base.py, line 238 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuyYmPBhaA2vO9RF9F1:-KuyYmPBhaA2vO9RF9F2:b-7ropln) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/path_server/base.py#L238)):*
> ```Python
>     def _handle_scmp_revocation(self, pld, meta):
>         rev_info = RevocationInfo.from_raw(pld.info.rev_info)
>         self._handle_revocation(CtrlPayload(PathMgmt(rev_info)), meta)
> ```

ditto

---

*[python/path_server/base.py, line 350 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuyYy6fZmZ9i0mTBmNw:-KuyYy6fZmZ9i0mTBmNx:bhkijhy) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/path_server/base.py#L350)):*
> ```Python
>             for key in self.pending_req:
>                 for req_id, (req, meta, logger) in self.pending_req[key].items():
>                     if self.path_resolution(CtrlPayload(PathMgmt(req)), meta,
> ```

See comment about `handle_revocation`. It applies to all methods that are called from `SCIONElement` with a `CtrlPayload` and in different places with only the inner type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1249)*

**Comment by kormat** [comment]
Review status: 45 of 52 files reviewed at latest revision, 5 unresolved discussions.

---

*[python/lib/drkey/drkey_mgmt.py, line 104 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuy_GeAQ_beF0kCc9aZ:-Kuyf6iJLNYVPOJuISsK:bws4bm0) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/lib/drkey/drkey_mgmt.py#L104)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Move to `DRKeyMgmt` class definition like in other places.
</blockquote></details>

As documented above, this is not possible.

---

*[python/lib/packet/cert_mgmt.py, line 106 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuy_SfJLU3_IEZ9myfr:-Kuyf8rV0PJzeQkvydg9:bws4bm0) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/lib/packet/cert_mgmt.py#L106)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

ditto
</blockquote></details>

As documented above, this is not possible.

---

*[python/path_server/base.py, line 234 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuyXp1_W4PJqu9vQ4-q:-KuygDunap_GVRHVfGiT:b69n4b9) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/path_server/base.py#L234)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Seems unnecessary to wrap the `rev_info` inside a `PathMgmt` and then inside `CtrlPayload`. I suggest you  something like:
```
def _handle_revocation(self, cpld, meta):
    pgmt = cpld.contents
    rev_info = pgmt.contents
    self._process_rev_info(rev_info, meta)

def _process_rev_info(self, rev_info, meta):
    assert instance(rev_info, RevocationInfo), type(rev_info)
    if not self_.validate_revocation(rev_info):
    ...
```
and call `self_process_rev_info(rev_info, meta)` here.
</blockquote></details>

Ignoring, as discussed.

---

*[python/path_server/base.py, line 238 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuyYmPBhaA2vO9RF9F1:-KuygFR0mqjWA1Aqjmud:b69n4b9) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/path_server/base.py#L238)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Ignoring, as discussed.

---

*[python/path_server/base.py, line 350 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-KuyYy6fZmZ9i0mTBmNw:-KuygGAnaju12sDeU7nY:b69n4b9) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/path_server/base.py#L350)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

See comment about `handle_revocation`. It applies to all methods that are called from `SCIONElement` with a `CtrlPayload` and in different places with only the inner type.
</blockquote></details>

Ignoring, as discussed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1249)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 3 of 50 files at r1, 4 of 14 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/lib/drkey/drkey_mgmt.py, line 104 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-Kuy_GeAQ_beF0kCc9aZ:-Kuygta9B7lI7eri5zjy:b-s502jv) ([raw file](https://github.com/netsec-ethz/scion/blob/3b596fa2eef94536efdf315e98ea4b4722271914/python/lib/drkey/drkey_mgmt.py#L104)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As documented above, this is not possible.
</blockquote></details>

My bad. Sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1249#-:-Kuyh544O3NjM0jGeqbu:bnfp4nl)*

**Pull request merged**
