### PR TITLE
Fix CertChain fetching in Cert server

### PR DESCRIPTION
**Pull request by Oncilla**
Fixes fetching of certificate chains on the certificate server.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1087)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[infrastructure/cert_server/main.py, line 210 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoPb-lTTQts2Af5B02:-KkoPb-lTTQts2Af5B03:b957la2) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L210)):*
> ```Python
>     def _fetch_cc(self, key, _):
>         isd_as, ver = key
>         req = CertChainRequest.from_values(isd_as, ver)
> ```

Add `cache_only=True`

---

*[infrastructure/cert_server/main.py, line 271 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoPWhotbG3k9isOioO:-KkoPWhotbG3k9isOioP:b957la2) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L271)):*
> ```Python
>         isd, ver = key
>         isd_as = ISD_AS.from_values(isd, info[1])
>         trc_req = TRCRequest.from_values(isd_as, ver)
> ```

Add `cache_only=True`

---

*[infrastructure/cert_server/main.py, line 299 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoOAKj87-Ii8A5mDpB:-KkoOAKkB3TyuQYFGnbt:brihfqq) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L299)):*
> ```Python
>                 logging.error("Error during path lookup: %s" % e)
>                 continue
>         if path_entries:
> ```

This `if` clause needs to be inside the `while` loop.

---

*[infrastructure/cert_server/main.py, line 301 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoPkb2QO4GzZgndNRY:-KkoPkb3Pg3v3xJS9Vdi:b-d09gqt) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L301)):*
> ```Python
>         if path_entries:
>             return path_entries[0].path().fwd_path()
>         logging.info("Unable to get path from local api.")
> ```

Change to warning, and please include the destination IA in the output.

---

*[infrastructure/cert_server/main.py, line 304 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoQ5kfCjhoOPK5rcSW:-KkoQ5kgjq9GjT7jmZkQ:b-7avqc0) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L304)):*
> ```Python
>         return None
> 
>     def _send_payload(self, isd_as, payload, path, host=SVCType.CS_A, port=0):
> ```

`SCIONElement.send_meta` should handle this for you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1087)*

**Comment by Oncilla** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[infrastructure/cert_server/main.py, line 210 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoPb-lTTQts2Af5B02:-KkoRm7fUIcgLPNa91IG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L210)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Add `cache_only=True`
</blockquote></details>

Done.

---

*[infrastructure/cert_server/main.py, line 271 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoPWhotbG3k9isOioO:-KkoRmTVWbDDHt56QGbS:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L271)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Add `cache_only=True`
</blockquote></details>

Done.

---

*[infrastructure/cert_server/main.py, line 299 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoOAKj87-Ii8A5mDpB:-KkoXM3iJTOMfb0eAB1o:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L299)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This `if` clause needs to be inside the `while` loop.
</blockquote></details>

Done.

---

*[infrastructure/cert_server/main.py, line 301 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoPkb2QO4GzZgndNRY:-KkoZOSbMCq-uOAmt3g7:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L301)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Change to warning, and please include the destination IA in the output.
</blockquote></details>

Done.

---

*[infrastructure/cert_server/main.py, line 304 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkoQ5kfCjhoOPK5rcSW:-KkoWaGfkrnaJ5hee2gR:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/fb02f1343afd04f24b2cf3435fffd6ebaec13a64/infrastructure/cert_server/main.py#L304)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`SCIONElement.send_meta` should handle this for you.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1087)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[infrastructure/cert_server/main.py, line 183 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkodxmVElBUqoMdxuhg:-KkodxmWkdbHVLWKvIQf:b-xbjt9k) ([raw file](https://github.com/netsec-ethz/scion/blob/4ab7b5c7ae899fa8decd9beb63eb212615600358/infrastructure/cert_server/main.py#L183)):*
> ```Python
>                 "Dropping CC request from %s for %sv%s: "
>                 "CC not found && requester is not local)",
>                 meta.get_addr(), *key)
> ```

This needs a `return`, otherwise it still tries to handle the request. Same for trc requests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1087)*

**Comment by Oncilla** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[infrastructure/cert_server/main.py, line 183 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-KkodxmVElBUqoMdxuhg:-KkogWel3xTe_t7m6hXP:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/4ab7b5c7ae899fa8decd9beb63eb212615600358/infrastructure/cert_server/main.py#L183)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This needs a `return`, otherwise it still tries to handle the request. Same for trc requests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1087)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1087#-:-Kkp8SE019bllc6BiZHV:bnfp4nl)*

**Pull request merged**
