### PR TITLE
Rewrite posix i/o to use SRing, remove per-packet callbacks.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1212)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 5 of 11 files at r1.
Review status: 5 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[go/border/io.go, line 63 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW3Cm_51VJ-r0JKOYS:-KrW3Cm_51VJ-r0JKOYT:bopv1cv) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/io.go#L63)):*
> ```Go
> 			rp.DirFrom = s.Dir
> 			rp.Free = free
> 			start := monotime.Now()
> ```

Not related to this PR, but isn't getting a timestamp per packet relatively expensive? I remember having this discussion for a per frame timestamp in the SIG, which we discarded as being too expensive.

---

*[go/border/setup.go, line 206 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW6RcBiwpf-MJjWQkg:-KrW6RcBiwpf-MJjWQkh:bchdmj1) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/setup.go#L206)):*
> ```Go
> 	// Stop input functions that are no longer needed.
> 	if oldCtx != nil {
> 		for i, sock := range oldCtx.LocSockIn {
> ```

```
for i := len(ctx.LockSockIn); i < len(oldCtx.LockSockIn); i++ {
    oldCtx.LockSockIn[i].Stop()
}
```

---

*[go/border/setup.go, line 335 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW5jt0s7XOz17DwY0M:-KrW5jt0s7XOz17DwY0N:bfr5hxs) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/setup.go#L335)):*
> ```Go
> }
> 
> func newEgressRpktSRing(size int, desc string, labels prometheus.Labels) *sring.SRing {
> ```

Not used?

---

*[go/border/rctx/io.go, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW8tN8hOVESQeKDk-N:-KrW8tN8hOVESQeKDk-O:bnwvwuu) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/rctx/io.go#L59)):*
> ```Go
> }
> 
> func NewSock(sring *sring.SRing, conn conn.Conn, dir rcmn.Dir,
> ```

Should have a sanity check that `Reader` and/or `Writer` are set. Otherwise it's useless.

---

*[go/border/rctx/rctx.go, line 34 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW7wlD0NQKgdIiYfib:-KrW7wlD0NQKgdIiYfic:b225vdp) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/rctx/rctx.go#L34)):*
> ```Go
> 	// destinations (i.e. within the local ISD-AS), indexed by the local
> 	// address id.
> 	// TODO(shitz): Change this to be a slice.
> ```

Remove TODO

---

*[go/border/rpkt/route.go, line 64 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrWBBnZna0LA_-C_hrv:-KrWBBnZna0LA_-C_hrw:b-do7dyj) ([raw file](https://github.com/netsec-ethz/scion/blob/116a817f131cf436d24459132ccffac57f904064/go/border/rpkt/route.go#L64)):*
> ```Go
> 	// Call all egress functions.
> 	for _, epair := range rp.Egress {
> 		epair.S.Sring.Write(sring.EntryList{&EgressRtrPkt{rp, epair.Dst}})
> ```

I think you're not use an `sring` that contains `EgressRtrPkt`. Should fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1212)*

**Comment by kormat** [comment]
Review status: 3 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/border/io.go, line 63 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW3Cm_51VJ-r0JKOYS:-Kr_1mkhAb-xJd4MCXoW:bab06wv) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/io.go#L63)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Not related to this PR, but isn't getting a timestamp per packet relatively expensive? I remember having this discussion for a per frame timestamp in the SIG, which we discarded as being too expensive.
</blockquote></details>

Oh, **cough**. It's basically a necessary evil, otherwise we can track things well in the BR. That said, this particular timestamp is going move, with the kernel timestamping packets as they arrive at the NIC.

---

*[go/border/setup.go, line 206 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW6RcBiwpf-MJjWQkg:-Kr_2gvT7AfrE_PrBsZ0:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/setup.go#L206)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

```
for i := len(ctx.LockSockIn); i < len(oldCtx.LockSockIn); i++ {
    oldCtx.LockSockIn[i].Stop()
}
```
</blockquote></details>

Done.

---

*[go/border/setup.go, line 335 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW5jt0s7XOz17DwY0M:-Kr_2nJLBNub38JOXSD-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/setup.go#L335)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Not used?
</blockquote></details>

Done.

---

*[go/border/rctx/io.go, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW8tN8hOVESQeKDk-N:-Kr_2pW37ehRmWXicT18:b-83if5b) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/rctx/io.go#L59)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Should have a sanity check that `Reader` and/or `Writer` are set. Otherwise it's useless.
</blockquote></details>

It's not useless - there doesn't _have_ to be dedicated reading/writing goroutines. The ringbuffer is accessible to anything which has the `Sock` instance. We don't use it that way currently, but there's no reason we couldn't at some point. 

---

*[go/border/rctx/rctx.go, line 34 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrW7wlD0NQKgdIiYfib:-Kr_4DgBKQsQEo_m437w:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/085b2629a4437d219ac6f586fb5d84f4cab9327b/go/border/rctx/rctx.go#L34)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Remove TODO
</blockquote></details>

Done.

---

*[go/border/rpkt/route.go, line 64 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-KrWBBnZna0LA_-C_hrv:-Kr_4GWousep3sC1g2ES:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/116a817f131cf436d24459132ccffac57f904064/go/border/rpkt/route.go#L64)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I think you're not use an `sring` that contains `EgressRtrPkt`. Should fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1212)*

**Comment by shitz** [comment]
Reviewed 5 of 11 files at r3.
Review status: 8 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/border/io.go, line 69 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-Kr_AT0hM2p25gFGRpwb:-Kr_AT0hM2p25gFGRpwc:b45or85) ([raw file](https://github.com/netsec-ethz/scion/blob/d7f43878ea7b0260f8879a88de54e5a6866bea23/go/border/io.go#L69)):*
> ```Go
> 			if err != nil {
> 				log.Error("Error reading from socket", "socket", dst, "err", err)
> 				rp.Reset()
> ```

This `RtrPkt` doesn't get freed afaics.

---

*[go/border/setup.go, line 261 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-Kr_D-RSaKbucQekcAZB:-Kr_D-RSaKbucQekcAZC:b-5erswh) ([raw file](https://github.com/netsec-ethz/scion/blob/d7f43878ea7b0260f8879a88de54e5a6866bea23/go/border/setup.go#L261)):*
> ```Go
> 	}
> 	// Setup input goroutine.
> 	ctx.LocSockIn[idx] = rctx.NewSock(ringbuf.New(1024, nil, "locIn", labels),
> ```

No pre-allocation for these?

---

*[go/border/rpkt/rpkt.go, line 146 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-Kr_BdHgA16kwTImcI1O:-Kr_BdHgA16kwTImcI1P:bj5318s) ([raw file](https://github.com/netsec-ethz/scion/blob/d7f43878ea7b0260f8879a88de54e5a6866bea23/go/border/rpkt/rpkt.go#L146)):*
> ```Go
> 	}
> 	rp.refCnt -= 1
> 	if rp.refCnt == 0 && rp.Free != nil {
> ```

You should log if `refCnt` reaches 0, but `Free` is `nil`. This probably means that we are leaking the `RtrPkt`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1212)*

**Comment by kormat** [comment]
Review status: 8 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/border/io.go, line 69 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-Kr_AT0hM2p25gFGRpwb:-Kr_DM3Z9yvmrKhWPBYc:bvc7lxn) ([raw file](https://github.com/netsec-ethz/scion/blob/d7f43878ea7b0260f8879a88de54e5a6866bea23/go/border/io.go#L69)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This `RtrPkt` doesn't get freed afaics.
</blockquote></details>

The for-loop directly afterwards frees everything that hasn't already been written to the ringbuf, starting with this RtrPkt. This `Reset()` call is unnecessary however. I've added a comment.

---

*[go/border/setup.go, line 261 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-Kr_D-RSaKbucQekcAZB:-Kr_ESgI-g19vrZjDl9y:bu1hl9b) ([raw file](https://github.com/netsec-ethz/scion/blob/d7f43878ea7b0260f8879a88de54e5a6866bea23/go/border/setup.go#L261)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

No pre-allocation for these?
</blockquote></details>

No. The only pre-allocation done in the BR is in the global free buffer list. Everything else either takes a buffer from that free buffer list (i.e. all incoming packets), or creates its own buffer (i.e. everything sent by gen.go). 

---

*[go/border/rpkt/rpkt.go, line 146 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-Kr_BdHgA16kwTImcI1O:-Kr_DCfoGsUxxse7PtbT:b-5m3ek) ([raw file](https://github.com/netsec-ethz/scion/blob/d7f43878ea7b0260f8879a88de54e5a6866bea23/go/border/rpkt/rpkt.go#L146)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You should log if `refCnt` reaches 0, but `Free` is `nil`. This probably means that we are leaking the `RtrPkt`.
</blockquote></details>

No, that's expected to happen. Any packets that the router creates (e.g. ifid packets) aren't taken from the global free ringbuf, and are just dropped after use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1212)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 5 of 11 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/border/io.go, line 69 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-Kr_AT0hM2p25gFGRpwb:-Kr_F2BKzi0Fc37YQs1h:b-oq41bl) ([raw file](https://github.com/netsec-ethz/scion/blob/d7f43878ea7b0260f8879a88de54e5a6866bea23/go/border/io.go#L69)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The for-loop directly afterwards frees everything that hasn't already been written to the ringbuf, starting with this RtrPkt. This `Reset()` call is unnecessary however. I've added a comment.
</blockquote></details>

Right, it starts at `i`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1212#-:-Kr_FUlCo93KYc33vx6g:bnfp4nl)*

**Pull request merged**
