### PR TITLE
TCP fixes (continuation of #890)

### PR DESCRIPTION
**Pull request by pszalach**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/895)

### CODE REVIEW

**Comment by pszalach** [comment]
@kormat  (I published some responses in #890)

**Comment by kormat** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[infrastructure/scion_elem.py, line 435 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/895#-KRhnQSHGGqhMON6qn-h:-KRhnQSHGGqhMON6qn-i:b-r96q1e) ([raw file](https://github.com/netsec-ethz/scion/blob/e013c78422cfbf6b57a191eed4a8b3bc12a4395c/infrastructure/scion_elem.py#L435)):*
> ```Python
>             return False
>         self._udp_sock.send(packet.pack(), (dst, dst_port))
>         return True
> ```

This ignores any errors in `send`

---

*[infrastructure/scion_elem.py, line 444 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/895#-KRhnUzfyPJmlgfh6QE_:-KRhnUzfyPJmlgfh6QEa:b-r96q1e) ([raw file](https://github.com/netsec-ethz/scion/blob/e013c78422cfbf6b57a191eed4a8b3bc12a4395c/infrastructure/scion_elem.py#L444)):*
> ```Python
>         elif isinstance(meta, SockOnlyMetadata):
>             assert not next_hop_port, next_hop_port
>             meta.sock.send(msg)
> ```

This ignores any errors in `send`

---

*[lib/socket.py, line 416 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/895#-KRhnuz4ipPsfPkqEUKH:-KRhnuz4ipPsfPkqEUKI:bwb5cc8) ([raw file](https://github.com/netsec-ethz/scion/blob/e013c78422cfbf6b57a191eed4a8b3bc12a4395c/lib/socket.py#L416)):*
> ```Python
>                 return False
>             try:
>                 self._sock.send(raw)
> ```

Will all possible send failures raise `SCIONTCPError`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/895)*

**Comment by pszalach** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[infrastructure/scion_elem.py, line 435 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/895#-KRhnQSHGGqhMON6qn-h:-KRhtYmvm51HLZ5g57Je:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e013c78422cfbf6b57a191eed4a8b3bc12a4395c/infrastructure/scion_elem.py#L435)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> This ignores any errors in `send`
</details>
Done.

---

*[infrastructure/scion_elem.py, line 444 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/895#-KRhnUzfyPJmlgfh6QE_:-KRhuSX77h-iCCJK4dy8:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e013c78422cfbf6b57a191eed4a8b3bc12a4395c/infrastructure/scion_elem.py#L444)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> This ignores any errors in `send`
</details>
Done.

---

*[lib/socket.py, line 416 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/895#-KRhnuz4ipPsfPkqEUKH:-KRhurpZMlo2DsvF7ZpG:b2nhswy) ([raw file](https://github.com/netsec-ethz/scion/blob/e013c78422cfbf6b57a191eed4a8b3bc12a4395c/lib/socket.py#L416)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary>
> Will all possible send failures raise `SCIONTCPError`?
</details>
Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/895)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/895)*

**Pull request merged**
