### PR TITLE
Update snet to accept and fill in path/nexthop info in snet.Addr.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1283)

### CODE REVIEW

**Comment by shitz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1283#-:-Kw64tXk3SsOJLQVqFTr:bnfp4nl)*

**Comment by scrye** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1283)*

**Comment by scrye** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1283#-:-KwAW0xhoPkfG9UMaW07:bnfp4nl)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/snet/addr.go, line 63 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1283#-KwAVjWHoR-Z2W3vLnf-:-KwAVjWHoR-Z2W3vLnf0:br5a47f) ([raw file](https://github.com/netsec-ethz/scion/blob/ead6f43649c76ba4a5e65cd0b4dc339460ef0f83/go/lib/snet/addr.go#L63)):*
> ```Go
> // EqAddr compares the IA/Host/L4port values with the supplied Addr
> func (a *Addr) EqAddr(o *Addr) bool {
> 	if a == nil || o == nil {
> ```

So `a` cannot be `nil` here. This should become `if o == nil { return false }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1283)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/snet/addr.go, line 63 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1283#-KwAVjWHoR-Z2W3vLnf-:-KwAWY9E3BkbWsGFnWy3:b-83og3x) ([raw file](https://github.com/netsec-ethz/scion/blob/fc9bf95bc8e36abca40df905fc7dfc46a7610ab0/go/lib/snet/addr.go#L63)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

So `a` cannot be `nil` here. This should become `if o == nil { return false }`
</blockquote></details>

Nope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1283)*

**Comment by shitz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1283#-:-KwAWgBKFMBvF4WDQmMa:bnfp4nl)*

**Pull request merged**
