### PR TITLE
Prometheus metrics for infrastructure

### PR DESCRIPTION
**Pull request by shitz**
This PR adds exporting of fine-grained metrics for infrastructure elements to prometheus. The metrics are defined as module level Counters/Gauges and can be labelled where necessary. The following metrics are available:

PathDB:
* Total \# and size of segments (can be labelled by type)
* \# of segments added/removed (can be labelled by type)

RevCache:
* Total \# and size of revocations
* \# of revocations added/removed

RequestHandler:
* \# of pending requests (can be labelled by type)

Path server:
* Total \# of path requests
* \# of pending path requests
* Length of segments/revocations to ZK dict
* Length of segments to master/prop dict

Beacon server:
* \# of beacons propagated
*  \# of segments registered
* \# of revocation issued

Certificate server:
* \# of requests received (can be labelled by type)

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1135)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 5 of 20 files at r1.
Review status: 5 of 20 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[python/scion_elem/scion_elem.py, line 871 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn3mXxalyYVrsSpFP1c:-Kn3mXxalyYVrsSpFP1d:b-qf46in) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L871)):*
> ```Python
>                 self._in_buf.put(item, block=False)
>                 PKT_BUF_TOTAL.inc()
>                 PKT_BUF_BYTES.inc(len(item[0]))
> ```

These are never decremented for packets which aren't dropped. `_packet_process` needs to be modified.

Also, `PKT_BUF_TOTAL` is directly calculable from  `self._in_buf.qsize()`.

---

*[python/scion_elem/scion_elem.py, line 881 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn3ot-zzJM3S3wpzapi:-Kn3ot0-hifNJPk16Qxs:b-fig2lq) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L881)):*
> ```Python
>         if dropped > 0:
>             self.total_dropped += dropped
>             PKTS_DROPPED_TOTAL.inc(dropped)
> ```

This could be moved up to `dropped += 1`, so that it's grouped with the other metric updates.

---

*[python/scion_elem/scion_elem.py, line 919 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn3p4IsNFibGJX2TF_0:-Kn3p4IsNFibGJX2TF_1:bh6bl7s) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L919)):*
> ```Python
>         except SCIONParseError as e:
>             logging.error("Cannot parse payload\n  Error: %s\n  Pkt: %s", e, pkt)
>             return None, 0, meta
> ```

Uh? There's 3 _other_ return statements in this method that only return 2 values. I also can't find any call site that expects 3 return values.

---

*[python/scion_elem/scion_elem.py, line 1130 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn4U5IaqNhzIOImOOlk:-Kn4U5IaqNhzIOImOOll:b-qjc5n3) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L1130)):*
> ```Python
>         """
>         # Create a dummy counter to export the server_id as a label for correlating
>         # server_id and other metrics.
> ```

Nooo. The server id needs to be a label on every metric that gets exported. Otherwise you can't do _any_ correlation.

---

*[python/topology/generator.py, line 708 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn4diG4eK9pbW1mywI7:-Kn4diG4eK9pbW1mywI8:b-f8i4z7) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/topology/generator.py#L708)):*
> ```Python
> class PrometheusGenerator(object):
>     PROM_DIR = "prometheus"
>     BR_TARGET_FILE = "prometheus.yml"
> ```

There should be a target file for each element type.

---

*[python/topology/generator.py, line 722 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn4ZXjtGWSaV0CNOOkv:-Kn4ZXjtGWSaV0CNOOkw:b-1603v6) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/topology/generator.py#L722)):*
> ```Python
>             for svc_type in ["BeaconService", "PathService", "CertificateService"]:
>                 for elem_id, elem in as_topo[svc_type].items():
>                     router_list.append(_prom_addr_infra(elem))
> ```

`router_list`? That needs renaming. This also puts all targets under a single job, which is undesirable. Each type of element needs to be in its own job (and hence also in its own config).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1135)*

**Comment by kormat** [comment]
Review status: 5 of 20 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[python/scion_elem/scion_elem.py, line 1130 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn4U5IaqNhzIOImOOlk:-Kn4drF59pMrrQ4Ez5ar:bkua0tz) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L1130)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Nooo. The server id needs to be a label on every metric that gets exported. Otherwise you can't do _any_ correlation.
</blockquote></details>

We probably also want an isd_as label.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1135)*

**Comment by shitz** [comment]
Review status: 3 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[python/scion_elem/scion_elem.py, line 871 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn3mXxalyYVrsSpFP1c:-KnAPk9L71bhzLNHqMpb:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L871)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These are never decremented for packets which aren't dropped. `_packet_process` needs to be modified.

Also, `PKT_BUF_TOTAL` is directly calculable from  `self._in_buf.qsize()`.
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 881 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn3ot-zzJM3S3wpzapi:-KnAPvP3OLH96_oyQrbf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L881)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This could be moved up to `dropped += 1`, so that it's grouped with the other metric updates.
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 919 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn3p4IsNFibGJX2TF_0:-KnAPzhTj1t98vK5eqaK:b-dx1xk8) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L919)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Uh? There's 3 _other_ return statements in this method that only return 2 values. I also can't find any call site that expects 3 return values.
</blockquote></details>

Good catch. That's some orphan from an intermediate version. Removed.

---

*[python/scion_elem/scion_elem.py, line 1130 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn4U5IaqNhzIOImOOlk:-KnAQSlsP_0frFiTOEOy:b-fwwb5t) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L1130)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

We probably also want an isd_as label.
</blockquote></details>

You can join the `server_id` with whatever other metrics you want on the `instance` label that gets added by the client library by default, e.g.:
`scion_server_id * on(instance) group_right(server_id)   rate(ps_reqs_total[30s])`
This is an actual multiplication, but the `scion_server_id` metric always has value 1, so it works. The base idea is from here: https://www.robustperception.io/how-to-have-labels-for-machine-roles/ 
Doesn't this give you the same thing as adding the server_id label to every metric that you export?

---

*[python/topology/generator.py, line 708 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn4diG4eK9pbW1mywI7:-KnDnriHas37CoFqcHq8:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/topology/generator.py#L708)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There should be a target file for each element type.
</blockquote></details>

Done.

---

*[python/topology/generator.py, line 722 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn4ZXjtGWSaV0CNOOkv:-KnDnrKUIheb_vmul6Jt:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/topology/generator.py#L722)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`router_list`? That needs renaming. This also puts all targets under a single job, which is undesirable. Each type of element needs to be in its own job (and hence also in its own config).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1135)*

**Comment by shitz** [comment]
Review status: 3 of 20 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[python/scion_elem/scion_elem.py, line 1130 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-Kn4U5IaqNhzIOImOOlk:-Kne71h7CkM_dmBD9ppG:bfaedbu) ([raw file](https://github.com/netsec-ethz/scion/blob/4a73ecb4d5f0bbd6e9b6339dc167037662f27cb3/python/scion_elem/scion_elem.py#L1130)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You can join the `server_id` with whatever other metrics you want on the `instance` label that gets added by the client library by default, e.g.:
`scion_server_id * on(instance) group_right(server_id)   rate(ps_reqs_total[30s])`
This is an actual multiplication, but the `scion_server_id` metric always has value 1, so it works. The base idea is from here: https://www.robustperception.io/how-to-have-labels-for-machine-roles/ 
Doesn't this give you the same thing as adding the server_id label to every metric that you export?
</blockquote></details>

I added `server_id` and `isd_as` labels to every metric.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1135)*

**Comment by kormat** [comment]
I've only looked at this very quickly, but from what i've seen, LGTM.

---

Reviewed 2 of 12 files at r2.
Review status: 5 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-:-KneCrSz6xbQX8WNcGMK:b-rehc0e)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 8 of 20 files at r1, 12 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-:-Knig_yu45cA_vgZ57pc:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1135)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1135#-:-KnjRmG-LEk0YMyJLKVh:bnfp4nl)*

**Pull request merged**
