### PR TITLE
Trc certificate update

### PR DESCRIPTION
**Pull request by sezergueler**
TRC synchronized with book. (Online/offline root keys added, verification adjusted.)

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/962)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[lib/util.py, line 90 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcIdx8ljZmZWrW-Sblh:-KcIdx8ljZmZWrW-Sbli:b26qogw) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/util.py#L90)):*
> ```Python
> def get_online_key_file_path(conf_dir):  # pragma: no cover
>     """
>     Return the signing key file path.
> ```

Needs updating. Same for the next method.

---

*[lib/crypto/certificate_chain.py, line 30 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcIjTBuLmhr6Ioiy4Ee:-KcIjTBuLmhr6Ioiy4Ef:b-l4d3r7) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/certificate_chain.py#L30)):*
> ```Python
> from lib.crypto.trc import (
>     TRC,
>     ONLINE_KEY_STRING,
> ```

Sort imports.

---

*[lib/crypto/trc.py, line 87 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcIta4q03VjjM4H6xv_:-KcIta4q03VjjM4H6xva:b-bxz32h) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L87)):*
> ```Python
>         CORE_ASES_STRING: ("core_ases", dict),
>         ROOT_CAS_STRING: ("root_cas", dict),
>         PKI_LOGS_STRING: ("logs", dict),
> ```

Rename to `pki_logs`?

---

*[lib/crypto/trc.py, line 110 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcItnAZN5Pl-BxAS3yg:-KcItnAZN5Pl-BxAS3yh:bpi087g) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L110)):*
> ```Python
>         for subject in trc_dict[CORE_ASES_STRING]:
>             dec = base64.b64decode(
>                 trc_dict[CORE_ASES_STRING][subject][ONLINE_KEY_STRING]). \
> ```

Hah, it's not even clear to me how that's valid python, but moving the `)` to the next line makes it read properly again.

---

*[lib/crypto/trc.py, line 112 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNUHOqblXH45jMY8Hp:-KcNUHOrvuHv20FI-SJ6:b-rkjxcj) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L112)):*
> ```Python
>                 trc_dict[CORE_ASES_STRING][subject][ONLINE_KEY_STRING]). \
>                 decode("utf-8")
>             self.core_ases[subject][ONLINE_KEY_STRING] = base64.b64decode(dec)
> ```

This gets b64decoded _twice_?

---

*[lib/crypto/trc.py, line 165 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNUNj8Nlkn_zcl9hJm:-KcNUNj8Nlkn_zcl9hJn:b-5zl77f) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L165)):*
> ```Python
>             CORE_ASES_STRING: core_ases,
>             ROOT_CAS_STRING: root_cas,
>             PKI_LOGS_STRING: logs,
> ```

`pki_logs`

---

*[topology/generator.py, line 52 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNUa7Wtc8bXiVldaoa:-KcNUa7Wtc8bXiVldaob:b-l4d3r7) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/topology/generator.py#L52)):*
> ```Python
>     ONLINE_KEY_STRING,
>     OFFLINE_KEY_ALG_STRING,
>     OFFLINE_KEY_STRING,
> ```

Sort imports.

---

*[topology/generator.py, line 343 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNVApoJehV2uC1cbRW:-KcNVApoJehV2uC1cbRX:b2n8w9o) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/topology/generator.py#L343)):*
> ```Python
> 
>     def is_core(self, as_conf):
>         return "core" in as_conf and as_conf["core"]
> ```

Can be simplified to `return as_conf.get("core")`

---

*[topology/generator.py, line 363 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNVbxzmC32tE0wwAV4:-KcNVbxzmC32tE0wwAV5:b89znzq) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/topology/generator.py#L363)):*
> ```Python
>     def _create_trc(self, isd):
>         self.trcs[isd] = TRC.from_values(
>             isd, '', 0, {}, {'ca.com': 'ca.com_cert_base64'}, {},
> ```

I'd use a non-empty description, like `"ISD %s" % isd`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/962)*

**Comment by pszalach** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[lib/crypto/certificate.py, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcSvW_fIBM8ts9r-CWZ:-KcSvW_fIBM8ts9r-CW_:b-kbib2c) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/certificate.py#L126)):*
> ```Python
>         return True
> 
>     def verify_core(self, pub_online_root_key):
> ```

any description?

---

*[lib/crypto/certificate_chain.py, line 124 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcSvZJiCuX6KbmWNZOT:-KcSvZJiCuX6KbmWNZOU:b32uwx) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/certificate_chain.py#L124)):*
> ```Python
>             subject = cert.subject
>         # First check whether a root cert was added to the chain.
>         if not cert.issuer == subject:
> ```

!=

---

*[lib/crypto/trc.py, line 36 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcSw6vwiPz89caLOAdr:-KcSw6vwiPz89caLOAds:bysrzja) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L36)):*
> ```Python
> VERSION_STRING = 'Version'
> CREATION_TIME_STRING = 'CreationTime'
> EXPIRATION_TIME_STRING = 'ExpirationTime'
> ```

we don't have that it (at least now)

---

*[lib/crypto/trc.py, line 191 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcSvwFIUZcd2sFmEuVI:-KcSvwFIUZcd2sFmEuVJ:bfi42f3) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L191)):*
> ```Python
>         :rtype: bool
>         """
>         # Check if TRC expired
> ```

TRCs don't expire (did we decide that they do?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/962)*

**Comment by sezergueler** [comment]
Review status: 0 of 5 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[lib/util.py, line 90 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcIdx8ljZmZWrW-Sblh:-KcYb5tZb9ttL6KtTJ3S:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/util.py#L90)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Needs updating. Same for the next method.
</blockquote></details>

Done.

---

*[lib/crypto/certificate.py, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcSvW_fIBM8ts9r-CWZ:-KcYbw4UzrPpXFd2Ciz2:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/certificate.py#L126)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

any description?
</blockquote></details>

Done.

---

*[lib/crypto/certificate_chain.py, line 30 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcIjTBuLmhr6Ioiy4Ee:-KcYc6ABbyD2E-DevSbE:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/certificate_chain.py#L30)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Sort imports.
</blockquote></details>

Done.

---

*[lib/crypto/certificate_chain.py, line 124 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcSvZJiCuX6KbmWNZOT:-KcYcCznwfiou07O9E0A:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/certificate_chain.py#L124)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

!=
</blockquote></details>

Done.

---

*[lib/crypto/trc.py, line 36 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcSw6vwiPz89caLOAdr:-KcYcu3AkXEpPmGOqcbF:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L36)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

we don't have that it (at least now)
</blockquote></details>

Done.

---

*[lib/crypto/trc.py, line 87 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcIta4q03VjjM4H6xv_:-KcYdGViGnR0ogpS2U3t:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L87)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Rename to `pki_logs`?
</blockquote></details>

Done.

---

*[lib/crypto/trc.py, line 110 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcItnAZN5Pl-BxAS3yg:-KcYdX5DnxrrGsfwBSGH:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L110)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Hah, it's not even clear to me how that's valid python, but moving the `)` to the next line makes it read properly again.
</blockquote></details>

Done.

---

*[lib/crypto/trc.py, line 112 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNUHOqblXH45jMY8Hp:-KcYdaCOLLFBMRQxjl-o:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L112)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This gets b64decoded _twice_?
</blockquote></details>

Done.

---

*[lib/crypto/trc.py, line 165 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNUNj8Nlkn_zcl9hJm:-KcYdcV_UfRRpFTMtdTJ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L165)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`pki_logs`
</blockquote></details>

Done.

---

*[lib/crypto/trc.py, line 191 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcSvwFIUZcd2sFmEuVI:-KcYddlQr80320UA7aX-:b-1i3hle) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/lib/crypto/trc.py#L191)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

TRCs don't expire (did we decide that they do?)
</blockquote></details>

We did not conclude, so I added it. I removed it again.

---

*[topology/generator.py, line 52 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNUa7Wtc8bXiVldaoa:-KcYe53VS4bfMMk1aeGX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/topology/generator.py#L52)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Sort imports.
</blockquote></details>

Done.

---

*[topology/generator.py, line 343 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNVApoJehV2uC1cbRW:-KcYeZ5Y-ehGjLjBw73k:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/topology/generator.py#L343)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Can be simplified to `return as_conf.get("core")`
</blockquote></details>

Done.

---

*[topology/generator.py, line 363 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-KcNVbxzmC32tE0wwAV4:-KcYevMb9Pd2wYEvA6Gn:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/3da98d49aea78528eb0714e02a757611f52638df/topology/generator.py#L363)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'd use a non-empty description, like `"ISD %s" % isd`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/962)*

**Comment by sezergueler** [comment]
@kormat @pszalach Done, ready for review.

**Comment by pszalach** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-:-KccJf9W_GIOfkiAhnFh:bnfp4nl)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/962#-:-Kcck1bLKHuCgxOIzfPJ:bnfp4nl)*

**Pull request merged**
