### PR TITLE
CMAC instead of CBC-MAC

### LINKED ISSUE #985: CBC-MAC -> CMAC
Switch from CBC-MAC to CMAC for hop field MACing.

### LINKED ISSUE #1003: Replace pycrypto
Pycrypto hasn't had a stable release since 2013, and even the "latest" experimental release is from 2014. It should be considered dead, and we should move to a replacement. It looks like both pynacl (which we already use in some places), and cryptography.io can fulfill our needs in combination.

### PR DESCRIPTION
**Pull request by pszalach**
fixes #985
~~CMAC.py is taken from the current version of pycrypto (unfortunately, currently neither `apt` nor `pip` provide it)~~
fixes #1003 

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/999)

### CODE REVIEW

**Comment by kormat** [comment]
Holding off on reviewing this until https://github.com/netsec-ethz/scion/issues/1003 is done.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-:-KeIzCf7l5-gwTRpiANd:b-4yj4dn)*

**Comment by pszalach** [comment]
@kormat it is ready

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-:-Kffexj0mr-b30LGydAd:b-tkcx2p)*

**Comment by kormat** [comment]
Reviewed 19 of 21 files at r1.
Review status: 19 of 21 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[go/lib/util/mac.go, line 22 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvYnJdqGl3V3ZTZOiq:-KfvYnJdqGl3V3ZTZOir:b-hmmouq) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/go/lib/util/mac.go#L22)):*
> ```Go
> 
> 	log "github.com/inconshreveable/log15"
> ```

There should not be a blank line here. The grouping of imports is stdlib, external, and project (same as with python).

---

*[go/lib/util/mac.go, line 23 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfqT2Ats6JBHBA4FP5b:-Kfv_JAPMzGnGZIUMKq_:b-8fx2u7) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/go/lib/util/mac.go#L23)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Did you check that this is a commonly used cmac implementation for Go?
</blockquote></details>

:+1: 

---

*[go/lib/util/mac.go, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvZQ2iEWUATVyirGzc:-KfvZQ2iEWUATVyirGzd:b-om92dh) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/go/lib/util/mac.go#L48)):*
> ```Go
> 	mac.Write(msg)
> 	tmp := make([]byte, 0, 0)
> 	tag := mac.Sum(tmp)
> ```

This.. passes in an empty slice? Why? Oh. that's the buffer that it writes out to. In that case make sure you create it with the capacity of the output, but with len 0. You also don't actually need to save the return value, if you do that correctly.

What does `tag` mean?

---

*[lib/crypto/hash_tree.py, line 45 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfqPGB8S2irfPlU9S2b:-Kfv_LuvMsrLPBykhcz9:b-8fx2u7) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/lib/crypto/hash_tree.py#L45)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You should at least define the interface of the hash function that can be plugged in.
</blockquote></details>

:+1: 

---

*[lib/packet/pcb.py, line 291 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvXJjEq61EpsTv1zb-:-KfvXJjEq61EpsTv1zb0:bc5wxf1) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/lib/packet/pcb.py#L291)):*
> ```Python
>         the path segment.
>         """
>         data = b""
> ```

This isn't very efficient. The data gets copied multiple times.
```
data = []
for ...:
  ...
  data.append(asm.isd_as().pack()
  data.append(struct.pack(...)
data = b"".join(data)
if hex:
  ...
```

---

*[sub/lwip, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfqQFAyzabelcNkBIFv:-Kfv_Ng29FxrkQ4z1Z97:b-8fx2u7) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/sub/lwip#L1)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

intended?
</blockquote></details>

:+1: 

---

*[test/lib/crypto/hash_tree_test.py, line 75 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvY-LvgRSPpLHzspsN:-KfvY-LvgRSPpLHzspsO:b-b6cuwb) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/test/lib/crypto/hash_tree_test.py#L75)):*
> ```Python
>                   b"0", b"30s300", b"10s1020s20", b"10s1020s2030s300"]
>         hash_func = create_mock()
>         hash_func.side_effect = hashes
> ```

`hash_func = create_mock_full(side_effect=hashes)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999)*

**Comment by pszalach** [comment]
Review status: 19 of 21 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[go/lib/util/mac.go, line 22 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvYnJdqGl3V3ZTZOiq:-KgUjqp7ybjaeNEGasmj:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/go/lib/util/mac.go#L22)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There should not be a blank line here. The grouping of imports is stdlib, external, and project (same as with python).
</blockquote></details>

Done.

---

*[go/lib/util/mac.go, line 23 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfqT2Ats6JBHBA4FP5b:-KgUjr9VQEZFIITxQ-nl:bpefs6n) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/go/lib/util/mac.go#L23)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

This is the best I've found, however, cmac doesn't seem to be popular in go projects (I also couldn't find a reason why it was dropped from the standard lib).

---

*[go/lib/util/mac.go, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvZQ2iEWUATVyirGzc:-KgUkKuFqGFGAxqCtb3U:b-2f87f1) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/go/lib/util/mac.go#L48)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This.. passes in an empty slice? Why? Oh. that's the buffer that it writes out to. In that case make sure you create it with the capacity of the output, but with len 0. You also don't actually need to save the return value, if you do that correctly.

What does `tag` mean?
</blockquote></details>

`Sum()` appends mac to a message, so to get only mac I pass an empty message.
`tag` is other name of a MAC scheme's output.

---

*[lib/crypto/hash_tree.py, line 45 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfqPGB8S2irfPlU9S2b:-KgUl3tGgu8l7adGjw9z:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/lib/crypto/hash_tree.py#L45)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.

---

*[lib/packet/pcb.py, line 291 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvXJjEq61EpsTv1zb-:-KgUlCc0RGTgQd0M8P86:b-fr362c) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/lib/packet/pcb.py#L291)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This isn't very efficient. The data gets copied multiple times.
```
data = []
for ...:
  ...
  data.append(asm.isd_as().pack()
  data.append(struct.pack(...)
data = b"".join(data)
if hex:
  ...
```
</blockquote></details>

Done. But "... premature optimization is the root of all evil." ;-)

---

*[sub/lwip, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfqQFAyzabelcNkBIFv:-KgUlctdYEoNv3Zw2rct:bos1ttn) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/sub/lwip#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

actually, yes.

---

*[test/lib/crypto/hash_tree_test.py, line 75 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvY-LvgRSPpLHzspsN:-KgUo0cARQbFtsOAsbBV:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/test/lib/crypto/hash_tree_test.py#L75)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`hash_func = create_mock_full(side_effect=hashes)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999)*

**Comment by kormat** [comment]
Reviewed 2 of 21 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[go/lib/util/mac.go, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvZQ2iEWUATVyirGzc:-KgnZeIvd57iJBsK9wCB:btxqrj5) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/go/lib/util/mac.go#L48)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

`Sum()` appends mac to a message, so to get only mac I pass an empty message.
`tag` is other name of a MAC scheme's output.
</blockquote></details>

My suggested changes are still outstanding.

---

*[sub/lwip, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfqQFAyzabelcNkBIFv:-Kgn_-oKdsMYcd-R4VdA:boe5xqh) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/sub/lwip#L1)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

actually, yes.
</blockquote></details>

There's nothing in the PR description that says why these submodules are changing. Manually looking at the change, that's completely unrelated to this PR. Please put it in a separate PR.

---

*[sub/web, line 1 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-Kgn_R3aauVrvU3XcCGC:-Kgn_R3bqV5jqkGX8Sj6:b-muhid8) ([raw file](https://github.com/netsec-ethz/scion/blob/556b71c2b324ceddd2bc96bb9c28f0f7d520f16f/sub/web#L1)):*
> ```
> Subproject commit d18e88e110ee57cde790edcf4839f13ef526d2ca
> ```

Argh. This **reverts** `sub/web` by **21** commits. Please, rebase on master, and remove all submodule updates from this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999)*

**Comment by pszalach** [comment]
Review status: 18 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/lib/util/mac.go, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfvZQ2iEWUATVyirGzc:-KhX1MQLPjP1ob1tU_jS:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/go/lib/util/mac.go#L48)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

My suggested changes are still outstanding.
</blockquote></details>

Done.

---

*[sub/lwip, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KfqQFAyzabelcNkBIFv:-KhX2RfEZ7XDiqinD-WK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/c139683098d15d3649ffb39117eb5c74ca95444a/sub/lwip#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There's nothing in the PR description that says why these submodules are changing. Manually looking at the change, that's completely unrelated to this PR. Please put it in a separate PR.
</blockquote></details>

Done.

---

*[sub/web, line 1 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-Kgn_R3aauVrvU3XcCGC:-KhX2STy_IiIs6nX5nr0:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/556b71c2b324ceddd2bc96bb9c28f0f7d520f16f/sub/web#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Argh. This **reverts** `sub/web` by **21** commits. Please, rebase on master, and remove all submodule updates from this PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-:-KiAzMRyzI5-6vHtHZa2:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 2 of 3 files at r4, 10 of 11 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[env/debian/pkgs.txt, line 52 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KkQMsoLgZ1tRhqbYAxy:-KkQMsoLgZ1tRhqbYAxz:bz5qgv1) ([raw file](https://github.com/netsec-ethz/scion/blob/b3ec83f7ee63d079eef179bc3e2a34ac08a7a1c5/env/debian/pkgs.txt#L52)):*
> ```
> uthash-dev
> xtail
> zlib1g-dev
> ```

This is a dependency of `libssl-dev`, so it doesn't need to be listed separately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999)*

**Comment by pszalach** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[env/debian/pkgs.txt, line 52 at r5](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-KkQMsoLgZ1tRhqbYAxy:-KkQOfDJ5nHO0EUcGT5V:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/b3ec83f7ee63d079eef179bc3e2a34ac08a7a1c5/env/debian/pkgs.txt#L52)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is a dependency of `libssl-dev`, so it doesn't need to be listed separately.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-:-KkQUFoh9ifGiVLoM-d0:bnfp4nl)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999#-:-KkQ_jisesKgATV5BfoS:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/999)*

**Pull request merged**
