### PR TITLE
Bug fix in TRC

### PR DESCRIPTION
**Pull request by sezergueler**
There was an expression without assignment in trc class

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/998)

### CODE REVIEW

**Comment by pszalach** [comment]
This changes a lot more than you described. Why the assignments  with `SIGNATURES_STRING` are gone?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/998#-:-KeDMKmyFUo-ETMUZRW5:b4b9o9i)*

**Comment by sezergueler** [comment]
Because the sign function was already encoding it and the signatures were hold in encoded format. You are right, I changed it again. I removed encoding from sign function. Now it is consistent with root_ca certificates and core_ases keys.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/998#-:-KeDdkIAekI6gR4MVbgm:bjmjb84)*

**Comment by ercanucan** [comment]
@sezergueler I can confirm that this fixes the `to_json()` function. I gave some minor comments. In general, the changes look good to me. I am not very familiar with the implementation so it would be good if @pszalach or @kormat could also take a look.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/crypto/trc.py, line 109 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/998#-KecnY-T6xPZIF7AE_41:-KecnY-T6xPZIF7AE_42:b-4s838y) ([raw file](https://github.com/netsec-ethz/scion/blob/25d47b824588d7d4c3188b6815c254f1780b7654/lib/crypto/trc.py#L109)):*
> ```Python
>             self.core_ases[subject][ONLINE_KEY_STRING] = \
>                 base64.b64decode(key_.encode('utf-8'))
>             key_ = trc_dict[CORE_ASES_STRING][subject][OFFLINE_KEY_STRING]
> ```

Is there a particular reason why you name the variable as `key_` instead of just `key`? `key` is not a reserved word in Python. I guess you could name them `key` similar to the way you do in `get_core_ases()` function.

---

*[lib/crypto/trc.py, line 254 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/998#-KeconYeRr1RsGOUfM6M:-KeconYfX0UweVSFZq9X:b-qhn86o) ([raw file](https://github.com/netsec-ethz/scion/blob/25d47b824588d7d4c3188b6815c254f1780b7654/lib/crypto/trc.py#L254)):*
> ```Python
>             d = trc_dict[CORE_ASES_STRING][subject]
>             for key_ in (ONLINE_KEY_STRING, OFFLINE_KEY_STRING, ):
>                 key_str = trc_dict[CORE_ASES_STRING][subject][key_]
> ```

This is now a `bytes` object right? So the variable name should probably not have the `_str` anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/998#-:-KecpYdepUGOyjFamZwh:b-m6ogs1)*

**Comment by sezergueler** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/crypto/trc.py, line 109 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/998#-KecnY-T6xPZIF7AE_41:-Kecv4tP4Y1rwL51EnYz:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/25d47b824588d7d4c3188b6815c254f1780b7654/lib/crypto/trc.py#L109)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Is there a particular reason why you name the variable as `key_` instead of just `key`? `key` is not a reserved word in Python. I guess you could name them `key` similar to the way you do in `get_core_ases()` function.
</blockquote></details>

Done.

---

*[lib/crypto/trc.py, line 254 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/998#-KeconYeRr1RsGOUfM6M:-Kecv5hJzqYhdsrFAQHR:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/25d47b824588d7d4c3188b6815c254f1780b7654/lib/crypto/trc.py#L254)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

This is now a `bytes` object right? So the variable name should probably not have the `_str` anymore.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/998)*

**Comment by kormat** [comment]
The change itself LGTM, but what i'm wondering is how this bug wasn't caught by any tests.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/998#-:-Keh6VVK0QJZXVpdWMum:bye4a0q)*

**Comment by ercanucan** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/998)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/998#-:-KehgRUWuhgcwRvkf6gv:bnfp4nl)*

**Comment by sezergueler** [comment]
Signatures were hold in encoded format -> Encoding from sign function was removed and moved to init to make it consistent with root_ca certificates and core_ases keys.

Core ASes offline keys, were not initialized on trc init -> Added initialization of offline keys

There was an expression without assignment inside the to_json function, online/offline root keys were not encoded here. This bug was not detected, beacuse the keys were already encoded in generator -> Encoding of online/offline keys was removed from generator and the assignment in to_json was fixed. 

CA certificate addition to trc in generator.py was moved from _create_trc to ge_trc_entry, this makes it more consistent since core_as entries are also added there.

**Pull request merged**
