### PR TITLE
Add a tool to prune/reduce topologies

### PR DESCRIPTION
**Pull request by klausman**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1230)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/topology/raw.go, line 37 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNwf0oeFRZxzgY4R1c:-KsNwf0oeFRZxzgY4R1d:b1mljrv) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/raw.go#L37)):*
> ```Go
> 
> // The contents of the topo file (unprocessed) when we last loaded it
> var DiskTopo []byte
> ```

I would prefer to refactor a bit such that there doesn't need to be a module-level variable for this. You could have `func Load(b common.RawBytes) *Topo`, `LoadFromFile(path string) *Topo`, `LoadRaw(b common.RawBytes) *RawTopo`, `LoadRawFromFile(path string) *RawTopo`, with the `FromFile` variants loading the file, and then calling the bare variants. That way a caller which cares about havnig the raw file would have called ioutil.ReadFile on it themselves, and then called `Load` or `LoadRaw` with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by kormat** [comment]
Reviewed 1 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/lib/topology/strip.go, line 24 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNy3gRHh1Iv28ODk2r:-KsNy3gRHh1Iv28ODk2s:b-khyicz) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L24)):*
> ```Go
> 	// Clear services that don't need to be publicly visible
> 	rt.BeaconService = make(map[string]RawAddrInfo)
> 	// TODO(klausman): Does the public *really* not care about SIBRA?
> ```

For now, no. If/when the sibra service gets implemented, maybe.

---

*[go/lib/topology/strip.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNyCVzjHQ01bZe7_Y1:-KsNyCVzjHQ01bZe7_Y2:bxexpy) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L31)):*
> ```Go
> func StripBind(rt *RawTopo) {
> 	// These services may have Bind sections that we need to remove
> 	removeSVCBind(rt.CertificateService)
> ```

`SVC` is a bit of an unfortunate term, as that generally implies SVC addresses, which aren't in topo files. `removeSrvBind`?

---

*[go/lib/topology/strip.go, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNyTgOw3ksrgCpyO-R:-KsNyTgOw3ksrgCpyO-S:bfzxiqb) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L48)):*
> ```Go
> func removeBRBind(brs map[string]RawBRInfo) {
> 	for name, bri := range brs {
> 		newias := make([]RawAddrInfo, 0)
> ```

`newIntAddrs` is probably clearer.

---

*[go/lib/topology/strip.go, line 55 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNyxLyLX_tLLMfdOEg:-KsNyxLyLX_tLLMfdOEh:bnvg5ip) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L55)):*
> ```Go
> 		for id, brintf := range bri.Interfaces {
> 			// The nil elements are of no interest to the public
> 			nbrintf := RawBRIntf{
> ```

This can be assigned directly. `newifds[id] = nbrintf`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by kormat** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[go/lib/topology/strip.go, line 29 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsO-6qC5EnvPjSr6bHO:-KsO-6qC5EnvPjSr6bHP:b8vv59q) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L29)):*
> ```Go
> }
> 
> func StripBind(rt *RawTopo) {
> ```

As this is the more general function, i'd put it at the top.

---

*[go/tools/topopruner/topopruner.go, line 34 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNzHD6qoG_WezeHxnX:-KsNzHD6qoG_WezeHxnY:b-2p6s7e) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/tools/topopruner/topopruner.go#L34)):*
> ```Go
> }
> 
> func main() {
> ```

Our convention puts main at the top, so order roughly follows execution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[go/lib/topology/raw.go, line 37 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNwf0oeFRZxzgY4R1c:-KsO30znbtmWfQMmcKtS:bx73sng) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/raw.go#L37)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I would prefer to refactor a bit such that there doesn't need to be a module-level variable for this. You could have `func Load(b common.RawBytes) *Topo`, `LoadFromFile(path string) *Topo`, `LoadRaw(b common.RawBytes) *RawTopo`, `LoadRawFromFile(path string) *RawTopo`, with the `FromFile` variants loading the file, and then calling the bare variants. That way a caller which cares about havnig the raw file would have called ioutil.ReadFile on it themselves, and then called `Load` or `LoadRaw` with that.
</blockquote></details>

This var can be nuked now.

---

*[go/lib/topology/raw.go, line 189 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsO2uUsnn5CdDqX6LT1:-KsO2uUsnn5CdDqX6LT2:b-ufi6m0) ([raw file](https://github.com/netsec-ethz/scion/blob/76921d0b194ea6757c993f2a39551e9502192e53/go/lib/topology/raw.go#L189)):*
> ```Go
> 		return nil, common.NewError(ErrorOpen, "err", err, "path", path)
> 	}
> 	rt, cerr := LoadRaw(b)
> ```

This can just be `return LoadRaw(b)`. Same for `LoadFromFile`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by klausman** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[go/lib/topology/raw.go, line 37 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNwf0oeFRZxzgY4R1c:-KsO31LKgVViYOTPwm5T:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/raw.go#L37)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I would prefer to refactor a bit such that there doesn't need to be a module-level variable for this. You could have `func Load(b common.RawBytes) *Topo`, `LoadFromFile(path string) *Topo`, `LoadRaw(b common.RawBytes) *RawTopo`, `LoadRawFromFile(path string) *RawTopo`, with the `FromFile` variants loading the file, and then calling the bare variants. That way a caller which cares about havnig the raw file would have called ioutil.ReadFile on it themselves, and then called `Load` or `LoadRaw` with that.
</blockquote></details>

Done.

---

*[go/lib/topology/raw.go, line 189 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsO2uUsnn5CdDqX6LT1:-KsO480Rb99oovOBwdcK:b6yqbwe) ([raw file](https://github.com/netsec-ethz/scion/blob/76921d0b194ea6757c993f2a39551e9502192e53/go/lib/topology/raw.go#L189)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can just be `return LoadRaw(b)`. Same for `LoadFromFile`.
</blockquote></details>

This function *is* `LoadRaw()`

---

*[go/lib/topology/strip.go, line 29 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsO-6qC5EnvPjSr6bHO:-KsO38kg7aREsSFWoG-8:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L29)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As this is the more general function, i'd put it at the top.
</blockquote></details>

Done.

---

*[go/lib/topology/strip.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNyCVzjHQ01bZe7_Y1:-KsO3Zt3VioW_OCyeX7T:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L31)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`SVC` is a bit of an unfortunate term, as that generally implies SVC addresses, which aren't in topo files. `removeSrvBind`?
</blockquote></details>

Done.

---

*[go/lib/topology/strip.go, line 48 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNyTgOw3ksrgCpyO-R:-KsO3mlZYtccyWnYtWJL:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L48)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`newIntAddrs` is probably clearer.
</blockquote></details>

Done.

---

*[go/lib/topology/strip.go, line 55 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNyxLyLX_tLLMfdOEg:-KsO3rzg7zlDF8UUykU3:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L55)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be assigned directly. `newifds[id] = nbrintf`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by klausman** [comment]
Review status: 3 of 6 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[go/tools/topopruner/topopruner.go, line 34 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNzHD6qoG_WezeHxnX:-KsO4qJGhboerUt39o22:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/tools/topopruner/topopruner.go#L34)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Our convention puts main at the top, so order roughly follows execution.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by klausman** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[go/lib/topology/raw.go, line 37 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNwf0oeFRZxzgY4R1c:-KsO5-Pu4WrvvikCdqsY:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/raw.go#L37)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by klausman** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[go/lib/topology/strip.go, line 24 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNy3gRHh1Iv28ODk2r:-KsO5AVHdl7FpqjyOu8i:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L24)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

For now, no. If/when the sibra service gets implemented, maybe.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by klausman** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[go/lib/topology/raw.go, line 189 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsO2uUsnn5CdDqX6LT1:-KsO5DFm9cXZ12-CG1wd:b-ry5gl1) ([raw file](https://github.com/netsec-ethz/scion/blob/76921d0b194ea6757c993f2a39551e9502192e53/go/lib/topology/raw.go#L189)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This function *is* `LoadRaw()`
</blockquote></details>

And here Reviewable outright lied to me. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by kormat** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/topology/strip.go, line 29 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsO-6qC5EnvPjSr6bHO:-KsO6yZedjoCaRz6Phs9:b-6rd3g2) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L29)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not visible.

---

*[go/lib/topology/strip.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNyCVzjHQ01bZe7_Y1:-KsO6zcl45SsRutnc7g7:b-6rd3g2) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L31)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not visible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by klausman** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/topology/strip.go, line 29 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsO-6qC5EnvPjSr6bHO:-KsO7KX5mUXjLVYJT1m9:b-7us23c) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L29)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Not visible.
</blockquote></details>

GoRename is a dick and undoes my changes. Lovely. Fixed now.

---

*[go/lib/topology/strip.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-KsNyCVzjHQ01bZe7_Y1:-KsO7aUwh-Z6YOTDXRBq:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/e8da7632517c94052725e0240d5459b5ab108bdf/go/lib/topology/strip.go#L31)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Not visible.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1230#-:-KsO7xyP9vBAJgRAXbwJ:bnfp4nl)*

**Pull request merged**
