### PR TITLE
Cleaned up logging in path server and beacon server.

### PR DESCRIPTION
**Pull request by shitz**
Cleaned up logging in path server and beacon server. Introduced custom path request logger. Moved logging from PathStore and asymcrypto to applications. This part of the effort to clean up logging in Python (see #984)

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1076)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 295 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkFLb_Orsx9kdJHv8oN:-KkFLb_Orsx9kdJHv8oO:byakn4r) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/scion_elem.py#L295)):*
> ```Python
>                 seg_meta.meta.close()
>             seg_meta.callback(seg_meta)
>         except SCIONVerificationError:
> ```

`try`/`except` should contain the minimum amount of code. If this exception can only be caused by `_verify_path_seg`, then wrap only it in try/except, and put a return after `logging.error`.

Also, it's good to include the original exception in the log message.

---

*[infrastructure/beacon_server/base.py, line 430 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGUnM5nIzdXPclqckl:-KkGUnM5nIzdXPclqckm:b-cfeugs) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/beacon_server/base.py#L430)):*
> ```Python
>             # at this point, there should be <= HASHTREE_UPDATE_WINDOW
>             # seconds left in current ttl
>             logging.info("Started computing hashtree for next ttl (%d)", cur_ttl_window + 2)
> ```

I would use "next TTL window" so it's at least a bit clearer (though why this isn't all referring to epoch i don't know :( ).

---

*[infrastructure/beacon_server/base.py, line 440 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGV--hS8EQD3P1_D7p:-KkGV--hS8EQD3P1_D7q:b-i7oqrb) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/beacon_server/base.py#L440)):*
> ```Python
>             with self._hash_tree_lock:
>                 self._next_tree = tree
>             logging.info("Finished computing hashtree for TTL %d in %.3fs" %
> ```

TTL window

---

*[infrastructure/beacon_server/local.py, line 77 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGVefi2QAefOumnZxU:-KkGVefi2QAefOumnZxV:beq41wf) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/beacon_server/local.py#L77)):*
> ```Python
>         dst_ia = pcb.asm(0).isd_as()
>         meta = self.DefaultMeta.from_values(ia=dst_ia, host=SVCType.PS_A, path=core_path)
>         logging.debug("Registering down-segment to %s: %s" % (meta, pcb.short_desc()))
> ```

s/to/with/ is less ambiguous. Same for up-segment.

---

*[infrastructure/path_server/base.py, line 255 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGVwLwCcwO7NoTe2fT:-KkGVwLxzOm67aQ0iv0S:bckjgr5) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/path_server/base.py#L255)):*
> ```Python
>                                 DBResult.ENTRY_DELETED):
>                             up_segs_removed += 1
>             logging.debug("Removed segments containing IF %d: UP: %d DOWN: %d CORE: %d" %
> ```

Please include the relevant AS (that the ifid belongs to).

---

*[infrastructure/path_server/base.py, line 480 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGWDK79nRRq9_edAKV:-KkGWDK79nRRq9_edAKW:b-yrvoer) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/path_server/base.py#L480)):*
> ```Python
>         Initializes the request logger.
>         """
>         logging.debug("_init_request_logger")
> ```

Still needed?

---

*[infrastructure/path_server/base.py, line 493 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGXXdjCDwy7VlOczPi:-KkGXXdk5cit8HLOBB_z:b-7z7rgw) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/path_server/base.py#L493)):*
> ```Python
>         """
>         # Random ID to relate log entries for a request.
>         req_id = random.randint(0, 2**32 - 1)
> ```

`"%08x" % random.randint(0, 2**32 - 1)`. Gives constant width, doesn't have `0x` prefix, and is already pre-formatted :)

---

*[infrastructure/path_server/core.py, line 359 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGYe_en2ijjRyaAo51:-KkGYe_en2ijjRyaAo52:bczj2u6) ([raw file](https://github.com/netsec-ethz/scion/blob/e57ec9b33baa02a442eae4cdb60f58e22d2b1ffc/infrastructure/path_server/core.py#L359)):*
> ```Python
>                  rev_isd_as[0] != self.addr.isd_as[0])):
>             logging.debug("Propagating Revocation of IF %d to other cores."
>                           % rev_info.p.ifID)
> ```

Why remove this? Not useful?

---

*[lib/log.py, line 84 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGJEvuXuIjovw0Ayqz:-KkGJEvuXuIjovw0Ayr-:bkv0yfx) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/lib/log.py#L84)):*
> ```Python
> 
> def add_formatter(name, formatter):  # pragma: no cover
>     global _dispatch_formatter
> ```

This isn't needed, as you're not doing an assignment in this function.

---

*[lib/path_store.py, line 329 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGMaGye2EcM5UvcTMj:-KkGMaGye2EcM5UvcTMk:b-o7mn55) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/lib/path_store.py#L329)):*
> ```Python
>             self.path_policy.check_filters(pcb)
>         except SCIONPathPolicyViolated:
>             print("mooo")
> ```

Really? :) :cow: 

---

*[lib/crypto/certificate.py, line 111 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGMkPy1S3rprIR146I:-KkGMkPy1S3rprIR146J:b-r6rdd8) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/lib/crypto/certificate.py#L111)):*
> ```Python
>         if subject != self.subject:
>             raise SCIONVerificationError(
>                 "The given subject(%s) doesn't match the certificate's subject(%s):\n%s" %
> ```

Put a space before the `(%s)`'s.

---

*[lib/crypto/certificate_chain.py, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGNGDyICipptGXsbAJ:-KkGNGDyICipptGXsbAK:bskakq9) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/lib/crypto/certificate_chain.py#L126)):*
> ```Python
>             cert.verify_core(trc.core_ases[cert.issuer][ONLINE_KEY_STRING])
>         except SCIONVerificationError:
>             raise SCIONVerificationError("Core AS certificate verification failed.")
> ```

Is there only one possible reason for the error? If not, include the original exception in the message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1076)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 295 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkFLb_Orsx9kdJHv8oN:-KkGq0KXsS7XweEzn3sP:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/scion_elem.py#L295)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`try`/`except` should contain the minimum amount of code. If this exception can only be caused by `_verify_path_seg`, then wrap only it in try/except, and put a return after `logging.error`.

Also, it's good to include the original exception in the log message.
</blockquote></details>

Done.

---

*[infrastructure/beacon_server/base.py, line 430 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGUnM5nIzdXPclqckl:-KkGqBzcM_o402wYJFmZ:bui8qs4) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/beacon_server/base.py#L430)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I would use "next TTL window" so it's at least a bit clearer (though why this isn't all referring to epoch i don't know :( ).
</blockquote></details>

Done. It's not referring to epochs because a TTL window consists of X epochs.

---

*[infrastructure/beacon_server/base.py, line 440 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGV--hS8EQD3P1_D7p:-KkGqNdLhtcchJTD_7Q8:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/beacon_server/base.py#L440)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

TTL window
</blockquote></details>

Done.

---

*[infrastructure/beacon_server/local.py, line 77 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGVefi2QAefOumnZxU:-KkGqWH5dTT60h5Lovv4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/beacon_server/local.py#L77)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

s/to/with/ is less ambiguous. Same for up-segment.
</blockquote></details>

Done.

---

*[infrastructure/path_server/base.py, line 255 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGVwLwCcwO7NoTe2fT:-KkGrBKOhVZpi9OPDtOo:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/path_server/base.py#L255)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Please include the relevant AS (that the ifid belongs to).
</blockquote></details>

Done.

---

*[infrastructure/path_server/base.py, line 480 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGWDK79nRRq9_edAKV:-KkGrF1tVAQ5XADM8l_N:bu2j3sr) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/path_server/base.py#L480)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Still needed?
</blockquote></details>

Nope. Removed.

---

*[infrastructure/path_server/base.py, line 493 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGXXdjCDwy7VlOczPi:-KkGrOloN9g0nl9PByRg:b14qjgr) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/infrastructure/path_server/base.py#L493)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`"%08x" % random.randint(0, 2**32 - 1)`. Gives constant width, doesn't have `0x` prefix, and is already pre-formatted :)
</blockquote></details>

:+1: Done.

---

*[infrastructure/path_server/core.py, line 359 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGYe_en2ijjRyaAo51:-KkGrzm5Xj-LqKi6ASL_:brrmaw) ([raw file](https://github.com/netsec-ethz/scion/blob/e57ec9b33baa02a442eae4cdb60f58e22d2b1ffc/infrastructure/path_server/core.py#L359)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Why remove this? Not useful?
</blockquote></details>

Not sure if it's useful, but I doesn't hurt I guess.

---

*[lib/log.py, line 84 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGJEvuXuIjovw0Ayqz:-KkGsFJoQYOF6sn649z3:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/lib/log.py#L84)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This isn't needed, as you're not doing an assignment in this function.
</blockquote></details>

Done.

---

*[lib/path_store.py, line 329 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGMaGye2EcM5UvcTMj:-KkGsN-3IHxH33iahf1b:b-9koxa8) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/lib/path_store.py#L329)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Really? :) :cow: 
</blockquote></details>

:face_with_thermometer: 

---

*[lib/crypto/certificate.py, line 111 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGMkPy1S3rprIR146I:-KkGsh0EOZVKdqrwtpbL:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/lib/crypto/certificate.py#L111)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Put a space before the `(%s)`'s.
</blockquote></details>

Done.

---

*[lib/crypto/certificate_chain.py, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkGNGDyICipptGXsbAJ:-KkGsycofPbP3omhYwrI:bdugrs9) ([raw file](https://github.com/netsec-ethz/scion/blob/dae035051509564e1abb3984ac6ea30282bddbf6/lib/crypto/certificate_chain.py#L126)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Is there only one possible reason for the error? If not, include the original exception in the message.
</blockquote></details>

It's the only reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1076)*

**Comment by kormat** [comment]
Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[infrastructure/beacon_server/base.py, line 310 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLUr5u7W8bfY6azVfs:-KkLUr5u7W8bfY6azVft:b-ajkl9q) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/infrastructure/beacon_server/base.py#L310)):*
> ```Python
>     def _log_registrations(self, registrations, seg_type):
>         for dst_ps, pcbs in registrations.items():
>             logging.debug("Registered %d %s-segments to %s (%s)", len(pcbs),
> ```

s/`to`/@`/ - the ambiguity throws me.

---

*[infrastructure/beacon_server/core.py, line 122 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLX-EQ4L1qkZPyxoJI:-KkLX-EQ4L1qkZPyxoJJ:bvo7rdl) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/infrastructure/beacon_server/core.py#L122)):*
> ```Python
>             addr, port = self.dns_query_topo(SIBRA_SERVICE)[0]
>         except SCIONServiceLookupError:
>             return ps_meta
> ```

Wait, why return this if there's an exception? There's only a single caller, which already handles this exception.n

---

*[infrastructure/beacon_server/local.py, line 68 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLYV6wwy10Ulw2xHaK:-KkLYV6wwy10Ulw2xHaL:b-ani1yj) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/infrastructure/beacon_server/local.py#L68)):*
> ```Python
>             addr, port = self.dns_query_topo(SIBRA_SERVICE)[0]
>         except SCIONServiceLookupError:
>             return ps_meta
> ```

Same question here as for core.

---

*[infrastructure/beacon_server/local.py, line 123 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLYgPslMMFtT8RR_lc:-KkLYgPslMMFtT8RR_ld:baggd82) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/infrastructure/beacon_server/local.py#L123)):*
> ```Python
>             for k, v in propagated.items():
>                 propagated_pcbs[k].extend(v)
>         for (isd_as, if_id), pcbs in propagated_pcbs.items():
> ```

Seeing as this code occurs 3 times, maybe make a method for it in `base`, like `_log_registrations`.

---

*[lib/packet/scion_addr.py, line 211 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLSYL_lEYbA89kOmJc:-KkLSYL_lEYbA89kOmJd:b-zg37d3) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/lib/packet/scion_addr.py#L211)):*
> ```Python
>         Return a string containing ISD-AS, and host address.
>         """
>         return "(%s (%s) %s)" % (self.isd_as or "local", self.host.name(), self.host)
> ```

When does it happen that `isd_as` isn't set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1076)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[infrastructure/beacon_server/base.py, line 310 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLUr5u7W8bfY6azVfs:-KkLa9WJiBznGgun29QO:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/infrastructure/beacon_server/base.py#L310)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

s/`to`/@`/ - the ambiguity throws me.
</blockquote></details>

Done.

---

*[infrastructure/beacon_server/core.py, line 122 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLX-EQ4L1qkZPyxoJI:-KkLs57Y179di_JZKhdA:b-3nyyzv) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/infrastructure/beacon_server/core.py#L122)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Wait, why return this if there's an exception? There's only a single caller, which already handles this exception.n
</blockquote></details>

Refactored the code to take a service type argument as discussed offline.

---

*[infrastructure/beacon_server/local.py, line 68 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLYV6wwy10Ulw2xHaK:-KkLsAM2Y07I8_97SAfj:b-7ropln) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/infrastructure/beacon_server/local.py#L68)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Same question here as for core.
</blockquote></details>

ditto

---

*[infrastructure/beacon_server/local.py, line 123 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLYgPslMMFtT8RR_lc:-KkLt4OWeaXoLCPGQxdf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/infrastructure/beacon_server/local.py#L123)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Seeing as this code occurs 3 times, maybe make a method for it in `base`, like `_log_registrations`.
</blockquote></details>

Done.

---

*[lib/packet/scion_addr.py, line 211 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-KkLSYL_lEYbA89kOmJc:-KkLtBg5ho1N88qH_g5P:bsu1kru) ([raw file](https://github.com/netsec-ethz/scion/blob/c12bc94ffe93d02024ea54e9f926bc2853c52233/lib/packet/scion_addr.py#L211)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

When does it happen that `isd_as` isn't set?
</blockquote></details>

It used to happen when the destination was local. Now with Pawel's changes `_build_meta` sets `isd_as` to the local one, so this is not needed anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1076)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1076#-:-KkPpwFK1eOslhF5ckpV:bnfp4nl)*

**Pull request merged**
