### PR TITLE
Fix connection closing race in python e2e

### PR DESCRIPTION
**Pull request by scrye**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1245)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/lib/util.py, line 267 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1245#-KtHdr6rrMB9w-k_1f0l:-KtHdr6rrMB9w-k_1f0m:b-g3tyzq) ([raw file](https://github.com/netsec-ethz/scion/blob/de805f516934ee9b98ace331542df43ba5ad0376/python/lib/util.py#L267)):*
> ```Python
>         except ConnectionResetError:
>             # Client closed the connection without reading
>             logging.error("socket closed by client")
> ```

This assumes the remote end is the client. "Connection reset by peer" is more accurate i think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1245)*

**Comment by scrye** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/lib/util.py, line 267 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1245#-KtHdr6rrMB9w-k_1f0l:-KtHeQlyLArVz_Wp8pfM:b-clh693) ([raw file](https://github.com/netsec-ethz/scion/blob/de805f516934ee9b98ace331542df43ba5ad0376/python/lib/util.py#L267)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This assumes the remote end is the client. "Connection reset by peer" is more accurate i think.
</blockquote></details>

Good point, updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1245)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/lib/util.py, line 266 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1245#-KtHeZ9u7Cd3H6i3dIUT:-KtHeZ9u7Cd3H6i3dIUU:bnhu2jw) ([raw file](https://github.com/netsec-ethz/scion/blob/000163a8c096a2ee2c9f682f7fc5b52246010004/python/lib/util.py#L266)):*
> ```Python
>             continue
>         except ConnectionResetError:
>             # Client closed the connection without reading
> ```

Comment still assumes client.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1245)*

**Comment by scrye** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/lib/util.py, line 266 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1245#-KtHeZ9u7Cd3H6i3dIUT:-KtHf1CVIizL_5kp8Q8V:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/000163a8c096a2ee2c9f682f7fc5b52246010004/python/lib/util.py#L266)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Comment still assumes client.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1245)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1245#-:-KtHf7OKz8esZiUx7hlt:bnfp4nl)*

**Pull request merged**
