### PR TITLE
add waiting time to the packet generator.

### PR DESCRIPTION
**Pull request by forstern**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1043)

### CODE REVIEW

**Comment by forstern** [comment]
@ercanucan @kormat

**Comment by forstern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/pktgen.py, line 102 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1043#-KhSSkUHuZ_juvLF8F6R:-KhSSkUHuZ_juvLF8F6S:bjcv0vq) ([raw file](https://github.com/netsec-ethz/scion/blob/dab1fba37cc833575f9e35696b22a0966f7ac43b/tools/pktgen.py#L102)):*
> ```Python
>     api_path_default = os.path.join(SCIOND_API_SOCKDIR, "sd%s.sock" % src.isd_as)
>     api_path = os.getenv(SCIOND_API_PATH_ENV_VAR) or api_path_default
>     gen = PktGen(b"data", "finished", src, dst, 3000, size=args.size)
> ```

Can someone verify that I can just remove api_path? After a commit of Sam the signature of the methods changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1043)*

**Comment by shitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/pktgen.py, line 102 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1043#-KhSSkUHuZ_juvLF8F6R:-KhSpbCD1-im6inL3sKi:bdd9k4b) ([raw file](https://github.com/netsec-ethz/scion/blob/dab1fba37cc833575f9e35696b22a0966f7ac43b/tools/pktgen.py#L102)):*
<details><summary><i>Previously, forstern (Nicolas Forster) wrote…</i></summary><blockquote>

Can someone verify that I can just remove api_path? After a commit of Sam the signature of the methods changed.
</blockquote></details>

Yes you can remove it. You only need to provide an API path if you don't use the default SCIOND for the source AS.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1043)*

**Comment by ercanucan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1043#-:-KiAFM2ist2ledieFJnZ:bnfp4nl)*

**Comment by ercanucan** [comment]
Please rebase

**Comment by forstern** [comment]
done

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1043#-:-KiAIu_a6Gg02Gzt2KZw:bb7f2mf)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1043#-:-KiAyb-pb3i38gDCc_2g:bnfp4nl)*

**Pull request merged**
