### PR TITLE
Simplified IngressWorker to not handle reordering anymore

### PR DESCRIPTION
**Pull request by shitz**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1178)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/sig/base/ingress.go, line 111 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-Kpsk3w9ZCmx_C6sFO_i:-Kpsk3w9ZCmx_C6sFO_j:bm8hmjc) ([raw file](https://github.com/netsec-ethz/scion/blob/adc67b74db8c40ba274ebb482d6297e2249929cb/go/sig/base/ingress.go#L111)):*
> ```Go
> func (fb *FrameBuf) ProcessCompletePkts() {
> 	if fb.index == 0 || fb.completePktsProcessed {
> 		fb.completePktsProcessed = true
> ```

It turns out that this gets set in all cases in this function, so you might as well just set it unconditionally at the top.

---

*[go/sig/base/ingress.go, line 288 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-Kpsn1OAu4MHr0mC99-d:-Kpsn1OAu4MHr0mC99-e:b-yr1a8i) ([raw file](https://github.com/netsec-ethz/scion/blob/adc67b74db8c40ba274ebb482d6297e2249929cb/go/sig/base/ingress.go#L288)):*
> ```Go
> 	// If there is a gap between this frame and the last in the reassembly list,
> 	// remove all packets from the reassembly list and only add this frame.
> 	if frame.seqNr > lastFrame.seqNr+1 {
> ```

A `!=` would be more conservative, though maybe explicitly logging an error if `frame.seqNr` isn't valid would be better.

---

*[go/sig/base/ingress.go, line 329 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-KpsnkEgNKADQbt-_c0z:-KpsnkEgNKADQbt-_c1-:biv9t9h) ([raw file](https://github.com/netsec-ethz/scion/blob/adc67b74db8c40ba274ebb482d6297e2249929cb/go/sig/base/ingress.go#L329)):*
> ```Go
> 	start := l.entries.Front()
> 	startFrame := start.Value.(*FrameBuf)
> 	bytes := startFrame.frameLen - startFrame.frag0Start
> ```

Add a check to make sure that there _is_ a frag0 in this frame, and error otherwise. Just.. paranoia.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1178)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/sig/base/ingress.go, line 111 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-Kpsk3w9ZCmx_C6sFO_i:-KpssMs-fBg-igYIjtVf:b-q9uhyl) ([raw file](https://github.com/netsec-ethz/scion/blob/adc67b74db8c40ba274ebb482d6297e2249929cb/go/sig/base/ingress.go#L111)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It turns out that this gets set in all cases in this function, so you might as well just set it unconditionally at the top.
</blockquote></details>

But then I would immediately return ;) I removed this statement as it gets set at the end of the method.

---

*[go/sig/base/ingress.go, line 288 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-Kpsn1OAu4MHr0mC99-d:-KpssvY9ZBwOxjgVIf9J:b-sqq2zu) ([raw file](https://github.com/netsec-ethz/scion/blob/adc67b74db8c40ba274ebb482d6297e2249929cb/go/sig/base/ingress.go#L288)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

A `!=` would be more conservative, though maybe explicitly logging an error if `frame.seqNr` isn't valid would be better.
</blockquote></details>

Changed to `!=` not sure if it is an error though. Receiving frame out-of-order is totally within the specification.

---

*[go/sig/base/ingress.go, line 329 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-KpsnkEgNKADQbt-_c0z:-Kpsthbqttv9rgO4L88f:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/adc67b74db8c40ba274ebb482d6297e2249929cb/go/sig/base/ingress.go#L329)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Add a check to make sure that there _is_ a frag0 in this frame, and error otherwise. Just.. paranoia.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1178)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/sig/base/ingress.go, line 288 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-Kpsn1OAu4MHr0mC99-d:-KpsueuIebURIjU4c6Iv:bnhjedu) ([raw file](https://github.com/netsec-ethz/scion/blob/adc67b74db8c40ba274ebb482d6297e2249929cb/go/sig/base/ingress.go#L288)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Changed to `!=` not sure if it is an error though. Receiving frame out-of-order is totally within the specification.
</blockquote></details>

This would only be triggered by a bug in the code, not by real-world data. If it ever happened that due to a bug you have a hole in the list, then this error log would make it obvious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1178)*

**Comment by shitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/sig/base/ingress.go, line 288 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-Kpsn1OAu4MHr0mC99-d:-KpswfrEvbpyx7YjSK1d:b-5jaq9m) ([raw file](https://github.com/netsec-ethz/scion/blob/adc67b74db8c40ba274ebb482d6297e2249929cb/go/sig/base/ingress.go#L288)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This would only be triggered by a bug in the code, not by real-world data. If it ever happened that due to a bug you have a hole in the list, then this error log would make it obvious.
</blockquote></details>

Added an explicit check for duplicate frames.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1178)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/sig/base/ingress.go, line 111 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-Kpsk3w9ZCmx_C6sFO_i:-Kpswmc-JFZxoyBm_pTW:blvbz8r) ([raw file](https://github.com/netsec-ethz/scion/blob/adc67b74db8c40ba274ebb482d6297e2249929cb/go/sig/base/ingress.go#L111)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

But then I would immediately return ;) I removed this statement as it gets set at the end of the method.
</blockquote></details>

I was wrong :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1178#-:-Kpsx97-Vn6fm60S1t3F:bnfp4nl)*

**Pull request merged**
