### PR TITLE
Added a check for the current interface and the router's interface.

### PR DESCRIPTION
**Pull request by shitz**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/956)

### CODE REVIEW

**Comment by klausman** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[infrastructure/router/main.py, line 464 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_i8rIhobwk82hDsTk4:-K_i8rIhobwk82hDsTk5:bf8987k) ([raw file](https://github.com/netsec-ethz/scion/blob/8cf9422ff1f6b530d0f171361f054cdfa0fb656e/infrastructure/router/main.py#L464)):*
> ```Python
>         prev_hof = path.get_hof_ver(ingress=ingress)
>         # Check that the interface in the current hop field matches the
>         # interface in the current hop field.
> ```

This comment is tautological.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/956)*

**Comment by shitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[infrastructure/router/main.py, line 464 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_i8rIhobwk82hDsTk4:-K_i9EoYETSEeLH8uqtm:bymi2ww) ([raw file](https://github.com/netsec-ethz/scion/blob/8cf9422ff1f6b530d0f171361f054cdfa0fb656e/infrastructure/router/main.py#L464)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This comment is tautological.
</blockquote></details>

Brainfart.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/956)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-:-K_i9lQIBTn_34udiTdr:bnfp4nl)*

**Comment by shitz** [comment]
Thx. Merging after CircleCI gives green light.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-:-K_iAXeVzzFNKJRs6Rir:b-mo51er)*

**Comment by kormat** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[infrastructure/router/errors.py, line 25 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_iPvqNAjzgXsbBadCQ:-K_iPvqOZzJnYDT6MVdg:bktozk5) ([raw file](https://github.com/netsec-ethz/scion/blob/f485c34644bea8dd1f5a273e109f4181220fe81d/infrastructure/router/errors.py#L25)):*
> ```Python
> class SCIONIFVerificationError(SCIONBaseError):
>     """
>     The current interface does not match the interface of the border router.
> ```

"current interface" is ambiguous.

---

*[infrastructure/router/main.py, line 465 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_iQ8fgoFr3Cdy9aZV5:-K_iQ8fgoFr3Cdy9aZV6:b-yq6c) ([raw file](https://github.com/netsec-ethz/scion/blob/f485c34644bea8dd1f5a273e109f4181220fe81d/infrastructure/router/main.py#L465)):*
> ```Python
>         # Check that the interface in the current hop field matches the
>         # interface in the router.
>         if self.interface.if_id not in [hof.ingress_if, hof.egress_if]:
> ```

Which it is compared against should really be dependant on the direction of the packet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/956)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[infrastructure/router/errors.py, line 25 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_iPvqNAjzgXsbBadCQ:-K_iQ_roQBVTzuuoyvEV:b-zhv7sb) ([raw file](https://github.com/netsec-ethz/scion/blob/f485c34644bea8dd1f5a273e109f4181220fe81d/infrastructure/router/errors.py#L25)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"current interface" is ambiguous.
</blockquote></details>

Suggestions?

---

*[infrastructure/router/main.py, line 465 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_iQ8fgoFr3Cdy9aZV5:-K_iQd_hgnaiycyCqsOj:b-qyazoo) ([raw file](https://github.com/netsec-ethz/scion/blob/f485c34644bea8dd1f5a273e109f4181220fe81d/infrastructure/router/main.py#L465)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Which it is compared against should really be dependant on the direction of the packet.
</blockquote></details>

Not really. As long as the interface ID is unique within the AS, this works fine. The Go router also does it this way if I'm not mistaken.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/956)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[infrastructure/router/errors.py, line 25 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_iPvqNAjzgXsbBadCQ:-K_iQwJ2l_q8BbavMaoi:b-8paa1s) ([raw file](https://github.com/netsec-ethz/scion/blob/f485c34644bea8dd1f5a273e109f4181220fe81d/infrastructure/router/errors.py#L25)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Suggestions?
</blockquote></details>

I suggest you make it less ambiguous. ;) "The current hop field (ingress or egress, depending on context) interface does not match the interface of the border router" maybe?

---

*[infrastructure/router/main.py, line 465 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_iQ8fgoFr3Cdy9aZV5:-K_ieAMpCfdhoz1tAhY2:b-ixtcs7) ([raw file](https://github.com/netsec-ethz/scion/blob/f485c34644bea8dd1f5a273e109f4181220fe81d/infrastructure/router/main.py#L465)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Not really. As long as the interface ID is unique within the AS, this works fine. The Go router also does it this way if I'm not mistaken.
</blockquote></details>

The Go router checks the correct one depending on the direction when retrieving it from the Hop Field: https://github.com/netsec-ethz/scion/blob/master/go/border/rpkt/path.go#L358

Otherwise things like a router accidentally forwarding a packet to itself will pass this check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/956)*

**Comment by shitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[infrastructure/router/errors.py, line 25 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_iPvqNAjzgXsbBadCQ:-KbuXad1PD8Aw9U2HDMf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f485c34644bea8dd1f5a273e109f4181220fe81d/infrastructure/router/errors.py#L25)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I suggest you make it less ambiguous. ;) "The current hop field (ingress or egress, depending on context) interface does not match the interface of the border router" maybe?
</blockquote></details>

Done.

---

*[infrastructure/router/main.py, line 465 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-K_iQ8fgoFr3Cdy9aZV5:-KbuXbdeotmeprTDrK1b:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f485c34644bea8dd1f5a273e109f4181220fe81d/infrastructure/router/main.py#L465)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The Go router checks the correct one depending on the direction when retrieving it from the Hop Field: https://github.com/netsec-ethz/scion/blob/master/go/border/rpkt/path.go#L358

Otherwise things like a router accidentally forwarding a packet to itself will pass this check.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/956)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/956#-:-Kby1axXrg4QcBP9g8g7:bnfp4nl)*

**Pull request merged**
