### PR TITLE
Update wireshark dissector, handle common/address header.

### PR DESCRIPTION
**Pull request by kormat**
The existing wireshark dissector has been unmainainted and woefully
outdated for a couple of years. This is a ~fresh start, and currently
handles the common and address headers. Later PRs will expand the
support.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1317)

### CODE REVIEW

**Comment by klausman** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/wireshark/scion.lua, line 58 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1317#-KyVsQQbJRwyE-w4BjsK:-KyVsQQbJRwyE-w4BjsL:bqjngx9) ([raw file](https://github.com/netsec-ethz/scion/blob/d2c7885fed46833232b3ccf9d082107b5e3bcc9f/tools/wireshark/scion.lua#L58)):*
> ```Lua
> local scion_ch_ver_expert = ProtoExpert.new("scion.ch.version.expert",
>     "Unsupported SCION version", expert.group.MALFORMED, expert.severity.ERROR)
> local scion_ch_addrtype_expert = ProtoExpert.new("scion.ch.addrtype.expert",
> ```

Why is the second arg here just ""?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1317)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/wireshark/scion.lua, line 58 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1317#-KyVsQQbJRwyE-w4BjsK:-KyVyrz3bnWkYrLlMavZ:b-gm266s) ([raw file](https://github.com/netsec-ethz/scion/blob/d2c7885fed46833232b3ccf9d082107b5e3bcc9f/tools/wireshark/scion.lua#L58)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Why is the second arg here just ""?
</blockquote></details>

The second arg is the default error string, but for most of these errors the default is never used, as there are multiple possible problems, each with their own string provided when the expert is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1317)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1317#-:-KyW5sXtteXz4MVUL6n9:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1317)*

**Pull request merged**
