### PR TITLE
New peer revocation handling.

### PR DESCRIPTION
**Pull request by shitz**
Simplified peer revocation handling a lot. A path server now adds revocations for peer interfaces to every path reply. Also implemented a revocation cache that for more efficient access to revocations by (ISD_AS, if_id).

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/979)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed everything except tests for this pass. Generally looks really good.

---

Reviewed 11 of 13 files at r1.
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[infrastructure/path_server/base.py, line 290 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-KdzE89jUXlBFwWSTgir:-KdzE89jUXlBFwWSTgis:bm2aexf) ([raw file](https://github.com/netsec-ethz/scion/blob/a2b12d7133bab07875bc386fb420002b18c34ec6/infrastructure/path_server/base.py#L290)):*
> ```Python
>             "Sending PATH_REPLY with %d segment(s) to:%s "
>             "port:%s in response to: %s", len(all_segs),
>             meta.get_addr(), meta.port, req,
> ```

Why the change from `req.short_desc()` to `req`? From a quick test, the old format gives:
```
PathSegmentReq: 2-23 -> 1-16 (())
```
and the new format gives:
PathSegmentReq: PathSegmentReq: 2-23 -> 2-24 (())
```
```


---

*[lib/packet/path_mgmt/seg_recs.py, line 80 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-KdzYXEgqX-9YHiXnMiI:-KdzYXEgqX-9YHiXnMiJ:bnuz2el) ([raw file](https://github.com/netsec-ethz/scion/blob/a2b12d7133bab07875bc386fb420002b18c34ec6/lib/packet/path_mgmt/seg_recs.py#L80)):*
> ```Python
>                 s.append("  %s:" % PST.to_str(type_))
>             s.append("    %s" % pcb.short_desc())
>         for rev_info in rev_infos:
> ```

`for rev_info in self.iter_rev_infos()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-:-KdzYhGFyfKHNtYEioFL:b-12sios)*

**Comment by shitz** [comment]
Review status: 10 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[infrastructure/path_server/base.py, line 290 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-KdzE89jUXlBFwWSTgir:-KdzlHQ7T1i--YTuLGwp:bqvpup8) ([raw file](https://github.com/netsec-ethz/scion/blob/a2b12d7133bab07875bc386fb420002b18c34ec6/infrastructure/path_server/base.py#L290)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Why the change from `req.short_desc()` to `req`? From a quick test, the old format gives:
```
PathSegmentReq: 2-23 -> 1-16 (())
```
and the new format gives:
PathSegmentReq: PathSegmentReq: 2-23 -> 2-24 (())
```
</blockquote></details>

Mostly because there is a `__str__` method and no `short_desc()` on `PathSegmentReq`.  I think dumping the `__str__` is better than dumping`self.p`, since `__str__` calls `short_desc` on `rev_info`. Removed the extra "PathSegmentReq".

---

*[lib/packet/path_mgmt/seg_recs.py, line 80 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-KdzYXEgqX-9YHiXnMiI:-KdzlNByIksbjdWh2MJD:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/a2b12d7133bab07875bc386fb420002b18c34ec6/lib/packet/path_mgmt/seg_recs.py#L80)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`for rev_info in self.iter_rev_infos()`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/979)*
<!-- Sent from Reviewable.io -->

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r2.
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[infrastructure/path_server/base.py, line 290 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-KdzE89jUXlBFwWSTgir:-KdzrlK_P_qwBEW5cAiD:bvtw5d6) ([raw file](https://github.com/netsec-ethz/scion/blob/a2b12d7133bab07875bc386fb420002b18c34ec6/infrastructure/path_server/base.py#L290)):*
> Removed the extra "PathSegmentReq".

Lies. Did you not push it yet?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/979)*

**Comment by kormat** [comment]
Reviewed 2 of 13 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[test/lib/rev_cache_test.py, line 31 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Kdzvd4GTvWqEQi0aPiU:-Kdzvd4H4i13aoIFEqD_:b-lrqsed) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L31)):*
> ```Python
> class TestRevCacheGet:
>     """Unit tests for lib.rev_cache.RevCache.get"""
>     @patch("lib.rev_cache.RevCache._validate_entry", new_callable=create_mock)
> ```

As `_validate_entry` is not a class(/static) method, you don't need to patch it like this. You can just do `rev_cache._validate_entry = create_mock()`.

---

*[test/lib/rev_cache_test.py, line 39 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Kdzw8J3J7tTYJoql5fF:-Kdzw8J3J7tTYJoql5fG:b-ctsyr) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L39)):*
> ```Python
>         rev_cache._cache[key] = rev_info
>         validate_entry.return_value = True
>         # Test
> ```

The convention in our python tests is to use `# Call` for the actual call being tested (even if the call line directly contains a test itself), and `# Tests` for any subsequent post-call tests.

---

*[test/lib/rev_cache_test.py, line 40 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Kdzw6qar2OyRovQSYYB:-Kdzw6qar2OyRovQSYYC:bij1tq2) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L40)):*
> ```Python
>         validate_entry.return_value = True
>         # Test
>         ntools.eq_(rev_cache.get(key, default=default), rev_info)
> ```

There needs to be a check to make sure _validate_entry was called. E.g. `assert_these_calls(rev_cache._validate_entry, [rev_info])`.

---

*[test/lib/rev_cache_test.py, line 81 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke-R02SHKTzb1NcdukE:-Ke-R02SHKTzb1NcdukF:b-oksblu) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L81)):*
> ```Python
>         ret = rev_cache.add(rev_info)
>         # Tests
>         ntools.assert_true(ret)
> ```

This can be done on the `Call` line.

---

*[test/lib/rev_cache_test.py, line 96 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke-Sxe2MAHNjld38Lyy:-Ke-Sxe3Fd2f2R_xNSc_:b-1nuqn0) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L96)):*
> ```Python
>            new_callable=create_mock)
>     @patch("lib.rev_cache.RevCache.__getitem__", new_callable=create_mock)
>     def test_same_entry_exists(self, get_item, verify_epoch):
> ```

Needs a similar test when the new rev_info is for a later epoch (or did i miss that one?).

---

*[test/lib/packet/path_test.py, line 967 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke-TttkcM-3gVElOh3m:-Ke-TttkcM-3gVElOh3n:b4z69en) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/packet/path_test.py#L967)):*
> ```Python
>             if key in data:
>                 return data[key]
>             return None
> ```

Can be simplified to just `return data.get(key)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/979)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[infrastructure/path_server/base.py, line 290 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-KdzE89jUXlBFwWSTgir:-Ke2ilr_v7ha8eHhDI4-:bq41wjw) ([raw file](https://github.com/netsec-ethz/scion/blob/a2b12d7133bab07875bc386fb420002b18c34ec6/infrastructure/path_server/base.py#L290)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

> Removed the extra "PathSegmentReq".

Lies. Did you not push it yet?
</blockquote></details>

Disregard what I said about `short_desc()` not being present. `PathSegmentReq` actually implements it and I reverted to using it again.

---

*[test/lib/rev_cache_test.py, line 31 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Kdzvd4GTvWqEQi0aPiU:-Ke2mtKLqeRfOpQMu1z4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L31)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As `_validate_entry` is not a class(/static) method, you don't need to patch it like this. You can just do `rev_cache._validate_entry = create_mock()`.
</blockquote></details>

Done.

---

*[test/lib/rev_cache_test.py, line 39 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Kdzw8J3J7tTYJoql5fF:-Ke2ojcEUlJ3ivOEo5rg:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L39)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The convention in our python tests is to use `# Call` for the actual call being tested (even if the call line directly contains a test itself), and `# Tests` for any subsequent post-call tests.
</blockquote></details>

Done.

---

*[test/lib/rev_cache_test.py, line 40 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Kdzw6qar2OyRovQSYYB:-Ke33Em_OBqkfs7eSL2R:b5gmhkc) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L40)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There needs to be a check to make sure _validate_entry was called. E.g. `assert_these_calls(rev_cache._validate_entry, [rev_info])`.
</blockquote></details>

Done and added a couple more `assert_these_calls`

---

*[test/lib/rev_cache_test.py, line 81 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke-R02SHKTzb1NcdukE:-Ke33LQa8xGGbhK3SDsY:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L81)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be done on the `Call` line.
</blockquote></details>

Done.

---

*[test/lib/rev_cache_test.py, line 96 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke-Sxe2MAHNjld38Lyy:-Ke33Sj4W00yJNPn4H-1:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L96)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Needs a similar test when the new rev_info is for a later epoch (or did i miss that one?).
</blockquote></details>

Done.

---

*[test/lib/packet/path_test.py, line 967 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke-TttkcM-3gVElOh3m:-Ke33zRIY6Quc2I3PRew:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/packet/path_test.py#L967)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Can be simplified to just `return data.get(key)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/979)*

**Comment by kormat** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/lib/rev_cache_test.py, line 96 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke-Sxe2MAHNjld38Lyy:-Ke4-WFtMYcNOWnaYj6B:b-4by1fv) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L96)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Uh, the test you added was the opposite actually :)

---

*[test/lib/rev_cache_test.py, line 38 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke3MsSowAACKVycDvz7:-Ke3MsSpLzwSo7dYic00:b-rht2vv) ([raw file](https://github.com/netsec-ethz/scion/blob/acddb72e504f7b9b82b79bbf5f7568cca083a7f4/test/lib/rev_cache_test.py#L38)):*
> ```Python
>         rev_cache._cache[key] = rev_info
>         rev_cache._validate_entry = create_mock()
>         rev_cache._validate_entry.return_value = True
> ```

Ah, i had forgotten, but you can just do `rev_cache._validate_entry = create_mock_full(return_value=True)` in a single line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/979)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/lib/rev_cache_test.py, line 96 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke-Sxe2MAHNjld38Lyy:-Ke4dJuHMEOtQ7RprIiA:b-65no41) ([raw file](https://github.com/netsec-ethz/scion/blob/6ff58f601d49370ca2080e5015f2cd171ef10a00/test/lib/rev_cache_test.py#L96)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Uh, the test you added was the opposite actually :)
</blockquote></details>

My bad. Added that test as well.

---

*[test/lib/rev_cache_test.py, line 38 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-Ke3MsSowAACKVycDvz7:-Ke4c9Jv3flZpiC9u9Zq:b-y0rvb6) ([raw file](https://github.com/netsec-ethz/scion/blob/acddb72e504f7b9b82b79bbf5f7568cca083a7f4/test/lib/rev_cache_test.py#L38)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Ah, i had forgotten, but you can just do `rev_cache._validate_entry = create_mock_full(return_value=True)` in a single line.
</blockquote></details>

Done. This doesn't work if you want to set the return value to `None`. In these cases I still manually set it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/979)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/979#-:-Ke8FYevr0Dzd023Comj:bnfp4nl)*

**Pull request merged**
