### PR TITLE
Add doc describing path reversal.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/948)

### CODE REVIEW

**Comment by kormat** [comment]
@shitz @pszalach @klausman

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/948#-:-KYZIAFVaPbosZOvAfLC:bnfp4nl)*

**Comment by shitz** [comment]
Thx for this @kormat

**Comment by pszalach** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/948#-:-KYZkbJAgMVPN3YEcWaN:bnfp4nl)*

**Pull request merged**
