### PR TITLE
Make all go code consistently use the error interface.

### PR DESCRIPTION
**Pull request by kormat**
Mixing *common.Error and error has been casuing a fair amount of
problems, so this change switches everything to use the error interface.

- The type has been renamed to *common.CError, to make old references
  obvious.
- All old `cerr` variables have been renamed to `err`.
- (Unchecked) type assertions are used everywhere code actually cares
  about the concrete error type.

Also:
- Remove abortive go/discovery skeleton.
- Run `infrarunning`-tagged go tests via `integration_test.sh`.
- Did some fixing of HSR code, but far from complete, so it still
  doesn't compile.
- Remove error return from OverlayFromIP, as there is never an error
  generated.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1247)

### CODE REVIEW

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 103 of 103 files at r1, 4 of 10 files at r2.
Review status: 101 of 107 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1247#-:-KtMobGBaCeO3zz4DyH1:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 6 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1247)*

**Comment by shitz** [comment]
Reviewed 7 of 103 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1247)*

**Comment by shitz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1247#-:-KtMreAI87DHG3LuROTd:bnfp4nl)*

**Comment by shitz** [comment]
Reviewed 1 of 10 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1247)*

**Comment by scrye** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1247#-:-KtMsEs_GrZiOtMX6rbJ:bnfp4nl)*

**Pull request merged**
