### PR TITLE
Nonblocking send_msg() with TCP and other fixes

### PR DESCRIPTION
**Pull request by pszalach**
- nonblocking send_msg() with TCP (see #944)
- fix in PS with prematurely closed connections
- less annoying logging
- sub/lwip-contrib updated

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/952)

### CODE REVIEW

**Comment by klausman** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[infrastructure/scion_elem.py, line 468 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZ0pFLPfkUlXyT4ysd8:-KZ0pFLPfkUlXyT4ysd9:b-pnvbfs) ([raw file](https://github.com/netsec-ethz/scion/blob/f8da0f91d5d5f7647acbb97f4f5233b73bb14c22/infrastructure/scion_elem.py#L468)):*
> ```Python
>         tcp_sock = self._tcp_sock_from_meta(meta)
>         if not tcp_sock.is_active():
>             return
> ```

Are you just discarding the msg here? How does the caller distinguish between this return and the implicit one at the end of this method?

---

*[infrastructure/scion_elem.py, line 522 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZ0pqSS_q5hNpfsficS:-KZ0pqSTMsZC2b1yGCPP:b-o91re9) ([raw file](https://github.com/netsec-ethz/scion/blob/f8da0f91d5d5f7647acbb97f4f5233b73bb14c22/infrastructure/scion_elem.py#L522)):*
> ```Python
>                 break
>         if dropped > 0:
>             logging.warning("%d TCP connection(s) dropped" % dropped)
> ```

This is not dropping connections but messages, AIUI.

---

*[lib/socket.py, line 449 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZ0r-mvpD5DUG9x_cS9:-KZ0r-mwSxEsh963jk9R:bi7bj0l) ([raw file](https://github.com/netsec-ethz/scion/blob/f8da0f91d5d5f7647acbb97f4f5233b73bb14c22/lib/socket.py#L449)):*
> ```Python
>                 return sent
>             except SCIONTCPError as e:
>                 logging.error("TCP: inactivating after socket error: %s", e)
> ```

s/inactivating/deactivating/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/952)*

**Comment by pszalach** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[infrastructure/scion_elem.py, line 468 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZ0pFLPfkUlXyT4ysd8:-KZ1T3ja0fJhX10VpKxV:bdhqn9g) ([raw file](https://github.com/netsec-ethz/scion/blob/f8da0f91d5d5f7647acbb97f4f5233b73bb14c22/infrastructure/scion_elem.py#L468)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Are you just discarding the msg here? How does the caller distinguish between this return and the implicit one at the end of this method?
</blockquote></details>

Yes, I'm discarding the msg here. This is called as a separate thread, so caller does not care.
btw. the latest commit changes locking a bit.

---

*[infrastructure/scion_elem.py, line 522 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZ0pqSS_q5hNpfsficS:-KZ1MYIDuYJ6h5Sc4KAp:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f8da0f91d5d5f7647acbb97f4f5233b73bb14c22/infrastructure/scion_elem.py#L522)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This is not dropping connections but messages, AIUI.
</blockquote></details>

Done.

---

*[lib/socket.py, line 449 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZ0r-mvpD5DUG9x_cS9:-KZ1N1uybBashMXxLeTq:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/f8da0f91d5d5f7647acbb97f4f5233b73bb14c22/lib/socket.py#L449)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

s/inactivating/deactivating/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/952)*

**Comment by klausman** [comment]
Looks good to me, but since Stephen is more familiar with the code, I'd prefer to have his final sign-off on this.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-:-KZ1zmz8bDss4mvl9vWO:b-we7yi6)*

**Comment by pszalach** [comment]
@klausman thanks. Yes, sure, it waits for Stephen now;-)

**Comment by kormat** [comment]
Reviewed 5 of 8 files at r1, 1 of 2 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 456 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZMsQ1i_PxI2_3kjdS7:-KZMsQ1i_PxI2_3kjdS8:b-wiwhqr) ([raw file](https://github.com/netsec-ethz/scion/blob/0d3bebbb63d81ba64f396fb3822e19b2f55b46d2/infrastructure/scion_elem.py#L456)):*
> ```Python
>     def _send_meta_tcp(self, msg, meta):
>         if not meta.sock:
>             threading.Thread(
> ```

This is a terrible way to do this. If `_send_meta_tcp` gets called multiple times before any of the threads finish, you have automatic race-conditions.

---

*[infrastructure/scion_elem.py, line 468 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZQj0cVIWFNdBBIvhDf:-KZQj0cVIWFNdBBIvhDg:b-8h1zuz) ([raw file](https://github.com/netsec-ethz/scion/blob/292250d59b2598cf866c7a126ddf36400a03aa67/infrastructure/scion_elem.py#L468)):*
> ```Python
>             if not meta.sock:
>                 tcp_sock = self._tcp_sock_from_meta(meta)
>                 if not tcp_sock.is_active():
> ```

Connection errors automatically drop messages? Also if a connection drops, further messages using that meta are lost, right?

---

*[lib/socket.py, line 435 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZQjnSA59stSrDPvgvy:-KZQjnSA59stSrDPvgvz:bkxwg0k) ([raw file](https://github.com/netsec-ethz/scion/blob/292250d59b2598cf866c7a126ddf36400a03aa67/lib/socket.py#L435)):*
> ```Python
>                 self._last_io = time.time()
>             except SCIONTCPError:
>                 logging.debug("TCP: deactivating socket after socket error")
> ```

Include error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/952)*

**Comment by pszalach** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[infrastructure/scion_elem.py, line 456 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZMsQ1i_PxI2_3kjdS7:-KZR8RuxxiUOswzDr7sU:br577wr) ([raw file](https://github.com/netsec-ethz/scion/blob/0d3bebbb63d81ba64f396fb3822e19b2f55b46d2/infrastructure/scion_elem.py#L456)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is a terrible way to do this. If `_send_meta_tcp` gets called multiple times before any of the threads finish, you have automatic race-conditions.
</blockquote></details>

where I have this race condition? There is a lock at the beginning of the called method.

---

*[infrastructure/scion_elem.py, line 468 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZQj0cVIWFNdBBIvhDf:-KZR8iM5E5ht3Z6-CNu_:b-o8e51u) ([raw file](https://github.com/netsec-ethz/scion/blob/292250d59b2598cf866c7a126ddf36400a03aa67/infrastructure/scion_elem.py#L468)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Connection errors automatically drop messages? Also if a connection drops, further messages using that meta are lost, right?
</blockquote></details>

Right. If connection is inactive (timeouted or an error happened) we do not reconnect.

---

*[lib/socket.py, line 435 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZQjnSA59stSrDPvgvy:-KZR9ioP4Pnl5Vne2NA3:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/292250d59b2598cf866c7a126ddf36400a03aa67/lib/socket.py#L435)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Include error?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/952)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[infrastructure/scion_elem.py, line 456 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZMsQ1i_PxI2_3kjdS7:-KZW9oEy_32B80hQqGWi:b-liyfua) ([raw file](https://github.com/netsec-ethz/scion/blob/0d3bebbb63d81ba64f396fb3822e19b2f55b46d2/infrastructure/scion_elem.py#L456)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

where I have this race condition? There is a lock at the beginning of the called method.
</blockquote></details>

This comment is from a previous version of the code. Now what you have is a way to spawn ~infinite threads, if messages keep being sent using a meta to a destination that isn't connectable. There should only ever be a single connect thread per meta, and it needs to be spawned in the sending loop, so that any connections which timeout or error can be restarted.

---

*[infrastructure/scion_elem.py, line 468 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion/952#-KZQj0cVIWFNdBBIvhDf:-KZW8oEaeqy5PWjS5v2F:b-fd7e7r) ([raw file](https://github.com/netsec-ethz/scion/blob/292250d59b2598cf866c7a126ddf36400a03aa67/infrastructure/scion_elem.py#L468)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

Right. If connection is inactive (timeouted or an error happened) we do not reconnect.
</blockquote></details>

That needs to be fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/952)*

**Comment by pszalach** [comment]
That PR will be replaced soon.

**Pull request closed without merging**
