### PR TITLE
Add issuing TRC version to Certificates

### PR DESCRIPTION
**Pull request by Oncilla**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1104)

### CODE REVIEW

**Comment by pszalach** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/crypto/certificate.py, line 176 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2u_6kKTU9-lwZO36X:-Kl2u_6lGwrdp_MeoulP:bybm525) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate.py#L176)):*
> ```Python
>         :param bytes subject_enc_key: the public part of the encryption key.
>         :param str issuer: the certificate issuer. It can only be an AS.
>         :param int trc_version: the version of the issuing certificate/trc.
> ```

version of the issuing certificate?

---

*[lib/crypto/certificate_chain.py, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2vGjOHdUJdkzF5M4Z:-Kl2vGjOHdUJdkzF5M4_:b-zh6hhg) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate_chain.py#L35)):*
> ```Python
> 
> 
> def verify_sig_chain_trc(msg, sig, subject, chain, trc):
> ```

Interesting, I'm curious:
1) why lint did not complain about that,
2) how your PR passes CircleCI (it seems to be called in `certificates_test.py`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1104)*

**Comment by pszalach** [comment]
(cc @sezergueler)

**Comment by sezergueler** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/crypto/certificate_chain.py, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2vGjOHdUJdkzF5M4Z:-Kl3-788gW1HnCk5vNJw:b-2ylx0l) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate_chain.py#L35)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

Interesting, I'm curious:
1) why lint did not complain about that,
2) how your PR passes CircleCI (it seems to be called in `certificates_test.py`)
</blockquote></details>

Ahh, this was from the old implementation. I forgot to remove that from the arguments list, thanks for removing. 

1. Is a good question, pylint in Visual Studio code detects and marks this. But ./scion.sh lint does not...
2. Seems to be a good point, is it possible that ```certificates_test.py``` is never executed?

---

*[lib/crypto/certificate_chain.py, line 52 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2z2EbZoBSfPNp02i6:-Kl2z2Ec1hI1jn0Pi54r:b28tcnn) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate_chain.py#L52)):*
> ```Python
>     subject = str(subject)
>     try:
>         chain.verify(str(subject), trc)
> ```

subject is converted to string two lines above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1104)*

**Comment by Oncilla** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/crypto/certificate.py, line 176 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2u_6kKTU9-lwZO36X:-Kl36vvMmSvryAIqqc5B:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate.py#L176)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

version of the issuing certificate?
</blockquote></details>

Done.

---

*[lib/crypto/certificate_chain.py, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2vGjOHdUJdkzF5M4Z:-Kl37jVbN0_Wp1HQrJMm:b-1ypy8m) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate_chain.py#L35)):*
<details><summary><i>Previously, sezergueler wrote…</i></summary><blockquote>

Ahh, this was from the old implementation. I forgot to remove that from the arguments list, thanks for removing. 

1. Is a good question, pylint in Visual Studio code detects and marks this. But ./scion.sh lint does not...
2. Seems to be a good point, is it possible that ```certificates_test.py``` is never executed?
</blockquote></details>

Currently only following integration tests are run by CircleCi:
  test/integration/end2end_test.py
  test/integration/cli_srv_ext_test.py
  test/integration/scmp_error_test.py
  test/integration/cert_req_test.py
  test/integration/revocation_test.sh

Btw: certificates_test.py is completely broken. I'm not sure, what to do with it.

---

*[lib/crypto/certificate_chain.py, line 52 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2z2EbZoBSfPNp02i6:-Kl38e34SqZTAI3PsUq8:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate_chain.py#L52)):*
<details><summary><i>Previously, sezergueler wrote…</i></summary><blockquote>

subject is converted to string two lines above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1104)*

**Comment by pszalach** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/crypto/certificate_chain.py, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2vGjOHdUJdkzF5M4Z:-Kl39SlNfoNWSeh7bDmK:b-nv7s7r) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate_chain.py#L35)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Currently only following integration tests are run by CircleCi:
  test/integration/end2end_test.py
  test/integration/cli_srv_ext_test.py
  test/integration/scmp_error_test.py
  test/integration/cert_req_test.py
  test/integration/revocation_test.sh

Btw: certificates_test.py is completely broken. I'm not sure, what to do with it.
</blockquote></details>

yes, it seems to be completely outdated. Also now certificate/TRC requests are part of integration test, so I'm fine with dropping `certificates_test.py` (cc @kormat).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-:-Kl39w-tQLk0o50fgvkc:bnfp4nl)*

**Comment by sezergueler** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-:-Kl3AcUCU3jexIHJ797T:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/crypto/certificate_chain.py, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2vGjOHdUJdkzF5M4Z:-KlOEkfY9PcOG5BfvHyc:b-ay2j67) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate_chain.py#L35)):*
<details><summary><i>Previously, pszalach (Paweł Szałachowski) wrote…</i></summary><blockquote>

yes, it seems to be completely outdated. Also now certificate/TRC requests are part of integration test, so I'm fine with dropping `certificates_test.py` (cc @kormat).
</blockquote></details>

Agreed, nuke `certificates_test.py` in this PR please.

We don't use `pylint` as it tends to be _very_ noisy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1104)*

**Comment by Oncilla** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/crypto/certificate_chain.py, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-Kl2vGjOHdUJdkzF5M4Z:-KlOH95hO0js0j_uh4-J:b-ipkb2y) ([raw file](https://github.com/netsec-ethz/scion/blob/411cad05c229dab8f9f022cf3e525ca389090750/lib/crypto/certificate_chain.py#L35)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Agreed, nuke `certificates_test.py` in this PR please.

We don't use `pylint` as it tends to be _very_ noisy.
</blockquote></details>

Has been nuked by #1108.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1104)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1104#-:-KlSg_zSPVhBxffmG2hL:bnfp4nl)*

**Comment by pszalach** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1104)*

**Pull request merged**
