### PR TITLE
Optimized egress fastpath

### PR DESCRIPTION
**Pull request by scrye**
Changes:
  * use packet buffers when communicating between goroutines
  * delete useless memory allocations

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion/1189)

### CODE REVIEW

**Comment by shitz** [comment]
Review status: 0 of 8 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[go/lib/pring/pring.go, line 71 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7UE_DYTqb_GM6RMRQ:-Kq7UE_DYTqb_GM6RMRR:bv1put) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/pring/pring.go#L71)):*
> ```Go
> }
> 
> func (r *PRing) write(b []byte) int {
> ```

Add comments, since it's not obvious how the wrap around works.

---

*[go/lib/pring/pring_test.go, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VTnqRfsyHmQQSqsJ:-Kq7VTnqRfsyHmQQSqsK:b-z4d2c1) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/pring/pring_test.go#L32)):*
> ```Go
> }
> 
> func TestWrite(t *testing.T) {
> ```

You should also add tests for the error condition, i.e., reading with supplying a buffer that is too small, or writing where the supplied buffer is too large.

---

*[go/lib/pring/pring_test.go, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VjemAz0rPeue9hxV:-Kq7VgUzIu5UShHUpdwK:b-lamaqw) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/pring/pring_test.go#L73)):*
> ```Go
> 
> 	/*
> 		b := NewPRing(10)
> ```

Remove if not used.

---

*[go/lib/sock/reliable/reliable.go, line 317 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VvEzd07caqKvDw61:-Kq7VvEzd07caqKvDw62:b-l6mwxj) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/sock/reliable/reliable.go#L317)):*
> ```Go
> 
> 	_, err := conn.aw.Write(header)
> 	//_, err := conn.UnixConn.Write(header)
> ```

remove

---

*[go/lib/sock/reliable/reliable.go, line 323 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VxGg-Ypi6twbowEn:-Kq7VxGhdtFmQk91hxCN:b-l6mwxj) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/sock/reliable/reliable.go#L323)):*
> ```Go
> 	}
> 	written, err := conn.aw.Write(buf)
> 	//written, err := conn.UnixConn.Write(buf)
> ```

remove

---

*[go/sig/sig.go, line 61 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7W-QAr3qVNJu12jny:-Kq7W-QAr3qVNJu12jnz:b-k9te7a) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/sig/sig.go#L61)):*
> ```Go
> 
> 	go func() {
> 		http.ListenAndServe("localhost:6060", nil)
> ```

Remove this. `metrics.Start()` already starts an HTTP server. You probably have to register some handler for `pprof`.

---

*[go/sig/base/forward.go, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7MoBMbnIAzBVZa9Wq:-Kq7MoBMbnIAzBVZa9Wr:b-lg8ge8) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/sig/base/forward.go#L126)):*
> ```Go
> 	e.frameOff += PktLenSize
> 	pktOff := 0
> 	//log.Debug("Starting to copy packet")
> ```

I think we can remove these by now.

---

*[go/sig/base/forward.go, line 172 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7S-sgwDhyJRB-SQGc:-Kq7S-shv5g4TaMZ1WRY:bc8a4f4) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/sig/base/forward.go#L172)):*
> ```Go
> 		e.epoch = uint16(time.Now().Unix() & 0xFFFF)
> 	}
> 	//log.Debug("EgressWorker.Write", "len", len(frame), "epoch", e.epoch,
> ```

Leave this debug statement.

---

*[go/sig/base/forward.go, line 208 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7RtBDyjP242juzRnu:-Kq7RtBDyjP242juzRnv:b-jurpfv) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/sig/base/forward.go#L208)):*
> ```Go
> 		return nil, nil
> 	}
> 	if pr.buffer[pr.index]&0xF0 != 0x40 {
> ```

This has to be protocol agnostic. You cannot use the length field in the IP header.

---

*[go/sig/lib/scion/scion.go, line 197 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7WT_NuZcUdGt_EQeF:-Kq7WT_NuZcUdGt_EQeG:bi54u4r) ([raw file](https://github.com/netsec-ethz/scion/blob/796a2a776804834a8c26647626372c84a33271f0/go/sig/lib/scion/scion.go#L197)):*
> ```Go
> func (c *SCIONConn) createUDPPacket(b []byte, raddr *SCIONAppAddr, path sciond.PathReplyEntry) (common.RawBytes, error) {
> 	// SCION Version 0 common headers are 8-byte long
> 	commonHeaderSize := 8
> ```

Don't remove this. This could even be made a package level constant.

---

*[go/vendor/vendor.json, line 261 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7Wipx7QbDkxIwJudd:-Kq7Wipx7QbDkxIwJude:byp18fd) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/vendor/vendor.json#L261)):*
> ```JSON
> 		},
> 		{
> 			"checksumSHA1": "SAqULvDxUY5gQwFEHvypcVkIxkw=",
> ```

Remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1189)*

**Comment by scrye** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[go/lib/pring/pring.go, line 71 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7UE_DYTqb_GM6RMRQ:-Kq7XCUC8cMwjrx7bwKQ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/pring/pring.go#L71)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Add comments, since it's not obvious how the wrap around works.
</blockquote></details>

Done.

---

*[go/lib/pring/pring_test.go, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VTnqRfsyHmQQSqsJ:-Kq7fBKBsBu9RbfxEBK7:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/pring/pring_test.go#L32)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You should also add tests for the error condition, i.e., reading with supplying a buffer that is too small, or writing where the supplied buffer is too large.
</blockquote></details>

Done.

---

*[go/lib/pring/pring_test.go, line 73 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VjemAz0rPeue9hxV:-Kq7fCUR_UKLesW0nwrA:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/pring/pring_test.go#L73)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Remove if not used.
</blockquote></details>

Done.

---

*[go/lib/sock/reliable/reliable.go, line 317 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VvEzd07caqKvDw61:-Kq7fJqR0ODS4o_8PzRs:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/sock/reliable/reliable.go#L317)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[go/lib/sock/reliable/reliable.go, line 323 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VxGg-Ypi6twbowEn:-Kq7fKEhQqnTQ3p0yeCz:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/sock/reliable/reliable.go#L323)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[go/sig/base/forward.go, line 126 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7MoBMbnIAzBVZa9Wq:-Kq7fgYotkSsnly-FnX4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/sig/base/forward.go#L126)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I think we can remove these by now.
</blockquote></details>

Done.

---

*[go/sig/base/forward.go, line 172 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7S-sgwDhyJRB-SQGc:-Kq7fiTfNu9Dh3pCO2YJ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/sig/base/forward.go#L172)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Leave this debug statement.
</blockquote></details>

Done.

---

*[go/sig/base/forward.go, line 208 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7RtBDyjP242juzRnu:-Kq7fjDrqmfbqXj-9xO4:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/sig/base/forward.go#L208)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This has to be protocol agnostic. You cannot use the length field in the IP header.
</blockquote></details>

Done.

---

*[go/sig/lib/scion/scion.go, line 197 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7WT_NuZcUdGt_EQeF:-Kq7gDvQcWYQTWtSng_S:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/796a2a776804834a8c26647626372c84a33271f0/go/sig/lib/scion/scion.go#L197)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Don't remove this. This could even be made a package level constant.
</blockquote></details>

Done.

---

*[go/sig/sig.go, line 61 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7W-QAr3qVNJu12jny:-Kq7fRgkO-L7Juh1LpAS:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/sig/sig.go#L61)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Remove this. `metrics.Start()` already starts an HTTP server. You probably have to register some handler for `pprof`.
</blockquote></details>

Done.

---

*[go/vendor/vendor.json, line 261 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7Wipx7QbDkxIwJudd:-Kq7gRtWz2g2UFFAWbnX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/vendor/vendor.json#L261)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1189)*

**Comment by shitz** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/lib/pring/pring.go, line 26 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq8Gdjt_jcrlEXo4Cih:-Kq8Gdjt_jcrlEXo4Cii:b-sd0s9) ([raw file](https://github.com/netsec-ethz/scion/blob/74f10ba493f79f2ef75ae1c0c31be5196df6dc95/go/lib/pring/pring.go#L26)):*
> ```Go
> }
> 
> func NewPRing(size int) *PRing {
> ```

Actually, since the package is called `pring` this can just be called `New()`

---

*[go/lib/pring/pring_test.go, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VTnqRfsyHmQQSqsJ:-Kq8Ksr5IozewFxUndzR:b8vo463) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/pring/pring_test.go#L32)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You should add a unit test for `Read`, `TestRead` and test the normal case and the error case there.

---

*[go/sig/base/forward.go, line 212 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq8LOmj8grAnI3OJR3W:-Kq8LOmj8grAnI3OJR3X:b-jyehrw) ([raw file](https://github.com/netsec-ethz/scion/blob/74f10ba493f79f2ef75ae1c0c31be5196df6dc95/go/sig/base/forward.go#L212)):*
> ```Go
> 		return nil, nil
> 	}
> 	length := int(binary.BigEndian.Uint16(pr.buffer[pr.index : pr.index+2]))
> ```

do `pr.index += 2` after this line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1189)*

**Comment by scrye** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/lib/pring/pring.go, line 26 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq8Gdjt_jcrlEXo4Cih:-Kq8PRdWDnPk91JK3YBm:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/74f10ba493f79f2ef75ae1c0c31be5196df6dc95/go/lib/pring/pring.go#L26)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Actually, since the package is called `pring` this can just be called `New()`
</blockquote></details>

Done.

---

*[go/lib/pring/pring_test.go, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq7VTnqRfsyHmQQSqsJ:-Kq8RsZyjAMh7hiaBXVo:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/386897a7aea5864847e035cc45be579fb68200b3/go/lib/pring/pring_test.go#L32)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You should add a unit test for `Read`, `TestRead` and test the normal case and the error case there.
</blockquote></details>

Done.

---

*[go/sig/base/forward.go, line 212 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-Kq8LOmj8grAnI3OJR3W:-Kq8PZdIGnljqWaAFF4C:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/74f10ba493f79f2ef75ae1c0c31be5196df6dc95/go/sig/base/forward.go#L212)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

do `pr.index += 2` after this line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1189)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1189#-:-Kq8TlfIx5AIR4LE8kMz:bnfp4nl)*

**Comment by scrye** [comment]
Splitting this across multiple, more manageable, PRs.

**Pull request closed without merging**
